CREATE TABLE [dbo].[CASHIER_UPLOAD_MAIN] (
    [CODE]              NVARCHAR (50)  NOT NULL,
    [BATCH_NO]          NVARCHAR (50)  NOT NULL,
    [FINTECH_CODE]      NVARCHAR (50)  NOT NULL,
    [FINTECH_NAME]      NVARCHAR (250) NOT NULL,
    [VALUE_DATE]        DATETIME       NOT NULL,
    [TRX_DATE]          DATETIME       NOT NULL,
    [BRANCH_BANK_CODE]  NVARCHAR (50)  NOT NULL,
    [BRANCH_BANK_NAME]  NVARCHAR (50)  NOT NULL,
    [BANK_GL_LINK_CODE] NVARCHAR (50)  NOT NULL,
    [STATUS]            NVARCHAR (50)  NOT NULL,
    [REFF_NO]           NVARCHAR (50)  NULL,
    [CRE_DATE]          DATETIME       NOT NULL,
    [CRE_BY]            NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    [MOD_DATE]          DATETIME       NOT NULL,
    [MOD_BY]            NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_CASHIER_UPLOAD_MAIN] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

