CREATE TABLE [dbo].[CASHIER_UPLOAD_DETAIL] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [CASHIER_UPLOAD_CODE]      NVARCHAR (50)   NOT NULL,
    [REFF_LOAN_NO]             NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NOT NULL,
    [CLIENT_NAME]              NVARCHAR (250)  NOT NULL,
    [TOTAL_INSTALLMENT_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [TOTAL_OBLIGATION_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (50)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (50)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (50)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_CASHIER_UPLOAD_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CASHIER_UPLOAD_DETAIL_CASHIER_UPLOAD_MAIN] FOREIGN KEY ([CASHIER_UPLOAD_CODE]) REFERENCES [dbo].[CASHIER_UPLOAD_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

