CREATE TABLE [dbo].[DEPOSIT_MOVE_DETAIL] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [DEPOSIT_MOVE_CODE]    NVARCHAR (50)   NOT NULL,
    [TO_AGREEMENT_NO]      NVARCHAR (50)   NOT NULL,
    [TO_DEPOSIT_TYPE_CODE] NVARCHAR (15)   NOT NULL,
    [TO_AMOUNT]            DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_MOVE_DEPOSIT_TO_AMOUNT] DEFAULT (N'0') NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DEPOSIT_MOVE_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEPOSIT_MOVE_DETAIL_AGREEMENT_MAIN] FOREIGN KEY ([TO_AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]),
    CONSTRAINT [FK_DEPOSIT_MOVE_DETAIL_DEPOSIT_MOVE] FOREIGN KEY ([DEPOSIT_MOVE_CODE]) REFERENCES [dbo].[DEPOSIT_MOVE] ([CODE])
);

