CREATE TABLE [dbo].[DOCUMENT_TBO_DOCUMENT_CONTRACT] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [DOCUMENT_TBO_CODE] NVARCHAR (50)   NULL,
    [DESCRIPTION]       NVARCHAR (4000) NULL,
    [FILE_PATH]         NVARCHAR (250)  NULL,
    [FILE_NAME]         NVARCHAR (250)  NULL,
    [PROMISE_DATE]      DATETIME        NULL,
    [EXPIRED_DATE]      DATETIME        NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DOCUMENT_TBO_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

