CREATE TABLE [dbo].[FIN_INTERFACE_BANK_MUTATION] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [GL_LINK_CODE]         NVARCHAR (50)   NOT NULL,
    [REFF_NO]              NVARCHAR (50)   NOT NULL,
    [REFF_NAME]            NVARCHAR (250)  NOT NULL,
    [REFF_REMARKS]         NVARCHAR (4000) NOT NULL,
    [MUTATION_DATE]        DATETIME        NOT NULL,
    [MUTATION_VALUE_DATE]  DATETIME        NOT NULL,
    [MUTATION_ORIG_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_BANK_MUTATION_MUTATION_AMOUNT1] DEFAULT ((0)) NOT NULL,
    [MUTATION_EXCH_RATE]   DECIMAL (18, 6) CONSTRAINT [DF_FIN_INTERFACE_BANK_MUTATION_MUTATION_EXCH_RATE] DEFAULT ((1)) NOT NULL,
    [MUTATION_BASE_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_BANK_MUTATION_MUTATION_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FIN_INTERFACE_BANK_MUTATION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nilai tukar mata uang pada data received voucher tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FIN_INTERFACE_BANK_MUTATION', @level2type = N'COLUMN', @level2name = N'MUTATION_EXCH_RATE';

