CREATE TABLE [dbo].[FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [GL_LINK_TRANSACTION_CODE] NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [GL_LINK_CODE]             NVARCHAR (50)   NULL,
    [CONTRA_GL_LINK_CODE]      NVARCHAR (50)   NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NULL,
    [ORIG_CURRENCY_CODE]       NVARCHAR (3)    NOT NULL,
    [ORIG_AMOUNT_DB]           DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_ORIG_AMOUNT_DB] DEFAULT ((0)) NULL,
    [ORIG_AMOUNT_CR]           DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_ORIG_AMOUNT_CR] DEFAULT ((0)) NULL,
    [EXCH_RATE]                DECIMAL (18, 6) CONSTRAINT [DF_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_EXCH_RATE] DEFAULT ((1)) NOT NULL,
    [BASE_AMOUNT_DB]           DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_BASE_AMOUNT_DB] DEFAULT ((0)) NULL,
    [BASE_AMOUNT_CR]           DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_BASE_AMOUNT_CR] DEFAULT ((0)) NULL,
    [REMARKS]                  NVARCHAR (4000) CONSTRAINT [DF_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_REMARKS] DEFAULT (N'REMARK TRANSAKSI') NULL,
    [DIVISION_CODE]            NVARCHAR (50)   NULL,
    [DIVISION_NAME]            NVARCHAR (250)  NULL,
    [DEPARTMENT_CODE]          NVARCHAR (50)   NULL,
    [DEPARTMENT_NAME]          NVARCHAR (250)  NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [EXT_PPH_TYPE]             NVARCHAR (20)   NULL,
    [EXT_VENDOR_CODE]          NVARCHAR (50)   NULL,
    [EXT_VENDOR_NAME]          NVARCHAR (250)  NULL,
    [EXT_VENDOR_NPWP]          NVARCHAR (20)   NULL,
    [EXT_VENDOR_ADDRESS]       NVARCHAR (4000) NULL,
    [EXT_INCOME_TYPE]          NVARCHAR (250)  NULL,
    [EXT_INCOME_BRUTO_AMOUNT]  DECIMAL (18, 2) NULL,
    [EXT_TAX_RATE_PCT]         DECIMAL (5, 2)  NULL,
    [EXT_PPH_AMOUNT]           DECIMAL (18, 2) NULL,
    [EXT_DESCRIPTION]          NVARCHAR (4000) NULL,
    [EXT_TAX_NUMBER]           NVARCHAR (50)   NULL,
    [EXT_SALE_TYPE]            NVARCHAR (10)   NULL,
    [EXT_VENDOR_TYPE]          NVARCHAR (20)   NULL,
    [EXT_TAX_DATE]             DATETIME        NULL,
    [ADD_REFF_01]              NVARCHAR (50)   NULL,
    [ADD_REFF_02]              NVARCHAR (50)   NULL,
    [ADD_REFF_03]              NVARCHAR (50)   NULL,
    [EXT_NITKU]                NVARCHAR (50)   NULL,
    [EXT_NPWP_HO]              NVARCHAR (50)   NULL,
    CONSTRAINT [FK_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION] FOREIGN KEY ([GL_LINK_TRANSACTION_CODE]) REFERENCES [dbo].[FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_GL_LINK_TRANSACTION_CODE]
    ON [dbo].[FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL]([GL_LINK_TRANSACTION_CODE] ASC)
    INCLUDE([GL_LINK_CODE], [ORIG_AMOUNT_DB], [ORIG_AMOUNT_CR], [BASE_AMOUNT_DB], [BASE_AMOUNT_CR]);

