CREATE TABLE [dbo].[FIN_INTERFACE_AGREEMENT_OBLIGATION_PAYMENT] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]        NVARCHAR (50)   NOT NULL,
    [INSTALLMENT_NO]      INT             NULL,
    [OBLIGATION_TYPE]     NVARCHAR (10)   NOT NULL,
    [PAYMENT_DATE]        DATETIME        NOT NULL,
    [VALUE_DATE]          DATETIME        NOT NULL,
    [PAYMENT_SOURCE_TYPE] NVARCHAR (50)   NULL,
    [PAYMENT_SOURCE_NO]   NVARCHAR (50)   NOT NULL,
    [PAYMENT_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [PAYMENT_REMARKS]     NVARCHAR (4000) NOT NULL,
    [IS_WAIVE]            NVARCHAR (1)    NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FIN_INTERFACE_AGREEMENT_OBLIGATION_PAYMENT] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_FIN_INTERFACE_AGREEMENT_OBLIGATION_PAYMENT_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor angsuran pada data obligasi kontrak pembiayaan tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FIN_INTERFACE_AGREEMENT_OBLIGATION_PAYMENT', @level2type = N'COLUMN', @level2name = N'INSTALLMENT_NO';

