CREATE TABLE [dbo].[FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION] (
    [ID]                     BIGINT         IDENTITY (1, 1) NOT NULL,
    [CODE]                   NVARCHAR (50)  NOT NULL,
    [BRANCH_CODE]            NVARCHAR (50)  NOT NULL,
    [BRANCH_NAME]            NVARCHAR (250) NOT NULL,
    [TRANSACTION_STATUS]     NVARCHAR (10)  NOT NULL,
    [TRANSACTION_DATE]       DATETIME       NOT NULL,
    [TRANSACTION_VALUE_DATE] DATETIME       NOT NULL,
    [TRANSACTION_CODE]       NVARCHAR (50)  NOT NULL,
    [TRANSACTION_NAME]       NVARCHAR (250) NOT NULL,
    [REFF_MODULE_CODE]       NVARCHAR (10)  NOT NULL,
    [REFF_SOURCE_NO]         NVARCHAR (50)  NOT NULL,
    [REFF_SOURCE_NAME]       NVARCHAR (250) NOT NULL,
    [IS_JOURNAL_REVERSAL]    NVARCHAR (1)   NOT NULL,
    [REVERSAL_REFF_NO]       NVARCHAR (50)  NULL,
    [CRE_DATE]               DATETIME       NOT NULL,
    [CRE_BY]                 NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)  NOT NULL,
    [MOD_DATE]               DATETIME       NOT NULL,
    [MOD_BY]                 NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_TRANSACTION_CODE_20250615]
    ON [dbo].[FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION]([TRANSACTION_CODE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NEW, HOLD, POST', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION', @level2type = N'COLUMN', @level2name = N'TRANSACTION_STATUS';

