CREATE TABLE [dbo].[FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_NO]          NVARCHAR (50)   NOT NULL,
    [ASSET_NO]              NVARCHAR (50)   NULL,
    [INVOICE_STATUS]        NVARCHAR (10)   NOT NULL,
    [TRANSACTION_DATE]      DATETIME        NOT NULL,
    [TRANSACTION_NO]        NVARCHAR (50)   NOT NULL,
    [TRANSACTION_NAME]      NVARCHAR (250)  NOT NULL,
    [TRANSACTION_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [CUSTOMER_CLIENT_NO]    NVARCHAR (50)   NULL,
    [CUSTOMER_NAME]         NVARCHAR (250)  NULL,
    [INVOICE_NO]            NVARCHAR (50)   NULL,
    [INVOICE_DATE]          DATETIME        NULL,
    [INVOICE_DUE_DATE]      DATETIME        NULL,
    [INVOICE_PAST_DUE_DATE] DATETIME        NULL,
    [GROSS_AMOUNT]          DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY_GROSS_AMOUNT] DEFAULT ((0)) NULL,
    [VAT_PCT]               DECIMAL (9, 6)  CONSTRAINT [DF_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY_VAT_PCT] DEFAULT ((0)) NULL,
    [PPH_PCT]               DECIMAL (9, 6)  CONSTRAINT [DF_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY_PPH_PCT] DEFAULT ((0)) NULL,
    [NET_AMOUNT]            DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY_NET_AMOUNT] DEFAULT ((0)) NULL,
    [USED_AMOUNT]           DECIMAL (18, 2) CONSTRAINT [DF_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY_USED_AMOUNT] DEFAULT ((0)) NULL,
    [REMARKS]               NVARCHAR (4000) CONSTRAINT [DF_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY_REMARKS] DEFAULT ('') NULL,
    [PUG_DATE]              DATETIME        NULL,
    [SOURCE_REFF_MODULE]    NVARCHAR (50)   NOT NULL,
    [SOURCE_REFF_REMARKS]   NVARCHAR (4000) NOT NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : FAETP', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY', @level2type = N'COLUMN', @level2name = N'CUSTOMER_CLIENT_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : FAETP', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY', @level2type = N'COLUMN', @level2name = N'CUSTOMER_NAME';

