CREATE TABLE [dbo].[FIN_INTERFACE_AGREEMENT_FUND_IN_USED_HISTORY] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_NO]        NVARCHAR (50)   NOT NULL,
    [CHARGES_DATE]        DATETIME        NULL,
    [CHARGES_TYPE]        NVARCHAR (50)   NOT NULL,
    [TRANSACTION_NO]      NVARCHAR (50)   NOT NULL,
    [TRANSACTION_NAME]    NVARCHAR (250)  NOT NULL,
    [CHARGES_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [SOURCE_REFF_MODULE]  NVARCHAR (50)   NOT NULL,
    [SOURCE_REFF_REMARKS] NVARCHAR (4000) NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FIN_INTERFACE_AGREEMENT_FUND_IN_USED] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FIN_INTERFACE_AGREEMENT_FUND_IN_USED] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

