CREATE TABLE [dbo].[FIN_INTERFACE_CASHIER_RECEIVED_REQUEST_24112023] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                     NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [REQUEST_STATUS]           NVARCHAR (10)   NOT NULL,
    [REQUEST_CURRENCY_CODE]    NVARCHAR (5)    NOT NULL,
    [REQUEST_DATE]             DATETIME        NOT NULL,
    [REQUEST_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [REQUEST_REMARKS]          NVARCHAR (4000) NOT NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NULL,
    [PDC_CODE]                 NVARCHAR (50)   NULL,
    [PDC_NO]                   NVARCHAR (50)   NULL,
    [DOC_REF_CODE]             NVARCHAR (50)   NOT NULL,
    [DOC_REF_NAME]             NVARCHAR (250)  NOT NULL,
    [DOC_REF_FLAG]             NVARCHAR (10)   NULL,
    [COLLECTOR_CODE]           NVARCHAR (50)   NULL,
    [COLLECTOR_NAME]           NVARCHAR (250)  NULL,
    [PDC_ALLOCATION_TYPE]      NVARCHAR (15)   NULL,
    [BRANCH_BANK_CODE]         NVARCHAR (50)   NULL,
    [BRANCH_BANK_NAME]         NVARCHAR (250)  NULL,
    [BRANCH_BANK_GL_LINK_CODE] NVARCHAR (50)   NULL,
    [INVOICE_NO]               NVARCHAR (50)   NULL,
    [INVOICE_EXTERNAL_NO]      NVARCHAR (50)   NULL,
    [INVOICE_DATE]             DATETIME        NULL,
    [INVOICE_DUE_DATE]         DATETIME        NULL,
    [INVOICE_BILLING_AMOUNT]   DECIMAL (18, 2) NULL,
    [INVOICE_PPN_AMOUNT]       DECIMAL (18, 2) NULL,
    [INVOICE_PPH_AMOUNT]       DECIMAL (18, 2) NULL,
    [PROCESS_DATE]             DATETIME        NULL,
    [PROCESS_REFF_NO]          NVARCHAR (50)   NULL,
    [PROCESS_REFF_NAME]        NVARCHAR (250)  NULL,
    [MANUAL_UPLOAD_STATUS]     NVARCHAR (10)   NULL,
    [MANUAL_UPLOAD_REMARKS]    NVARCHAR (4000) NULL,
    [VOUCHER_NO]               NVARCHAR (50)   NULL,
    [JOB_STATUS]               NVARCHAR (10)   NOT NULL,
    [FAILED_REMARKS]           NVARCHAR (4000) NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NULL
);

