CREATE TABLE [dbo].[FIN_INTERFACE_AGREEMENT_AMORTIZATION_PAYMENT] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_NO]        NVARCHAR (50)   NOT NULL,
    [INSTALLMENT_NO]      INT             NOT NULL,
    [PAYMENT_DATE]        DATETIME        NOT NULL,
    [VALUE_DATE]          DATETIME        NOT NULL,
    [PAYMENT_SOURCE_TYPE] NVARCHAR (10)   NOT NULL,
    [PAYMENT_SOURCE_NO]   NVARCHAR (50)   NOT NULL,
    [PAYMENT_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [PRINCIPAL_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [INTEREST_AMOUNT]     DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FIN_INTERFACE_AGREEMENT_AMORTIZATION_PAYMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FIN_INTERFACE_AGREEMENT_AMORTIZATION_PAYMENT_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

