CREATE TABLE [dbo].[MASTER_CONTRACT] (
    [MAIN_CONTRACT_NO]  NVARCHAR (50)   NOT NULL,
    [CLIENT_CODE]       NVARCHAR (50)   NULL,
    [CLIENT_NAME]       NVARCHAR (250)  NULL,
    [DATE]              DATETIME        NULL,
    [CONTRACT_STANDART] NVARCHAR (50)   NULL,
    [REMARK]            NVARCHAR (4000) NULL,
    [FILE_NAME]         NVARCHAR (250)  NULL,
    [FILE_PATH]         NVARCHAR (250)  NULL,
    [MEMO_FILE_NAME]    NVARCHAR (250)  NULL,
    [MEMO_FILE_PATH]    NVARCHAR (250)  NULL,
    [STATUS]            NVARCHAR (50)   NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CONTRACT] PRIMARY KEY CLUSTERED ([MAIN_CONTRACT_NO] ASC)
);

