CREATE TABLE [dbo].[MASTER_UPLOAD_TABLE] (
    [CODE]             NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]      NVARCHAR (250) NOT NULL,
    [TABEL_NAME]       NVARCHAR (250) NOT NULL,
    [TEMPLATE_NAME]    NVARCHAR (250) NOT NULL,
    [SP_GETROWS_NAME]  NVARCHAR (250) NOT NULL,
    [SP_VALIDATE_NAME] NVARCHAR (250) NOT NULL,
    [SP_UPLOAD_NAME]   NVARCHAR (250) NOT NULL,
    [SP_POST_NAME]     NVARCHAR (250) NOT NULL,
    [SP_CANCEL_NAME]   NVARCHAR (250) NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)   NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_UPLOAD_INTERFACE] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_Insert_Audit] 
			ON [dbo].[MASTER_UPLOAD_TABLE]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE]
([CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_Delete_Audit]    
			ON [dbo].[MASTER_UPLOAD_TABLE]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE]
([CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_Update_Audit]      
			ON [dbo].[MASTER_UPLOAD_TABLE]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([TABEL_NAME]) THEN '[TABEL_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TEMPLATE_NAME]) THEN '[TEMPLATE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([SP_GETROWS_NAME]) THEN '[SP_GETROWS_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([SP_VALIDATE_NAME]) THEN '[SP_VALIDATE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([SP_UPLOAD_NAME]) THEN '[SP_UPLOAD_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([SP_POST_NAME]) THEN '[SP_POST_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([SP_CANCEL_NAME]) THEN '[SP_CANCEL_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE]
([CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE]
([CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DESCRIPTION],[TABEL_NAME],[TEMPLATE_NAME],[SP_GETROWS_NAME],[SP_VALIDATE_NAME],[SP_UPLOAD_NAME],[SP_POST_NAME],[SP_CANCEL_NAME],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END