CREATE TABLE [dbo].[MUFG_FILE_LOG] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [LOG_DATE]         DATETIME        NOT NULL,
    [FILE_NAME]        NVARCHAR (250)  NOT NULL,
    [STATUS]           NVARCHAR (4000) NOT NULL,
    [TEXT_LINE]        NVARCHAR (4000) NOT NULL,
    [TRANSACTION_CODE] NVARCHAR (50)   NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MUFG_FILE_LOG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

