CREATE TABLE [dbo].[RPT_SURAT_PERINGATAN] (
    [USER_ID]                                  NVARCHAR (50)   NULL,
    [REPORT_IMAGE]                             NVARCHAR (250)  NULL,
    [REPORT_TITLE]                             NVARCHAR (250)  NULL,
    [REPORT_COMANY_NAME]                       NVARCHAR (250)  NULL,
    [REPORT_COMPANY_CITY]                      NVARCHAR (4000) NULL,
    [BANK_NAME]                                NVARCHAR (250)  NULL,
    [BANK_ACCOUNT_NAME]                        NVARCHAR (250)  NULL,
    [BANK_ACCOUNT_NO]                          NVARCHAR (50)   NULL,
    [NOMOR_SURAT]                              NVARCHAR (50)   NULL,
    [TANGGAL_SURAT]                            DATETIME        NULL,
    [CLIENT_NAME]                              NVARCHAR (250)  NULL,
    [CLIENT_ADDRESS]                           NVARCHAR (4000) NULL,
    [DIREKRTUR_LESSEE]                         NVARCHAR (250)  NULL,
    [TOTAL_OBJEK_SEWA]                         INT             NULL,
    [TOTAL_KONTRAK_SEWA]                       INT             NULL,
    [TUNGGAKAN_PEMBAYARAN_UANG_SEWA]           DECIMAL (18, 2) NULL,
    [DENDA_KETERLAMBATAN_PEMBAYARAN_UANG_SEWA] DECIMAL (18, 2) NULL,
    [TOTAL]                                    DECIMAL (18, 2) NULL,
    [TANGGAL_PELUNASAN]                        DATETIME        NULL,
    [DEPT_HEAD_OPL]                            NVARCHAR (250)  NULL,
    [PENASIHAT_HUKUM]                          NVARCHAR (250)  NULL,
    [CRE_DATE]                                 DATETIME        NULL,
    [CRE_BY]                                   NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]                           NVARCHAR (15)   NULL,
    [MOD_DATE]                                 DATETIME        NULL,
    [MOD_BY]                                   NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]                           NVARCHAR (15)   NULL,
    [NO_PERIOD]                                INT             NULL,
    [JABATAN]                                  NVARCHAR (250)  NULL
);

