CREATE TABLE [dbo].[RPT_AP_PAYMENT_REQUEST] (
    [USER_ID]              NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]         NVARCHAR (250)  NOT NULL,
    [FILTER_FROM_DATE]     DATETIME        NOT NULL,
    [FILTER_TO_DATE]       DATETIME        NOT NULL,
    [FILTER_BRANCH_CODE]   NVARCHAR (50)   NOT NULL,
    [TRANSACTION_NO]       NVARCHAR (50)   NULL,
    [DATE]                 DATETIME        NULL,
    [AP_DATE]              DATETIME        NULL,
    [AP_TYPE]              NVARCHAR (50)   NULL,
    [DESCRIPTION]          NVARCHAR (250)  NULL,
    [TO_BANK_NAME]         NVARCHAR (50)   NULL,
    [TO_BANK_ACCOUNT_NAME] NVARCHAR (50)   NULL,
    [TO_BANK_ACCOUNT]      NVARCHAR (50)   NULL,
    [AMOUNT]               DECIMAL (18, 2) NULL,
    [PAYMENT_STATUS]       NVARCHAR (50)   NULL,
    [PAYMENT_DATE]         DATETIME        NULL,
    [BRANCH_NAME]          NVARCHAR (50)   NULL,
    [IS_CONDITION]         NVARCHAR (1)    NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL
);

