CREATE TABLE [dbo].[RPT_PENDING_DISBURSEMENT] (
    [USER_ID]              NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]         NVARCHAR (250)  NOT NULL,
    [FILTER_FROM_DATE]     DATETIME        NOT NULL,
    [FILTER_TO_DATE]       DATETIME        NOT NULL,
    [FILTER_BRANCH_CODE]   NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]         NVARCHAR (50)   NOT NULL,
    [CLIENT_NAME]          NVARCHAR (250)  NOT NULL,
    [AGREEMENT_DATE]       DATETIME        NOT NULL,
    [TO_BANK_NAME]         NVARCHAR (50)   NOT NULL,
    [TO_BANK_ACCOUNT_NAME] NVARCHAR (50)   NOT NULL,
    [TO_BANK_ACCOUNT_NO]   NVARCHAR (50)   NOT NULL,
    [AMOUNT]               DECIMAL (18, 2) NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL
);

