CREATE TABLE [dbo].[RPT_FINANCE_TRANSACTION] (
    [USER_ID]                 NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]          NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]            NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]            NVARCHAR (250)  NOT NULL,
    [FILTER_TRANSCATION_TYPE] NVARCHAR (50)   NULL,
    [FILTER_GL_LINK]          NVARCHAR (50)   NULL,
    [FILTER_GL_LINK_NAME]     NVARCHAR (250)  NULL,
    [FILTER_FROM_DATE]        DATETIME        NULL,
    [FILTER_TO_DATE]          DATETIME        NULL,
    [FILTER_BRANCH_CODE]      NVARCHAR (50)   NULL,
    [FILTER_BRANCH_NAME]      NVARCHAR (250)  NULL,
    [DATE]                    DATETIME        NULL,
    [CLIENT_NAME]             NVARCHAR (250)  NULL,
    [TRANSACTION_NO]          NVARCHAR (50)   NULL,
    [DESCRIPTION]             NVARCHAR (250)  NULL,
    [AGREEMENT_NO]            NVARCHAR (50)   NULL,
    [CURRENCY]                NVARCHAR (3)    NULL,
    [RATE]                    DECIMAL (18, 6) NULL,
    [ORIG_AMOUNT]             DECIMAL (18, 2) NULL,
    [BASE_AMOUNNT]            DECIMAL (18, 2) NULL,
    [BRANCH_NAME]             NVARCHAR (50)   NULL,
    [GL_LINK_NAME]            NVARCHAR (50)   NULL,
    [IS_CONDITION]            NVARCHAR (1)    NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL
);

