CREATE TABLE [dbo].[RPT_BANK_BOOK] (
    [USER_ID]            NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]       NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]       NVARCHAR (250)  NOT NULL,
    [FILTER_DATA_TYPE]   NVARCHAR (50)   NULL,
    [FILTER_FROM_DATE]   DATETIME        NULL,
    [FILTER_TO_DATE]     DATETIME        NULL,
    [FILTER_BRANCH_CODE] NVARCHAR (50)   NULL,
    [FILTER_BANK_CODE]   NVARCHAR (50)   NULL,
    [FILTER_BANK_NAME]   NVARCHAR (250)  NULL,
    [FILTER_SALDO_AWAL]  DECIMAL (18, 2) NULL,
    [BANK_NAME]          NVARCHAR (50)   NULL,
    [BANK_ACCOUNT_NO]    NVARCHAR (50)   NULL,
    [DATE]               DATETIME        NULL,
    [CLIENT_NAME]        NVARCHAR (250)  NULL,
    [TRANSACTION_NO]     NVARCHAR (50)   NULL,
    [DESCRIPTION]        NVARCHAR (250)  NULL,
    [AGREEMENT_NO]       NVARCHAR (50)   NULL,
    [CURRENCY]           NVARCHAR (3)    NULL,
    [RATE]               DECIMAL (18, 6) NULL,
    [DEBET]              DECIMAL (18, 2) NULL,
    [CREDIT]             DECIMAL (18, 2) NULL,
    [BALANCE]            DECIMAL (18, 2) NULL,
    [SALDO_AKHIR]        DECIMAL (18, 2) NULL,
    [BRANCH_NAME]        NVARCHAR (50)   NULL,
    [IS_CONDITION]       NVARCHAR (1)    NULL,
    [CRE_BY]             NVARCHAR (15)   NOT NULL,
    [CRE_DATE]           DATETIME        NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [MOD_BY]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [VALUE_DATE]         DATETIME        NULL,
    [DATA_TYPE]          NVARCHAR (50)   NULL
);


GO
CREATE NONCLUSTERED INDEX [RPT_BANK_BOOK_USER_ID]
    ON [dbo].[RPT_BANK_BOOK]([USER_ID] ASC);

