CREATE TABLE [dbo].[SYS_JOB_TASKLIST] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [TYPE]           NVARCHAR (20)   NOT NULL,
    [DESCRIPTION]    NVARCHAR (250)  NOT NULL,
    [SP_NAME]        NVARCHAR (250)  NOT NULL,
    [ORDER_NO]       INT             NOT NULL,
    [IS_ACTIVE]      NVARCHAR (1)    NOT NULL,
    [LAST_ID]        BIGINT          NOT NULL,
    [ROW_TO_PROCESS] INT             CONSTRAINT [DF_SYS_JOB_TASKLIST_ROW_TO_PROCESS_1] DEFAULT ((10)) NOT NULL,
    [EOD_STATUS]     NVARCHAR (20)   NULL,
    [EOD_REMARK]     NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_SYS_JOB_TASKLIST] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[SYS_JOB_TASKLIST_Delete_Audit]    
			ON [dbo].[SYS_JOB_TASKLIST]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_JOB_TASKLIST]
([CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_JOB_TASKLIST_Update_Audit]      
			ON [dbo].[SYS_JOB_TASKLIST]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TYPE]) THEN '[TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([SP_NAME]) THEN '[SP_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([ORDER_NO]) THEN '[ORDER_NO]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([LAST_ID]) THEN '[LAST_ID]-' ELSE '' END + 
CASE WHEN UPDATE([ROW_TO_PROCESS]) THEN '[ROW_TO_PROCESS]-' ELSE '' END + 
CASE WHEN UPDATE([EOD_STATUS]) THEN '[EOD_STATUS]-' ELSE '' END + 
CASE WHEN UPDATE([EOD_REMARK]) THEN '[EOD_REMARK]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_JOB_TASKLIST]
([CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_JOB_TASKLIST]
([CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[SYS_JOB_TASKLIST_Insert_Audit] 
			ON [dbo].[SYS_JOB_TASKLIST]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_JOB_TASKLIST]
([CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[DESCRIPTION],[SP_NAME],[ORDER_NO],[IS_ACTIVE],[LAST_ID],[ROW_TO_PROCESS],[EOD_STATUS],[EOD_REMARK],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'PULL, IN, OUT', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_JOB_TASKLIST', @level2type = N'COLUMN', @level2name = N'TYPE';

