CREATE TABLE [dbo].[XXX_TEMP2] (
    [PAYMENT_FINANCE]          NVARCHAR (50)   NULL,
    [PAYMENT_REQ_FINANCE]      NVARCHAR (50)   NOT NULL,
    [PAYMENT_AMS]              NVARCHAR (50)   NOT NULL,
    [PAYMENT_TRANSACTION_CODE] NVARCHAR (50)   NULL,
    [AGREEMENT_FINANCE]        NVARCHAR (50)   NULL,
    [AGREEMENT_AMS]            NVARCHAR (50)   NULL,
    [TAX_FINANCE]              NVARCHAR (50)   NULL,
    [TAX_AMS]                  NVARCHAR (50)   NULL,
    [DESC_FINANCE]             NVARCHAR (4000) NULL,
    [DESC_AMS]                 NVARCHAR (4000) NULL
);

