CREATE TABLE [dbo].[XXX_BANK_MUTATION_20240820] (
    [CODE]             NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]      NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]      NVARCHAR (250)  NOT NULL,
    [BRANCH_BANK_CODE] NVARCHAR (50)   NOT NULL,
    [BRANCH_BANK_NAME] NVARCHAR (250)  NOT NULL,
    [GL_LINK_CODE]     NVARCHAR (50)   NOT NULL,
    [BALANCE_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL
);

