CREATE TABLE [dbo].[XXX_BANK_MUTATION_HISTORY_20240820] (
    [ID]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [BANK_MUTATION_CODE] NVARCHAR (50)   NOT NULL,
    [TRANSACTION_DATE]   DATETIME        NOT NULL,
    [VALUE_DATE]         DATETIME        NOT NULL,
    [SOURCE_REFF_CODE]   NVARCHAR (50)   NULL,
    [SOURCE_REFF_NAME]   NVARCHAR (250)  NULL,
    [ORIG_AMOUNT]        DECIMAL (18, 2) NOT NULL,
    [ORIG_CURRENCY_CODE] NVARCHAR (3)    NOT NULL,
    [EXCH_RATE]          DECIMAL (18, 6) NOT NULL,
    [BASE_AMOUNT]        DECIMAL (18, 2) NOT NULL,
    [IS_RECONCILE]       NVARCHAR (1)    NOT NULL,
    [REMARKS]            NVARCHAR (4000) NOT NULL,
    [CRE_DATE]           DATETIME        NOT NULL,
    [CRE_BY]             NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_BY]             NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)   NOT NULL
);

