CREATE TABLE [dbo].[xxx_deposit_allocation_2024_08_31] (
    [CODE]                     NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [ALLOCATION_STATUS]        NVARCHAR (10)   NOT NULL,
    [ALLOCATION_TRX_DATE]      DATETIME        NOT NULL,
    [ALLOCATION_VALUE_DATE]    DATETIME        NOT NULL,
    [ALLOCATION_ORIG_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [ALLOCATION_CURRENCY_CODE] NVARCHAR (3)    NOT NULL,
    [ALLOCATION_EXCH_RATE]     DECIMAL (18, 6) NOT NULL,
    [ALLOCATION_BASE_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [ALLOCATIONT_REMARKS]      NVARCHAR (4000) NOT NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NOT NULL,
    [DEPOSIT_CODE]             NVARCHAR (50)   NOT NULL,
    [DEPOSIT_TYPE]             NVARCHAR (15)   NULL,
    [DEPOSIT_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [DEPOSIT_GL_LINK_CODE]     NVARCHAR (50)   NOT NULL,
    [IS_RECEIVED_REQUEST]      NVARCHAR (1)    NOT NULL,
    [REVERSAL_CODE]            NVARCHAR (50)   NULL,
    [REVERSAL_DATE]            DATETIME        NULL,
    [VOUCHER_NO]               NVARCHAR (50)   NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL
);

