CREATE TABLE [dbo].[XXX_CASHIER_TRANSACTION_20250317] (
    [CODE]                        NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                 NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                 NVARCHAR (250)  NOT NULL,
    [CASHIER_MAIN_CODE]           NVARCHAR (50)   NOT NULL,
    [CASHIER_STATUS]              NVARCHAR (10)   NOT NULL,
    [CASHIER_TRX_DATE]            DATETIME        NOT NULL,
    [CASHIER_VALUE_DATE]          DATETIME        NULL,
    [CASHIER_TYPE]                NVARCHAR (10)   NOT NULL,
    [CASHIER_ORIG_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [CASHIER_CURRENCY_CODE]       NVARCHAR (3)    NOT NULL,
    [CASHIER_EXCH_RATE]           DECIMAL (18, 6) NOT NULL,
    [CASHIER_BASE_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [CASHIER_REMARKS]             NVARCHAR (4000) NOT NULL,
    [RECEIVED_REQUEST_CODE]       NVARCHAR (50)   NULL,
    [AGREEMENT_NO]                NVARCHAR (50)   NULL,
    [DEPOSIT_AMOUNT]              DECIMAL (18, 2) NOT NULL,
    [IS_USE_DEPOSIT]              NVARCHAR (1)    NOT NULL,
    [DEPOSIT_USED_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [RECEIVED_AMOUNT]             DECIMAL (18, 2) NOT NULL,
    [RECEIPT_CODE]                NVARCHAR (50)   NULL,
    [IS_RECEIVED_REQUEST]         NVARCHAR (1)    NOT NULL,
    [CARD_RECEIPT_REFF_NO]        NVARCHAR (50)   NULL,
    [CARD_BANK_NAME]              NVARCHAR (250)  NULL,
    [CARD_ACCOUNT_NAME]           NVARCHAR (250)  NULL,
    [BRANCH_BANK_CODE]            NVARCHAR (50)   NOT NULL,
    [BRANCH_BANK_NAME]            NVARCHAR (250)  NOT NULL,
    [BANK_GL_LINK_CODE]           NVARCHAR (50)   NULL,
    [PDC_CODE]                    NVARCHAR (50)   NULL,
    [PDC_NO]                      NVARCHAR (50)   NULL,
    [RECEIVED_FROM]               NVARCHAR (50)   NOT NULL,
    [RECEIVED_COLLECTOR_CODE]     NVARCHAR (50)   NULL,
    [RECEIVED_COLLECTOR_NAME]     NVARCHAR (250)  NULL,
    [RECEIVED_PAYOR_NAME]         NVARCHAR (250)  NULL,
    [RECEIVED_PAYOR_AREA_NO_HP]   NVARCHAR (4)    NULL,
    [RECEIVED_PAYOR_NO_HP]        NVARCHAR (15)   NULL,
    [RECEIVED_PAYOR_REFERENCE_NO] NVARCHAR (50)   NULL,
    [REVERSAL_CODE]               NVARCHAR (50)   NULL,
    [REVERSAL_DATE]               DATETIME        NULL,
    [PRINT_COUNT]                 INT             NOT NULL,
    [PRINT_MAX_COUNT]             INT             NOT NULL,
    [REFF_NO]                     NVARCHAR (250)  NULL,
    [IS_RECONCILE]                NVARCHAR (1)    NOT NULL,
    [RECONCILE_DATE]              DATETIME        NULL,
    [VOUCHER_NO]                  NVARCHAR (50)   NULL,
    [CRE_DATE]                    DATETIME        NOT NULL,
    [CRE_BY]                      NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                    DATETIME        NOT NULL,
    [MOD_BY]                      NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [BANK_ACCOUNT_NAME]           NVARCHAR (250)  NULL,
    [BANK_ACCOUNT_NO]             NVARCHAR (50)   NULL
);

