CREATE TABLE [dbo].[XXX_RECEIVED_REQUEST_AFTER_EOM_20250731] (
    [CODE]                      NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]               NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]               NVARCHAR (250)  NOT NULL,
    [RECEIVED_SOURCE]           NVARCHAR (50)   NOT NULL,
    [RECEIVED_REQUEST_DATE]     DATETIME        NOT NULL,
    [RECEIVED_SOURCE_NO]        NVARCHAR (50)   NOT NULL,
    [RECEIVED_STATUS]           NVARCHAR (10)   NOT NULL,
    [RECEIVED_CURRENCY_CODE]    NVARCHAR (3)    NOT NULL,
    [RECEIVED_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [RECEIVED_REMARKS]          NVARCHAR (4000) NOT NULL,
    [RECEIVED_TRANSACTION_CODE] NVARCHAR (50)   NULL,
    [BRANCH_BANK_CODE]          NVARCHAR (50)   NULL,
    [BRANCH_BANK_NAME]          NVARCHAR (250)  NULL,
    [BRANCH_BANK_GL_LINK_CODE]  NVARCHAR (50)   NULL,
    [CRE_DATE]                  DATETIME        NOT NULL,
    [CRE_BY]                    NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                  DATETIME        NOT NULL,
    [MOD_BY]                    NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NOT NULL
);

