CREATE TABLE [dbo].[DOC_INTERFACE_COLLATERAL_SWITCH] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [SOURCE_TYPE]    NVARCHAR (50)   NOT NULL,
    [SOURCE_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [SWITCH_STATUS]  NVARCHAR (10)   NOT NULL,
    [SWITCH_DATE]    DATETIME        NOT NULL,
    [SWITCH_REMARKS] NVARCHAR (4000) NOT NULL,
    [JOB_STATUS]     NVARCHAR (20)   CONSTRAINT [DF_DOC_INTERFACE_COLLATERAL_SWITCH_JOB_STATUS] DEFAULT (N'HOLD') NOT NULL,
    [FAILED_REMARK]  NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DOC_INTERFACE_COLLATERAL_SWITCH] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

