CREATE TABLE [dbo].[FILE_IFINDOC_DOCUMENT_MAIN] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [MODULE]         NVARCHAR (15)  NOT NULL,
    [DOC_TYPE]       NVARCHAR (250) NOT NULL,
    [DOC_NO]         NVARCHAR (50)  NOT NULL,
    [DOC_NAME]       NVARCHAR (250) NOT NULL,
    [DOC_FILE]       IMAGE          NOT NULL,
    [DOC_DATE]       DATETIME       NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_FILE_IFINDOC_DOCUMENT_MAIN] PRIMARY KEY CLUSTERED ([ID] ASC)
);

