CREATE TABLE [dbo].[MIGRASI_SPBPKB_1] (
    [BRANCH_CODE]              NVARCHAR (50)   NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NULL,
    [COVER_NOTE_NO]            NVARCHAR (50)   NULL,
    [COVER_NOTE_DATE]          DATETIME        NULL,
    [COVER_NOTE_EXP_DATE]      DATETIME        NULL,
    [VENDOR_CODE]              NVARCHAR (50)   NULL,
    [VENDOR_NAME]              NVARCHAR (250)  NULL,
    [VENDOR_ADDRESS]           NVARCHAR (4000) NULL,
    [VENDOR_PIC_NAME]          NVARCHAR (250)  NULL,
    [VENDOR_PIC_AREA_PHONE_NO] NVARCHAR (4)    NULL,
    [VENDOR_PIC_PHONE_NO]      NVARCHAR (15)   NULL,
    [DOCUMENT_NAME]            NVARCHAR (50)   NULL,
    [COUNT_ASSET]              INT             NULL,
    [RECEIVED_ASSET]           INT             NULL,
    [EXTEND_COUNT]             INT             NULL,
    [FILE_NAME]                NVARCHAR (250)  NULL,
    [PATHS]                    NVARCHAR (250)  NULL,
    [STATUS]                   NVARCHAR (10)   NULL,
    [REMARKS]                  NVARCHAR (500)  NULL,
    [REPLACEMENT_CODE]         NVARCHAR (50)   NULL,
    [CRE_BY]                   NVARCHAR (15)   NULL,
    [CRE_DATE]                 DATETIME        NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NULL,
    [MOD_BY]                   NVARCHAR (15)   NULL,
    [MOD_DATE]                 DATETIME        NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NULL,
    [ID_MIGRATION]             BIGINT          NULL
);

