CREATE TABLE [dbo].[REPLACEMENT_REQUEST_DETAIL] (
    [ID]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [REPLACEMENT_REQUEST_ID] BIGINT        NULL,
    [ASSET_NO]               NVARCHAR (50) NULL,
    [STATUS]                 NCHAR (10)    NULL,
    [REPLACEMENT_CODE]       NVARCHAR (50) NULL,
    [DOCUMENT_MAIN_CODE]     NVARCHAR (50) NULL,
    [CRE_BY]                 NVARCHAR (15) NOT NULL,
    [CRE_DATE]               DATETIME      NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15) NOT NULL,
    [MOD_BY]                 NVARCHAR (15) NOT NULL,
    [MOD_DATE]               DATETIME      NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15) NOT NULL,
    [MIGRATION_ID]           BIGINT        NULL,
    [COVER_NOTE_NO]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_REPLACEMENT_REQUEST_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REPLACEMENT_REQUEST_DETAIL_REPLACEMENT_REQUEST] FOREIGN KEY ([REPLACEMENT_REQUEST_ID]) REFERENCES [dbo].[REPLACEMENT_REQUEST] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_REPLACEMENT_REQUEST_DETAIL_REPLACEMENT_REQUEST_ID_20250615]
    ON [dbo].[REPLACEMENT_REQUEST_DETAIL]([REPLACEMENT_REQUEST_ID] ASC);

