CREATE TABLE [dbo].[Replacement_header] (
    [BRANCH_CODE]              NVARCHAR (10)  NULL,
    [BRANCH_NAME]              NVARCHAR (255) NULL,
    [COVER_NOTE_NO]            NVARCHAR (255) NULL,
    [COVER_NOTE_DATE]          DATETIME       NULL,
    [COVER_NOTE_EXP_DATE]      DATETIME       NULL,
    [VENDOR_CODE]              NVARCHAR (255) NULL,
    [VENDOR_NAME]              NVARCHAR (255) NULL,
    [VENDOR_ADDRESS]           NVARCHAR (255) NULL,
    [VENDOR_PIC_NAME]          NVARCHAR (255) NULL,
    [VENDOR_PIC_AREA_PHONE_NO] NVARCHAR (255) NULL,
    [VENDOR_PIC_PHONE_NO]      NVARCHAR (50)  NULL,
    [Document_name]            NVARCHAR (255) NULL,
    [COUNT_ASSET]              REAL           NULL,
    [RECEIVED_ASSET]           NVARCHAR (255) NULL,
    [EXTEND_COUNT]             NVARCHAR (255) NULL,
    [FILE_NAME]                NVARCHAR (255) NULL,
    [PATHS]                    NVARCHAR (255) NULL,
    [STATUS]                   NVARCHAR (255) NULL,
    [REMARKS]                  NVARCHAR (255) NULL,
    [REPLACEMENT_CODE]         NVARCHAR (255) NULL,
    [CRE_BY]                   NVARCHAR (255) NULL,
    [CRE_DATE]                 DATETIME       NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (255) NULL,
    [MOD_BY]                   NVARCHAR (255) NULL,
    [MOD_DATE]                 DATETIME       NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (255) NULL,
    [ID_MIGRATION]             NVARCHAR (255) NULL
);

