CREATE TABLE [dbo].[RPT_BORROW_BPKB] (
    [USER_ID]             NVARCHAR (50)  NOT NULL,
    [FILTER_BRANCH_CODE]  NVARCHAR (50)  NOT NULL,
    [FILTER_BRANCH_NAME]  NVARCHAR (250) NOT NULL,
    [FILTER_AS_OF_DATE]   DATETIME       NOT NULL,
    [REPORT_COMPANY]      NVARCHAR (250) NULL,
    [REPORT_TITLE]        NVARCHAR (250) NULL,
    [REPORT_IMAGE]        NVARCHAR (250) NULL,
    [BRANCH_NAME]         NVARCHAR (250) NULL,
    [AGREEMENT_NO]        NVARCHAR (250) NULL,
    [CLIENT_NAME]         NVARCHAR (250) NULL,
    [CHASIS_NO]           NVARCHAR (50)  NULL,
    [ENGINE_NO]           NVARCHAR (50)  NULL,
    [BPKB_NO]             NVARCHAR (50)  NULL,
    [YEAR]                NVARCHAR (4)   NULL,
    [PLAT_NO]             NVARCHAR (50)  NULL,
    [FAKTUR]              NVARCHAR (50)  NULL,
    [KWINTASI]            NVARCHAR (50)  NULL,
    [REGISTERED_NAME]     NVARCHAR (250) NULL,
    [REASON]              NVARCHAR (400) NULL,
    [BORROWED_DATE]       DATETIME       NULL,
    [RETURNED_DATE]       DATETIME       NULL,
    [RESPONS_PERSON]      NVARCHAR (250) NULL,
    [MO]                  NVARCHAR (50)  NULL,
    [CRE_DATE]            DATETIME       NOT NULL,
    [CRE_BY]              NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)  NOT NULL,
    [MOD_DATE]            DATETIME       NOT NULL,
    [MOD_BY]              NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)  NOT NULL,
    [IS_CONDITION]        NVARCHAR (1)   NULL,
    [ITEM_NAME]           NVARCHAR (250) NULL,
    [INPUT_BY]            NVARCHAR (50)  NULL,
    [CHECKED_BY]          NVARCHAR (50)  NULL,
    [ACKNOWLEDGE_BY]      NVARCHAR (50)  NULL,
    [JABATAN_ACKNOWLEDGE] NVARCHAR (50)  NULL,
    [NAMA_USER]           NVARCHAR (50)  NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_BORROW_BPKB_USER_ID_20250615]
    ON [dbo].[RPT_BORROW_BPKB]([USER_ID] ASC)
    INCLUDE([REASON]);

