CREATE TABLE [dbo].[RPT_RETURN_OF_LOAN_BPKB] (
    [USER_ID]            NVARCHAR (50)  NOT NULL,
    [FILTER_BRANCH_CODE] NVARCHAR (50)  NOT NULL,
    [FILTER_BRANCH_NAME] NVARCHAR (250) NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]       NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]       NVARCHAR (50)  NULL,
    [BRANCH_CODE]        NVARCHAR (50)  NULL,
    [BRANCH_NAME]        NVARCHAR (50)  NULL,
    [AS_OF_DATE]         DATETIME       NULL,
    [AGREEMENT_NO]       NVARCHAR (50)  NULL,
    [CLIENT_NAME]        NVARCHAR (50)  NULL,
    [SEQ]                NVARCHAR (50)  NULL,
    [BPKB_NO]            NVARCHAR (50)  NULL,
    [CHASSIS_NO]         NVARCHAR (50)  NULL,
    [ENGINE_NO]          NVARCHAR (50)  NULL,
    [PLAT_NO]            NVARCHAR (50)  NULL,
    [RETURN_DATE]        DATETIME       NULL,
    [UPDATE_BY]          NVARCHAR (50)  NULL,
    [IS_CONDITION]       NVARCHAR (1)   NULL
);

