CREATE TABLE [dbo].[RPT_RELEASED_BORROW_BPKB_SUMMARY] (
    [USER_ID]        NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY] NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]   NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]   NVARCHAR (50)  NULL,
    [BRANCH_CODE]    NVARCHAR (50)  NULL,
    [BRANCH_NAME]    NVARCHAR (50)  NULL,
    [PRODUCT]        NVARCHAR (50)  NULL,
    [REASON]         NVARCHAR (50)  NULL,
    [TOTAL]          INT            NULL
);

