CREATE TABLE [dbo].[RPT_DOCUMENT_AND_STATUS] (
    [USER_ID]            NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]       NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]       NVARCHAR (250) NOT NULL,
    [FILTER_BRANCH_CODE] NVARCHAR (50)  NOT NULL,
    [FILTER_LOCKER_CODE] NVARCHAR (50)  NOT NULL,
    [FILTER_LOCKER_NAME] NVARCHAR (250) NOT NULL,
    [BRANCH_CODE]        NVARCHAR (50)  NOT NULL,
    [BRANCH_NAME]        NVARCHAR (250) NOT NULL,
    [ASSET_NO]           NVARCHAR (50)  NOT NULL,
    [ASSET_NAME]         NVARCHAR (250) NOT NULL,
    [DOCUMENT_CODE]      NVARCHAR (50)  NOT NULL,
    [DOCUMENT_NAME]      NVARCHAR (250) NOT NULL,
    [DOCUMENT_NO]        NVARCHAR (50)  NOT NULL,
    [DOCUMENT_TYPE]      NVARCHAR (250) NOT NULL,
    [EXPIRED_DATE]       DATETIME       NOT NULL,
    [LOCATION]           NVARCHAR (250) NOT NULL,
    [LOCKER]             NVARCHAR (250) NOT NULL,
    [DRAWER]             NVARCHAR (250) NOT NULL,
    [ROW]                NVARCHAR (250) NOT NULL,
    [PLAT_NO]            NVARCHAR (20)  NULL,
    [CHASSIS_NO]         NVARCHAR (50)  NULL,
    [ENGINE_NO]          NVARCHAR (50)  NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [IS_CONDITION]       NVARCHAR (1)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_DOCUMENT_AND_STATUS_USER_ID_20250615]
    ON [dbo].[RPT_DOCUMENT_AND_STATUS]([USER_ID] ASC);

