CREATE TABLE [dbo].[RPT_SEND_OR_RELEASE_DOCUMENT_DETAIL] (
    [USER_ID]        NVARCHAR (50)   NOT NULL,
    [MOVEMENT_CODE]  NVARCHAR (50)   NULL,
    [DOCUMENT_NAME]  NVARCHAR (250)  NULL,
    [DOCUMENT_NO]    NVARCHAR (50)   NULL,
    [REMARKS]        NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NULL,
    [CRE_BY]         NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NULL,
    [MOD_DATE]       DATETIME        NULL,
    [MOD_BY]         NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NULL
);

