CREATE TABLE [dbo].[RPT_SERAH_TERIMA_DOCUMENT_RELEASE_PERMANENT_DETAIL] (
    [USER_ID]                       NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]                NVARCHAR (250) NULL,
    [REPORT_TITLE]                  NVARCHAR (250) NULL,
    [REPORT_IMAGE]                  NVARCHAR (250) NULL,
    [TANGGAL_PERJANJIAN]            DATETIME       NULL,
    [VALUE_DATE]                    DATETIME       NULL,
    [LESSEE_OR_CONSUMEN]            NVARCHAR (50)  NULL,
    [PERJANJIAN_LESSEE_OR_CONSUMEN] NVARCHAR (50)  NULL,
    [OBJEK_PEMBIAYAAN]              NVARCHAR (250) NULL,
    [DOKUMEN_YANG_DIKELUARKAN]      NVARCHAR (250) NULL
);

