CREATE TABLE [dbo].[RPT_RECEIVED_ADDITIONAL_COLLATERAL_DETAIL] (
    [USER_ID]        NVARCHAR (50)  NOT NULL,
    [DOC_CODE]       NVARCHAR (50)  NULL,
    [AGREEMENT_NO]   NVARCHAR (50)  NULL,
    [CUSTOMER_NAME]  NVARCHAR (250) NULL,
    [DOCUMENT_NAME]  NVARCHAR (50)  NULL,
    [DOCUMENT_NO]    NVARCHAR (50)  NULL,
    [DESCRIPTION]    NVARCHAR (250) NULL,
    [RECEIVING_DATE] DATETIME       NULL,
    [INPUT_BY]       NVARCHAR (50)  NULL
);

