CREATE TABLE [dbo].[RPT_DAILY_RECEIVED_OF_LEASED_GOODS_DETAIL] (
    [USER_ID]       NVARCHAR (50)  NOT NULL,
    [DOC_CODE]      NVARCHAR (50)  NULL,
    [PRODUCT_TYPE]  NVARCHAR (50)  NULL,
    [AGREEMENT_NO]  NVARCHAR (50)  NULL,
    [CUSTOMER_NAME] NVARCHAR (250) NULL,
    [BRAND]         NVARCHAR (250) NULL,
    [TYPE_MODEL]    NVARCHAR (250) NULL,
    [REGISTER_NAME] NVARCHAR (250) NULL,
    [BPKB_NO]       NVARCHAR (50)  NULL,
    [FAKTUR]        NVARCHAR (50)  NULL,
    [NIK]           NVARCHAR (50)  NULL,
    [FORM_A]        NVARCHAR (50)  NULL,
    [SPH_NO]        NVARCHAR (50)  NULL,
    [KWITANSI_NO]   NVARCHAR (50)  NULL,
    [SUPPLIER]      NVARCHAR (250) NULL,
    [CHASIS_NO]     NVARCHAR (50)  NULL,
    [ENGINE_NO]     NVARCHAR (50)  NULL,
    [YEAR]          NVARCHAR (4)   NULL,
    [INPUT_DATE]    DATETIME       NULL,
    [INPUT_BY]      NVARCHAR (50)  NULL
);

