CREATE TABLE [dbo].[RPT_TANDA_TERIMA_DOKUMEN_RELEASE_DETAIL] (
    [USER_ID]        NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY] NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]   NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]   NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (250)  NULL,
    [DOCUMENT_NAME]  NVARCHAR (250)  NULL,
    [DOCUMENT_NO]    NVARCHAR (250)  NULL,
    [REASON]         NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NULL,
    [CRE_BY]         NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NULL,
    [MOD_DATE]       DATETIME        NULL,
    [MOD_BY]         NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NULL,
    [ASSET_CODE]     NVARCHAR (50)   NULL,
    [MERK_NAME]      NVARCHAR (400)  NULL,
    [ENGINE_NO]      NVARCHAR (50)   NULL,
    [CHASSIS_NO]     NVARCHAR (50)   NULL,
    [PLAT_NO]        NVARCHAR (50)   NULL,
    [BPKB_NAME]      NVARCHAR (250)  NULL
);

