CREATE TABLE [dbo].[RPT_ADH_COLLATERAL_DETAIL] (
    [USER_ID]       NVARCHAR (50)  NOT NULL,
    [DOC_CODE]      NVARCHAR (50)  NULL,
    [AGREEMENT_NO]  NVARCHAR (50)  NULL,
    [CUSTOMER_NAME] NVARCHAR (250) NULL,
    [TRX_DATE]      DATETIME       NULL,
    [RECEIVED_DATE] DATETIME       NULL,
    [DOCUMENT_NAME] NVARCHAR (50)  NULL,
    [DOCUMENT_NO]   NVARCHAR (50)  NULL,
    [DESCRIPTION]   NVARCHAR (250) NULL,
    [INPUT_BY]      NVARCHAR (50)  NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_ADH_COLLATERAL_DETAIL_USER_ID_20250615]
    ON [dbo].[RPT_ADH_COLLATERAL_DETAIL]([USER_ID] ASC)
    INCLUDE([AGREEMENT_NO]);

