CREATE TABLE [dbo].[RPT_SERAH_TERIMA_DOCUMENT_BORROW_DETAIL] (
    [USER_ID]    NVARCHAR (50)  NOT NULL,
    [MERK_NAME]  NVARCHAR (250) NULL,
    [ENGINE_NO]  NVARCHAR (50)  NULL,
    [CHASIS_NO]  NVARCHAR (50)  NULL,
    [POLICE_NO]  NVARCHAR (50)  NULL,
    [ASSET_CODE] NVARCHAR (50)  NULL,
    [BPKB_NAME]  NVARCHAR (50)  NULL
);

