CREATE TABLE [dbo].[RPT_DOCUMENT_REPLACEMENT] (
    [USER_ID]             NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]      NVARCHAR (50)  NULL,
    [REPORT_TITLE]        NVARCHAR (50)  NULL,
    [REPORT_IMAGE]        NVARCHAR (50)  NULL,
    [REPLACEMENT_NO]      NVARCHAR (50)  NULL,
    [REPLACEMENT_DATE]    DATETIME       NULL,
    [ASSET_NO]            NVARCHAR (50)  NULL,
    [ASSET_NAME]          NVARCHAR (50)  NULL,
    [DOCUMENT_NAME]       NVARCHAR (50)  NULL,
    [TYPE]                NVARCHAR (50)  NULL,
    [COVER_NOTE_NO]       NVARCHAR (50)  NULL,
    [COVER_NOTE_DATE]     DATETIME       NULL,
    [COVER_NOTE_EXP_DATE] DATETIME       NULL,
    [STNK_NAME]           NVARCHAR (50)  NULL,
    [STNK_TAX_DATE]       DATETIME       NULL,
    [STNK_EXP_DATE]       DATETIME       NULL,
    [BPKB_NO]             NVARCHAR (50)  NULL,
    [BPKB_NAME]           NVARCHAR (50)  NULL,
    [BPKB_DATE]           DATETIME       NULL,
    [BPKB_ADDRESS]        NVARCHAR (250) NULL,
    [CRE_DATE]            DATETIME       NULL,
    [CRE_BY]              NVARCHAR (15)  NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)  NULL,
    [MOD_DATE]            DATETIME       NULL,
    [MOD_BY]              NVARCHAR (15)  NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)  NULL
);

