CREATE TABLE [dbo].[RPT_RELEASED_BORROW_BPKB] (
    [USER_ID]            NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]       NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]       NVARCHAR (50)  NULL,
    [FILTER_BRANCH_NAME] NVARCHAR (250) NULL,
    [BRANCH_CODE]        NVARCHAR (50)  NULL,
    [BRANCH_NAME]        NVARCHAR (50)  NULL,
    [AS_OF_DATE]         DATETIME       NULL,
    [AGREEMENT_NO]       NVARCHAR (50)  NULL,
    [CLIENT_NAME]        NVARCHAR (50)  NULL,
    [SEQ]                INT            NULL,
    [MERK]               NVARCHAR (50)  NULL,
    [MODEL]              NVARCHAR (50)  NULL,
    [TYPE]               NVARCHAR (50)  NULL,
    [CHASSIS_NO]         NVARCHAR (50)  NULL,
    [ENGINE_NO]          NVARCHAR (50)  NULL,
    [BPKB_NO]            NVARCHAR (50)  NULL,
    [YEAR]               NVARCHAR (50)  NULL,
    [PLAT_NO]            NVARCHAR (50)  NULL,
    [FAKTUR]             NVARCHAR (50)  NULL,
    [KWITANSI]           NVARCHAR (50)  NULL,
    [REGISTERED_NAME]    NVARCHAR (50)  NULL,
    [REASON]             NVARCHAR (50)  NULL,
    [BORROWED_DATE]      DATETIME       NULL,
    [RETURNED_DATE]      DATETIME       NULL,
    [RESPONS_PERSON]     NVARCHAR (50)  NULL,
    [MO]                 NVARCHAR (50)  NULL,
    [IS_CONDITION]       NVARCHAR (1)   NULL
);

