CREATE TABLE [dbo].[RPT_ADDITIONAL_COLLATERAL] (
    [USER_ID]            NVARCHAR (50)  NOT NULL,
    [FILTER_BRANCH_CODE] NVARCHAR (50)  NOT NULL,
    [FILTER_BRANCH_NAME] NVARCHAR (250) NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NULL,
    [REPORT_TITLE]       NVARCHAR (250) NULL,
    [REPORT_IMAGE]       NVARCHAR (250) NULL,
    [AGREEMENT_NO]       NVARCHAR (50)  NULL,
    [BRANCH_NAME]        NVARCHAR (250) NULL,
    [CLIENT_NAME]        NVARCHAR (250) NULL,
    [DATE]               DATETIME       NULL,
    [RECEIVED_DATE]      DATETIME       NULL,
    [DOCUMENT_NAME]      NVARCHAR (250) NULL,
    [DOCUMENT_NO]        NVARCHAR (50)  NULL,
    [REMARK]             NVARCHAR (250) NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [IS_CONDITION]       NVARCHAR (1)   NULL
);

