CREATE TABLE [dbo].[RPT_MONITORING_BPKB] (
    [USER_ID]            NVARCHAR (50)  NOT NULL,
    [FILTER_FROM_DATE]   DATETIME       NOT NULL,
    [FILTER_TO_DATE]     DATETIME       NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NULL,
    [REPORT_TITLE]       NVARCHAR (250) NULL,
    [REPORT_IMAGE]       NVARCHAR (250) NULL,
    [AGREEMENT_NO]       NVARCHAR (50)  NULL,
    [SEQ]                NVARCHAR (50)  NULL,
    [CUSTOMER_NAME]      NVARCHAR (250) NULL,
    [OBJECT_LEASED]      NVARCHAR (250) NULL,
    [YEAR]               NVARCHAR (4)   NULL,
    [CHASSIS_NO]         NVARCHAR (50)  NULL,
    [ENGINE_NO]          NVARCHAR (50)  NULL,
    [PLAT_NO]            NVARCHAR (50)  NULL,
    [SPBPKB_DATE]        DATETIME       NULL,
    [SPBPKB_NO]          NVARCHAR (50)  NULL,
    [NOW]                DATETIME       NULL,
    [AGING]              INT            NULL,
    [MONTHLY]            DECIMAL (9, 6) NULL,
    [DEALER]             NVARCHAR (250) NULL,
    [NO_TELP]            NVARCHAR (20)  NULL,
    [NAMA_PIC]           NVARCHAR (50)  NULL,
    [BAST_SPBPKB]        DATETIME       NULL,
    [CREATED]            DATETIME       NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [IS_CONDITION]       NVARCHAR (1)   NULL,
    [BAST_DATE]          DATETIME       NULL,
    [BPKB_RECEIVED_DATE] DATETIME       NULL,
    [AREA_BBN]           NVARCHAR (250) NULL
);

