CREATE TABLE [dbo].[RPT_COUNT_BPKB_DETAIL] (
    [USER_ID]           NVARCHAR (50)  NULL,
    [AGREEMENT_NO]      NVARCHAR (50)  NULL,
    [DOCUMENT_NO]       NVARCHAR (50)  NULL,
    [CUSTOMER]          NVARCHAR (250) NULL,
    [ASSET_NAME]        NVARCHAR (250) NULL,
    [ASSET_TYPE]        NVARCHAR (250) NULL,
    [ASSET_NO]          NVARCHAR (50)  NULL,
    [CHASSIS_NO]        NVARCHAR (50)  NULL,
    [ENGINE_NO]         NVARCHAR (50)  NULL,
    [YEAR]              NVARCHAR (4)   NULL,
    [TRX_DATE]          DATETIME       NULL,
    [REGISTERED_NAME]   NVARCHAR (250) NULL,
    [BPKB_NO]           NVARCHAR (250) NULL,
    [DOC_TYPE]          NVARCHAR (250) NULL,
    [PLAT_NO]           NVARCHAR (250) NULL,
    [AGREEMENT_STATUS]  NVARCHAR (250) NULL,
    [DOCUMENT_LOCATION] NVARCHAR (250) NULL,
    [OUTLET]            NVARCHAR (250) NULL,
    [BRANCH_NAME]       NVARCHAR (250) NULL,
    [PRODUCT]           NVARCHAR (250) NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_COUNT_BPKB_DETAIL_20231004]
    ON [dbo].[RPT_COUNT_BPKB_DETAIL]([USER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_COUNT_BPKB_DETAIL_20231004_2]
    ON [dbo].[RPT_COUNT_BPKB_DETAIL]([USER_ID] ASC)
    INCLUDE([AGREEMENT_NO], [ASSET_TYPE], [ASSET_NO], [BRANCH_NAME], [PRODUCT]);

