CREATE TABLE [dbo].[RPT_TANDA_TERIMA_JAMINAN_RECEIVE_DETAIL] (
    [USER_ID]       NVARCHAR (50)  NOT NULL,
    [DOC_CODE]      NVARCHAR (50)  NULL,
    [AGREEMENT_NO]  NVARCHAR (50)  NULL,
    [CUSTOMER_NAME] NVARCHAR (250) NULL,
    [DOCUMENT_NAME] NVARCHAR (50)  NULL,
    [BPKB_NO]       NVARCHAR (50)  NULL,
    [RETURN_DATE]   DATETIME       NULL,
    [CHASIS_NO]     NVARCHAR (50)  NULL,
    [ENGINE_NO]     NVARCHAR (50)  NULL,
    [POLICE_NO]     NVARCHAR (50)  NULL,
    [UPDATE_BY]     NVARCHAR (50)  NULL
);

