CREATE TABLE [dbo].[RPT_SURAT_TAGIH_DETAIL] (
    [USER_ID]        NVARCHAR (50)  NOT NULL,
    [KENDARAAN]      NVARCHAR (250) NULL,
    [TAHUN]          NVARCHAR (4)   NULL,
    [NOMOR_RANGKA]   NVARCHAR (50)  NULL,
    [NOMOR_MESIN]    NVARCHAR (50)  NULL,
    [BPKB_ATAS_NAMA] NVARCHAR (250) NULL
);

