CREATE TABLE [dbo].[RPT_RELEASED_PERMANENT_BPKB] (
    [USER_ID]             NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]      NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]        NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]        NVARCHAR (50)  NULL,
    [FILTER_BRANCH_NAME]  NVARCHAR (250) NULL,
    [BRANCH_CODE]         NVARCHAR (50)  NULL,
    [BRANCH_NAME]         NVARCHAR (250) NULL,
    [FILTER_FROM_DATE]    DATETIME       NULL,
    [FILTER_TO_DATE]      DATETIME       NULL,
    [AGREEMENT_NO]        NVARCHAR (250) NULL,
    [CLIENT_NAME]         NVARCHAR (50)  NULL,
    [SEQ]                 INT            NULL,
    [MERK]                NVARCHAR (50)  NULL,
    [MODEL]               NVARCHAR (50)  NULL,
    [TYPE]                NVARCHAR (250) NULL,
    [CHASSIS_NO]          NVARCHAR (50)  NULL,
    [ENGINE_NO]           NVARCHAR (50)  NULL,
    [BPKB_NO]             NVARCHAR (50)  NULL,
    [YEAR]                INT            NULL,
    [PLAT_NO]             NVARCHAR (50)  NULL,
    [REASON]              NVARCHAR (450) NULL,
    [RELEASE_DATE]        DATETIME       NULL,
    [RELEASE_BY]          NVARCHAR (250) NULL,
    [NAMA_USER]           NVARCHAR (250) NULL,
    [NAMA_ACKNOWLEDGE]    NVARCHAR (50)  NULL,
    [JABATAN_ACKNOWLEDGE] NVARCHAR (250) NULL,
    [IS_CONDITION]        NVARCHAR (1)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_RELEASED_PERMANENT_BPKB_USER_ID_20250615]
    ON [dbo].[RPT_RELEASED_PERMANENT_BPKB]([USER_ID] ASC)
    INCLUDE([REASON]);

