CREATE TABLE [dbo].[SYS_AUDIT_DETAIL] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [AUDIT_CODE]     NVARCHAR (50)   NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [PROGRESS]       NVARCHAR (250)  NOT NULL,
    [REMARK]         NVARCHAR (4000) NOT NULL,
    [FILE_NAME]      NVARCHAR (250)  NULL,
    [PATHS]          NVARCHAR (250)  NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_SYS_AUDIT_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYS_AUDIT_DETAIL_SYS_AUDIT] FOREIGN KEY ([AUDIT_CODE]) REFERENCES [dbo].[SYS_AUDIT] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[SYS_AUDIT_DETAIL_Insert_Audit] 
			ON [dbo].[SYS_AUDIT_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_AUDIT_DETAIL]
([ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_AUDIT_DETAIL_Delete_Audit]    
			ON [dbo].[SYS_AUDIT_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_AUDIT_DETAIL]
([ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_AUDIT_DETAIL_Update_Audit]      
			ON [dbo].[SYS_AUDIT_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([AUDIT_CODE]) THEN '[AUDIT_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DATE]) THEN '[DATE]-' ELSE '' END + 
CASE WHEN UPDATE([PROGRESS]) THEN '[PROGRESS]-' ELSE '' END + 
CASE WHEN UPDATE([REMARK]) THEN '[REMARK]-' ELSE '' END + 
CASE WHEN UPDATE([FILE_NAME]) THEN '[FILE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PATHS]) THEN '[PATHS]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_AUDIT_DETAIL]
([ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_AUDIT_DETAIL]
([ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[AUDIT_CODE],[DATE],[PROGRESS],[REMARK],[FILE_NAME],[PATHS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END