CREATE TABLE [dbo].[SYS_CALENDER_EMPLOYEE] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [TITLE]          NVARCHAR (50) NOT NULL,
    [START]          NVARCHAR (50) NOT NULL,
    [ENDDAY]         NVARCHAR (50) NOT NULL,
    [CLASSNAME]      NVARCHAR (50) NOT NULL,
    [EMPLOYEE_CODE]  NVARCHAR (50) NOT NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NOT NULL
);


GO
    
			CREATE TRIGGER [dbo].[SYS_CALENDER_EMPLOYEE_Delete_Audit]    
			ON [dbo].[SYS_CALENDER_EMPLOYEE]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_CALENDER_EMPLOYEE]
([ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_CALENDER_EMPLOYEE_Update_Audit]      
			ON [dbo].[SYS_CALENDER_EMPLOYEE]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([TITLE]) THEN '[TITLE]-' ELSE '' END + 
CASE WHEN UPDATE([START]) THEN '[START]-' ELSE '' END + 
CASE WHEN UPDATE([ENDDAY]) THEN '[ENDDAY]-' ELSE '' END + 
CASE WHEN UPDATE([CLASSNAME]) THEN '[CLASSNAME]-' ELSE '' END + 
CASE WHEN UPDATE([EMPLOYEE_CODE]) THEN '[EMPLOYEE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_CALENDER_EMPLOYEE]
([ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_CALENDER_EMPLOYEE]
([ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[SYS_CALENDER_EMPLOYEE_Insert_Audit] 
			ON [dbo].[SYS_CALENDER_EMPLOYEE]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_CALENDER_EMPLOYEE]
([ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TITLE],[START],[ENDDAY],[CLASSNAME],[EMPLOYEE_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 