CREATE TABLE [dbo].[SYS_PREVIEW_LOG] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [REPORT_CODE]     NVARCHAR (50)  NOT NULL,
    [REPORT_NAME]     NVARCHAR (250) NOT NULL,
    [PREVIEW_DATE]    DATETIME       NOT NULL,
    [PREVIEW_BY_CODE] NVARCHAR (50)  NOT NULL,
    [PREVIEW_BY_NAME] NVARCHAR (250) NOT NULL,
    [PREVIEW_BY_IP]   NVARCHAR (50)  NOT NULL,
    [CRE_DATE]        DATETIME       NOT NULL,
    [CRE_BY]          NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)  NOT NULL,
    [MOD_DATE]        DATETIME       NOT NULL,
    [MOD_BY]          NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)  NOT NULL
);


GO
    
			CREATE TRIGGER [dbo].[SYS_PREVIEW_LOG_Insert_Audit] 
			ON [dbo].[SYS_PREVIEW_LOG]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_PREVIEW_LOG]
([ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_PREVIEW_LOG_Delete_Audit]    
			ON [dbo].[SYS_PREVIEW_LOG]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_PREVIEW_LOG]
([ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_PREVIEW_LOG_Update_Audit]      
			ON [dbo].[SYS_PREVIEW_LOG]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([REPORT_CODE]) THEN '[REPORT_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([REPORT_NAME]) THEN '[REPORT_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PREVIEW_DATE]) THEN '[PREVIEW_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([PREVIEW_BY_CODE]) THEN '[PREVIEW_BY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PREVIEW_BY_NAME]) THEN '[PREVIEW_BY_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PREVIEW_BY_IP]) THEN '[PREVIEW_BY_IP]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_PREVIEW_LOG]
([ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_PREVIEW_LOG]
([ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REPORT_CODE],[REPORT_NAME],[PREVIEW_DATE],[PREVIEW_BY_CODE],[PREVIEW_BY_NAME],[PREVIEW_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END