CREATE TABLE [dbo].[SYS_DOC_ACCESS_LOG] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [MODULE_NAME]      NVARCHAR (50)  NOT NULL,
    [TRANSACTION_NAME] NVARCHAR (250) NOT NULL,
    [TRANSACTION_NO]   NVARCHAR (50)  NOT NULL,
    [ACCESS_DATE]      DATETIME       NOT NULL,
    [ACESS_TYPE]       NVARCHAR (250) NOT NULL,
    [FILE_NAME]        NVARCHAR (250) NOT NULL,
    [PRINT_BY_CODE]    NVARCHAR (50)  NOT NULL,
    [PRINT_BY_NAME]    NVARCHAR (250) NOT NULL,
    [PRINT_BY_IP]      NVARCHAR (50)  NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL
);


GO
    
			CREATE TRIGGER [dbo].[SYS_DOC_ACCESS_LOG_Insert_Audit] 
			ON [dbo].[SYS_DOC_ACCESS_LOG]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_DOC_ACCESS_LOG]
([ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_DOC_ACCESS_LOG_Delete_Audit]    
			ON [dbo].[SYS_DOC_ACCESS_LOG]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_DOC_ACCESS_LOG]
([ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_DOC_ACCESS_LOG_Update_Audit]      
			ON [dbo].[SYS_DOC_ACCESS_LOG]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([MODULE_NAME]) THEN '[MODULE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_NAME]) THEN '[TRANSACTION_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_NO]) THEN '[TRANSACTION_NO]-' ELSE '' END + 
CASE WHEN UPDATE([ACCESS_DATE]) THEN '[ACCESS_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([ACESS_TYPE]) THEN '[ACESS_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([FILE_NAME]) THEN '[FILE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PRINT_BY_CODE]) THEN '[PRINT_BY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PRINT_BY_NAME]) THEN '[PRINT_BY_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PRINT_BY_IP]) THEN '[PRINT_BY_IP]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_DOC_ACCESS_LOG]
([ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_DOC_ACCESS_LOG]
([ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MODULE_NAME],[TRANSACTION_NAME],[TRANSACTION_NO],[ACCESS_DATE],[ACESS_TYPE],[FILE_NAME],[PRINT_BY_CODE],[PRINT_BY_NAME],[PRINT_BY_IP],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END