CREATE TABLE [dbo].[SYS_BRANCH] (
    [BRANCH_CODE]         NVARCHAR (50)  NOT NULL,
    [BRANCH_NAME]         NVARCHAR (250) NOT NULL,
    [IS_CUSTODY_BRANCH]   NVARCHAR (1)   NOT NULL,
    [CUSTODY_BRANCH_CODE] NVARCHAR (50)  NOT NULL,
    [CUSTODY_BRANCH_NAME] NVARCHAR (250) NOT NULL,
    [CRE_DATE]            DATETIME       NOT NULL,
    [CRE_BY]              NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)  NOT NULL,
    [MOD_DATE]            DATETIME       NOT NULL,
    [MOD_BY]              NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_SYS_BRANCH] PRIMARY KEY CLUSTERED ([BRANCH_CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[SYS_BRANCH_Insert_Audit] 
			ON [dbo].[SYS_BRANCH]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_BRANCH]
([BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_BRANCH_Delete_Audit]    
			ON [dbo].[SYS_BRANCH]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_BRANCH]
([BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_BRANCH_Update_Audit]      
			ON [dbo].[SYS_BRANCH]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([BRANCH_CODE]) THEN '[BRANCH_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([BRANCH_NAME]) THEN '[BRANCH_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([IS_CUSTODY_BRANCH]) THEN '[IS_CUSTODY_BRANCH]-' ELSE '' END + 
CASE WHEN UPDATE([CUSTODY_BRANCH_CODE]) THEN '[CUSTODY_BRANCH_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CUSTODY_BRANCH_NAME]) THEN '[CUSTODY_BRANCH_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_BRANCH]
([BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_BRANCH]
([BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [BRANCH_CODE],[BRANCH_NAME],[IS_CUSTODY_BRANCH],[CUSTODY_BRANCH_CODE],[CUSTODY_BRANCH_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END