CREATE TABLE [dbo].[TEMPORARY_REQ$] (
    [BRANCH_CODE]    FLOAT (53)     NULL,
    [BRANCH_NAME]    NVARCHAR (255) NULL,
    [COVER_NOTE]     NVARCHAR (255) NULL,
    [CN_DATE]        DATETIME       NULL,
    [CN_EXP_DATE]    DATETIME       NULL,
    [DEALER]         NVARCHAR (255) NULL,
    [DOCUMENT_NAME]  NVARCHAR (255) NULL,
    [COUNT_ASSET ]   FLOAT (53)     NULL,
    [RECEIVED_ASSET] FLOAT (53)     NULL,
    [EXTEND_COUNT]   FLOAT (53)     NULL,
    [STATUS]         NVARCHAR (255) NULL,
    [CRE_BY]         NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS] NVARCHAR (255) NULL,
    [MOD_BY]         NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS] NVARCHAR (255) NULL
);

