CREATE TABLE [dbo].[TEMPORARY_REQ_DETAIL$] (
    [ASSET_CODE]     NVARCHAR (255) NULL,
    [STATUS]         NVARCHAR (255) NULL,
    [CRE_BY]         NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS] NVARCHAR (255) NULL,
    [MOD_BY]         NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS] NVARCHAR (255) NULL,
    [COVER_NOTE]     NVARCHAR (255) NULL,
    [TYPE_ITEM_NAME] NVARCHAR (255) NULL,
    [PLAT_NO]        NVARCHAR (255) NULL,
    [ENGINE_NO]      NVARCHAR (255) NULL,
    [CHASSIS_NO]     NVARCHAR (255) NULL
);

