CREATE TABLE [dbo].[TEMP_LOKASI_DOCUMENT] (
    [CODE]        NVARCHAR (50) NULL,
    [LOCKER_CODE] NVARCHAR (50) NULL,
    [DRAWER_CODE] NVARCHAR (50) NULL,
    [ROW_CODE]    NVARCHAR (50) NULL
);

