CREATE TABLE [dbo].[XXX_DOCUMENT_REQUEST_20250214] (
    [CODE]                       NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                NVARCHAR (250)  NOT NULL,
    [REQUEST_TYPE]               NVARCHAR (20)   NOT NULL,
    [REQUEST_LOCATION]           NVARCHAR (20)   NOT NULL,
    [REQUEST_FROM]               NVARCHAR (50)   NULL,
    [REQUEST_TO]                 NVARCHAR (50)   NULL,
    [REQUEST_TO_AGREEMENT_NO]    NVARCHAR (50)   NULL,
    [REQUEST_TO_CLIENT_NAME]     NVARCHAR (250)  NULL,
    [REQUEST_TO_BRANCH_CODE]     NVARCHAR (50)   NULL,
    [REQUEST_TO_BRANCH_NAME]     NVARCHAR (250)  NULL,
    [REQUEST_FROM_DEPT_CODE]     NVARCHAR (50)   NULL,
    [REQUEST_FROM_DEPT_NAME]     NVARCHAR (250)  NULL,
    [REQUEST_TO_DEPT_CODE]       NVARCHAR (50)   NULL,
    [REQUEST_TO_DEPT_NAME]       NVARCHAR (250)  NULL,
    [REQUEST_TO_THIRDPARTY_TYPE] NVARCHAR (50)   NULL,
    [REQUEST_BY]                 NVARCHAR (250)  NOT NULL,
    [REQUEST_STATUS]             NVARCHAR (50)   NOT NULL,
    [REQUEST_DATE]               DATETIME        NOT NULL,
    [REMARKS]                    NVARCHAR (4000) NOT NULL,
    [DOCUMENT_CODE]              NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]               NVARCHAR (50)   NULL,
    [COLLATERAL_NO]              NVARCHAR (50)   NULL,
    [ASSET_NO]                   NVARCHAR (50)   NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   NOT NULL
);

