CREATE TABLE [dbo].[XXX_DOCUMENT_STORAGE_16112023] (
    [CODE]           NVARCHAR (50)  NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)  NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250) NOT NULL,
    [STORAGE_STATUS] NVARCHAR (20)  NOT NULL,
    [STORAGE_DATE]   DATETIME       NOT NULL,
    [STORAGE_TYPE]   NVARCHAR (20)  NOT NULL,
    [LOCKER_CODE]    NVARCHAR (50)  NULL,
    [DRAWER_CODE]    NVARCHAR (50)  NULL,
    [ROW_CODE]       NVARCHAR (50)  NULL,
    [REMARK]         NVARCHAR (250) NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL
);

