CREATE TABLE [dbo].[XXX_DOCUMENT_PENDING_20240821] (
    [CODE]                NVARCHAR (50)  NOT NULL,
    [BRANCH_CODE]         NVARCHAR (50)  NOT NULL,
    [BRANCH_NAME]         NVARCHAR (250) NOT NULL,
    [INITIAL_BRANCH_CODE] NVARCHAR (50)  NULL,
    [INITIAL_BRANCH_NAME] NVARCHAR (250) NULL,
    [DOCUMENT_TYPE]       NVARCHAR (20)  NOT NULL,
    [DOCUMENT_STATUS]     NVARCHAR (10)  NOT NULL,
    [ASSET_NO]            NVARCHAR (50)  NULL,
    [ASSET_NAME]          NVARCHAR (250) NULL,
    [COVER_NOTE_NO]       NVARCHAR (50)  NULL,
    [COVER_NOTE_DATE]     DATETIME       NULL,
    [COVER_NOTE_EXP_DATE] DATETIME       NULL,
    [FILE_NAME]           NVARCHAR (250) NULL,
    [FILE_PATH]           NVARCHAR (250) NULL,
    [ENTRY_DATE]          DATETIME       NULL,
    [CRE_DATE]            DATETIME       NOT NULL,
    [CRE_BY]              NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)  NOT NULL,
    [MOD_DATE]            DATETIME       NOT NULL,
    [MOD_BY]              NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)  NOT NULL
);

