CREATE TABLE [dbo].[XXX_DOCUMENT_MOVEMENT_16112023] (
    [CODE]                        NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                 NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                 NVARCHAR (250)  NOT NULL,
    [MOVEMENT_DATE]               DATETIME        NOT NULL,
    [MOVEMENT_STATUS]             NVARCHAR (20)   NOT NULL,
    [MOVEMENT_TYPE]               NVARCHAR (20)   NOT NULL,
    [MOVEMENT_LOCATION]           NVARCHAR (20)   NULL,
    [MOVEMENT_FROM]               NVARCHAR (50)   NULL,
    [MOVEMENT_TO]                 NVARCHAR (50)   NULL,
    [MOVEMENT_TO_AGREEMENT_NO]    NVARCHAR (50)   NULL,
    [MOVEMENT_TO_CLIENT_NAME]     NVARCHAR (250)  NULL,
    [MOVEMENT_TO_BRANCH_CODE]     NVARCHAR (50)   NULL,
    [MOVEMENT_TO_BRANCH_NAME]     NVARCHAR (250)  NULL,
    [MOVEMENT_FROM_DEPT_CODE]     NVARCHAR (50)   NULL,
    [MOVEMENT_FROM_DEPT_NAME]     NVARCHAR (250)  NULL,
    [MOVEMENT_TO_DEPT_CODE]       NVARCHAR (50)   NULL,
    [MOVEMENT_TO_DEPT_NAME]       NVARCHAR (250)  NULL,
    [MOVEMENT_BY_EMP_CODE]        NVARCHAR (50)   NOT NULL,
    [MOVEMENT_BY_EMP_NAME]        NVARCHAR (250)  NOT NULL,
    [MOVEMENT_TO_THIRDPARTY_TYPE] NVARCHAR (50)   NULL,
    [RECEIVED_BY]                 NVARCHAR (1)    NULL,
    [RECEIVED_ID_NO]              NVARCHAR (50)   NULL,
    [RECEIVED_NAME]               NVARCHAR (250)  NULL,
    [FILE_NAME]                   NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PATHS]                       NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MOVEMENT_COURIER_CODE]       NVARCHAR (50)   NULL,
    [MOVEMENT_REMARKS]            NVARCHAR (4000) NULL,
    [ESTIMATE_RETURN_DATE]        DATETIME        NULL,
    [RECEIVE_STATUS]              NVARCHAR (20)   NULL,
    [RECEIVE_DATE]                DATETIME        NULL,
    [RECEIVE_REMARK]              NVARCHAR (4000) NULL,
    [FLAG_BORROW]                 NVARCHAR (15)   NULL,
    [CRE_DATE]                    DATETIME        NOT NULL,
    [CRE_BY]                      NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                    DATETIME        NOT NULL,
    [MOD_BY]                      NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (15)   NOT NULL
);

