create procedure [dbo].[xsp_mig_agreement_asset_replacement_history_validation]
(	
	@TABLE_NAME				NVARCHAR(50)
	,@AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI		NVARCHAR(4000)  OUTPUT
)
as
BEGIN   
--- MIG_AGREEMENT_ASSET_REPLACEMENT_HISTORY
--1. data pada kolom ASSET_NO harus sama dengan data pada kolom CODE di tabel MIG_AGREEMENT_ASSET
--2. data pada kolom NEW_FIXED_ASSET_CODE harus sama dengan data pada kolom CODE di tabel MIG_ASSET
--3. data pada kolom IS_LATEST harus: 0 atau 1


DECLARE @AGREEMENT_ASSET_REPLACEMENT_HISTORY_COUNT					INT	

	SET @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI	= 'MIG_AGREEMENT_ASSET_REPLACEMENT_HISTORY: TOTAL = ' + CONVERT(NVARCHAR(10),(SELECT COUNT(1) FROM dbo.MIG_AGREEMENT_ASSET_REPLACEMENT_HISTORY))

	SET @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI = @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI + ' 1. ASSET_NO tidak terdaftar pada tabel dbo.MIG_AGREEMENT_ASSET = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_AGREEMENT_ASSET_REPLACEMENT_HISTORY WHERE ISNULL(ASSET_NO,'') NOT IN (SELECT ISNULL(ASSET_NO,'') FROM dbo.MIG_AGREEMENT_ASSET))) + ' , data pada kolom ASSET_NO harus sama dengan data pada kolom ASSET_NO di tabel MIG_AGREEMENT_ASSET'

	SET @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI = @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI + ' 2. NEW_FIXED_ASSET_CODE tidak terdaftar pada tabel dbo.MIG_AGREEMENT_ASSET = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_AGREEMENT_ASSET_REPLACEMENT_HISTORY WHERE ISNULL(NEW_FIXED_ASSET_CODE,'') NOT IN (SELECT ISNULL(ASSET_NO,'') FROM dbo.MIG_AGREEMENT_ASSET))) + ' , data pada kolom NEW_FIXED_ASSET_CODE harus sama dengan data pada kolom ASSET_NO di tabel MIG_AGREEMENT_ASSET'

	SET @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI = @AGREEMENT_ASSET_REPLACEMENT_HISTORY_VALIDASI + ' 3. IS_LATEST Bukan 0 Atau 1 = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_AGREEMENT_ASSET_REPLACEMENT_HISTORY WHERE ISNULL(IS_LATEST,'') NOT IN ('0','1'))) + ' , data pada kolom IS_LATEST harus: 0 Atau 1'

end