CREATE TABLE [dbo].[xxx_WARNING_LETTER_DELIVERY_DETAIL_backupcrphase3] (
    [ID]               INT             IDENTITY (1, 1) NOT NULL,
    [DELIVERY_CODE]    NVARCHAR (50)   NOT NULL,
    [LETTER_CODE]      NVARCHAR (50)   NOT NULL,
    [RECEIVED_STATUS]  NVARCHAR (20)   NULL,
    [RECEIVED_DATE]    DATETIME        NULL,
    [RECEIVED_BY]      NVARCHAR (250)  NULL,
    [RECEIVED_REMARKS] NVARCHAR (4000) NULL,
    [FILE_NAME]        NVARCHAR (250)  NULL,
    [PATHS]            NVARCHAR (250)  NULL,
    [IS_POST]          NVARCHAR (1)    NOT NULL,
    [SURAT_NO_SP_1]    NVARCHAR (50)   NULL,
    [SURAT_NO_SP_2]    NVARCHAR (50)   NULL,
    [SURAT_NO_SOMASI]  NVARCHAR (50)   NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL
);

