CREATE TABLE [dbo].[xxx_WARNING_LETTER_backupcrphase3] (
    [CODE]                        NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                 NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                 NVARCHAR (250)  NOT NULL,
    [LETTER_STATUS]               NVARCHAR (20)   NOT NULL,
    [LETTER_DATE]                 DATETIME        NOT NULL,
    [LETTER_NO]                   NVARCHAR (50)   NOT NULL,
    [LETTER_TYPE]                 NVARCHAR (10)   NOT NULL,
    [LETTER_REMARKS]              NVARCHAR (4000) NULL,
    [AGREEMENT_NO]                NVARCHAR (50)   NULL,
    [MAX_PRINT_COUNT]             INT             NOT NULL,
    [PRINT_COUNT]                 INT             NOT NULL,
    [LAST_PRINT_BY]               NVARCHAR (50)   NULL,
    [GENERATE_TYPE]               NVARCHAR (10)   NOT NULL,
    [PREVIOUS_LETTER_CODE]        NVARCHAR (50)   NULL,
    [INSTALLMENT_AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [OVERDUE_DAYS]                INT             NULL,
    [INSTALLMENT_NO]              INT             NULL,
    [OVERDUE_PENALTY_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [OVERDUE_INSTALLMENT_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [DELIVERY_CODE]               NVARCHAR (50)   NULL,
    [DELIVERY_DATE]               DATETIME        NULL,
    [RECEIVED_BY]                 NVARCHAR (250)  NULL,
    [RECEIVED_DATE]               DATETIME        NULL,
    [CRE_DATE]                    DATETIME        NOT NULL,
    [CRE_BY]                      NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                    DATETIME        NOT NULL,
    [MOD_BY]                      NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [CLIENT_NO]                   NVARCHAR (50)   NULL,
    [TOTAL_AGREEMENT_COUNT]       BIGINT          NULL,
    [TOTAL_ASSET_COUNT]           BIGINT          NULL,
    [TOTAL_MONTHLY_RENTAL_AMOUNT] DECIMAL (18, 2) NULL
);

