CREATE TABLE [dbo].[Z_AUDIT_MASTER_MACHINERY_UNIT] (
    [CODE]                         NVARCHAR (50)  NOT NULL,
    [MACHINERY_CATEGORY_CODE]      NVARCHAR (50)  NOT NULL,
    [MACHINERY_SUBCATEGORY_CODE]   NVARCHAR (50)  NOT NULL,
    [MACHINERY_MERK_CODE]          NVARCHAR (50)  NOT NULL,
    [MACHINERY_MODEL_CODE]         NVARCHAR (50)  NOT NULL,
    [MACHINERY_TYPE_CODE]          NVARCHAR (50)  NOT NULL,
    [MACHINERY_NAME]               NVARCHAR (250) NULL,
    [DESCRIPTION]                  NVARCHAR (250) NOT NULL,
    [USEFULL_LIFE]                 INT            NULL,
    [CATEGORY_TYPE]                NVARCHAR (20)  NULL,
    [CLASS_TYPE_CODE]              NVARCHAR (50)  NULL,
    [CLASS_TYPE_NAME]              NVARCHAR (250) NULL,
    [INSURANCE_ASSET_TYPE_CODE]    NVARCHAR (50)  NULL,
    [INSURANCE_ASSET_TYPE_NAME]    NVARCHAR (250) NULL,
    [REGISTRATION_CLASS_TYPE_CODE] NVARCHAR (50)  NULL,
    [REGISTRATION_CLASS_TYPE_NAME] NVARCHAR (250) NULL,
    [IS_SPAF]                      NVARCHAR (1)   NULL,
    [SPAF_PCT]                     DECIMAL (9, 6) NULL,
    [IS_ACTIVE]                    NVARCHAR (1)   NOT NULL,
    [CRE_DATE]                     DATETIME       NOT NULL,
    [CRE_BY]                       NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                     DATETIME       NOT NULL,
    [MOD_BY]                       NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)  NOT NULL,
    [AuditDataState]               VARCHAR (10)   NULL,
    [AuditDMLAction]               VARCHAR (10)   NULL,
    [AuditUser]                    [sysname]      NULL,
    [AuditDateTime]                DATETIME       NULL,
    [UpdateColumns]                VARCHAR (MAX)  NULL
);

