CREATE TABLE [dbo].[Z_AUDIT_MASTER_FACILITY] (
    [CODE]           NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]    NVARCHAR (250) NOT NULL,
    [FACILITY_TYPE]  NVARCHAR (2)   NOT NULL,
    [DESKCOLL_MIN]   INT            NOT NULL,
    [DESKCOLL_MAX]   INT            NOT NULL,
    [SP1_DAYS]       INT            NOT NULL,
    [SP2_DAYS]       INT            NOT NULL,
    [SOMASI_DAYS]    INT            NOT NULL,
    [AGING_DAYS1]    INT            NOT NULL,
    [AGING_DAYS2]    INT            NOT NULL,
    [AGING_DAYS3]    INT            NOT NULL,
    [AGING_DAYS4]    INT            NOT NULL,
    [IS_ACTIVE]      NVARCHAR (1)   NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [AuditDataState] VARCHAR (10)   NULL,
    [AuditDMLAction] VARCHAR (10)   NULL,
    [AuditUser]      [sysname]      NULL,
    [AuditDateTime]  DATETIME       NULL,
    [UpdateColumns]  VARCHAR (MAX)  NULL
);

