CREATE TABLE [dbo].[Z_AUDIT_MASTER_VEHICLE_PRICELIST] (
    [CODE]                     NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]              NVARCHAR (250) NOT NULL,
    [VEHICLE_CATEGORY_CODE]    NVARCHAR (50)  NOT NULL,
    [VEHICLE_SUBCATEGORY_CODE] NVARCHAR (50)  NOT NULL,
    [VEHICLE_MERK_CODE]        NVARCHAR (50)  NOT NULL,
    [VEHICLE_MODEL_CODE]       NVARCHAR (50)  NOT NULL,
    [VEHICLE_TYPE_CODE]        NVARCHAR (50)  NOT NULL,
    [VEHICLE_UNIT_CODE]        NVARCHAR (50)  NOT NULL,
    [ASSET_YEAR]               NVARCHAR (4)   NOT NULL,
    [CONDITION]                NVARCHAR (10)  NOT NULL,
    [IS_ACTIVE]                NVARCHAR (1)   NOT NULL,
    [CRE_DATE]                 DATETIME       NOT NULL,
    [CRE_BY]                   NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                 DATETIME       NOT NULL,
    [MOD_BY]                   NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)  NOT NULL,
    [AuditDataState]           VARCHAR (10)   NULL,
    [AuditDMLAction]           VARCHAR (10)   NULL,
    [AuditUser]                [sysname]      NULL,
    [AuditDateTime]            DATETIME       NULL,
    [UpdateColumns]            VARCHAR (MAX)  NULL
);

