CREATE TABLE [dbo].[Z_AUDIT_MASTER_FEE_AMOUNT] (
    [CODE]             NVARCHAR (50)   NOT NULL,
    [FEE_CODE]         NVARCHAR (50)   NOT NULL,
    [EFFECTIVE_DATE]   DATETIME        NOT NULL,
    [FACILITY_CODE]    NVARCHAR (50)   NOT NULL,
    [CURRENCY_CODE]    NVARCHAR (15)   NOT NULL,
    [CALCULATE_BY]     NVARCHAR (10)   NOT NULL,
    [CALCULATE_BASE]   NVARCHAR (11)   NOT NULL,
    [CALCULATE_FROM]   NVARCHAR (20)   NOT NULL,
    [FEE_RATE]         DECIMAL (9, 6)  NULL,
    [FEE_AMOUNT]       DECIMAL (18, 2) NULL,
    [FN_DEFAULT_NAME]  NVARCHAR (250)  NULL,
    [IS_FN_OVERRIDE]   NVARCHAR (1)    NULL,
    [FN_OVERRIDE_NAME] NVARCHAR (250)  NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [AuditDataState]   VARCHAR (10)    NULL,
    [AuditDMLAction]   VARCHAR (10)    NULL,
    [AuditUser]        [sysname]       NULL,
    [AuditDateTime]    DATETIME        NULL,
    [UpdateColumns]    VARCHAR (MAX)   NULL
);

