CREATE TABLE [dbo].[Z_AUDIT_MASTER_CHARGES_AMOUNT] (
    [CODE]             NVARCHAR (50)   NOT NULL,
    [CHARGE_CODE]      NVARCHAR (50)   NOT NULL,
    [EFFECTIVE_DATE]   DATETIME        NOT NULL,
    [FACILITY_CODE]    NVARCHAR (50)   NOT NULL,
    [CURRENCY_CODE]    NVARCHAR (3)    NOT NULL,
    [CALCULATE_BY]     NVARCHAR (10)   NOT NULL,
    [CHARGES_RATE]     DECIMAL (9, 6)  NOT NULL,
    [CHARGES_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [FN_DEFAULT_NAME]  NVARCHAR (250)  NULL,
    [IS_FN_OVERRIDE]   NVARCHAR (1)    NULL,
    [FN_OVERRIDE_NAME] NVARCHAR (250)  NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [AuditDataState]   VARCHAR (10)    NULL,
    [AuditDMLAction]   VARCHAR (10)    NULL,
    [AuditUser]        [sysname]       NULL,
    [AuditDateTime]    DATETIME        NULL,
    [UpdateColumns]    VARCHAR (MAX)   NULL
);

