CREATE TABLE [dbo].[Z_AUDIT_MASTER_DOCUMENT_GROUP] (
    [CODE]                     NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]              NVARCHAR (250) NOT NULL,
    [IS_ACTIVE]                NVARCHAR (1)   NOT NULL,
    [DOCUMENT_GROUP_TYPE_CODE] NVARCHAR (50)  NOT NULL,
    [DIM_COUNT]                INT            NOT NULL,
    [DIM_1]                    NVARCHAR (50)  NULL,
    [OPERATOR_1]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_1]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_1]           NVARCHAR (50)  NULL,
    [DIM_2]                    NVARCHAR (50)  NULL,
    [OPERATOR_2]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_2]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_2]           NVARCHAR (50)  NULL,
    [DIM_3]                    NVARCHAR (50)  NULL,
    [OPERATOR_3]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_3]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_3]           NVARCHAR (50)  NULL,
    [DIM_4]                    NVARCHAR (50)  NULL,
    [OPERATOR_4]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_4]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_4]           NVARCHAR (50)  NULL,
    [DIM_5]                    NVARCHAR (50)  NULL,
    [OPERATOR_5]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_5]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_5]           NVARCHAR (50)  NULL,
    [DIM_6]                    NVARCHAR (50)  NULL,
    [OPERATOR_6]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_6]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_6]           NVARCHAR (50)  NULL,
    [DIM_7]                    NVARCHAR (50)  NULL,
    [OPERATOR_7]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_7]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_7]           NVARCHAR (50)  NULL,
    [DIM_8]                    NVARCHAR (50)  NULL,
    [OPERATOR_8]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_8]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_8]           NVARCHAR (50)  NULL,
    [DIM_9]                    NVARCHAR (50)  NULL,
    [OPERATOR_9]               NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_9]         NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_9]           NVARCHAR (50)  NULL,
    [DIM_10]                   NVARCHAR (50)  NULL,
    [OPERATOR_10]              NVARCHAR (50)  NULL,
    [DIM_VALUE_FROM_10]        NVARCHAR (50)  NULL,
    [DIM_VALUE_TO_10]          NVARCHAR (50)  NULL,
    [CRE_DATE]                 DATETIME       NOT NULL,
    [CRE_BY]                   NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                 DATETIME       NOT NULL,
    [MOD_BY]                   NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)  NOT NULL,
    [AuditDataState]           VARCHAR (10)   NULL,
    [AuditDMLAction]           VARCHAR (10)   NULL,
    [AuditUser]                [sysname]      NULL,
    [AuditDateTime]            DATETIME       NULL,
    [UpdateColumns]            VARCHAR (MAX)  NULL
);

