CREATE TABLE [dbo].[Z_AUDIT_MASTER_REFUND] (
    [CODE]              NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]       NVARCHAR (250)  NOT NULL,
    [CURRENCY_CODE]     NVARCHAR (3)    NOT NULL,
    [REFUND_TYPE]       NVARCHAR (10)   NOT NULL,
    [FACILITY_CODE]     NVARCHAR (50)   NOT NULL,
    [FEE_CODE]          NVARCHAR (50)   NULL,
    [CALCULATE_BY]      NVARCHAR (10)   NOT NULL,
    [REFUND_AMOUNT]     DECIMAL (18, 2) NULL,
    [REFUND_PCT]        DECIMAL (9, 6)  NULL,
    [MAX_REFUND_AMOUNT] DECIMAL (18, 2) NULL,
    [FN_DEFAULT_NAME]   NVARCHAR (250)  NULL,
    [IS_FN_OVERRIDE]    NVARCHAR (1)    NULL,
    [FN_OVERRIDE_NAME]  NVARCHAR (250)  NULL,
    [IS_PSAK]           NVARCHAR (1)    NULL,
    [IS_ACTIVE]         NVARCHAR (1)    NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [AuditDataState]    VARCHAR (10)    NULL,
    [AuditDMLAction]    VARCHAR (10)    NULL,
    [AuditUser]         [sysname]       NULL,
    [AuditDateTime]     DATETIME        NULL,
    [UpdateColumns]     VARCHAR (MAX)   NULL
);

