CREATE procedure dbo.xsp_mig_master_service_validation
(	
	@TABLE_NAME				NVARCHAR(50)
	,@SERVICE_VALIDASI		NVARCHAR(4000)  OUTPUT
)
as
BEGIN
-- MIG_MASTER_SERVICE
--1. data pada kolom CODE tidak boleh sama dengan yang lain/ harus unik
--2. data pada kolom COMPANY_CODE harus: DSF
--3. data pada kolom GROUP_CODE harus: CLT, BRK, ELCT, NONE, OTH, OTPART, PWT, RAD, RMTN, SSPN, STR Atau WHL
--4. data pada kolom TYPE_ASSET_CODE harus: VHCL
--5. data pada kolom IS_ACTIVE harus: 0 Atau 1
--6. data pada kolom SERVICE_TYPE harus: ITEM Atau JASA

	DECLARE @SERVICE_COUNT		INT	
			,@SERVICE_DISTINCT_COUNT	INT
			
	SELECT @SERVICE_COUNT = COUNT(CODE) FROM dbo.MIG_MASTER_SERVICE
	SELECT @SERVICE_DISTINCT_COUNT = COUNT(DISTINCT CODE) FROM dbo.MIG_MASTER_SERVICE

	SET @SERVICE_VALIDASI = 'MIG_MASTER_SERVICE: TOTAL = ' + CONVERT(NVARCHAR(10),@SERVICE_COUNT)

	IF @SERVICE_COUNT <> @SERVICE_DISTINCT_COUNT
	BEGIN
    
		SET @SERVICE_VALIDASI = ' - 1. DUPLICATE CODE = ' + CONVERT(NVARCHAR(10), (@SERVICE_COUNT - @SERVICE_DISTINCT_COUNT)) + ', data pada kolom CODE tidak boleh sama dengan yang lain/ harus unik'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_SERVICE WHERE COMPANY_CODE <> 'DSF')
	BEGIN
		SET @SERVICE_VALIDASI = @SERVICE_VALIDASI + ' - 2. COMPANY_CODE Bukan DSF = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_SERVICE WHERE COMPANY_CODE <> 'DSF')) + ', data pada kolom COMPANY_CODE harus: DSF'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_SERVICE WHERE GROUP_CODE NOT IN ('CLT', 'BRK', 'ELCT', 'NONE', 'OTH', 'OTPART', 'PWT', 'RAD', 'RMTN', 'SSPN', 'STR', 'WHL'))
	BEGIN
		SET @SERVICE_VALIDASI = @SERVICE_VALIDASI + ' - 3. TYPE_ASSET_CODE Bukan CLT, BRK, ELCT, NONE, OTH, OTPART, PWT, RAD, RMTN, SSPN, STR Atau WHL = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_SERVICE WHERE GROUP_CODE NOT IN ('CLT', 'BRK', 'ELCT', 'NONE', 'OTH', 'OTPART', 'PWT', 'RAD', 'RMTN', 'SSPN', 'STR', 'WHL'))) + ', data pada kolom GROUP_CODE harus: CLT, BRK, ELCT, NONE, OTH, OTPART, PWT, RAD, RMTN, SSPN, STR Atau WHL'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_SERVICE WHERE TYPE_ASSET_CODE <> 'VHCL')
	BEGIN
		SET @SERVICE_VALIDASI = @SERVICE_VALIDASI + ' - 4. TYPE_ASSET_CODE Bukan VHCL = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_SERVICE WHERE TYPE_ASSET_CODE <> 'VHCL')) + ', data pada kolom TYPE_ASSET_CODE harus: VHCL'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_SERVICE WHERE IS_ACTIVE NOT IN ('1','0'))
	BEGIN
		SET @SERVICE_VALIDASI = @SERVICE_VALIDASI + ' - 5. IS_ACTIVE Bukan 0 Atau 1 = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_SERVICE WHERE IS_ACTIVE NOT IN ('1','0'))) + ', data pada kolom IS_ACTIVE harus: 0 Atau 1'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_SERVICE WHERE SERVICE_TYPE NOT IN ('ITEM','JASA'))
	BEGIN
		SET @SERVICE_VALIDASI = @SERVICE_VALIDASI + ' - 6. SERVICE_TYPE Bukan ITEM Atau JASA = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_SERVICE WHERE SERVICE_TYPE NOT IN ('ITEM','JASA'))) + ', data pada kolom SERVICE_TYPE harus: ITEM Atau JASA'
	END

end
