CREATE PROCEDURE dbo.xsp_maintenence_data_cleanup 
	@P_CLEANUP_TYPE NVARCHAR(10) -- 'ALL', 'TRANSAKSI', 'SETTING','INTERFACE','INJECT'
AS
BEGIN
	declare	@msg		nvarchar(max)
			,@code		nvarchar(50)
			,@name		nvarchar(250)
			,@temp		nvarchar(10)
			,@index		int

    -- CLEAN UP TRANSAKSI
    IF @P_CLEANUP_TYPE = 'ALL'
       OR @P_CLEANUP_TYPE = 'TRANSAKSI'
    BEGIN
		delete	dbo.SUSPEND_REVENUE_DETAIL
		delete	dbo.SUSPEND_REVENUE
		delete	dbo.SUSPEND_RELEASE
		delete	dbo.SUSPEND_MERGER_DETAIL
		delete	dbo.SUSPEND_MERGER
		delete	dbo.SUSPEND_HISTORY
		delete	dbo.SUSPEND_ALLOCATION_DETAIL
		delete	dbo.SUSPEND_ALLOCATION
		delete	dbo.SUSPEND_MAIN
		delete	RPT_UNKNOWN_MONITORING
		delete	RPT_BANK_BOOK
		delete	RPT_FINANCE_TRANSACTION
		delete	RPT_AP_PAYMENT_REQUEST
		delete	RPT_AUTO_DEBET
		delete	RPT_PENDING_DISBURSEMENT
		delete	RPT_RECEIVED_VOUCHER
		delete	RPT_PAYMENT_VOUCHER
		delete	RPT_ADVANCE_ALLOCATION_PER_AGREEMENT
		delete	RPT_INVOICE_ALLOCATION
		delete	RPT_CASHIER_TRANSACTION_CASH
		delete	dbo.REVERSAL_MAIN
		delete	dbo.REPRINT_RECEIPT
		delete	dbo.RECONCILE_TRANSACTION
		delete	dbo.RECONCILE_MAIN
		delete	dbo.RECEIVED_VOUCHER_DETAIL
		delete	dbo.RECEIVED_VOUCHER
		delete	dbo.RECEIVED_TRANSACTION_DETAIL
		delete	dbo.RECEIVED_TRANSACTION
		delete	dbo.RECEIVED_REQUEST_DETAIL
		delete	dbo.RECEIVED_REQUEST
		delete	dbo.RECEIPT_VOID_DETAIL
		delete	dbo.RECEIPT_VOID
		delete	dbo.RECEIPT_REGISTER_DETAIL
		delete	dbo.RECEIPT_REGISTER
		delete	dbo.CASHIER_RECEIPT_ALLOCATED
		delete	dbo.RECEIPT_MAIN
		delete	dbo.PAYMENT_VOUCHER_DETAIL
		delete	dbo.PAYMENT_VOUCHER
		delete	dbo.PAYMENT_TRANSACTION_DETAIL
		delete	dbo.PAYMENT_TRANSACTION
		delete	dbo.PAYMENT_REQUEST_DETAIL
		delete	dbo.PAYMENT_REQUEST
		TRUNCATE TABLE	dbo.IFINFIN_INTERFACE_AGREEMENT_OBLIGATION_PAYMENT
		TRUNCATE TABLE	dbo.FIN_INTERFACE_RECEIVED_REQUEST_DETAIL
		DELETE	dbo.FIN_INTERFACE_RECEIVED_REQUEST
		TRUNCATE TABLE	dbo.FIN_INTERFACE_PAYMENT_REQUEST_DETAIL
		DELETE	dbo.FIN_INTERFACE_PAYMENT_REQUEST
		TRUNCATE TABLE	dbo.FIN_INTERFACE_NOTIFICATION_REQUEST
		TRUNCATE TABLE	dbo.FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL
		DELETE	dbo.FIN_INTERFACE_JOURNAL_GL_LINK_TRANSACTION
		TRUNCATE TABLE	dbo.FIN_INTERFACE_DEPOSIT_ALLOCATION_DETAIL
		DELETE	dbo.FIN_INTERFACE_DEPOSIT_ALLOCATION
		TRUNCATE TABLE	dbo.FIN_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL
		DELETE	dbo.FIN_INTERFACE_CASHIER_RECEIVED_REQUEST
		TRUNCATE TABLE	dbo.FIN_INTERFACE_BANK_MUTATION
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_UPDATE
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_OBLIGATION_PAYMENT
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_MAIN
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_INVOICE_LEDGER_HISTORY
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_FUND_IN_USED_HISTORY
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_DEPOSIT_HISTORY
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_AP_THIRDPARTY_HISTORY
		TRUNCATE TABLE	dbo.FIN_INTERFACE_AGREEMENT_AMORTIZATION_PAYMENT
		TRUNCATE TABLE dbo.AGREEMENT_MAIN_EXTENTION
		delete	dbo.DEPOSIT_REVENUE_DETAIL
		delete	dbo.DEPOSIT_REVENUE
		delete	dbo.DEPOSIT_RELEASE_DETAIL
		delete	dbo.DEPOSIT_RELEASE
		delete	dbo.DEPOSIT_MOVE
		delete	dbo.DEPOSIT_ALLOCATION_DETAIL
		delete	dbo.DEPOSIT_ALLOCATION
		delete	dbo.CORE_UPLOAD_GENERIC
		delete	dbo.CASHIER_TRANSACTION_INVOICE
		delete	dbo.CASHIER_TRANSACTION_DETAIL
		delete	dbo.CASHIER_TRANSACTION
		delete	dbo.CASHIER_RECEIVED_REQUEST_DETAIL
		delete	dbo.CASHIER_RECEIVED_REQUEST
		delete	dbo.CASHIER_MAIN
		delete	dbo.CASHIER_BANKNOTE_AND_COIN
		delete	dbo.BANK_MUTATION_HISTORY
		delete	dbo.BANK_MUTATION
		delete	dbo.AGREEMENT_MAIN
		delete	dbo.ACCOUNT_TRANSFER
    END;

	-- CLEAN UP MASTER
    IF @P_CLEANUP_TYPE = 'ALL'
       OR @P_CLEANUP_TYPE = 'MASTER'
    BEGIN
		delete	dbo.MASTER_UPLOAD_VALIDATION
		delete	dbo.MASTER_UPLOAD_TABLE
		delete	dbo.MASTER_UPLOAD_TABEL_VALIDATION
		delete	dbo.MASTER_UPLOAD_TABEL_COLUMN
		delete	dbo.MASTER_TRANSACTION
		delete	dbo.MASTER_TAX_DETAIL
		delete	dbo.MASTER_TAX
		delete	dbo.MASTER_REVERSAL_VALIDATION
		delete	dbo.MASTER_OJK_REFERENCE
		delete	dbo.MASTER_CASHIER_QUESTION
		delete	dbo.MASTER_CASHIER_PRIORITY_DETAIL
		delete	dbo.MASTER_CASHIER_PRIORITY
		delete	dbo.MASTER_BANKNOTE_AND_COIN
		delete	dbo.MASTER_ACCOUNT_PAYABLE_DETAIL
		delete	dbo.MASTER_ACCOUNT_PAYABLE
		delete	dbo.JOURNAL_GL_LINK
	END

	SELECT		(schema_name(a.schema_id) + '.' + a.name) as tablename
				,sum(b.rows) as recordcount
	from		sys.objects a
				inner join sys.partitions b on a.object_id = b.object_id
	where		a.type = 'u'
	group by	a.schema_id
				,a.name 
	order BY	tablename DESC

END;

