CREATE procedure dbo.xsp_mig_master_item_validation
(	
	@TABLE_NAME					NVARCHAR(50) 
	,@VALIDASI_ITEM				NVARCHAR(4000) OUTPUT
)
as
BEGIN
--- MIG_MASTER_ITEM
--1. data pada kolom CODE tidak boleh sama dengan yang lain/ harus unik
--2. data pada kolom COMPANY_CODE harus: DSF
--3. data pada kolom TRANSACTION_TYPE harus: FXDAST 
--4. data pada kolom ITEM_GROUP_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_ITEM_GROUP
--5. data pada kolom MERK_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_MERK 
--6. data pada kolom MODEL_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_MODEL
--7. data pada kolom TYPE_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_TYPE
--8. data pada kolom UOM_CODE harus sama dengan data pada kolom CODE di tabel MASTER_UOM
--9. data pada kolom TYPE_ASSET_CODE harus: VHCL 
--10. data pada kolom FA_CATEGORY_CODE harus: VHCL 
--11. data pada kolom FA_CATEGORY_NAME harus: VEHICLE 
--12. data pada kolom CATEGORY_TYPE harus: ASSET, MOBILISASI, KAROSERI Atau ACCESSORIES
--13. data pada kolom CLASS_TYPE_CODE harus: COMM, COMMT, LCV, LCVNT, PSG, PSGJ, PSGM Atau PSGSV
--14. data pada kolom IS_RENT harus: 0 Atau 1
--15. data pada kolom IS_ACTIVE harus: 0 Atau 1
--16. data pada kolom INSURANCE_ASSET_TYPE harus: BUS, MOTO, PSGC Atau TRCK
--17. data pada kolom REGISTRATION_CLASS_TYPE harus: RGABR, RGLCV, RGPC, RGPU, RGTRC Atau RGTRT

	DECLARE @ITEM_COUNT		INT	
			,@ITEM_DISTINCT_COUNT	INT
			
	SET @VALIDASI_ITEM = 'MIG_MASTER_ITEM: '

	SELECT @ITEM_COUNT = COUNT(CODE) FROM dbo.MIG_MASTER_ITEM
	SELECT @ITEM_DISTINCT_COUNT = COUNT(DISTINCT CODE) FROM dbo.MIG_MASTER_ITEM

	IF @ITEM_COUNT <> @ITEM_DISTINCT_COUNT
	BEGIN
    
		SET @VALIDASI_ITEM = ' - 1. DUPLICATE CODE = ' + CONVERT(NVARCHAR(10), (@ITEM_COUNT - @ITEM_DISTINCT_COUNT)) + ', data pada kolom CODE tidak boleh sama dengan yang lain/ harus unik'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE COMPANY_CODE <> 'DSF')
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 2. COMPANY_CODE Bukan DSF = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE COMPANY_CODE <> 'DSF') + ', data pada kolom COMPANY_CODE harus: DSF'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE TRANSACTION_TYPE <> 'FXDAST')
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 3. TRANSACTION_TYPE Bukan FXDAST = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE TRANSACTION_TYPE <> 'FXDAST') + ', data pada kolom TRANSACTION_TYPE harus: FXDAST '
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE ITEM_GROUP_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_ITEM_GROUP))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 4. ITEM_GROUP_CODE tidak terdaftar pada tabel MIG_MASTER_ITEM_GROUP = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE ITEM_GROUP_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_MERK)) + ', data pada kolom ITEM_GROUP_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_ITEM_GROUP'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE MERK_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_MERK))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 5. MERK_CODE tidak terdaftar pada tabel MIG_MASTER_MERK = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE MERK_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_MERK)) + ', data pada kolom MERK_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_MERK'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE MODEL_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_MODEL))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 6. MODEL_CODE tidak terdaftar pada tabel MIG_MASTER_MODEL = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE MODEL_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_MODEL)) + ', data pada kolom MODEL_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_MODEL'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE TYPE_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_TYPE))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 7. TYPE_CODE tidak terdaftar pada tabel MIG_MASTER_TYPE = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE TYPE_CODE NOT IN (SELECT CODE FROM dbo.MIG_MASTER_TYPE)) + ', data pada kolom TYPE_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_TYPE'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE UOM_CODE NOT IN (SELECT CODE FROM MIFINBAM.dbo.MASTER_UOM))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 8. UOM_CODE tidak terdaftar pada tabel MASTER_UOM = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE UOM_CODE NOT IN (SELECT CODE FROM MIFINBAM.dbo.MASTER_UOM)) + ', data pada kolom UOM_CODE harus sama dengan data pada kolom CODE di tabel MASTER_UOM'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_ITEM WHERE TYPE_ASSET_CODE <> 'VHCL')
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 9. IS_ACTIVE Bukan VHCL = ' + (SELECT COUNT(1) FROM MIG_MASTER_ITEM WHERE TYPE_ASSET_CODE <> 'VHCL') + ', data pada kolom TYPE_ASSET_CODE harus: VHCL'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE FA_CATEGORY_CODE <> 'VHCL')
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 10. FA_CATEGORY_CODE Bukan VHCL = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE FA_CATEGORY_CODE <> 'FXDAST') + ', data pada kolom FA_CATEGORY_CODE harus: VHCL'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE FA_CATEGORY_NAME <> 'VEHICLE')
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 11. FA_CATEGORY_NAME Bukan VEHICLE = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE FA_CATEGORY_NAME <> 'VEHICLE') + ', data pada kolom FA_CATEGORY_NAME harus: VEHICLE'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE CATEGORY_TYPE NOT IN ('ASSET','MOBILISASI', 'KAROSERI','ACCESSORIES'))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 12. CATEGORY_TYPE Bukan ASSET, MOBILISASI, KAROSERI Atau ACCESSORIES = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE CATEGORY_TYPE NOT IN ('ASSET','MOBILISASI', 'KAROSERI','ACCESSORIES')) + ', data pada kolom CATEGORY_TYPE harus: ASSET, MOBILISASI, KAROSERI Atau ACCESSORIES'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE CLASS_TYPE_CODE NOT IN ('COMM','COMMT','LCV', 'LCVNT', 'PSG', 'PSGJ', 'PSGM','PSGSV'))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 13. CLASS_TYPE_CODE Bukan ASSET, MOBILISASI, KAROSERI Atau ACCESSORIES = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE CLASS_TYPE_CODE NOT IN ('COMM','COMMT','LCV', 'LCVNT', 'PSG', 'PSGJ', 'PSGM','PSGSV')) + ', data pada kolom CLASS_TYPE_CODE harus: COMM, COMMT, LCV, LCVNT, PSG, PSGJ, PSGM Atau PSGSV'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_ITEM WHERE IS_RENT NOT IN ('1','0'))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 14. IS_RENT Bukan 0 Atau 1 = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE IS_RENT NOT IN ('1','0')) + ', data pada kolom IS_RENT harus: 0 Atau 1'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_ITEM WHERE IS_ACTIVE NOT IN ('1','0'))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 15. IS_ACTIVE Bukan 0 Atau 1 = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE IS_ACTIVE NOT IN ('1','0')) + ', data pada kolom IS_ACTIVE harus: 0 Atau 1'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE INSURANCE_ASSET_TYPE NOT IN ('BUS', 'MOTO', 'PSGC','TRCK'))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 16. INSURANCE_ASSET_TYPE Bukan BUS, MOTO, PSGC Atau TRCK = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE INSURANCE_ASSET_TYPE NOT IN ('BUS', 'MOTO', 'PSGC','TRCK')) + ', data pada kolom INSURANCE_ASSET_TYPE harus: BUS, MOTO, PSGC Atau TRCK'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_ITEM WHERE REGISTRATION_CLASS_TYPE NOT IN ('RGABR', 'RGLCV', 'RGPC', 'RGPU', 'RGTRC','RGTRT'))
	BEGIN
		SET @VALIDASI_ITEM = @VALIDASI_ITEM + ' - 17. REGISTRATION_CLASS_TYPE Bukan RGABR, RGLCV, RGPC, RGPU, RGTRC Atau RGTRT = ' + (SELECT COUNT(1) FROM dbo.MIG_MASTER_ITEM WHERE INSURANCE_ASSET_TYPE NOT IN ('BUS', 'MOTO', 'PSGC','TRCK')) + ', data pada kolom REGISTRATION_CLASS_TYPE harus: RGABR, RGLCV, RGPC, RGPU, RGTRC Atau RGTRT'
	END

END



