CREATE procedure dbo.xsp_mig_master_vendor_item_group_validation
(	
	@TABLE_NAME				NVARCHAR(50)
	,@VENDOR_ITEM_GROUP_VALIDASI			NVARCHAR(4000)  OUTPUT
)
as
BEGIN
--- MIG_MASTER_VENDOR_ITEM_GROUP
--1. data pada kolom VENDOR_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_VENDOR
--2. data pada kolom TRANSACTION_TYPE harus: FXDAST
--3. data pada kolom GROUP_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_ITEM_GROUP

	DECLARE @VENDOR_ITEM_GROUP_COUNT			INT	
			,@VENDOR_ITEM_GROUP_DISTINCT_COUNT	INT

	SELECT @VENDOR_ITEM_GROUP_COUNT = COUNT(1) FROM MIG_MASTER_VENDOR_ITEM_GROUP
	
	SET @VENDOR_ITEM_GROUP_VALIDASI	= 'MIG_MASTER_VENDOR_ITEM_GROUP: ' + CONVERT(NVARCHAR(10),@VENDOR_ITEM_GROUP_COUNT)

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_VENDOR_ITEM_GROUP WHERE VENDOR_CODE NOT IN (SELECT VENDOR_CODE FROM MIG_MASTER_VENDOR))
	BEGIN
		SET @VENDOR_ITEM_GROUP_VALIDASI = @VENDOR_ITEM_GROUP_VALIDASI + ' - 1. VENDOR_CODE tidak terdaftar pada tabel MIG_MASTER_PUBLIC_SERVICE = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_VENDOR_ITEM_GROUP WHERE VENDOR_CODE NOT IN (SELECT CODE FROM MIG_MASTER_PUBLIC_SERVICE))) + ' , data pada kolom VENDOR_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_PUBLIC_SERVICE'
	END

	IF EXISTS (SELECT 1 FROM MIG_MASTER_VENDOR_ITEM_GROUP WHERE TRANSACTION_TYPE <> 'FXDAST')
	BEGIN
		SET @VENDOR_ITEM_GROUP_VALIDASI = @VENDOR_ITEM_GROUP_VALIDASI + ' - 2. TRANSACTION_TYPE Bukan FXDAST = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_VENDOR_ITEM_GROUP WHERE TRANSACTION_TYPE <> 'FXDAST')) + ', data pada kolom TRANSACTION_TYPE harus: FXDAST'
	END

	IF EXISTS (SELECT 1 FROM dbo.MIG_MASTER_VENDOR_ITEM_GROUP WHERE GROUP_CODE NOT IN (SELECT GROUP_CODE FROM MIG_MASTER_ITEM_GROUP))
	BEGIN
		SET @VENDOR_ITEM_GROUP_VALIDASI = @VENDOR_ITEM_GROUP_VALIDASI + ' - 3. GROUP_CODE tidak terdaftar pada tabel MIG_MASTER_ITEM_GROUP = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_MASTER_VENDOR_ITEM_GROUP WHERE GROUP_CODE NOT IN (SELECT CODE FROM MIG_MASTER_ITEM_GROUP))) + ' , data pada kolom GROUP_CODE harus sama dengan data pada kolom CODE di tabel MIG_MASTER_ITEM_GROUP'
	END

END