CREATE TABLE [dbo].[EPROC_INTERFACE_ASSET] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                        NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]                NVARCHAR (50)   NOT NULL,
    [ITEM_CODE]                   NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_ITEM_CODE] DEFAULT ('') NOT NULL,
    [ITEM_NAME]                   NVARCHAR (250)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_ITEM_NAME] DEFAULT ('') NOT NULL,
    [ITEM_GROUP_CODE]             NVARCHAR (50)   NULL,
    [CONDITION]                   NVARCHAR (50)   NULL,
    [BARCODE]                     NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_BARCODE] DEFAULT ('') NULL,
    [STATUS]                      NVARCHAR (20)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_STATUS] DEFAULT ('') NULL,
    [PO_NO]                       NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_PO_NO] DEFAULT ('') NULL,
    [REQUESTOR_CODE]              NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_REQUESTOR_CODE] DEFAULT ('') NULL,
    [REQUESTOR_NAME]              NVARCHAR (250)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_REQUESTOR_NAME] DEFAULT ('') NULL,
    [VENDOR_CODE]                 NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_VENDOR_CODE] DEFAULT ('') NULL,
    [VENDOR_NAME]                 NVARCHAR (250)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_VENDOR_NAME] DEFAULT ('') NULL,
    [IS_PO]                       NVARCHAR (1)    NULL,
    [IS_RENTAL]                   NVARCHAR (1)    NULL,
    [TYPE_CODE]                   NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_TYPE_CODE] DEFAULT ('') NULL,
    [TYPE_NAME]                   NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CATEGORY_CODE]               NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_CATEGORY_CODE] DEFAULT ('') NULL,
    [CATEGORY_NAME]               NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PURCHASE_DATE]               DATETIME        NULL,
    [PURCHASE_PRICE]              DECIMAL (18, 2) CONSTRAINT [DF_EPROC_INTERFACE_ASSET_PURCHASE_PRICE] DEFAULT ((0)) NULL,
    [INVOICE_NO]                  NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_INVOICE_NO] DEFAULT ('') NULL,
    [INVOICE_DATE]                DATETIME        CONSTRAINT [DF_EPROC_INTERFACE_ASSET_INVOICE_DATE] DEFAULT ('') NULL,
    [ORIGINAL_PRICE]              DECIMAL (18, 2) CONSTRAINT [DF_EPROC_INTERFACE_ASSET_ORIGINAL_PRICE] DEFAULT ((0)) NULL,
    [BRANCH_CODE]                 NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_BRANCH_CODE] DEFAULT ('') NULL,
    [BRANCH_NAME]                 NVARCHAR (250)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_BRANCH_NAME] DEFAULT ('') NULL,
    [DIVISION_CODE]               NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_DIVISION_CODE] DEFAULT ('') NULL,
    [DIVISION_NAME]               NVARCHAR (250)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_DIVISION_NAME] DEFAULT ('') NULL,
    [DEPARTMENT_CODE]             NVARCHAR (50)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_DEPARTMENT_CODE] DEFAULT ('') NULL,
    [DEPARTMENT_NAME]             NVARCHAR (250)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_DEPARTMENT_NAME] DEFAULT ('') NULL,
    [SETTLE_DATE]                 DATETIME        NULL,
    [PPH]                         DECIMAL (9, 6)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_PURCHASE_PRICE1] DEFAULT ((0)) NULL,
    [PPN]                         DECIMAL (9, 6)  CONSTRAINT [DF_EPROC_INTERFACE_ASSET_PURCHASE_PRICE1_1] DEFAULT ((0)) NULL,
    [ASSET_FROM]                  NVARCHAR (50)   NULL,
    [ASSET_PURPOSE]               NVARCHAR (50)   NULL,
    [SPAF_AMOUNT]                 DECIMAL (18, 2) NULL,
    [SUBVENTION_AMOUNT]           DECIMAL (18, 2) NULL,
    [BPKB_NO]                     NVARCHAR (50)   NULL,
    [COVER_NOTE]                  NVARCHAR (50)   NULL,
    [COVER_NOTE_DATE]             DATETIME        NULL,
    [COVER_NOTE_EXP_DATE]         DATETIME        NULL,
    [DOCUMENT_TYPE]               NVARCHAR (15)   NULL,
    [FILE_NAME]                   NVARCHAR (250)  NULL,
    [FILE_PATH]                   NVARCHAR (250)  NULL,
    [REFF_NO]                     NVARCHAR (50)   NULL,
    [REMARKS]                     NVARCHAR (4000) NULL,
    [JOB_STATUS]                  NVARCHAR (10)   CONSTRAINT [DF_EPROC_INTERFACE_ASSET_JOB_STATUS] DEFAULT (N'HOLD') NULL,
    [FAILED_REMARKS]              NVARCHAR (4000) NULL,
    [CRE_DATE]                    DATETIME        NOT NULL,
    [CRE_BY]                      NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                    DATETIME        NOT NULL,
    [MOD_BY]                      NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [STNK_NO]                     NVARCHAR (50)   NULL,
    [STNK_DATE]                   DATETIME        NULL,
    [STNK_EXP_DATE]               DATETIME        NULL,
    [STCK_NO]                     NVARCHAR (50)   NULL,
    [STCK_DATE]                   DATETIME        NULL,
    [STCK_EXP_DATE]               DATETIME        NULL,
    [KEUR_NO]                     NVARCHAR (50)   NULL,
    [KEUR_DATE]                   DATETIME        NULL,
    [KEUR_EXP_DATE]               DATETIME        NULL,
    [DISCOUNT_AMOUNT]             DECIMAL (18, 2) NULL,
    [PPN_AMOUNT]                  DECIMAL (18, 2) NULL,
    [PPH_AMOUNT]                  DECIMAL (18, 2) NULL,
    [POSTING_DATE]                DATETIME        NULL,
    [GRN_DETAIL_ID]               BIGINT          NULL,
    [FINAL_GRN_REQUEST_DETAIL_ID] BIGINT          NULL,
    [is_from_grn_process]         NVARCHAR (1)    NULL,
    [IS_FINAL_ALL]                NVARCHAR (1)    NULL,
    [IS_GPS]                      NVARCHAR (1)    NULL,
    [GPS_VENDOR_CODE]             NVARCHAR (50)   NULL,
    [GPS_VENDOR_NAME]             NVARCHAR (250)  NULL,
    [GPS_RECEIVED_DATE]           DATETIME        NULL,
    CONSTRAINT [PK_EPROC_INTERFACE_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC, [CODE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EPROC_INTERFACE_ASSET', @level2type = N'COLUMN', @level2name = N'CONDITION';

