CREATE TABLE [dbo].[FINAL_GRN_REQUEST_DETAIL] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [FINAL_GRN_REQUEST_NO] NVARCHAR (50)   NULL,
    [ASSET_NO]             NVARCHAR (50)   NULL,
    [DELIVERY_TO]          NVARCHAR (250)  NULL,
    [BBN_NAME]             NVARCHAR (250)  NULL,
    [BBN_LOCATION]         NVARCHAR (4000) NULL,
    [BBN_ADDRESS]          NVARCHAR (4000) NULL,
    [YEAR]                 NVARCHAR (50)   NULL,
    [COLOUR]               NVARCHAR (50)   NULL,
    [PO_CODE_ASSET]        NVARCHAR (50)   NULL,
    [GRN_CODE_ASSET]       NVARCHAR (50)   NULL,
    [GRN_DETAIL_ID_ASSET]  BIGINT          NULL,
    [SUPPLIER_NAME_ASSET]  NVARCHAR (250)  NULL,
    [GRN_RECEIVE_DATE]     DATETIME        NULL,
    [PLAT_NO]              NVARCHAR (50)   NULL,
    [ENGINE_NO]            NVARCHAR (50)   NULL,
    [CHASIS_NO]            NVARCHAR (50)   NULL,
    [STATUS]               NVARCHAR (50)   NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [IS_JOURNAL_ASSET]     NVARCHAR (1)    NULL,
    [ASSET_NAME]           NVARCHAR (50)   NULL,
    [ASSET_CODE]           NVARCHAR (50)   NULL,
    [GRN_PO_DETAIL_ID]     BIGINT          NULL,
    CONSTRAINT [PK_FINAL_GRN_REQUEST_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

