CREATE TABLE [dbo].[FINAL_GRN_REQUEST_DETAIL_KAROSERI_LOOKUP] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NO]   NVARCHAR (50)  NULL,
    [PO_NO]            NVARCHAR (50)  NULL,
    [GRN_CODE]         NVARCHAR (50)  NULL,
    [GRN_DETAIL_ID]    INT            NULL,
    [ITEM_CODE]        NVARCHAR (50)  NULL,
    [ITEM_NAME]        NVARCHAR (250) NULL,
    [SUPPLIER_NAME]    NVARCHAR (250) NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [GRN_PO_DETAIL_ID] BIGINT         NULL,
    CONSTRAINT [PK_FINAL_GRN_REQUEST_KAROSERI_LOOKUP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

