CREATE TABLE [dbo].[GOOD_RECEIPT_NOTE] (
    [CODE]                NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]        NVARCHAR (50)   NOT NULL,
    [PURCHASE_ORDER_CODE] NVARCHAR (50)   NOT NULL,
    [RECEIVE_DATE]        DATETIME        NOT NULL,
    [SUPPLIER_CODE]       NVARCHAR (50)   NOT NULL,
    [SUPPLIER_NAME]       NVARCHAR (250)  NOT NULL,
    [BRANCH_CODE]         NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]         NVARCHAR (250)  NOT NULL,
    [DIVISION_CODE]       NVARCHAR (50)   NOT NULL,
    [DIVISION_NAME]       NVARCHAR (25)   NOT NULL,
    [DEPARTMENT_CODE]     NVARCHAR (50)   NOT NULL,
    [DEPARTMENT_NAME]     NVARCHAR (250)  NOT NULL,
    [REMARK]              NVARCHAR (4000) NULL,
    [STATUS]              NVARCHAR (25)   NOT NULL,
    [REFF_NO]             NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [COVER_NOTE_STATUS]   NVARCHAR (25)   NULL,
    [IS_VALIDATE]         NVARCHAR (1)    NULL,
    [NEW_SPESIFICATION]   NVARCHAR (4000) NULL,
    [POSTING_DATE]        DATETIME        NULL,
    CONSTRAINT [PK_GOOD_RECEIPT_NOTE] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_GOOD_RECEIPT_NOTE_STATUS]
    ON [dbo].[GOOD_RECEIPT_NOTE]([STATUS] ASC);

