CREATE TABLE [dbo].[IFINPROC_NEW_ASSET] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]        NVARCHAR (50)   NOT NULL,
    [PURCHASE_PRICE]    DECIMAL (18, 2) NULL,
    [ORIG_AMOUNT]       DECIMAL (18, 2) NULL,
    [TYPE]              NVARCHAR (50)   NULL,
    [POSTING_DATE]      DATETIME        NULL,
    [RETURN_DATE]       DATETIME        NULL,
    [FIRST_ADJUST_DATE] DATETIME        NULL,
    [INVOICE_DATE_TYPE] NVARCHAR (50)   NULL,
    [INVOICE_CODE]      NVARCHAR (50)   NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_IFINPROC_NEW_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC)
);

