CREATE TABLE [dbo].[IFINPROC_INTERFACE_DOCUMENT_PENDING_DETAIL] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [DOCUMENT_PENDING_CODE] NVARCHAR (50)   NOT NULL,
    [DOCUMENT_NAME]         NVARCHAR (250)  NOT NULL,
    [DOCUMENT_DESCRIPTION]  NVARCHAR (4000) NOT NULL,
    [FILE_NAME]             NVARCHAR (250)  NULL,
    [PATHS]                 NVARCHAR (250)  NULL,
    [EXPIRED_DATE]          DATETIME        NULL,
    [IS_TEMPORARY]          NVARCHAR (1)    CONSTRAINT [DF_IFINPROC_INTERFACE_DOCUMENT_PENDING_DETAIL_IS_TEMPORARY] DEFAULT (N'0') NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL
);

