CREATE TABLE [dbo].[INVENTORY_CARD] (
    [ID]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [COMPANY_CODE]       NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_CARD_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_CODE]        NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_CARD_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]        NVARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_CARD_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [TRANSACTION_CODE]   NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TRANSACTION_TYPE]   NVARCHAR (5)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TRANSACTION_PERIOD] NVARCHAR (10)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_CODE]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_NAME]          NVARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_CARD_ITEM_NAME] DEFAULT ('') NOT NULL,
    [WAREHOUSE_CODE]     NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_CARD_WAREHOUSE_CODE] DEFAULT ('') NOT NULL,
    [PLUS_OR_MINUS]      NVARCHAR (5)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_CARD_PLUS_OR_MINUS] DEFAULT ('') NOT NULL,
    [QUANTITY]           INT            NOT NULL,
    [ON_HAND_QUANTITY]   INT            NOT NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_INVENTORY_CARD] PRIMARY KEY CLUSTERED ([ID] ASC)
);

