CREATE TABLE [dbo].[INVENTORY_OPNAME] (
    [CODE]               NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [COMPANY_CODE]       NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [OPNAME_DATE]        DATETIME       NOT NULL,
    [BRANCH_CODE]        NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]        NVARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [WAREHOUSE_CODE]     NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_WAREHOUSE_CODE] DEFAULT ('') NOT NULL,
    [ITEM_CODE]          NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_ITEM_CODE] DEFAULT ('') NOT NULL,
    [ITEM_NAME]          NVARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_ITEM_NAME] DEFAULT ('') NOT NULL,
    [UOM_CODE]           NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_UOM_CODE] DEFAULT ('') NOT NULL,
    [UOM_NAME]           NVARCHAR (250) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_UOM_NAME] DEFAULT ('') NOT NULL,
    [QUANTITY_STOCK]     INT            CONSTRAINT [DF_INVENTORY_OPNAME_QUANTITY_STOCK] DEFAULT ((0)) NOT NULL,
    [QUANTITY_OPNAME]    INT            CONSTRAINT [DF_INVENTORY_OPNAME_QUANTITY_OPNAME] DEFAULT ((0)) NOT NULL,
    [QUANTITY_DEVIATION] INT            CONSTRAINT [DF_INVENTORY_OPNAME_QUANTITY_DEVIATION] DEFAULT ((0)) NOT NULL,
    [STATUS]             NVARCHAR (25)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_OPNAME_STATUS] DEFAULT ('') NOT NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_INVENTORY_OPNAME] PRIMARY KEY CLUSTERED ([CODE] ASC, [COMPANY_CODE] ASC)
);

