CREATE TABLE [dbo].[INVENTORY_ADJUSTMENT_DETAIL] (
    [ID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [INVENTORY_ADJUSTMENT_CODE] NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_INVENTORY_ADJUSTMENT_CODE] DEFAULT ('') NOT NULL,
    [ITEM_CODE]                 NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_ITEM_CODE] DEFAULT ('') NOT NULL,
    [ITEM_NAME]                 NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_ITEM_NAME] DEFAULT ('') NOT NULL,
    [PLUS_OR_MINUS]             NVARCHAR (5)    COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_PLUS_OR_MINUS] DEFAULT ('') NOT NULL,
    [WAREHOUSE_CODE]            NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_WAREHOUSE_CODE] DEFAULT ('') NOT NULL,
    [TOTAL_ADJUSTMENT]          INT             CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_TOTAL_ADJUSTMENT] DEFAULT ((0)) NOT NULL,
    [REMARK]                    NVARCHAR (4000) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_INVENTORY_ADJUSTMENT_DETAIL_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]                  DATETIME        NOT NULL,
    [CRE_BY]                    NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]                  DATETIME        NOT NULL,
    [MOD_BY]                    NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_INVENTORY_ADJUSTMENT_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

