CREATE TABLE [dbo].[LIST_DATA_CLEANSING_INVOICE_DAN_MONITORING_AP_SEBELUM_CRPRIORITY_NAIK] (
    [INVOICE_OR_GNR_NO] NVARCHAR (50)   NULL,
    [STATUS_INVOICE]    NVARCHAR (50)   NULL,
    [ACTION]            NVARCHAR (15)   NULL,
    [REMARK]            NVARCHAR (4000) NULL,
    [CRE_DATE]          DATETIME        NULL
);

