CREATE TABLE [dbo].[MASTER_TASK_USER_DETAIL] (
    [CODE]                NVARCHAR (50) NOT NULL,
    [COMPANY_CODE]        NVARCHAR (50) CONSTRAINT [DF_MASTER_TASK_USER_DETAIL_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [SYS_CODE]            NVARCHAR (50) CONSTRAINT [DF_MASTER_TASK_USER_DETAIL_SYS_CODE] DEFAULT ('') NOT NULL,
    [MAIN_TASK_USER_CODE] NVARCHAR (50) NOT NULL,
    [ROLE_GROUP_CODE]     NVARCHAR (50) NOT NULL,
    [CRE_DATE]            DATETIME      NOT NULL,
    [CRE_BY]              NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15) NOT NULL,
    [MOD_DATE]            DATETIME      NOT NULL,
    [MOD_BY]              NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_MASTER_TASK_USER_DETAIL] PRIMARY KEY CLUSTERED ([CODE] ASC, [COMPANY_CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_TASK_USER_DETAIL_Insert_Audit] 
			ON [dbo].[MASTER_TASK_USER_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_TASK_USER_DETAIL]
([CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_TASK_USER_DETAIL_Delete_Audit]    
			ON [dbo].[MASTER_TASK_USER_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_TASK_USER_DETAIL]
([CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_TASK_USER_DETAIL_Update_Audit]      
			ON [dbo].[MASTER_TASK_USER_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([SYS_CODE]) THEN '[SYS_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([MAIN_TASK_USER_CODE]) THEN '[MAIN_TASK_USER_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ROLE_GROUP_CODE]) THEN '[ROLE_GROUP_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_TASK_USER_DETAIL]
([CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_TASK_USER_DETAIL]
([CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[SYS_CODE],[MAIN_TASK_USER_CODE],[ROLE_GROUP_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END