CREATE TABLE [dbo].[MASTER_TRANSACTION_PARAMETER] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_CODE]           NVARCHAR (50)   NOT NULL,
    [TRANSACTION_CODE]       NVARCHAR (50)   NOT NULL,
    [PROCESS_CODE]           NVARCHAR (50)   NOT NULL,
    [ORDER_KEY]              INT             NOT NULL,
    [PARAMETER_AMOUNT]       DECIMAL (18, 2) CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_PARAMETER_AMOUNT] DEFAULT ((0)) NOT NULL,
    [IS_CALCULATE_BY_SYSTEM] NVARCHAR (1)    NOT NULL,
    [IS_TRANSACTION]         NVARCHAR (1)    NOT NULL,
    [IS_AMOUNT_EDITABLE]     NVARCHAR (1)    NOT NULL,
    [IS_DISCOUNT_EDITABLE]   NVARCHAR (1)    CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_IS_DISCOUNT_EDITABLE] DEFAULT ((0)) NOT NULL,
    [GL_LINK_CODE]           NVARCHAR (50)   NULL,
    [GL_LINK_NAME]           NVARCHAR (250)  NULL,
    [DISCOUNT_GL_LINK_CODE]  NVARCHAR (50)   NULL,
    [DISCOUNT_GL_LINK_NAME]  NVARCHAR (250)  NULL,
    [MAXIMUM_DISC_PCT]       DECIMAL (9, 6)  CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_MAXIMUM_DISC_PCT] DEFAULT ((0)) NOT NULL,
    [MAXIMUM_DISC_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_MAXIMUM_DISC_AMOUNT] DEFAULT ((0)) NOT NULL,
    [IS_JOURNAL]             NVARCHAR (1)    NOT NULL,
    [DEBET_OR_CREDIT]        NVARCHAR (10)   NULL,
    [IS_DISCOUNT_JURNAL]     NVARCHAR (1)    NULL,
    [IS_REDUCE_TRANSACTION]  NVARCHAR (1)    NULL,
    [IS_PSAK]                NVARCHAR (1)    NULL,
    [PSAK_GL_LINK_CODE]      NVARCHAR (50)   NULL,
    [PSAK_GL_LINK_NAME]      NVARCHAR (250)  NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_TRANSACTION_PARAMETER] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_TRANSACTION_PARAMETER_Delete_Audit]    
			ON [dbo].[MASTER_TRANSACTION_PARAMETER]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_TRANSACTION_PARAMETER_Update_Audit]      
			ON [dbo].[MASTER_TRANSACTION_PARAMETER]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_CODE]) THEN '[TRANSACTION_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PROCESS_CODE]) THEN '[PROCESS_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ORDER_KEY]) THEN '[ORDER_KEY]-' ELSE '' END + 
CASE WHEN UPDATE([PARAMETER_AMOUNT]) THEN '[PARAMETER_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_CALCULATE_BY_SYSTEM]) THEN '[IS_CALCULATE_BY_SYSTEM]-' ELSE '' END + 
CASE WHEN UPDATE([IS_TRANSACTION]) THEN '[IS_TRANSACTION]-' ELSE '' END + 
CASE WHEN UPDATE([IS_AMOUNT_EDITABLE]) THEN '[IS_AMOUNT_EDITABLE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_DISCOUNT_EDITABLE]) THEN '[IS_DISCOUNT_EDITABLE]-' ELSE '' END + 
CASE WHEN UPDATE([GL_LINK_CODE]) THEN '[GL_LINK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([GL_LINK_NAME]) THEN '[GL_LINK_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DISCOUNT_GL_LINK_CODE]) THEN '[DISCOUNT_GL_LINK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DISCOUNT_GL_LINK_NAME]) THEN '[DISCOUNT_GL_LINK_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([MAXIMUM_DISC_PCT]) THEN '[MAXIMUM_DISC_PCT]-' ELSE '' END + 
CASE WHEN UPDATE([MAXIMUM_DISC_AMOUNT]) THEN '[MAXIMUM_DISC_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_JOURNAL]) THEN '[IS_JOURNAL]-' ELSE '' END + 
CASE WHEN UPDATE([DEBET_OR_CREDIT]) THEN '[DEBET_OR_CREDIT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_DISCOUNT_JURNAL]) THEN '[IS_DISCOUNT_JURNAL]-' ELSE '' END + 
CASE WHEN UPDATE([IS_REDUCE_TRANSACTION]) THEN '[IS_REDUCE_TRANSACTION]-' ELSE '' END + 
CASE WHEN UPDATE([IS_PSAK]) THEN '[IS_PSAK]-' ELSE '' END + 
CASE WHEN UPDATE([PSAK_GL_LINK_CODE]) THEN '[PSAK_GL_LINK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PSAK_GL_LINK_NAME]) THEN '[PSAK_GL_LINK_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_TRANSACTION_PARAMETER_Insert_Audit] 
			ON [dbo].[MASTER_TRANSACTION_PARAMETER]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[COMPANY_CODE],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[GL_LINK_NAME],[DISCOUNT_GL_LINK_CODE],[DISCOUNT_GL_LINK_NAME],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[IS_REDUCE_TRANSACTION],[IS_PSAK],[PSAK_GL_LINK_CODE],[PSAK_GL_LINK_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ID DATA TRANSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE PERUSAHAAN (DSF)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'COMPANY_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE TRANSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'TRANSACTION_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'PROCESS_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOMOR URUT', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'ORDER_KEY';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'PARAMETER_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'APAKAH PARAMETER TERSEBUT DI KALKULASI OLEH SISTEM', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_CALCULATE_BY_SYSTEM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'MENENTUKAN APAKAH DATA TERSEBUT TRAKSAKSI ATAU INFORMASI, IYA (1) TIDAK (0)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_TRANSACTION';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'APAKAH NILAI DATA PADA TRAKSAKSI TERSEBUT DAPAT DILAKUKAN PROSES EDIT, IYA (1) TIDAK (0)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_AMOUNT_EDITABLE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'MENENTUKAN APAKAH NILAI DISKON PADA DATA TERSEBUT DAPAT DILAKUKAN PROSES EDIT, IYA (1) TIDAK (0)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_DISCOUNT_EDITABLE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE GENERAL LEDGER PADA DATA PARAMETER TRANKSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'GL_LINK_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE GENERAL LEDGER DISKON PADA DATA PARAMETER TRANKSAKSI TERSEBUT', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'DISCOUNT_GL_LINK_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'PERSENTASE MAKSIMAL DISCOUNT PADA DATA PARAMETER TRANSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'MAXIMUM_DISC_PCT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NILAI MAKSIMAL DISKON PADA DATA PARAMETER TRANSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'MAXIMUM_DISC_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'MENENTUKAN APAKAH DATA PARAMETER TRANSAKSI TERSEBUT AKAN MEMBENTUK JURNAL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_JOURNAL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'MENENTUKAN APAKAH TIPE TRANSAKSI ADALAH DEBIT ATAU KREDIT', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'DEBET_OR_CREDIT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_DISCOUNT_JURNAL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_REDUCE_TRANSACTION';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'IYA (1) TIDAK (0)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_PSAK';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE PSAK PADA PARAMETER TRANKSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'PSAK_GL_LINK_CODE';

