CREATE TABLE [dbo].[MASTER_VENDOR] (
    [CODE]                   NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]           NVARCHAR (50)   CONSTRAINT [DF_MASTER_VENDOR_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [NAME]                   NVARCHAR (200)  NOT NULL,
    [ADDRESS]                NVARCHAR (4000) NOT NULL,
    [CITY_CODE]              NVARCHAR (50)   NOT NULL,
    [PROVINCE_CODE]          NVARCHAR (50)   NOT NULL,
    [ZIPCODE]                NVARCHAR (10)   NOT NULL,
    [VENDOR_TYPE]            NVARCHAR (50)   CONSTRAINT [DF_MASTER_VENDOR_VENDOR_TYPE] DEFAULT ('') NOT NULL,
    [ID_TYPE]                NVARCHAR (50)   CONSTRAINT [DF_MASTER_VENDOR_ID_TYPE] DEFAULT ('') NOT NULL,
    [ID_NO]                  NVARCHAR (100)  CONSTRAINT [DF_MASTER_VENDOR_ID_NO] DEFAULT ('') NOT NULL,
    [TAX_CALCULATION_METHOD] NVARCHAR (50)   CONSTRAINT [DF_MASTER_VENDOR_TAX_CALCULATION_METHOD] DEFAULT ('') NOT NULL,
    [PKP_NO]                 NVARCHAR (50)   CONSTRAINT [DF_MASTER_VENDOR_PKP_NO] DEFAULT ('') NOT NULL,
    [PHONE]                  NVARCHAR (200)  NOT NULL,
    [FAX]                    NVARCHAR (30)   CONSTRAINT [DF_MASTER_VENDOR_FAX] DEFAULT ('') NULL,
    [SERVICE_TYPE_CODE]      NVARCHAR (50)   NOT NULL,
    [BUSINESS_TYPE_CODE]     NVARCHAR (50)   NOT NULL,
    [OWNER_NAME]             NVARCHAR (100)  NOT NULL,
    [OWNER_PHONE]            NVARCHAR (25)   NOT NULL,
    [CONTACT_NAME]           NVARCHAR (100)  NOT NULL,
    [CONTACT_POSITION]       NVARCHAR (100)  NOT NULL,
    [CONTACT_PHONE]          NVARCHAR (25)   NOT NULL,
    [WEBSITE_ADDRESS]        NVARCHAR (50)   CONSTRAINT [DF_MASTER_VENDOR_WEBSITE_ADDRESS] DEFAULT ('') NULL,
    [EMAIL]                  NVARCHAR (50)   NOT NULL,
    [NPWP]                   NVARCHAR (20)   NOT NULL,
    [SIUP_NO]                NVARCHAR (25)   NULL,
    [SKU_NO]                 NVARCHAR (25)   NULL,
    [TDP_NO]                 NVARCHAR (25)   NULL,
    [REMARK]                 NVARCHAR (4000) CONSTRAINT [DF_MASTER_VENDOR_REMARK] DEFAULT ('') NULL,
    [ID_VENDOR]              NVARCHAR (150)  NULL,
    [STATUS]                 NVARCHAR (15)   NOT NULL,
    [IS_ACTIVE]              NVARCHAR (1)    CONSTRAINT [DF_MASTER_VENDOR_IS_ACTIVE] DEFAULT ('') NOT NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_VENDOR_1] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_VENDOR_Insert_Audit] 
			ON [dbo].[MASTER_VENDOR]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR]
([CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_VENDOR_Delete_Audit]    
			ON [dbo].[MASTER_VENDOR]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR]
([CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_VENDOR_Update_Audit]      
			ON [dbo].[MASTER_VENDOR]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([NAME]) THEN '[NAME]-' ELSE '' END + 
CASE WHEN UPDATE([ADDRESS]) THEN '[ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([CITY_CODE]) THEN '[CITY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PROVINCE_CODE]) THEN '[PROVINCE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ZIPCODE]) THEN '[ZIPCODE]-' ELSE '' END + 
CASE WHEN UPDATE([VENDOR_TYPE]) THEN '[VENDOR_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([ID_TYPE]) THEN '[ID_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([ID_NO]) THEN '[ID_NO]-' ELSE '' END + 
CASE WHEN UPDATE([TAX_CALCULATION_METHOD]) THEN '[TAX_CALCULATION_METHOD]-' ELSE '' END + 
CASE WHEN UPDATE([PKP_NO]) THEN '[PKP_NO]-' ELSE '' END + 
CASE WHEN UPDATE([PHONE]) THEN '[PHONE]-' ELSE '' END + 
CASE WHEN UPDATE([FAX]) THEN '[FAX]-' ELSE '' END + 
CASE WHEN UPDATE([SERVICE_TYPE_CODE]) THEN '[SERVICE_TYPE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([BUSINESS_TYPE_CODE]) THEN '[BUSINESS_TYPE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([OWNER_NAME]) THEN '[OWNER_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([OWNER_PHONE]) THEN '[OWNER_PHONE]-' ELSE '' END + 
CASE WHEN UPDATE([CONTACT_NAME]) THEN '[CONTACT_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([CONTACT_POSITION]) THEN '[CONTACT_POSITION]-' ELSE '' END + 
CASE WHEN UPDATE([CONTACT_PHONE]) THEN '[CONTACT_PHONE]-' ELSE '' END + 
CASE WHEN UPDATE([WEBSITE_ADDRESS]) THEN '[WEBSITE_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([EMAIL]) THEN '[EMAIL]-' ELSE '' END + 
CASE WHEN UPDATE([NPWP]) THEN '[NPWP]-' ELSE '' END + 
CASE WHEN UPDATE([SIUP_NO]) THEN '[SIUP_NO]-' ELSE '' END + 
CASE WHEN UPDATE([SKU_NO]) THEN '[SKU_NO]-' ELSE '' END + 
CASE WHEN UPDATE([TDP_NO]) THEN '[TDP_NO]-' ELSE '' END + 
CASE WHEN UPDATE([REMARK]) THEN '[REMARK]-' ELSE '' END + 
CASE WHEN UPDATE([ID_VENDOR]) THEN '[ID_VENDOR]-' ELSE '' END + 
CASE WHEN UPDATE([STATUS]) THEN '[STATUS]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR]
([CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR]
([CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[NAME],[ADDRESS],[CITY_CODE],[PROVINCE_CODE],[ZIPCODE],[VENDOR_TYPE],[ID_TYPE],[ID_NO],[TAX_CALCULATION_METHOD],[PKP_NO],[PHONE],[FAX],[SERVICE_TYPE_CODE],[BUSINESS_TYPE_CODE],[OWNER_NAME],[OWNER_PHONE],[CONTACT_NAME],[CONTACT_POSITION],[CONTACT_PHONE],[WEBSITE_ADDRESS],[EMAIL],[NPWP],[SIUP_NO],[SKU_NO],[TDP_NO],[REMARK],[ID_VENDOR],[STATUS],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END