CREATE TABLE [dbo].[MASTER_VENDOR_ITEM_GROUP] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [VENDOR_CODE]      NVARCHAR (50)  NOT NULL,
    [TRANSACTION_TYPE] NVARCHAR (50)  NOT NULL,
    [GROUP_CODE]       NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]      NVARCHAR (250) NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_ITEM_GROUP] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MASTER_VENDOR_ITEM_GROUP_MASTER_VENDOR] FOREIGN KEY ([VENDOR_CODE]) REFERENCES [dbo].[MASTER_VENDOR] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_VENDOR_ITEM_GROUP_Update_Audit]      
			ON [dbo].[MASTER_VENDOR_ITEM_GROUP]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([VENDOR_CODE]) THEN '[VENDOR_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_TYPE]) THEN '[TRANSACTION_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([GROUP_CODE]) THEN '[GROUP_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR_ITEM_GROUP]
([ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR_ITEM_GROUP]
([ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_VENDOR_ITEM_GROUP_Insert_Audit] 
			ON [dbo].[MASTER_VENDOR_ITEM_GROUP]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR_ITEM_GROUP]
([ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_VENDOR_ITEM_GROUP_Delete_Audit]    
			ON [dbo].[MASTER_VENDOR_ITEM_GROUP]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_VENDOR_ITEM_GROUP]
([ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[VENDOR_CODE],[TRANSACTION_TYPE],[GROUP_CODE],[DESCRIPTION],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED