CREATE TABLE [dbo].[MASTER_ITEM] (
    [CODE]             NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]     NVARCHAR (50)   NOT NULL,
    [TRANSACTION_TYPE] NVARCHAR (50)   NOT NULL,
    [ITEM_GROUP_CODE]  NVARCHAR (50)   NOT NULL,
    [MERK_CODE]        NVARCHAR (50)   NULL,
    [MODEL_CODE]       NVARCHAR (50)   NULL,
    [TYPE_CODE]        NVARCHAR (50)   NULL,
    [UOM_CODE]         NVARCHAR (50)   NOT NULL,
    [TYPE_ASSET_CODE]  NVARCHAR (50)   NOT NULL,
    [FA_CATEGORY_CODE] NVARCHAR (50)   NOT NULL,
    [FA_CATEGORY_NAME] NVARCHAR (250)  NOT NULL,
    [PO_LATEST_PRICE]  DECIMAL (18, 2) NOT NULL,
    [PO_AVERAGE_PRICE] DECIMAL (18, 2) NOT NULL,
    [DESCRIPTION]      NVARCHAR (250)  NOT NULL,
    [IS_RENT]          NVARCHAR (1)    NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)    NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_ITEM_1] PRIMARY KEY CLUSTERED ([CODE] ASC, [COMPANY_CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_ITEM_Insert_Audit] 
			ON [dbo].[MASTER_ITEM]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_ITEM]
([CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_ITEM_Delete_Audit]    
			ON [dbo].[MASTER_ITEM]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_ITEM]
([CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_ITEM_Update_Audit]      
			ON [dbo].[MASTER_ITEM]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_TYPE]) THEN '[TRANSACTION_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([ITEM_GROUP_CODE]) THEN '[ITEM_GROUP_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([MERK_CODE]) THEN '[MERK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([MODEL_CODE]) THEN '[MODEL_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TYPE_CODE]) THEN '[TYPE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([UOM_CODE]) THEN '[UOM_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TYPE_ASSET_CODE]) THEN '[TYPE_ASSET_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([FA_CATEGORY_CODE]) THEN '[FA_CATEGORY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([FA_CATEGORY_NAME]) THEN '[FA_CATEGORY_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PO_LATEST_PRICE]) THEN '[PO_LATEST_PRICE]-' ELSE '' END + 
CASE WHEN UPDATE([PO_AVERAGE_PRICE]) THEN '[PO_AVERAGE_PRICE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([IS_RENT]) THEN '[IS_RENT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_ITEM]
([CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_ITEM]
([CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[TRANSACTION_TYPE],[ITEM_GROUP_CODE],[MERK_CODE],[MODEL_CODE],[TYPE_CODE],[UOM_CODE],[TYPE_ASSET_CODE],[FA_CATEGORY_CODE],[FA_CATEGORY_NAME],[PO_LATEST_PRICE],[PO_AVERAGE_PRICE],[DESCRIPTION],[IS_RENT],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END