CREATE TABLE [dbo].[MASTER_DASHBOARD] (
    [CODE]           NVARCHAR (50)  NOT NULL,
    [DASHBOARD_NAME] NVARCHAR (250) NOT NULL,
    [DASHBOARD_TYPE] NVARCHAR (20)  NOT NULL,
    [DASHBOARD_GRID] NVARCHAR (50)  NOT NULL,
    [SP_NAME]        NVARCHAR (250) NULL,
    [IS_ACTIVE]      NVARCHAR (1)   CONSTRAINT [DF_MASTER_DASHBOARD_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    [IS_EDITABLE]    NVARCHAR (1)   CONSTRAINT [DF_MASTER_DASHBOARD_IS_EDITABLE] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_DASHBOARD] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_DASHBOARD_Delete_Audit]    
			ON [dbo].[MASTER_DASHBOARD]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD]
([CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_DASHBOARD_Update_Audit]      
			ON [dbo].[MASTER_DASHBOARD]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DASHBOARD_NAME]) THEN '[DASHBOARD_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DASHBOARD_TYPE]) THEN '[DASHBOARD_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([DASHBOARD_GRID]) THEN '[DASHBOARD_GRID]-' ELSE '' END + 
CASE WHEN UPDATE([SP_NAME]) THEN '[SP_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_EDITABLE]) THEN '[IS_EDITABLE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD]
([CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD]
([CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_DASHBOARD_Insert_Audit] 
			ON [dbo].[MASTER_DASHBOARD]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD]
([CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[DASHBOARD_NAME],[DASHBOARD_TYPE],[DASHBOARD_GRID],[SP_NAME],[IS_ACTIVE],[IS_EDITABLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 