CREATE TABLE [dbo].[MASTER_DASHBOARD_USER] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [EMPLOYEE_CODE]  NVARCHAR (50)  NOT NULL,
    [EMPLOYEE_NAME]  NVARCHAR (250) NOT NULL,
    [DASHBOARD_CODE] NVARCHAR (50)  NULL,
    [ORDER_KEY]      INT            NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_DASHBOARD_USER] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_DASHBOARD_USER_Insert_Audit] 
			ON [dbo].[MASTER_DASHBOARD_USER]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD_USER]
([ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_DASHBOARD_USER_Delete_Audit]    
			ON [dbo].[MASTER_DASHBOARD_USER]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD_USER]
([ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_DASHBOARD_USER_Update_Audit]      
			ON [dbo].[MASTER_DASHBOARD_USER]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([EMPLOYEE_CODE]) THEN '[EMPLOYEE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([EMPLOYEE_NAME]) THEN '[EMPLOYEE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DASHBOARD_CODE]) THEN '[DASHBOARD_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ORDER_KEY]) THEN '[ORDER_KEY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD_USER]
([ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_DASHBOARD_USER]
([ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[EMPLOYEE_CODE],[EMPLOYEE_NAME],[DASHBOARD_CODE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END