CREATE TABLE [dbo].[PROCUREMENT_MYFOTM444177$] (
    [CODE]                        NVARCHAR (255) NULL,
    [COMPANY_CODE]                NVARCHAR (255) NULL,
    [PROCUREMENT_REQUEST_ITEM_ID] FLOAT (53)     NULL,
    [PROCUREMENT_REQUEST_CODE]    NVARCHAR (255) NULL,
    [PROCUREMENT_REQUEST_DATE]    DATETIME       NULL,
    [BRANCH_CODE]                 FLOAT (53)     NULL,
    [BRANCH_NAME]                 NVARCHAR (255) NULL,
    [ITEM_CODE]                   NVARCHAR (255) NULL,
    [ITEM_NAME]                   NVARCHAR (255) NULL,
    [ITEM_GROUP_CODE]             NVARCHAR (255) NULL,
    [TYPE_CODE]                   NVARCHAR (255) NULL,
    [TYPE_NAME]                   NVARCHAR (255) NULL,
    [TYPE_ASSET_CODE]             NVARCHAR (255) NULL,
    [ITEM_CATEGORY_CODE]          NVARCHAR (255) NULL,
    [ITEM_CATEGORY_NAME]          NVARCHAR (255) NULL,
    [ITEM_MERK_CODE]              NVARCHAR (255) NULL,
    [ITEM_MERK_NAME]              NVARCHAR (255) NULL,
    [ITEM_MODEL_CODE]             NVARCHAR (255) NULL,
    [ITEM_MODEL_NAME]             NVARCHAR (255) NULL,
    [ITEM_TYPE_CODE]              NVARCHAR (255) NULL,
    [ITEM_TYPE_NAME]              NVARCHAR (255) NULL,
    [QUANTITY_REQUEST]            FLOAT (53)     NULL,
    [APPROVED_QUANTITY]           FLOAT (53)     NULL,
    [SPECIFICATION]               NVARCHAR (255) NULL,
    [REMARK]                      NVARCHAR (255) NULL,
    [NEW_PURCHASE]                NVARCHAR (255) NULL,
    [PURCHASE_TYPE_CODE]          NVARCHAR (255) NULL,
    [PURCHASE_TYPE_NAME]          NVARCHAR (255) NULL,
    [UNIT_FROM]                   NVARCHAR (255) NULL,
    [QUANTITY_PURCHASE]           FLOAT (53)     NULL,
    [STATUS]                      NVARCHAR (255) NULL,
    [REQUESTOR_CODE]              NVARCHAR (255) NULL,
    [REQUESTOR_NAME]              NVARCHAR (255) NULL,
    [SPAF_AMOUNT]                 FLOAT (53)     NULL,
    [SUBVENTION_AMOUNT]           FLOAT (53)     NULL,
    [CRE_DATE]                    DATETIME       NULL,
    [CRE_BY]                      NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (255) NULL,
    [MOD_DATE]                    DATETIME       NULL,
    [MOD_BY]                      NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (255) NULL
);

