CREATE TABLE [dbo].[PROCREQITEM_MYFORM444177$] (
    [ID]                       FLOAT (53)     NULL,
    [PROCUREMENT_REQUEST_CODE] NVARCHAR (255) NULL,
    [ITEM_CODE]                NVARCHAR (255) NULL,
    [ITEM_NAME]                NVARCHAR (255) NULL,
    [QUANTITY_REQUEST]         FLOAT (53)     NULL,
    [APPROVED_QUANTITY]        FLOAT (53)     NULL,
    [TYPE_ASSET_CODE]          NVARCHAR (255) NULL,
    [UOM_CODE]                 NVARCHAR (255) NULL,
    [UOM_NAME]                 NVARCHAR (255) NULL,
    [SPECIFICATION]            NVARCHAR (255) NULL,
    [ITEM_CATEGORY_CODE]       NVARCHAR (255) NULL,
    [ITEM_CATEGORY_NAME]       NVARCHAR (255) NULL,
    [ITEM_MERK_CODE]           NVARCHAR (255) NULL,
    [ITEM_MERK_NAME]           NVARCHAR (255) NULL,
    [ITEM_MODEL_CODE]          NVARCHAR (255) NULL,
    [ITEM_MODEL_NAME]          NVARCHAR (255) NULL,
    [ITEM_TYPE_CODE]           NVARCHAR (255) NULL,
    [ITEM_TYPE_NAME]           NVARCHAR (255) NULL,
    [FA_CODE]                  NVARCHAR (255) NULL,
    [FA_NAME]                  NVARCHAR (255) NULL,
    [CATEGORY_TYPE]            NVARCHAR (255) NULL,
    [SPAF_AMOUNT]              FLOAT (53)     NULL,
    [SUBVENTION_AMOUNT]        FLOAT (53)     NULL,
    [REMARK]                   NVARCHAR (255) NULL,
    [CRE_DATE]                 DATETIME       NULL,
    [CRE_BY]                   NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (255) NULL,
    [MOD_DATE]                 DATETIME       NULL,
    [MOD_BY]                   NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (255) NULL,
    [IS_BBN]                   FLOAT (53)     NULL,
    [BBN_NAME]                 NVARCHAR (255) NULL,
    [BBN_ADDRESS]              NVARCHAR (255) NULL,
    [IS_RECOM]                 FLOAT (53)     NULL
);

