CREATE TABLE [dbo].[PROCUREMENT_VENDOR] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [PROCUREMENT_CODE] NVARCHAR (50)  CONSTRAINT [DF_PROCUREMENT_VENDOR_PROCUREMENT_CODE] DEFAULT ('') NOT NULL,
    [VENDOR_CODE]      NVARCHAR (50)  CONSTRAINT [DF_PROCUREMENT_VENDOR_VENDOR_CODE] DEFAULT ('') NOT NULL,
    [VENDOR_NAME]      NVARCHAR (250) CONSTRAINT [DF_PROCUREMENT_VENDOR_VENDOR_NAME] DEFAULT ('') NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_PROCUREMENT_VENDOR] PRIMARY KEY CLUSTERED ([ID] ASC)
);

