CREATE TABLE [dbo].[PROC_ASSET_LOOKUP] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)  NULL,
    [ITEM_CODE]      NVARCHAR (50)  NULL,
    [ITEM_NAME]      NVARCHAR (250) NULL,
    [PLAT_NO]        NVARCHAR (50)  NULL,
    [ENGINE_NO]      NVARCHAR (50)  NULL,
    [CHASIS_NO]      NVARCHAR (50)  NULL,
    [APPLICATION_NO] NVARCHAR (50)  NULL,
    [ASSET_NO]       NVARCHAR (50)  NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_PROC_ASSET_LOOKUP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

