CREATE TABLE [dbo].[PROC_INTERFACE_ASSET_HE] (
    [ID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]              NVARCHAR (50)   NOT NULL,
    [MERK_CODE]               NVARCHAR (50)   NULL,
    [MERK_NAME]               NVARCHAR (250)  NULL,
    [TYPE_ITEM_CODE]          NVARCHAR (50)   NULL,
    [TYPE_ITEM_NAME]          NVARCHAR (250)  NULL,
    [MODEL_CODE]              NVARCHAR (50)   NULL,
    [MODEL_NAME]              NVARCHAR (250)  NULL,
    [PLAT_NO]                 NVARCHAR (20)   NULL,
    [CHASSIS_NO]              NVARCHAR (50)   NULL,
    [ENGINE_NO]               NVARCHAR (50)   NULL,
    [INVOICE_NO]              NVARCHAR (50)   NULL,
    [BPKB_NO]                 NVARCHAR (50)   NULL,
    [COLOUR]                  NVARCHAR (50)   NULL,
    [CYLINDER]                NVARCHAR (20)   NULL,
    [STNK_NO]                 NVARCHAR (50)   NULL,
    [STNK_EXPIRED_DATE]       DATETIME        NULL,
    [STNK_TAX_DATE]           DATETIME        NULL,
    [STNK_RENEWAL]            NVARCHAR (15)   NULL,
    [BUILT_YEAR]              NVARCHAR (4)    NULL,
    [LAST_MILES]              NVARCHAR (15)   NULL,
    [LAST_MAINTENANCE_DATE]   DATETIME        NULL,
    [PURCHASE]                NVARCHAR (50)   NULL,
    [NO_LEASE_AGREEMENT]      NVARCHAR (50)   NULL,
    [DATE_OF_LEASE_AGREEMENT] DATETIME        NULL,
    [SECURITY_DEPOSIT]        DECIMAL (18, 2) NULL,
    [TOTAL_RENTAL_PERIOD]     NVARCHAR (9)    NULL,
    [RENTAL_PERIOD]           NVARCHAR (15)   NULL,
    [RENTAL_PRICE]            DECIMAL (18, 2) NULL,
    [TOTAL_RENTAL_PRICE]      DECIMAL (18, 2) NULL,
    [START_RENTAL_DATE]       DATETIME        NULL,
    [END_RENTAL_DATE]         DATETIME        NULL,
    [REMARK]                  NVARCHAR (4000) NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_PROC_INTERFACE_ASSET_HE] PRIMARY KEY CLUSTERED ([ID] ASC, [ASSET_CODE] ASC)
);

