CREATE TABLE [dbo].[PURCHASE_ORDER] (
    [CODE]                 NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_CODE] DEFAULT ('') NOT NULL,
    [COMPANY_CODE]         NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [ORDER_DATE]           DATETIME        NOT NULL,
    [SUPPLIER_CODE]        NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_SUPPLIER_CODE] DEFAULT ('') NOT NULL,
    [SUPPLIER_NAME]        NVARCHAR (250)  CONSTRAINT [DF_PURCHASE_ORDER_SUPPLIER_CODE1] DEFAULT ('') NULL,
    [SUPPLIER_ADDRESS]     NVARCHAR (4000) NULL,
    [BRANCH_CODE]          NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]          NVARCHAR (250)  CONSTRAINT [DF_PURCHASE_ORDER_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [DIVISION_CODE]        NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_DIVISION_CODE] DEFAULT ('') NULL,
    [DIVISION_NAME]        NVARCHAR (250)  CONSTRAINT [DF_PURCHASE_ORDER_DIVISION_NAME] DEFAULT ('') NULL,
    [DEPARTMENT_CODE]      NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_DEPARTMENT_CODE] DEFAULT ('') NULL,
    [DEPARTMENT_NAME]      NVARCHAR (250)  CONSTRAINT [DF_PURCHASE_ORDER_DEPARTMENT_NAME] DEFAULT ('') NULL,
    [PAYMENT_METHODE_CODE] NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_PAYMENT_METHODE_CODE] DEFAULT ('') NOT NULL,
    [PAYMENT_METHODE_NAME] NVARCHAR (250)  CONSTRAINT [DF_PURCHASE_ORDER_PAYMENT_METHODE_CODE1] DEFAULT ('') NOT NULL,
    [CURRENCY_CODE]        NVARCHAR (20)   CONSTRAINT [DF_PURCHASE_ORDER_CURRENCY_CODE] DEFAULT ('') NOT NULL,
    [CURRENCY_NAME]        NVARCHAR (250)  CONSTRAINT [DF_PURCHASE_ORDER_CURRENCY_NAME] DEFAULT ('') NOT NULL,
    [ORDER_TYPE_CODE]      NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_ORDER_TYPE_CODE] DEFAULT ('') NOT NULL,
    [TOTAL_AMOUNT]         DECIMAL (18, 2) CONSTRAINT [DF_PURCHASE_ORDER_TOTAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PPN_AMOUNT]           DECIMAL (18, 2) CONSTRAINT [DF_PURCHASE_ORDER_PPN_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PPH_AMOUNT]           DECIMAL (18, 2) CONSTRAINT [DF_PURCHASE_ORDER_PPH_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PAYMENT_BY]           NVARCHAR (20)   CONSTRAINT [DF_PURCHASE_ORDER_PAYMENT_BY] DEFAULT ('') NOT NULL,
    [RECEIPT_BY]           NVARCHAR (20)   CONSTRAINT [DF_PURCHASE_ORDER_RECEIPT_BY] DEFAULT ('') NOT NULL,
    [IS_TERMIN]            NVARCHAR (1)    CONSTRAINT [DF_PURCHASE_ORDER_IS_TERMIN] DEFAULT ('') NULL,
    [UNIT_FROM]            NVARCHAR (25)   CONSTRAINT [DF_PURCHASE_ORDER_IS_RENT] DEFAULT ('') NULL,
    [PROCUREMENT_TYPE]     NVARCHAR (25)   NULL,
    [FLAG_PROCESS]         NVARCHAR (25)   CONSTRAINT [DF_PURCHASE_ORDER_FLAG_PROCESS] DEFAULT ('') NOT NULL,
    [REQUESTOR_CODE]       NVARCHAR (50)   NULL,
    [REQUESTOR_NAME]       NVARCHAR (250)  NULL,
    [STATUS]               NVARCHAR (20)   CONSTRAINT [DF_PURCHASE_ORDER_STATUS] DEFAULT ('') NOT NULL,
    [REFF_NO]              NVARCHAR (50)   CONSTRAINT [DF_PURCHASE_ORDER_COMPANY_CODE1] DEFAULT ('') NULL,
    [ETA_DATE]             DATETIME        NOT NULL,
    [REMARK]               NVARCHAR (4000) CONSTRAINT [DF_PURCHASE_ORDER_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   CONSTRAINT [DF_PURCHASE_ORDER_CRE_BY] DEFAULT ('') NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   CONSTRAINT [DF_PURCHASE_ORDER_CRE_IP_ADDRESS] DEFAULT ('') NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   CONSTRAINT [DF_PURCHASE_ORDER_MOD_BY] DEFAULT ('') NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   CONSTRAINT [DF_PURCHASE_ORDER_MOD_IP_ADDRESS] DEFAULT ('') NOT NULL,
    [IS_SPESIFIC_ADDRESS]  NVARCHAR (1)    NULL,
    [DELIVERY_NAME]        NVARCHAR (250)  NULL,
    [DELIVERY_ADDRESS]     NVARCHAR (4000) NULL,
    CONSTRAINT [PK_PURCHASE_ORDER] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_PURCHASE_ORDER_ORDER_DATE_20250615]
    ON [dbo].[PURCHASE_ORDER]([ORDER_DATE] ASC)
    INCLUDE([SUPPLIER_NAME], [BRANCH_CODE]);

