CREATE TABLE [dbo].[PURCHASE_ORDER_MYFORM444177$] (
    [ID]                           FLOAT (53)     NULL,
    [PO_CODE]                      NVARCHAR (255) NULL,
    [ITEM_CODE]                    NVARCHAR (255) NULL,
    [ITEM_NAME]                    NVARCHAR (255) NULL,
    [TYPE_ASSET_CODE]              NVARCHAR (255) NULL,
    [ITEM_CATEGORY_CODE]           NVARCHAR (255) NULL,
    [ITEM_CATEGORY_NAME]           NVARCHAR (255) NULL,
    [ITEM_MERK_CODE]               NVARCHAR (255) NULL,
    [ITEM_MERK_NAME]               NVARCHAR (255) NULL,
    [ITEM_MODEL_CODE]              NVARCHAR (255) NULL,
    [ITEM_MODEL_NAME]              NVARCHAR (255) NULL,
    [ITEM_TYPE_CODE]               NVARCHAR (255) NULL,
    [ITEM_TYPE_NAME]               NVARCHAR (255) NULL,
    [UOM_CODE]                     NVARCHAR (255) NULL,
    [UOM_NAME]                     NVARCHAR (255) NULL,
    [PRICE_AMOUNT]                 FLOAT (53)     NULL,
    [DISCOUNT_AMOUNT]              FLOAT (53)     NULL,
    [ORDER_QUANTITY]               FLOAT (53)     NULL,
    [ORDER_REMAINING]              FLOAT (53)     NULL,
    [DESCRIPTION]                  NVARCHAR (255) NULL,
    [TAX_CODE]                     NVARCHAR (255) NULL,
    [TAX_NAME]                     NVARCHAR (255) NULL,
    [PPN_PCT]                      FLOAT (53)     NULL,
    [PPH_PCT]                      FLOAT (53)     NULL,
    [PPN_AMOUNT]                   FLOAT (53)     NULL,
    [PPH_AMOUNT]                   FLOAT (53)     NULL,
    [REQUESTOR_CODE]               NVARCHAR (255) NULL,
    [REQUESTOR_NAME]               NVARCHAR (255) NULL,
    [SUPPLIER_SELECTION_DETAIL_ID] FLOAT (53)     NULL,
    [INITIATION_ETA_DATE]          DATETIME       NULL,
    [ETA_DATE]                     DATETIME       NULL,
    [SPESIFICATION]                NVARCHAR (255) NULL,
    [UNIT_AVAILABLE_STATUS]        NVARCHAR (255) NULL,
    [INDENT_DAYS]                  FLOAT (53)     NULL,
    [OFFERING]                     NVARCHAR (255) NULL,
    [CRE_DATE]                     DATETIME       NULL,
    [CRE_BY]                       NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (255) NULL,
    [MOD_DATE]                     DATETIME       NULL,
    [MOD_BY]                       NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (255) NULL,
    [INVOICE_NO]                   NVARCHAR (255) NULL,
    [INVOICE_DETAIL_ID]            FLOAT (53)     NULL,
    [ETA_DATE_REMARK]              NVARCHAR (255) NULL
);

