CREATE TABLE [dbo].[QUOTATION_REVIEW_VENDOR] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [QUOTATION_REVIEW_CODE]  NVARCHAR (50)   NULL,
    [SUPPLIER_CODE]          NVARCHAR (50)   NULL,
    [SUPPLIER_NAME]          NVARCHAR (250)  NULL,
    [SUPPLIER_ADDRESS]       NVARCHAR (4000) NULL,
    [SUPPLIER_NPWP]          NVARCHAR (50)   NULL,
    [TAX_CODE]               NVARCHAR (50)   NULL,
    [TAX_NAME]               NVARCHAR (250)  NULL,
    [TAX_PPN_PCT]            DECIMAL (9, 6)  NULL,
    [TAX_PPH_PCT]            DECIMAL (9, 6)  NULL,
    [WARRANTY_MONTH]         INT             NULL,
    [WARRANTY_PART_MONTH]    INT             NULL,
    [PRICE_AMOUNT]           DECIMAL (18, 2) NULL,
    [DISCOUNT_AMOUNT]        DECIMAL (18, 2) NULL,
    [NETT_PRICE]             DECIMAL (18, 2) NULL,
    [TOTAL_AMOUNT]           DECIMAL (18, 2) NULL,
    [OFFERING]               NVARCHAR (4000) NULL,
    [QUOTATION_DATE]         DATETIME        NULL,
    [QUOTATION_EXPIRED_DATE] DATETIME        NULL,
    [UNIT_AVAILABLE_STATUS]  NVARCHAR (50)   NULL,
    [INDENT_DAYS]            INT             NULL,
    [CRE_DATE]               DATETIME        NULL,
    [CRE_BY]                 NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NULL,
    [MOD_DATE]               DATETIME        NULL,
    [MOD_BY]                 NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NULL,
    [SUPPLIER_NITKU]         NVARCHAR (50)   NULL,
    [SUPPLIER_NPWP_PUSAT]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_QUOTATION_REVIEW_VENDOR] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_QUOTATION_REVIEW_VENDOR_20241128]
    ON [dbo].[QUOTATION_REVIEW_VENDOR]([QUOTATION_REVIEW_CODE] ASC);

