CREATE TABLE [dbo].[QUOTATION_MYFORM444177$] (
    [ID]                    FLOAT (53)     NULL,
    [QUOTATION_REVIEW_CODE] NVARCHAR (255) NULL,
    [QUOTATION_REVIEW_DATE] DATETIME       NULL,
    [REFF_NO]               NVARCHAR (255) NULL,
    [BRANCH_CODE]           FLOAT (53)     NULL,
    [BRANCH_NAME]           NVARCHAR (255) NULL,
    [CURRENCY_CODE]         NVARCHAR (255) NULL,
    [CURRENCY_NAME]         NVARCHAR (255) NULL,
    [PAYMENT_METHODE_CODE]  NVARCHAR (255) NULL,
    [ITEM_CODE]             NVARCHAR (255) NULL,
    [ITEM_NAME]             NVARCHAR (255) NULL,
    [TYPE_ASSET_CODE]       NVARCHAR (255) NULL,
    [ITEM_CATEGORY_CODE]    NVARCHAR (255) NULL,
    [ITEM_CATEGORY_NAME]    NVARCHAR (255) NULL,
    [ITEM_MERK_CODE]        NVARCHAR (255) NULL,
    [ITEM_MERK_NAME]        NVARCHAR (255) NULL,
    [ITEM_MODEL_CODE]       NVARCHAR (255) NULL,
    [ITEM_MODEL_NAME]       NVARCHAR (255) NULL,
    [ITEM_TYPE_CODE]        NVARCHAR (255) NULL,
    [ITEM_TYPE_NAME]        NVARCHAR (255) NULL,
    [SUPPLIER_CODE]         FLOAT (53)     NULL,
    [SUPPLIER_NAME]         NVARCHAR (255) NULL,
    [SUPPLIER_ADDRESS]      NVARCHAR (255) NULL,
    [TAX_CODE]              NVARCHAR (255) NULL,
    [TAX_NAME]              NVARCHAR (255) NULL,
    [PPN_PCT]               FLOAT (53)     NULL,
    [PPH_PCT]               FLOAT (53)     NULL,
    [WARRANTY_MONTH]        FLOAT (53)     NULL,
    [WARRANTY_PART_MONTH]   FLOAT (53)     NULL,
    [QUANTITY]              FLOAT (53)     NULL,
    [APPROVED_QUANTITY]     FLOAT (53)     NULL,
    [UOM_CODE]              NVARCHAR (255) NULL,
    [UOM_NAME]              NVARCHAR (255) NULL,
    [PRICE_AMOUNT]          FLOAT (53)     NULL,
    [DISCOUNT_AMOUNT]       FLOAT (53)     NULL,
    [REQUESTOR_CODE]        NVARCHAR (255) NULL,
    [REQUESTOR_NAME]        NVARCHAR (255) NULL,
    [UNIT_AVAILABLE_STATUS] NVARCHAR (255) NULL,
    [INDENT_DAYS]           FLOAT (53)     NULL,
    [OFFERING]              NVARCHAR (255) NULL,
    [UNIT_FROM]             NVARCHAR (255) NULL,
    [SPESIFICATION]         NVARCHAR (255) NULL,
    [REMARK]                NVARCHAR (255) NULL,
    [CRE_DATE]              DATETIME       NULL,
    [CRE_BY]                NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (255) NULL,
    [MOD_DATE]              DATETIME       NULL,
    [MOD_BY]                NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (255) NULL,
    [EXPIRED_DATE]          DATETIME       NULL,
    [TOTAL_AMOUNT]          FLOAT (53)     NULL,
    [NETT_PRICE]            FLOAT (53)     NULL,
    [SUPPLIER_NPWP]         FLOAT (53)     NULL
);

