CREATE TABLE [dbo].[RPT_PAYMENT_REQUEST_DETAIL] (
    [USER_ID]       NVARCHAR (50)   NOT NULL,
    [NAMA_UNIT]     NVARCHAR (250)  NULL,
    [NO_RANGKA]     NVARCHAR (50)   NULL,
    [NO_MESIN]      NVARCHAR (50)   NULL,
    [NOPOL]         NVARCHAR (50)   NULL,
    [HARGA_EXC_VAT] DECIMAL (18, 2) NULL,
    [VAT]           DECIMAL (18, 2) NULL,
    [HARGA_INC_VAT] DECIMAL (18, 2) NULL,
    [CUSTOMER_NAME] NVARCHAR (250)  NULL,
    [NO_KONTRAK]    NVARCHAR (50)   NULL
);

