CREATE TABLE [dbo].[RPT_SURAT_KUASA_PO] (
    [USER_ID]             NVARCHAR (50)   NOT NULL,
    [PO_NO]               NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]      NVARCHAR (250)  NULL,
    [REPORT_TITLE]        NVARCHAR (250)  NULL,
    [REPORT_IMAGE]        NVARCHAR (250)  NULL,
    [NAMA]                NVARCHAR (250)  NULL,
    [JABATAN]             NVARCHAR (250)  NULL,
    [ALAMAT]              NVARCHAR (4000) NULL,
    [NAMA_KUASA]          NVARCHAR (250)  NULL,
    [ALAMAT_KUASA]        NVARCHAR (4000) NULL,
    [MERK]                NVARCHAR (250)  NULL,
    [TYPE]                NVARCHAR (250)  NULL,
    [NO_RANGKA]           NVARCHAR (250)  NULL,
    [NO_MESIN]            NVARCHAR (250)  NULL,
    [TAHUN]               NVARCHAR (4)    NULL,
    [WARNA]               NVARCHAR (50)   NULL,
    [ATAS_NAMA]           NVARCHAR (250)  NULL,
    [ALAMAT_STNK_OR_BPKB] NVARCHAR (4000) NULL,
    [KOTA]                NVARCHAR (250)  NULL,
    [TANGGAL]             DATETIME        NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (50)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (50)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [REPORT_AREA_PHONE]   NVARCHAR (4)    NULL,
    [REPORT_PHONE_NO]     NVARCHAR (15)   NULL,
    [REPORT_FAX_AREA]     NVARCHAR (4)    NULL,
    [REPORT_FAX]          NVARCHAR (15)   NULL,
    [REPORT_ADDRESS]      NVARCHAR (4000) NULL
);

