CREATE TABLE [dbo].[RPT_HISTORY_INVOICE_REGISTER] (
    [USER_ID]              NVARCHAR (50)   NULL,
    [FILTER_FROM_DATE]     DATETIME        NOT NULL,
    [FILTER_TO_DATE]       DATETIME        NOT NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NULL,
    [REPORT_IMAGE]         NVARCHAR (250)  NULL,
    [CODE_INVOICE]         NVARCHAR (50)   NULL,
    [SUPPLIER_NAME]        NVARCHAR (250)  NULL,
    [INVOICE_RECEIVE_DATE] DATETIME        NULL,
    [DUE_DATE]             DATETIME        NULL,
    [TAX_INVOICE_DATE]     DATETIME        NULL,
    [INVOICE_NO]           NVARCHAR (50)   NULL,
    [DISCOUNT_AMOUNT]      DECIMAL (18, 2) NULL,
    [PPN_AMOUNT]           DECIMAL (18, 2) NULL,
    [PPH_AMOUNT]           DECIMAL (18, 2) NULL,
    [TOTAL_AMOUNT]         DECIMAL (18, 2) NULL,
    [REMARKS]              NVARCHAR (4000) NULL,
    [TO_BANK_NAME]         NVARCHAR (250)  NULL,
    [TO_BANK_ACCOUNT_NO]   NVARCHAR (50)   NULL,
    [TO_BANK_ACCOUNT_NAME] NVARCHAR (250)  NULL,
    [TOTAL_GRN]            INT             NULL,
    [STATUS]               NVARCHAR (50)   NULL,
    [CRE_DATE]             DATETIME        NULL,
    [CRE_BY]               NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (50)   NULL,
    [MOD_DATE]             DATETIME        NULL,
    [MOD_BY]               NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (50)   NULL
);

