CREATE TABLE [dbo].[SYS_COMPANY_USER_MAIN] (
    [CODE]             NVARCHAR (50)  NOT NULL,
    [COMPANY_CODE]     NVARCHAR (50)  NOT NULL,
    [UPASS]            NVARCHAR (20)  NOT NULL,
    [UPASSAPPROVAL]    NVARCHAR (20)  NOT NULL,
    [NAME]             NVARCHAR (100) NOT NULL,
    [USERNAME]         NVARCHAR (50)  NOT NULL,
    [MAIN_TASK_CODE]   NVARCHAR (50)  NOT NULL,
    [EMAIL]            NVARCHAR (50)  NOT NULL,
    [PHONE_NO]         NVARCHAR (25)  NOT NULL,
    [PROVINCE_CODE]    NVARCHAR (50)  NOT NULL,
    [PROVINCE_NAME]    NVARCHAR (250) CONSTRAINT [DF_SYS_COMPANY_USER_MAIN_PROVINCE_NAME] DEFAULT ('') NOT NULL,
    [CITY_CODE]        NVARCHAR (50)  NOT NULL,
    [CITY_NAME]        NVARCHAR (250) CONSTRAINT [DF_SYS_COMPANY_USER_MAIN_CITY_NAME] DEFAULT ('') NOT NULL,
    [LAST_LOGIN_DATE]  DATETIME       NULL,
    [LAST_FAIL_COUNT]  INT            NULL,
    [NEXT_CHANGE_PASS] DATETIME       NULL,
    [FILE_NAME]        NVARCHAR (250) NULL,
    [PATHS]            NVARCHAR (250) NULL,
    [MODULE]           NVARCHAR (20)  CONSTRAINT [DF_SYS_COMPANY_USER_MAIN_MODULE] DEFAULT ('') NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)   NOT NULL,
    [IS_DEFAULT]       NVARCHAR (1)   CONSTRAINT [DF_SYS_COMPANY_USER_MAIN_IS_DEFAULT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_SYS_COMPANY_USER_MAIN] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[SYS_COMPANY_USER_MAIN_Insert_Audit] 
			ON [dbo].[SYS_COMPANY_USER_MAIN]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN]
([CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_COMPANY_USER_MAIN_Delete_Audit]    
			ON [dbo].[SYS_COMPANY_USER_MAIN]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN]
([CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_COMPANY_USER_MAIN_Update_Audit]      
			ON [dbo].[SYS_COMPANY_USER_MAIN]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([UPASS]) THEN '[UPASS]-' ELSE '' END + 
CASE WHEN UPDATE([UPASSAPPROVAL]) THEN '[UPASSAPPROVAL]-' ELSE '' END + 
CASE WHEN UPDATE([NAME]) THEN '[NAME]-' ELSE '' END + 
CASE WHEN UPDATE([USERNAME]) THEN '[USERNAME]-' ELSE '' END + 
CASE WHEN UPDATE([MAIN_TASK_CODE]) THEN '[MAIN_TASK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([EMAIL]) THEN '[EMAIL]-' ELSE '' END + 
CASE WHEN UPDATE([PHONE_NO]) THEN '[PHONE_NO]-' ELSE '' END + 
CASE WHEN UPDATE([PROVINCE_CODE]) THEN '[PROVINCE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PROVINCE_NAME]) THEN '[PROVINCE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([CITY_CODE]) THEN '[CITY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CITY_NAME]) THEN '[CITY_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([LAST_LOGIN_DATE]) THEN '[LAST_LOGIN_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([LAST_FAIL_COUNT]) THEN '[LAST_FAIL_COUNT]-' ELSE '' END + 
CASE WHEN UPDATE([NEXT_CHANGE_PASS]) THEN '[NEXT_CHANGE_PASS]-' ELSE '' END + 
CASE WHEN UPDATE([FILE_NAME]) THEN '[FILE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([PATHS]) THEN '[PATHS]-' ELSE '' END + 
CASE WHEN UPDATE([MODULE]) THEN '[MODULE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_DEFAULT]) THEN '[IS_DEFAULT]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN]
([CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN]
([CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[UPASS],[UPASSAPPROVAL],[NAME],[USERNAME],[MAIN_TASK_CODE],[EMAIL],[PHONE_NO],[PROVINCE_CODE],[PROVINCE_NAME],[CITY_CODE],[CITY_NAME],[LAST_LOGIN_DATE],[LAST_FAIL_COUNT],[NEXT_CHANGE_PASS],[FILE_NAME],[PATHS],[MODULE],[IS_ACTIVE],[IS_DEFAULT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END