CREATE TABLE [dbo].[SYS_ROLE_GROUP_DETAIL] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [ROLE_GROUP_CODE] NVARCHAR (50)  NOT NULL,
    [ROLE_CODE]       NVARCHAR (50)  NOT NULL,
    [ROLE_NAME]       NVARCHAR (250) CONSTRAINT [DF_SYS_ROLE_GROUP_DETAIL_ROLE_NAME_1] DEFAULT ('') NOT NULL,
    [MENU_CODE]       NVARCHAR (50)  CONSTRAINT [DF_SYS_ROLE_GROUP_DETAIL_MENU_CODE_1] DEFAULT ('') NOT NULL,
    [MENU_NAME]       NVARCHAR (250) CONSTRAINT [DF_SYS_ROLE_GROUP_DETAIL_MENU_NAME_1] DEFAULT ('') NOT NULL,
    [SUBMENU_CODE]    NVARCHAR (50)  CONSTRAINT [DF_SYS_ROLE_GROUP_DETAIL_SUBMENU_CODE_1] DEFAULT ('') NOT NULL,
    [SUBMENU_NAME]    NVARCHAR (250) CONSTRAINT [DF_SYS_ROLE_GROUP_DETAIL_SUBMENU_NAME_1] DEFAULT ('') NOT NULL,
    [CRE_DATE]        DATETIME       NOT NULL,
    [CRE_BY]          NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)  NOT NULL,
    [MOD_DATE]        DATETIME       NOT NULL,
    [MOD_BY]          NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_SYS_ROLE_GROUP_DETAIL_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[SYS_ROLE_GROUP_DETAIL_Insert_Audit] 
			ON [dbo].[SYS_ROLE_GROUP_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_ROLE_GROUP_DETAIL]
([ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_ROLE_GROUP_DETAIL_Delete_Audit]    
			ON [dbo].[SYS_ROLE_GROUP_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_ROLE_GROUP_DETAIL]
([ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_ROLE_GROUP_DETAIL_Update_Audit]      
			ON [dbo].[SYS_ROLE_GROUP_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([ROLE_GROUP_CODE]) THEN '[ROLE_GROUP_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ROLE_CODE]) THEN '[ROLE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ROLE_NAME]) THEN '[ROLE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([MENU_CODE]) THEN '[MENU_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([MENU_NAME]) THEN '[MENU_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([SUBMENU_CODE]) THEN '[SUBMENU_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([SUBMENU_NAME]) THEN '[SUBMENU_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_ROLE_GROUP_DETAIL]
([ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_ROLE_GROUP_DETAIL]
([ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[ROLE_GROUP_CODE],[ROLE_CODE],[ROLE_NAME],[MENU_CODE],[MENU_NAME],[SUBMENU_CODE],[SUBMENU_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Auto Generate', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_ROLE_GROUP_DETAIL', @level2type = N'COLUMN', @level2name = N'ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode grup role', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_ROLE_GROUP_DETAIL', @level2type = N'COLUMN', @level2name = N'ROLE_GROUP_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode role', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_ROLE_GROUP_DETAIL', @level2type = N'COLUMN', @level2name = N'ROLE_CODE';

