CREATE TABLE [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION] (
    [EMP_CODE]       NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [NOTIF_CODE]     NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_EMPLOYEE_NOTIFICATION_SUBSCRIPTION] PRIMARY KEY CLUSTERED ([EMP_CODE] ASC, [NOTIF_CODE] ASC),
    CONSTRAINT [FK_SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION_SYS_NOTIFICATION] FOREIGN KEY ([NOTIF_CODE]) REFERENCES [dbo].[SYS_NOTIFICATION] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION_Update_Audit]      
			ON [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([EMP_CODE]) THEN '[EMP_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([NOTIF_CODE]) THEN '[NOTIF_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]
([EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]
([EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION_Insert_Audit] 
			ON [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]
([EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION_Delete_Audit]    
			ON [dbo].[SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION]
([EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [EMP_CODE],[NOTIF_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode employee', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION', @level2type = N'COLUMN', @level2name = N'EMP_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode notification ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_EMPLOYEE_NOTIFICATION_SUBSCRIPTION', @level2type = N'COLUMN', @level2name = N'NOTIF_CODE';

