CREATE TABLE [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC] (
    [ROLE_GROUP_CODE] NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [USER_CODE]       NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_DATE]        DATETIME      NOT NULL,
    [CRE_BY]          NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]        DATETIME      NOT NULL,
    [MOD_BY]          NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_SYS_COMPANY_USER_MAIN_GROUP_SEC_1] PRIMARY KEY CLUSTERED ([USER_CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC_Insert_Audit] 
			ON [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN_GROUP_SEC]
([ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC_Delete_Audit]    
			ON [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN_GROUP_SEC]
([ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC_Update_Audit]      
			ON [dbo].[SYS_COMPANY_USER_MAIN_GROUP_SEC]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ROLE_GROUP_CODE]) THEN '[ROLE_GROUP_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([USER_CODE]) THEN '[USER_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN_GROUP_SEC]
([ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN_GROUP_SEC]
([ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [ROLE_GROUP_CODE],[USER_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode grup role yang didaftarkan atas user tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_COMPANY_USER_MAIN_GROUP_SEC', @level2type = N'COLUMN', @level2name = N'ROLE_GROUP_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode user', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYS_COMPANY_USER_MAIN_GROUP_SEC', @level2type = N'COLUMN', @level2name = N'USER_CODE';

