CREATE TABLE [dbo].[TEMP_ASSET_FOR_UPDATE] (
    [ASSET_CODE]     NVARCHAR (50)   NULL,
    [PRICE_AMOUNT]   DECIMAL (18, 2) NULL,
    [ORIGINAL_PRICE] DECIMAL (18, 2) NULL,
    [PPN]            DECIMAL (18, 2) NULL,
    [DISCOUNT]       DECIMAL (18, 2) NULL,
    [PURCHASE_DATE]  DATETIME        NULL,
    [STATUS]         NVARCHAR (50)   NULL
);

