CREATE TABLE [dbo].[TERM_OF_PAYMENT] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [PO_CODE]          NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TRANSACTION_CODE] NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TRANSACTION_NAME] NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TRANSACTION_DATE] DATETIME        NULL,
    [TERMIN_TYPE_CODE] NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TERMIN_TYPE_NAME] NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [REFFERENCE_CODE]  NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PERCENTAGE]       DECIMAL (18, 6) NOT NULL,
    [AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [IS_PAID]          NVARCHAR (1)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PPH_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [PPN_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [REMARK]           NVARCHAR (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_TERM_OF_PAYMENT_CRE_BY] DEFAULT ('') NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_TERM_OF_PAYMENT_CRE_IP_ADDRESS] DEFAULT ('') NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_TERM_OF_PAYMENT_MOD_BY] DEFAULT ('') NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_TERM_OF_PAYMENT_MOD_IP_ADDRESS] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TERM_OF_PAYMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

