CREATE TABLE [dbo].[TRANSACTION_LOCK] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [USER_ID]        NVARCHAR (50)  NOT NULL,
    [USER_NAME]      NVARCHAR (250) NULL,
    [REFF_NAME]      NVARCHAR (250) NULL,
    [REFF_CODE]      NVARCHAR (50)  NOT NULL,
    [ACCESS_DATE]    DATETIME       NOT NULL,
    [IS_ACTIVE]      NVARCHAR (1)   NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_TRANSACTION_LOCK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

