CREATE TABLE [dbo].[XXX_SUPPLIER_SELECTION_DETAIL_20241204] (
    [ID]                               BIGINT          IDENTITY (1, 1) NOT NULL,
    [SELECTION_CODE]                   NVARCHAR (50)   NOT NULL,
    [SUPPLIER_SELECTION_DETAIL_STATUS] NVARCHAR (50)   NULL,
    [ITEM_CODE]                        NVARCHAR (50)   NOT NULL,
    [ITEM_NAME]                        NVARCHAR (250)  NOT NULL,
    [UOM_CODE]                         NVARCHAR (50)   NULL,
    [UOM_NAME]                         NVARCHAR (250)  NULL,
    [TYPE_ASSET_CODE]                  NVARCHAR (25)   NULL,
    [ITEM_CATEGORY_CODE]               NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_NAME]               NVARCHAR (250)  NULL,
    [ITEM_MERK_CODE]                   NVARCHAR (50)   NULL,
    [ITEM_MERK_NAME]                   NVARCHAR (250)  NULL,
    [ITEM_MODEL_CODE]                  NVARCHAR (50)   NULL,
    [ITEM_MODEL_NAME]                  NVARCHAR (250)  NULL,
    [ITEM_TYPE_CODE]                   NVARCHAR (50)   NULL,
    [ITEM_TYPE_NAME]                   NVARCHAR (250)  NULL,
    [SUPPLIER_CODE]                    NVARCHAR (50)   NOT NULL,
    [SUPPLIER_NAME]                    NVARCHAR (250)  NULL,
    [SUPPLIER_ADDRESS]                 NVARCHAR (4000) NULL,
    [TAX_CODE]                         NVARCHAR (50)   NULL,
    [TAX_NAME]                         NVARCHAR (250)  NULL,
    [PPN_PCT]                          DECIMAL (9, 6)  NULL,
    [PPH_PCT]                          DECIMAL (9, 6)  NULL,
    [PPH_AMOUNT]                       DECIMAL (18, 2) NULL,
    [PPN_AMOUNT]                       DECIMAL (18, 2) NULL,
    [AMOUNT]                           DECIMAL (18, 2) NOT NULL,
    [QUOTATION_AMOUNT]                 DECIMAL (18, 2) NOT NULL,
    [QUANTITY]                         INT             NOT NULL,
    [QUOTATION_QUANTITY]               INT             NOT NULL,
    [TOTAL_AMOUNT]                     DECIMAL (18, 2) NOT NULL,
    [DISCOUNT_AMOUNT]                  DECIMAL (18, 2) NULL,
    [REFF_NO]                          NVARCHAR (50)   NULL,
    [SPESIFICATION]                    NVARCHAR (4000) NULL,
    [REMARK]                           NVARCHAR (4000) NULL,
    [REQUESTOR_CODE]                   NVARCHAR (50)   NULL,
    [REQUESTOR_NAME]                   NVARCHAR (250)  NULL,
    [QUOTATION_DETAIL_ID]              INT             NULL,
    [PURCHASE_ORDER_NO]                NVARCHAR (50)   NULL,
    [UNIT_FROM]                        NVARCHAR (25)   NULL,
    [UNIT_AVAILABLE_STATUS]            NVARCHAR (25)   NULL,
    [INDENT_DAYS]                      INT             NULL,
    [OFFERING]                         NVARCHAR (4000) NULL,
    [CRE_DATE]                         DATETIME        NOT NULL,
    [CRE_BY]                           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                         DATETIME        NOT NULL,
    [MOD_BY]                           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                   NVARCHAR (15)   NOT NULL,
    [SUPPLIER_NPWP]                    NVARCHAR (20)   NULL,
    [ASSET_AMOUNT]                     DECIMAL (18, 2) NULL,
    [ASSET_DISCOUNT_AMOUNT]            DECIMAL (18, 2) NULL,
    [KAROSERI_AMOUNT]                  DECIMAL (18, 2) NULL,
    [KAROSERI_DISCOUNT_AMOUNT]         DECIMAL (18, 2) NULL,
    [ACCESORIES_AMOUNT]                DECIMAL (18, 2) NULL,
    [ACCESORIES_DISCOUNT_AMOUNT]       DECIMAL (18, 2) NULL,
    [MOBILIZATION_AMOUNT]              DECIMAL (18, 2) NULL,
    [APPLICATION_NO]                   NVARCHAR (50)   NULL,
    [OTR_AMOUNT]                       DECIMAL (18, 2) NULL,
    [GPS_AMOUNT]                       DECIMAL (18, 2) NULL,
    [BUDGET_AMOUNT]                    DECIMAL (18, 2) NULL
);

