CREATE TABLE [dbo].[XXX_AP_INVOICE_REGISTRATION_DETAIL_20240531] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [INVOICE_REGISTER_CODE] NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [GRN_CODE]              NVARCHAR (50)   NOT NULL,
    [CURRENCY_CODE]         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [UOM_CODE]              NVARCHAR (50)   NULL,
    [UOM_NAME]              NVARCHAR (250)  NULL,
    [QUANTITY]              INT             NULL,
    [ITEM_CODE]             NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_NAME]             NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PURCHASE_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [TOTAL_AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [TAX_CODE]              NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TAX_NAME]              NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PPN]                   DECIMAL (18, 2) NOT NULL,
    [PPH]                   DECIMAL (18, 2) NOT NULL,
    [SHIPPING_FEE]          DECIMAL (18, 2) NOT NULL,
    [DISCOUNT]              DECIMAL (18, 2) NOT NULL,
    [BRANCH_CODE]           NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [BRANCH_NAME]           NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DIVISION_CODE]         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DIVISION_NAME]         NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DEPARTMENT_CODE]       NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DEPARTMENT_NAME]       NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PURCHASE_ORDER_ID]     BIGINT          NOT NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL
);

