CREATE TABLE [dbo].[XXX_PROCUREMENT_REQUEST_ITEM_28032025] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [PROCUREMENT_REQUEST_CODE]   NVARCHAR (50)   NOT NULL,
    [ITEM_CODE]                  NVARCHAR (50)   NOT NULL,
    [ITEM_NAME]                  NVARCHAR (250)  NOT NULL,
    [QUANTITY_REQUEST]           INT             NOT NULL,
    [APPROVED_QUANTITY]          INT             NOT NULL,
    [TYPE_ASSET_CODE]            NVARCHAR (25)   NULL,
    [UOM_CODE]                   NVARCHAR (50)   NULL,
    [UOM_NAME]                   NVARCHAR (250)  NULL,
    [SPECIFICATION]              NVARCHAR (4000) NOT NULL,
    [ITEM_CATEGORY_CODE]         NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_NAME]         NVARCHAR (250)  NULL,
    [ITEM_MERK_CODE]             NVARCHAR (50)   NULL,
    [ITEM_MERK_NAME]             NVARCHAR (250)  NULL,
    [ITEM_MODEL_CODE]            NVARCHAR (50)   NULL,
    [ITEM_MODEL_NAME]            NVARCHAR (250)  NULL,
    [ITEM_TYPE_CODE]             NVARCHAR (50)   NULL,
    [ITEM_TYPE_NAME]             NVARCHAR (250)  NULL,
    [FA_CODE]                    NVARCHAR (50)   NULL,
    [FA_NAME]                    NVARCHAR (250)  NULL,
    [CATEGORY_TYPE]              NVARCHAR (15)   NULL,
    [SPAF_AMOUNT]                DECIMAL (18, 2) NULL,
    [SUBVENTION_AMOUNT]          DECIMAL (18, 2) NULL,
    [REMARK]                     NVARCHAR (4000) NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [IS_BBN]                     NVARCHAR (1)    NULL,
    [BBN_NAME]                   NVARCHAR (250)  NULL,
    [BBN_ADDRESS]                NVARCHAR (4000) NULL,
    [IS_RECOM]                   NVARCHAR (1)    NULL,
    [ASSET_AMOUNT]               DECIMAL (18, 2) NULL,
    [ASSET_DISCOUNT_AMOUNT]      DECIMAL (18, 2) NULL,
    [KAROSERI_AMOUNT]            DECIMAL (18, 2) NULL,
    [KAROSERI_DISCOUNT_AMOUNT]   DECIMAL (18, 2) NULL,
    [ACCESORIES_AMOUNT]          DECIMAL (18, 2) NULL,
    [ACCESORIES_DISCOUNT_AMOUNT] DECIMAL (18, 2) NULL,
    [MOBILIZATION_AMOUNT]        DECIMAL (18, 2) NULL,
    [OTR_AMOUNT]                 DECIMAL (18, 2) NULL,
    [GPS_AMOUNT]                 DECIMAL (18, 2) NULL,
    [BUDGET_AMOUNT]              DECIMAL (18, 2) NULL
);

