CREATE TABLE [dbo].[XXX_GOOD_RECEIPT_NOTE_DETAIL_20250492] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [GOOD_RECEIPT_NOTE_CODE]     NVARCHAR (50)   NOT NULL,
    [ITEM_CODE]                  NVARCHAR (50)   NOT NULL,
    [ITEM_NAME]                  NVARCHAR (250)  NOT NULL,
    [TYPE_ASSET_CODE]            NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_CODE]         NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_NAME]         NVARCHAR (250)  NULL,
    [ITEM_MERK_CODE]             NVARCHAR (50)   NULL,
    [ITEM_MERK_NAME]             NVARCHAR (250)  NULL,
    [ITEM_MODEL_CODE]            NVARCHAR (50)   NULL,
    [ITEM_MODEL_NAME]            NVARCHAR (250)  NULL,
    [ITEM_TYPE_CODE]             NVARCHAR (50)   NULL,
    [ITEM_TYPE_NAME]             NVARCHAR (250)  NULL,
    [UOM_CODE]                   NVARCHAR (50)   NOT NULL,
    [UOM_NAME]                   NVARCHAR (250)  NULL,
    [PRICE_AMOUNT]               DECIMAL (18, 2) NOT NULL,
    [PO_QUANTITY]                DECIMAL (18, 2) NOT NULL,
    [RECEIVE_QUANTITY]           DECIMAL (18, 2) NOT NULL,
    [SHIPPER_CODE]               NVARCHAR (50)   NOT NULL,
    [NO_RESI]                    NVARCHAR (50)   NULL,
    [PURCHASE_ORDER_DETAIL_ID]   INT             NULL,
    [SPESIFICATION]              NVARCHAR (4000) NULL,
    [DISCOUNT_AMOUNT]            DECIMAL (18, 2) NULL,
    [NETT_PRICE]                 DECIMAL (18, 2) NULL,
    [PPN_AMOUNT]                 DECIMAL (18, 2) NULL,
    [PPH_AMOUNT]                 DECIMAL (18, 2) NULL,
    [GRN_JOURNAL_CODE]           NVARCHAR (50)   NULL,
    [GRN_JOURNAL_DATE]           DATETIME        NULL,
    [FINAL_JOURNAL_CODE]         NVARCHAR (50)   NULL,
    [FINAL_JOURNAL_DATE]         DATETIME        NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MASTER_TAX_CODE]            NVARCHAR (50)   NULL,
    [MASTER_TAX_DESCRIPTION]     NVARCHAR (250)  NULL,
    [MASTER_TAX_PPN_PCT]         DECIMAL (18, 2) NULL,
    [MASTER_TAX_PPH_PCT]         DECIMAL (18, 2) NULL,
    [REVERSE_JOURNAL_CODE]       NVARCHAR (50)   NULL,
    [REVERSE_JOURNAL_DATE]       DATETIME        NULL,
    [NEW_GRN_JOURNAL_CODE]       NVARCHAR (50)   NULL,
    [NEW_GRN_JOURNAL_DATE]       DATETIME        NULL,
    [REVERSE_FINAL_JOURNAL_CODE] NVARCHAR (50)   NULL,
    [REVERSE_FINAL_JOURNAL_DATE] DATETIME        NULL,
    [NEW_FINAL_JOURNAL_CODE]     NVARCHAR (50)   NULL,
    [NEW_FINAL_JOURNAL_DATE]     DATETIME        NULL,
    [TOTAL_AMOUNT]               DECIMAL (18, 2) NULL,
    [ORIG_PRICE_AMOUNT]          DECIMAL (18, 2) NULL,
    [ORIG_DISCOUNT_AMOUNT]       DECIMAL (18, 2) NULL,
    [ORIG_PPN_AMOUNT]            DECIMAL (18, 2) NULL,
    [ORIG_PPH_AMOUNT]            DECIMAL (18, 2) NULL,
    [ORIG_TOTAL_AMOUNT]          DECIMAL (18, 2) NULL
);

