CREATE TABLE [dbo].[XXX_QUOTATION_REVIEW_DETAIL_20250106] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [QUOTATION_REVIEW_CODE]      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [QUOTATION_REVIEW_DATE]      DATETIME        NULL,
    [REFF_NO]                    NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [BRANCH_CODE]                NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                NVARCHAR (250)  NOT NULL,
    [CURRENCY_CODE]              NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CURRENCY_NAME]              NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PAYMENT_METHODE_CODE]       NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_CODE]                  NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_NAME]                  NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TYPE_ASSET_CODE]            NVARCHAR (25)   NULL,
    [ITEM_CATEGORY_CODE]         NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_NAME]         NVARCHAR (250)  NULL,
    [ITEM_MERK_CODE]             NVARCHAR (50)   NULL,
    [ITEM_MERK_NAME]             NVARCHAR (250)  NULL,
    [ITEM_MODEL_CODE]            NVARCHAR (50)   NULL,
    [ITEM_MODEL_NAME]            NVARCHAR (250)  NULL,
    [ITEM_TYPE_CODE]             NVARCHAR (50)   NULL,
    [ITEM_TYPE_NAME]             NVARCHAR (250)  NULL,
    [SUPPLIER_CODE]              NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SUPPLIER_NAME]              NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SUPPLIER_ADDRESS]           NVARCHAR (4000) NULL,
    [TAX_CODE]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TAX_NAME]                   NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PPN_PCT]                    DECIMAL (9, 6)  NOT NULL,
    [PPH_PCT]                    DECIMAL (9, 6)  NOT NULL,
    [WARRANTY_MONTH]             INT             NOT NULL,
    [WARRANTY_PART_MONTH]        INT             NULL,
    [QUANTITY]                   INT             NULL,
    [APPROVED_QUANTITY]          INT             NULL,
    [UOM_CODE]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UOM_NAME]                   NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PRICE_AMOUNT]               DECIMAL (18, 2) NULL,
    [DISCOUNT_AMOUNT]            DECIMAL (18, 2) NULL,
    [REQUESTOR_CODE]             NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [REQUESTOR_NAME]             NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UNIT_AVAILABLE_STATUS]      NVARCHAR (10)   NULL,
    [INDENT_DAYS]                INT             NULL,
    [OFFERING]                   NVARCHAR (4000) NULL,
    [UNIT_FROM]                  NVARCHAR (25)   NULL,
    [SPESIFICATION]              NVARCHAR (4000) NULL,
    [REMARK]                     NVARCHAR (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [EXPIRED_DATE]               DATETIME        NULL,
    [TOTAL_AMOUNT]               DECIMAL (18, 2) NULL,
    [NETT_PRICE]                 DECIMAL (18, 2) NULL,
    [SUPPLIER_NPWP]              NVARCHAR (20)   NULL,
    [TYPE]                       NVARCHAR (50)   NULL,
    [ASSET_AMOUNT]               DECIMAL (18, 2) NULL,
    [ASSET_DISCOUNT_AMOUNT]      DECIMAL (18, 2) NULL,
    [KAROSERI_AMOUNT]            DECIMAL (18, 2) NULL,
    [KAROSERI_DISCOUNT_AMOUNT]   DECIMAL (18, 2) NULL,
    [ACCESORIES_AMOUNT]          DECIMAL (18, 2) NULL,
    [ACCESORIES_DISCOUNT_AMOUNT] DECIMAL (18, 2) NULL,
    [MOBILIZATION_AMOUNT]        DECIMAL (18, 2) NULL,
    [APPLICATION_NO]             NVARCHAR (50)   NULL,
    [OTR_AMOUNT]                 DECIMAL (18, 2) NULL,
    [GPS_AMOUNT]                 DECIMAL (18, 2) NULL,
    [BUDGET_AMOUNT]              DECIMAL (18, 2) NULL
);

