CREATE TABLE [dbo].[XXX_PROCUREMENT_28032025] (
    [CODE]                        NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]                NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PROCUREMENT_REQUEST_ITEM_ID] BIGINT          NOT NULL,
    [PROCUREMENT_REQUEST_CODE]    NVARCHAR (50)   NOT NULL,
    [PROCUREMENT_REQUEST_DATE]    DATETIME        NOT NULL,
    [BRANCH_CODE]                 NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BRANCH_NAME]                 NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ITEM_CODE]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_NAME]                   NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ITEM_GROUP_CODE]             NVARCHAR (50)   NULL,
    [TYPE_CODE]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TYPE_NAME]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TYPE_ASSET_CODE]             NVARCHAR (25)   NULL,
    [ITEM_CATEGORY_CODE]          NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_NAME]          NVARCHAR (250)  NULL,
    [ITEM_MERK_CODE]              NVARCHAR (50)   NULL,
    [ITEM_MERK_NAME]              NVARCHAR (250)  NULL,
    [ITEM_MODEL_CODE]             NVARCHAR (50)   NULL,
    [ITEM_MODEL_NAME]             NVARCHAR (250)  NULL,
    [ITEM_TYPE_CODE]              NVARCHAR (50)   NULL,
    [ITEM_TYPE_NAME]              NVARCHAR (250)  NULL,
    [QUANTITY_REQUEST]            INT             NOT NULL,
    [APPROVED_QUANTITY]           INT             NOT NULL,
    [SPECIFICATION]               NVARCHAR (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [REMARK]                      NVARCHAR (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NEW_PURCHASE]                NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PURCHASE_TYPE_CODE]          NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PURCHASE_TYPE_NAME]          NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [UNIT_FROM]                   NVARCHAR (25)   NULL,
    [QUANTITY_PURCHASE]           INT             NOT NULL,
    [STATUS]                      NVARCHAR (20)   NOT NULL,
    [REQUESTOR_CODE]              NVARCHAR (50)   NULL,
    [REQUESTOR_NAME]              NVARCHAR (250)  NULL,
    [SPAF_AMOUNT]                 DECIMAL (18, 2) NULL,
    [SUBVENTION_AMOUNT]           DECIMAL (18, 2) NULL,
    [CRE_DATE]                    DATETIME        NOT NULL,
    [CRE_BY]                      NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]                    DATETIME        NOT NULL,
    [MOD_BY]                      NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [ASSET_AMOUNT]                DECIMAL (18, 2) NULL,
    [ASSET_DISCOUNT_AMOUNT]       DECIMAL (18, 2) NULL,
    [KAROSERI_AMOUNT]             DECIMAL (18, 2) NULL,
    [KAROSERI_DISCOUNT_AMOUNT]    DECIMAL (18, 2) NULL,
    [ACCESORIES_AMOUNT]           DECIMAL (18, 2) NULL,
    [ACCESORIES_DISCOUNT_AMOUNT]  DECIMAL (18, 2) NULL,
    [MOBILIZATION_AMOUNT]         DECIMAL (18, 2) NULL,
    [APPLICATION_NO]              NVARCHAR (50)   NULL,
    [OTR_AMOUNT]                  DECIMAL (18, 2) NULL,
    [GPS_AMOUNT]                  DECIMAL (18, 2) NULL,
    [BUDGET_AMOUNT]               DECIMAL (18, 2) NULL
);

