CREATE TABLE [dbo].[xxx_SUPPLIER_SELECTION_20240724] (
    [CODE]            NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]    NVARCHAR (50)   NOT NULL,
    [QUOTATION_CODE]  NVARCHAR (50)   NOT NULL,
    [SELECTION_DATE]  DATETIME        NOT NULL,
    [BRANCH_CODE]     NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]     NVARCHAR (250)  NOT NULL,
    [DIVISION_CODE]   NVARCHAR (50)   NULL,
    [DIVISION_NAME]   NVARCHAR (250)  NULL,
    [DEPARTMENT_CODE] NVARCHAR (50)   NULL,
    [DEPARTMENT_NAME] NVARCHAR (250)  NULL,
    [REQUESTOR_CODE]  NVARCHAR (50)   NULL,
    [REQUESTOR_NAME]  NVARCHAR (250)  NULL,
    [STATUS]          NVARCHAR (50)   NULL,
    [REMARK]          NVARCHAR (4000) NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   COLLATE Latin1_General_CS_AI NOT NULL
);

