CREATE TABLE [dbo].[XXX_FINAL_GOOD_RECEIPT_NOTE_DETAIL_20240703] (
    [ID]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [FINAL_GOOD_RECEIPT_NOTE_CODE] NVARCHAR (50)   NOT NULL,
    [GOOD_RECEIPT_NOTE_DETAIL_ID]  INT             NOT NULL,
    [REFF_NO]                      NVARCHAR (50)   NOT NULL,
    [REFF_NAME]                    NVARCHAR (50)   NOT NULL,
    [ITEM_CODE]                    NVARCHAR (50)   NOT NULL,
    [ITEM_NAME]                    NVARCHAR (250)  NOT NULL,
    [TYPE_ASSET_CODE]              NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_CODE]           NVARCHAR (50)   NULL,
    [ITEM_CATEGORY_NAME]           NVARCHAR (250)  NULL,
    [ITEM_MERK_CODE]               NVARCHAR (50)   NULL,
    [ITEM_MERK_NAME]               NVARCHAR (250)  NULL,
    [ITEM_MODEL_CODE]              NVARCHAR (50)   NULL,
    [ITEM_MODEL_NAME]              NVARCHAR (250)  NULL,
    [ITEM_TYPE_CODE]               NVARCHAR (50)   NULL,
    [ITEM_TYPE_NAME]               NVARCHAR (250)  NULL,
    [UOM_CODE]                     NVARCHAR (50)   NOT NULL,
    [UOM_NAME]                     NVARCHAR (250)  NULL,
    [PRICE_AMOUNT]                 DECIMAL (18, 2) NOT NULL,
    [SPECIFICATION]                NVARCHAR (250)  NOT NULL,
    [PO_QUANTITY]                  INT             NOT NULL,
    [RECEIVE_QUANTITY]             INT             NOT NULL,
    [LOCATION_CODE]                NVARCHAR (50)   NOT NULL,
    [LOCATION_NAME]                NVARCHAR (250)  NULL,
    [WAREHOUSE_CODE]               NVARCHAR (50)   NULL,
    [WAREHOUSE_NAME]               NVARCHAR (250)  NULL,
    [SHIPPER_CODE]                 NVARCHAR (50)   NOT NULL,
    [NO_RESI]                      NVARCHAR (50)   NULL,
    [CRE_DATE]                     DATETIME        NOT NULL,
    [CRE_BY]                       NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                     DATETIME        NOT NULL,
    [MOD_BY]                       NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)   NOT NULL
);

