CREATE TABLE [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER] (
    [ID]                     BIGINT          NULL,
    [COMPANY_CODE]           NVARCHAR (50)   NOT NULL,
    [TRANSACTION_CODE]       NVARCHAR (50)   NOT NULL,
    [PROCESS_CODE]           NVARCHAR (50)   NOT NULL,
    [ORDER_KEY]              INT             NOT NULL,
    [PARAMETER_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [IS_CALCULATE_BY_SYSTEM] NVARCHAR (1)    NOT NULL,
    [IS_TRANSACTION]         NVARCHAR (1)    NOT NULL,
    [IS_AMOUNT_EDITABLE]     NVARCHAR (1)    NOT NULL,
    [IS_DISCOUNT_EDITABLE]   NVARCHAR (1)    NOT NULL,
    [GL_LINK_CODE]           NVARCHAR (50)   NULL,
    [GL_LINK_NAME]           NVARCHAR (250)  NULL,
    [DISCOUNT_GL_LINK_CODE]  NVARCHAR (50)   NULL,
    [DISCOUNT_GL_LINK_NAME]  NVARCHAR (250)  NULL,
    [MAXIMUM_DISC_PCT]       DECIMAL (9, 6)  NOT NULL,
    [MAXIMUM_DISC_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [IS_JOURNAL]             NVARCHAR (1)    NOT NULL,
    [DEBET_OR_CREDIT]        NVARCHAR (10)   NULL,
    [IS_DISCOUNT_JURNAL]     NVARCHAR (1)    NULL,
    [IS_REDUCE_TRANSACTION]  NVARCHAR (1)    NULL,
    [IS_PSAK]                NVARCHAR (1)    NULL,
    [PSAK_GL_LINK_CODE]      NVARCHAR (50)   NULL,
    [PSAK_GL_LINK_NAME]      NVARCHAR (250)  NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [AuditDataState]         VARCHAR (10)    NULL,
    [AuditDMLAction]         VARCHAR (10)    NULL,
    [AuditUser]              [sysname]       NULL,
    [AuditDateTime]          DATETIME        NULL,
    [UpdateColumns]          VARCHAR (MAX)   NULL
);

