CREATE TABLE [dbo].[Z_AUDIT_MASTER_VENDOR] (
    [CODE]                   NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]           NVARCHAR (50)   NOT NULL,
    [NAME]                   NVARCHAR (200)  NOT NULL,
    [ADDRESS]                NVARCHAR (4000) NOT NULL,
    [CITY_CODE]              NVARCHAR (50)   NOT NULL,
    [PROVINCE_CODE]          NVARCHAR (50)   NOT NULL,
    [ZIPCODE]                NVARCHAR (10)   NOT NULL,
    [VENDOR_TYPE]            NVARCHAR (50)   NOT NULL,
    [ID_TYPE]                NVARCHAR (50)   NOT NULL,
    [ID_NO]                  NVARCHAR (100)  NOT NULL,
    [TAX_CALCULATION_METHOD] NVARCHAR (50)   NOT NULL,
    [PKP_NO]                 NVARCHAR (50)   NOT NULL,
    [PHONE]                  NVARCHAR (200)  NOT NULL,
    [FAX]                    NVARCHAR (30)   NULL,
    [SERVICE_TYPE_CODE]      NVARCHAR (50)   NOT NULL,
    [BUSINESS_TYPE_CODE]     NVARCHAR (50)   NOT NULL,
    [OWNER_NAME]             NVARCHAR (100)  NOT NULL,
    [OWNER_PHONE]            NVARCHAR (25)   NOT NULL,
    [CONTACT_NAME]           NVARCHAR (100)  NOT NULL,
    [CONTACT_POSITION]       NVARCHAR (100)  NOT NULL,
    [CONTACT_PHONE]          NVARCHAR (25)   NOT NULL,
    [WEBSITE_ADDRESS]        NVARCHAR (50)   NULL,
    [EMAIL]                  NVARCHAR (50)   NOT NULL,
    [NPWP]                   NVARCHAR (20)   NOT NULL,
    [SIUP_NO]                NVARCHAR (25)   NULL,
    [SKU_NO]                 NVARCHAR (25)   NULL,
    [TDP_NO]                 NVARCHAR (25)   NULL,
    [REMARK]                 NVARCHAR (4000) NULL,
    [ID_VENDOR]              NVARCHAR (150)  NULL,
    [STATUS]                 NVARCHAR (15)   NOT NULL,
    [IS_ACTIVE]              NVARCHAR (1)    NOT NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [AuditDataState]         VARCHAR (10)    NULL,
    [AuditDMLAction]         VARCHAR (10)    NULL,
    [AuditUser]              [sysname]       NULL,
    [AuditDateTime]          DATETIME        NULL,
    [UpdateColumns]          VARCHAR (MAX)   NULL
);

