CREATE TABLE [dbo].[Z_AUDIT_SYS_COMPANY_USER_MAIN] (
    [CODE]             NVARCHAR (50)  NOT NULL,
    [COMPANY_CODE]     NVARCHAR (50)  NOT NULL,
    [UPASS]            NVARCHAR (20)  NOT NULL,
    [UPASSAPPROVAL]    NVARCHAR (20)  NOT NULL,
    [NAME]             NVARCHAR (100) NOT NULL,
    [USERNAME]         NVARCHAR (50)  NOT NULL,
    [MAIN_TASK_CODE]   NVARCHAR (50)  NOT NULL,
    [EMAIL]            NVARCHAR (50)  NOT NULL,
    [PHONE_NO]         NVARCHAR (25)  NOT NULL,
    [PROVINCE_CODE]    NVARCHAR (50)  NOT NULL,
    [PROVINCE_NAME]    NVARCHAR (250) NOT NULL,
    [CITY_CODE]        NVARCHAR (50)  NOT NULL,
    [CITY_NAME]        NVARCHAR (250) NOT NULL,
    [LAST_LOGIN_DATE]  DATETIME       NULL,
    [LAST_FAIL_COUNT]  INT            NULL,
    [NEXT_CHANGE_PASS] DATETIME       NULL,
    [FILE_NAME]        NVARCHAR (250) NULL,
    [PATHS]            NVARCHAR (250) NULL,
    [MODULE]           NVARCHAR (20)  NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)   NOT NULL,
    [IS_DEFAULT]       NVARCHAR (1)   NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [AuditDataState]   VARCHAR (10)   NULL,
    [AuditDMLAction]   VARCHAR (10)   NULL,
    [AuditUser]        [sysname]      NULL,
    [AuditDateTime]    DATETIME       NULL,
    [UpdateColumns]    VARCHAR (MAX)  NULL
);

