CREATE TABLE [dbo].[Z_AUDIT_SYS_MENU] (
    [CODE]             NVARCHAR (50)  NOT NULL,
    [NAME]             NVARCHAR (250) NOT NULL,
    [ABBREVIATION]     NVARCHAR (50)  NOT NULL,
    [MODULE_CODE]      NVARCHAR (50)  NULL,
    [PARENT_MENU_CODE] NVARCHAR (50)  NULL,
    [ROUTING_MENU]     NVARCHAR (250) NULL,
    [URL_MENU]         NVARCHAR (250) NOT NULL,
    [ORDER_KEY]        INT            NOT NULL,
    [CSS_ICON]         NVARCHAR (250) NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)   NOT NULL,
    [TYPE]             NVARCHAR (5)   NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [AuditDataState]   VARCHAR (10)   NULL,
    [AuditDMLAction]   VARCHAR (10)   NULL,
    [AuditUser]        [sysname]      NULL,
    [AuditDateTime]    DATETIME       NULL,
    [UpdateColumns]    VARCHAR (MAX)  NULL
);

