CREATE procedure dbo.xsp_MIG_REPLACEMENT_REQUEST_validation
(	
	@TABLE_NAME					NVARCHAR(50)
	,@ASSET_PREPAID_SCHEDULE_VALIDASI	NVARCHAR(4000)  OUTPUT
)
as
BEGIN    
--- MIG_REPLACEMENT_REQUEST
--1. data pada kolom PREPAID_NO harus sama dengan data pada kolom PREPAID_NO di tabel MIG_ASSET_PREPAID_MAIN

	DECLARE  @ASSET_PREPAID_SCHEDULE_COUNT	INT	
	
	SELECT * FROM MIG_REPLACEMENT_REQUEST	

	SET @ASSET_PREPAID_SCHEDULE_VALIDASI	= 'MIG_ASSET_PREPAID_SCHEDULE: TOTAL = ' + CONVERT(NVARCHAR(10),(SELECT COUNT(1) FROM dbo.MIG_ASSET_PREPAID_SCHEDULE))

	SET @ASSET_PREPAID_SCHEDULE_VALIDASI = @ASSET_PREPAID_SCHEDULE_VALIDASI + ' 1. PREPAID_NO tidak terdaftar pada tabel dbo.MIG_ASSET_PREPAID_MAIN = ' + CONVERT(NVARCHAR(10), (SELECT COUNT(1) FROM dbo.MIG_ASSET_PREPAID_SCHEDULE WHERE ISNULL(PREPAID_NO,'') NOT IN (SELECT ISNULL(PREPAID_NO,'') FROM dbo.MIG_ASSET_PREPAID_MAIN))) + ' , data pada kolom PREPAID_NO harus sama dengan data pada kolom PREPAID_NO di tabel MIG_ASSET_PREPAID_MAIN'

END
