CREATE PROCEDURE dbo.xsp_rpt_perjanjian_pelaksanaan_word
(
	@p_user_id			nvarchar(50) = ''
)
as
begin
			select	USER_ID
					,isnull(APPLICATION_NO, '') 'APPLICATION_NO'
					,isnull(REPORT_COMPANY, '') 'REPORT_COMPANY'
					,isnull(REPORT_COMPANY, '') 'REPORT_COMPANY_2'
					,isnull(REPORT_COMPANY_ADDRESS, '') 'REPORT_COMPANY_ADDRESS'
					,isnull(REPORT_TITLE, '') 'REPORT_TITLE'
					,isnull(REPORT_IMAGE, '') 'REPORT_IMAGE'
					,isnull(AGREEMENT_EXTERNAL_NO, '') 'AGREEMENT_EXTERNAL_NO'
					,isnull(AGREEMENT_EXTERNAL_NO, '') 'AGREEMENT_EXTERNAL_NO_2'
					,isnull(AGREEMENT_DATE, '') 'AGREEMENT_DATE'
					,isnull(CLIENT_NAME, '') 'CLIENT_NAME_AGREEMENT'
					,isnull(MAIN_CONTRACT_NO, '') 'MAIN_CONTRACT_NO'
					,isnull(APPLICATION_DATE,'') 'APPLICATION_DATE'
					,isnull(LOKASI_PENYERAHAN, '') 'LOKASI_PENYERAHAN'
					,isnull(LOKASI_PENGAMBILAN, '') 'LOKASI_PENGAMBILAN'
					,isnull(JANGKA_WAKTU, NULL) 'JANGKA_WAKTU'
					,isnull(FROM_JANGKA_WAKTU,'') 'FROM_JANGKA_WAKTU'
					,isnull(END_JANGKA_WAKTU,'') 'END_JANGKA_WAKTU'
					,isnull(JENIS_KENDARAAN			,'')  	 'JENIS_KENDARAAN'		
					,isnull(JUMLAH					,null)	 'JUMLAH'				
					,isnull(TAHUN					,'')	 'TAHUN'				
					,dbo.xfn_separator_tiga(isnull(HARGA_SEWA_KESELURUHAN	,NULL))	 'HARGA_SEWA_KESELURUHAN'	
					,dbo.xfn_separator_tiga(isnull(HARGA_SEWA_PERBULAN		,NULL))	 'HARGA_SEWA_PERBULAN'	
					,isnull(TANGGAL_BAYAR,NULL) 'TANGGAL_BAYAR'
					,isnull(TANGGAL_SEWA_SATU,NULL) 'TANGGAL_SEWA_SATU'
					,isnull(STAR_SEWA_BERIKUTNYA	,'') 'STAR_SEWA_BERIKUTNYA'
					,isnull(END_SEWA_BERIKUTNYA		,'') 'END_SEWA_BERIKUTNYA'
					,isnull(METODE_PEMBAYARAN		,'') 'METODE_PEMBAYARAN'
					,cast(PERSEN_DENDA as decimal(18, 2)) 'PERSEN_DENDA'
					,replace(dbo.xfn_separator_tiga(isnull(JARAK_TEMPU,NULL)),',00','') 'JARAK_TEMPU'	
					,dbo.xfn_separator_tiga(isnull(BIAYA_KILOMETER,NULL)) 'BIAYA_KILOMETER'	
					,isnull(GOLIVE_DATE,NULL) 'GOLIVE_DATE'	
					,isnull(EMPLOYEE_LESSOR,'') 'EMPLOYEE_LESSOR'	
					,isnull(EMPLOYEE_LESSOR,'') 'EMPLOYEE_LESSOR_2'	
					,isnull(replace(JABATAN_LESSOR,'&','and'),'') 'JABATAN_LESSOR'
					,isnull(PIC_LESSEE,'') 'PIC_LESSEE'	
					,isnull(HARI ,'') 'DAY2Y'
					,isnull(DAY ,'') 'DAY_AGREEMENT_2'
					,isnull(MONTH ,'') 'MONTH_AGREEMENT_2'
					,isnull(YEAR ,'') 'TYEAR'
					,isnull(TANGGAL ,null) 'TANGGAL_AGREEMENT_REALIZATION_2'
					,isnull(CLIENT_ADDRESS,'') 'CLIENT_AGREEMENT_ADDRESS'
					,isnull(CREDIT_TERM,null) 'CREDIT_TERM'
					,isnull(BILLING_TYPE,null) 'BILLING_TYPE'
					,dbo.xfn_separator_tiga(isnull(INSURANCE_TPL,null)) 'INSURANCE_TPL'
					,dbo.xfn_separator_tiga(isnull(INSURANCE_PAD,null)) 'DRIVER'
					,dbo.xfn_separator_tiga(isnull(INSURANCE_PAP,null)) 'PASSENGER'
					,dbo.xfn_separator_tiga(isnull(INSURANCE_SRCCTS,null)) 'INSURANCE_SRCCTS'
					,cast(ET_PENALTY as decimal(18, 2)) 'ET_PENALTY'
					,isnull(TANGGAL_PEMBAYARAN_AWAL_DAN_AKHIR,'') 'TANGGAL_PEMBAYARAN_AWAL_DAN_AKHIR'
					,cast(PPN_PCT as decimal(18, 2)) 'PPN_PCT'
					,isnull(NO_RANGKA,null) 'NO_RANGKA'
					,isnull(NO_MESIN,null) 'NO_MESIN'
					,isnull(KAROSERI,null) 'KAROSERI'
					,isnull(AKSESORIS,null) 'AKSESORIS'
					,isnull(MAIN_CONTRACT_NO,null) 'KONTRAK'
					,isnull(LOKASI_PENGAMBILAN,null) 'AMBIL'
					,isnull(AGREEMENT_DATE,NULL) 'TANGGAL_AGREEMENT'
					,isnull(AGREEMENT_DATE,NULL) 'TANGGAL_AGREEMENT_2'
					,isnull(APPLICATION_DATE,'') 'APPLICATION_DATE'
					,ISNULL(GOLIVE_DATE,'') 'GOLIVE_DATE'
					,isnull(EMPLOYEE_LESSOR,'') 'EMPLOYEE_LESSOR'
					,isnull(PIC_LESSEE,'') 'PIC_LES'
					,cast(isnull(PCT_UNIT,0) as decimal(18,2)) 'PCT_UNIT'
					,isnull(COMPANY_NAME,'')'COMPANY_NAME'
					,isnull(CLIENT_NAME,'') 'CLIENT_NAME'
					,10 'PCT_RUGI'
					,dbo.xfn_separator_tiga(500000) 'NOMINAL_RUGI'
					,dbo.xfn_separator_tiga(300000) 'NOMINAL_GEMPA'
					,'1 (Satu)' 'TOTAL_GEMPA'
					,dbo.xfn_separator_tiga(300000) 'NOMINAL_KECELAKAAN'
					,'1 (Satu)' 'TOTAL_KECELAKAAN'
					,HARI 'REALIZATION_HARI'
					,isnull(AGREEMENT_SIGN_DATE,'') 'AGREEMENT_SIGN_DATE'
					--,isnull(REPORT_COMPANY_ADDRESS, '') 'DAY_AGREEMENT_REALIZATION_2'
					,isnull(REPORT_COMPANY_ADDRESS, '') 'ALAMAT_AGREEMENT_REALIZATION_2'
					,isnull(APPLICATION_DATE,'') 'UTM_KTRK'
					,isnull(TOP_DATE,'') 'TOP_P_DATE'
					,isnull(TANGGAL_BAYAR_AWAL,'') 'TGL_BYR_WL'
					,case when is_srcc = 1 then 'Ya'
						else 'Tidak'
						end	 'TES_2_SRCC'
					,case when is_ts = 1 then 'Ya'
						else 'Tidak'
						end	 'TES_3_SRCC'
					,case when is_earthquake = 1 then 'Ya'
						else 'Tidak'
						end 'TES_YES_NO'
					,case when is_flood_windstorm = 1 then 'Ya'
						else 'Tidak'
						end	 'TES_4_SRCC'
			from	ifinopl.dbo.rpt_perjanjian_pelaksanaan
			where	user_id = @p_user_id ;
end ;
