CREATE TABLE [dbo].[AMS_INTERFACE_APPROVAL_DIMENSION] (
    [ID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [REQUEST_CODE]    NVARCHAR (50) NOT NULL,
    [DIMENSION_CODE]  NVARCHAR (50) NOT NULL,
    [DIMENSION_VALUE] NVARCHAR (50) NOT NULL,
    [CRE_DATE]        DATETIME      NOT NULL,
    [CRE_BY]          NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15) NOT NULL,
    [MOD_DATE]        DATETIME      NOT NULL,
    [MOD_BY]          NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_AMS_INTERFACE_APPROVAL_DIMENSION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

