CREATE TABLE [dbo].[API_LOG] (
    [ID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [TRANSACTION_NO]   NVARCHAR (250) NULL,
    [LOG_DATE]         DATETIME       NULL,
    [URL_REQUEST]      NVARCHAR (MAX) NULL,
    [JSON_CONTENT]     NVARCHAR (MAX) NULL,
    [RESPONSE_CODE]    NVARCHAR (MAX) NULL,
    [RESPONSE_MESSAGE] NVARCHAR (MAX) NULL,
    [RESPONSE_JSON]    NVARCHAR (MAX) NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL
);

