CREATE TABLE [dbo].[ASSET_BARCODE_HISTORY] (
    [ID]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]       NVARCHAR (50) CONSTRAINT [DF_ASSET_BARCODE_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [PREVIOUS_BARCODE] NVARCHAR (50) CONSTRAINT [DF_ASSET_BARCODE_HISTORY_PREVIOUS_BARCODE] DEFAULT ('') NULL,
    [NEW_BARCODE]      NVARCHAR (50) NOT NULL,
    [REMARK]           NVARCHAR (50) NOT NULL,
    [CRE_DATE]         DATETIME      NOT NULL,
    [CRE_BY]           NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    [MOD_DATE]         DATETIME      NOT NULL,
    [MOD_BY]           NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_ASSET_BARCODE_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ASSET_BARCODE_HISTORY_ASSET] FOREIGN KEY ([ASSET_CODE]) REFERENCES [dbo].[ASSET] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

