CREATE TABLE [dbo].[ASSET_MACHINE_UPLOAD] (
    [FA_UPLOAD_ID]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [FILE_NAME]      NVARCHAR (250)  NOT NULL,
    [UPLOAD_NO]      NVARCHAR (50)   NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [MERK_CODE]      NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_MERK_CODE] DEFAULT ('') NULL,
    [MERK_NAME]      NVARCHAR (250)  CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_MERK_NAME] DEFAULT ('') NULL,
    [TYPE_ITEM_CODE] NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_TYPE_CODE] DEFAULT ('') NULL,
    [TYPE_ITEM_NAME] NVARCHAR (250)  CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_TYPE_NAME] DEFAULT ('') NULL,
    [MODEL_CODE]     NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_MODEL_CODE] DEFAULT ('') NULL,
    [MODEL_NAME]     NVARCHAR (250)  CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_TYPE_ITEM_NAME1] DEFAULT ('') NULL,
    [BUILT_YEAR]     NVARCHAR (4)    CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_BUILT_YEAR] DEFAULT ('') NULL,
    [CHASSIS_NO]     NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_CHASSIS_NO] DEFAULT ('') NULL,
    [ENGINE_NO]      NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_ENGINE_NO] DEFAULT ('') NULL,
    [COLOUR]         NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_COLOUR] DEFAULT ('') NULL,
    [SERIAL_NO]      NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_SERIAL_NO] DEFAULT ('') NULL,
    [PURCHASE]       NVARCHAR (50)   NULL,
    [REMARK]         NVARCHAR (4000) CONSTRAINT [DF_ASSET_MACHINE_UPLOAD_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_MACHINE_UPLOAD] PRIMARY KEY CLUSTERED ([FA_UPLOAD_ID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_MACHINE_UPLOAD', @level2type = N'COLUMN', @level2name = N'PURCHASE';

