CREATE TABLE [dbo].[ASSET_MAINTENANCE_TEMP] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50) CONSTRAINT [DF_ASSET_MAINTENANCE_TEMP_SERVICE_CODE1] DEFAULT ('') NULL,
    [SERVICE_CODE]   NVARCHAR (50) CONSTRAINT [DF_ASSET_MAINTENANCE_TEMP_SERVICE_CODE] DEFAULT ('') NULL,
    [MODEL_CODE]     NVARCHAR (50) CONSTRAINT [DF_ASSET_MAINTENANCE_TEMP_SERVICE_CODE1_1] DEFAULT ('') NULL,
    [CRE_BY]         NVARCHAR (15) NULL,
    [CRE_DATE]       DATETIME      NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NULL,
    [MOD_BY]         NVARCHAR (15) NULL,
    [MOD_DATE]       DATETIME      NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NULL,
    CONSTRAINT [PK_ASSET_MAINTENANCE_TEMP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

