CREATE TABLE [dbo].[ASSET_BARCODE_IMAGE] (
    [ASSET_CODE]    NVARCHAR (50)  CONSTRAINT [DF_ASSET_BARCODE_IMAGE_ASSET_CODE] DEFAULT ('') NOT NULL,
    [ASSET_NAME]    NVARCHAR (250) CONSTRAINT [DF_ASSET_BARCODE_IMAGE_BARCODE1] DEFAULT ('') NULL,
    [BARCODE]       NVARCHAR (50)  CONSTRAINT [DF_ASSET_BARCODE_IMAGE_BARCODE] DEFAULT ('') NULL,
    [BARCODE_IMAGE] IMAGE          CONSTRAINT [DF_ASSET_BARCODE_IMAGE_BARCODE_IMAGE1_1] DEFAULT ('') NULL,
    CONSTRAINT [PK_ASSET_BARCODE_IMAGE] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC),
    CONSTRAINT [FK_ASSET_BARCODE_IMAGE_ASSET] FOREIGN KEY ([ASSET_CODE]) REFERENCES [dbo].[ASSET] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

