CREATE TABLE [dbo].[ASSET_OTHER_UPLOAD_HISTORY] (
    [FA_UPLOAD_ID]   BIGINT          NOT NULL,
    [FILE_NAME]      NVARCHAR (250)  NOT NULL,
    [UPLOAD_NO]      NVARCHAR (50)   NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [REMARK]         NVARCHAR (4000) CONSTRAINT [DF_ASSET_OTHER_UPLOAD_HISTORY_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_OTHER_UPLOAD_HISTORY] PRIMARY KEY CLUSTERED ([FA_UPLOAD_ID] ASC)
);

