CREATE TABLE [dbo].[ASSET_OTHER_HISTORY] (
    [ASSET_CODE]         NVARCHAR (50)   NOT NULL,
    [LICENSE_NO]         NVARCHAR (50)   NULL,
    [START_DATE_LICENSE] DATETIME        NULL,
    [END_DATE_LICENSE]   DATETIME        NULL,
    [NOMINAL]            DECIMAL (18, 2) NULL,
    [REMARK]             NVARCHAR (4000) CONSTRAINT [DF_ASSET_OTHER_HISTORY_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]           DATETIME        NOT NULL,
    [CRE_BY]             NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_BY]             NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_OTHER_HISTORY] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);

