CREATE TABLE [dbo].[ASSET_DEPRECIATION] (
    [ID]                             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]                     NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_ASSET_CODE] DEFAULT ('') NOT NULL,
    [BARCODE]                        NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_BARCODE] DEFAULT ('') NOT NULL,
    [DEPRECIATION_DATE]              DATETIME        NOT NULL,
    [DEPRECIATION_COMMERCIAL_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_DEPRECIATION_COMMERCIAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NET_BOOK_VALUE_COMMERCIAL]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_NET_BOOK_VALUE_COMMERCIAL] DEFAULT ((0)) NOT NULL,
    [DEPRECIATION_FISCAL_AMOUNT]     DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_DEPRECIATION_FISCAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NET_BOOK_VALUE_FISCAL]          DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_NET_BOOK_VALUE_FISCAL] DEFAULT ((0)) NOT NULL,
    [PURCHASE_AMOUNT]                DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_PURCHASE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [JOURNAL_CODE]                   NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_JOURNAL_VOUCHER_NO] DEFAULT ('') NOT NULL,
    [STATUS]                         NVARCHAR (25)   CONSTRAINT [DF_ASSET_DEPRECIATION_STATUS] DEFAULT ('') NOT NULL,
    [CRE_DATE]                       DATETIME        NOT NULL,
    [CRE_BY]                         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                 NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                       DATETIME        NOT NULL,
    [MOD_BY]                         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                 NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_DEPRECIATION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_STATUS_DEPRE_DATE]
    ON [dbo].[ASSET_DEPRECIATION]([STATUS] ASC, [DEPRECIATION_DATE] ASC)
    INCLUDE([ASSET_CODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_ASSET_CODE]
    ON [dbo].[ASSET_DEPRECIATION]([ASSET_CODE] ASC)
    INCLUDE([STATUS]);

