CREATE TABLE [dbo].[ASSET_MAINTENANCE_SCHEDULE] (
    [ID]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]         NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_ASSET_CODE] DEFAULT ('') NOT NULL,
    [MAINTENANCE_NO]     NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_NO] DEFAULT ('') NULL,
    [MAINTENANCE_DATE]   DATETIME       CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_DATE] DEFAULT ('') NULL,
    [MAINTENANCE_STATUS] NVARCHAR (20)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_STATUS] DEFAULT ('') NULL,
    [LAST_STATUS_DATE]   DATETIME       CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_LAST_STATUS_DATE] DEFAULT ('') NULL,
    [REFF_TRX_NO]        NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_REFF_TRX_NO] DEFAULT ('') NULL,
    [MILES]              INT            CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MILES_CYCLE] DEFAULT ('') NULL,
    [MONTH]              INT            CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MONTH_CYCLE] DEFAULT ((0)) NULL,
    [HOUR]               INT            CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HOUR_CYCLE] DEFAULT ((0)) NULL,
    [SERVICE_CODE]       NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_NO1] DEFAULT ('') NULL,
    [SERVICE_NAME]       NVARCHAR (250) CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_NO1_1] DEFAULT ('') NULL,
    [SERVICE_TYPE]       NVARCHAR (50)  NULL,
    [SERVICE_DATE]       DATETIME       NULL,
    [CRE_BY]             NVARCHAR (15)  NULL,
    [CRE_DATE]           DATETIME       NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NULL,
    [MOD_BY]             NVARCHAR (15)  NULL,
    [MOD_DATE]           DATETIME       NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NULL,
    CONSTRAINT [PK_ASSET_MAINTENANCE_SCHEDULE] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_MAINTENANCE_SCHEDULE_20231009]
    ON [dbo].[ASSET_MAINTENANCE_SCHEDULE]([ASSET_CODE] ASC)
    INCLUDE([MAINTENANCE_DATE], [REFF_TRX_NO], [MILES], [SERVICE_CODE], [SERVICE_NAME]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_STATUS]
    ON [dbo].[ASSET_MAINTENANCE_SCHEDULE]([MAINTENANCE_STATUS] ASC)
    INCLUDE([ASSET_CODE], [MAINTENANCE_DATE]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_MAINTENANCE_SCHEDULE_20240104]
    ON [dbo].[ASSET_MAINTENANCE_SCHEDULE]([ASSET_CODE] ASC, [MAINTENANCE_DATE] ASC, [MAINTENANCE_STATUS] ASC);

