CREATE TABLE [dbo].[ASSET_DOCUMENT] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   CONSTRAINT [DF_ASSET_DOCUMENT_ASSET_CODE] DEFAULT ('') NULL,
    [DOCUMENT_CODE]  NVARCHAR (50)   CONSTRAINT [DF_ASSET_DOCUMENT_ASSET_CODE1] DEFAULT ('') NULL,
    [DOCUMENT_NO]    NVARCHAR (50)   CONSTRAINT [DF_ASSET_DOCUMENT_DOCUMENT_CODE1] DEFAULT ('') NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_ASSET_DOCUMENT_DESCRIPTION] DEFAULT ('') NULL,
    [FILE_NAME]      NVARCHAR (250)  CONSTRAINT [DF_ASSET_DOCUMENT_FILE_NAME] DEFAULT ('') NULL,
    [FILE_PATH]      NVARCHAR (250)  NULL,
    [DOC_FILE]       VARBINARY (MAX) NULL,
    [DOC_NO]         NVARCHAR (50)   NULL,
    [DOC_DATE]       DATETIME        NULL,
    [DOC_EXP_DATE]   DATETIME        NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DOCUMENT_ASSET_CODE_20250615]
    ON [dbo].[ASSET_DOCUMENT]([ASSET_CODE] ASC)
    INCLUDE([DOCUMENT_CODE]);

