CREATE TABLE [dbo].[ASSET_PROPERTY_UPLOAD_HISTORY] (
    [FA_UPLOAD_ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [FILE_NAME]                NVARCHAR (250)  NOT NULL,
    [UPLOAD_NO]                NVARCHAR (50)   NOT NULL,
    [ASSET_CODE]               NVARCHAR (50)   NOT NULL,
    [IMB_NO]                   NVARCHAR (50)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_IMB_NO] DEFAULT ('') NULL,
    [CERTIFICATE_NO]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_CERTIFICATE_NO] DEFAULT ('') NULL,
    [LAND_SIZE]                DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_LAND_SIZE] DEFAULT ((0)) NULL,
    [BUILDING_SIZE]            DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_BUILDING_SIZE] DEFAULT ((0)) NULL,
    [STATUS_OF_RUKO]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_STATUS_OF_RUKO] DEFAULT ('') NULL,
    [NUMBER_OF_RUKO_AND_FLOOR] NVARCHAR (50)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_NUMBER_OF_RUKO_AND_FLOOR] DEFAULT ('') NULL,
    [TOTAL_SQUARE]             NVARCHAR (10)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_TOTAL_SQUARE] DEFAULT ('') NULL,
    [VAT]                      DECIMAL (9, 6)  CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_VAT] DEFAULT ((0)) NULL,
    [NO_LEASE_AGREEMENT]       NVARCHAR (50)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_NO_LEASE_AGREEMENT] DEFAULT ('') NULL,
    [DATE_OF_LEASE_AGREEMENT]  DATETIME        NULL,
    [LAND_AND_BUILDING_TAX]    NVARCHAR (50)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_LAND_AND_BUILDING_TAX] DEFAULT ('') NULL,
    [SECURITY_DEPOSIT]         DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_SECURITY_DEPOSIT] DEFAULT ((0)) NULL,
    [PENALTY]                  DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_PENALTY] DEFAULT ((0)) NULL,
    [OWNER]                    NVARCHAR (250)  CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_OWNER] DEFAULT ('') NULL,
    [ADDRESS]                  NVARCHAR (400)  CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_ADDRESS] DEFAULT ('') NULL,
    [PURCHASE]                 NVARCHAR (50)   NULL,
    [TOTAL_RENTAL_PERIOD]      NVARCHAR (9)    CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_TOTAL_RENTAL_PERIOD] DEFAULT ('') NULL,
    [RENTAL_PERIOD]            NVARCHAR (15)   CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_RENTAL_PERIOD] DEFAULT ('') NULL,
    [RENTAL_PRICE_PER_YEAR]    DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_RENTAL_PRICE_PER_YEAR] DEFAULT ((0)) NULL,
    [RENTAL_PRICE_PER_MONTH]   DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_RENTAL_PRICE_PER_MONTH] DEFAULT ((0)) NULL,
    [TOTAL_RENTAL_PRICE]       DECIMAL (18, 2) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_TOTAL_RENTAL_PRICE] DEFAULT ((0)) NULL,
    [START_RENTAL_DATE]        DATETIME        NULL,
    [END_RENTAL_DATE]          DATETIME        NULL,
    [REMARK]                   NVARCHAR (4000) CONSTRAINT [DF_ASSET_PROPERTY_UPLOAD_HISTORY_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_PROPERTY_UPLOAD_HISTORY] PRIMARY KEY CLUSTERED ([FA_UPLOAD_ID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_PROPERTY_UPLOAD_HISTORY', @level2type = N'COLUMN', @level2name = N'PURCHASE';

