CREATE TABLE [dbo].[ASSET_MACHINE_HISTORY] (
    [ASSET_CODE]              NVARCHAR (50)   NOT NULL,
    [MERK_CODE]               NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_MERK_CODE] DEFAULT ('') NULL,
    [MERK_NAME]               NVARCHAR (250)  CONSTRAINT [DF_ASSET_MACHINE_HISTORY_MERK_NAME] DEFAULT ('') NULL,
    [TYPE_ITEM_CODE]          NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_TYPE_ITEM_CODE] DEFAULT ('') NULL,
    [TYPE_ITEM_NAME]          NVARCHAR (250)  CONSTRAINT [DF_ASSET_MACHINE_HISTORY_TYPE_ITEM_NAME] DEFAULT ('') NULL,
    [MODEL_CODE]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_MODEL_CODE] DEFAULT ('') NULL,
    [BUILT_YEAR]              NVARCHAR (4)    CONSTRAINT [DF_ASSET_MACHINE_HISTORY_BUILT_YEAR] DEFAULT ('') NULL,
    [INVOICE_NO]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_CHASSIS_NO1] DEFAULT ('') NULL,
    [CHASSIS_NO]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_CHASSIS_NO] DEFAULT ('') NULL,
    [ENGINE_NO]               NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_ENGINE_NO] DEFAULT ('') NULL,
    [COLOUR]                  NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_COLOUR] DEFAULT ('') NULL,
    [SERIAL_NO]               NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_SERIAL_NO] DEFAULT ('') NULL,
    [PURCHASE]                NVARCHAR (50)   NULL,
    [NO_LEASE_AGREEMENT]      NVARCHAR (50)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_NO_LEASE_AGREEMENT] DEFAULT ('') NULL,
    [DATE_OF_LEASE_AGREEMENT] DATETIME        NULL,
    [SECURITY_DEPOSIT]        DECIMAL (18, 2) CONSTRAINT [DF_ASSET_MACHINE_HISTORY_SECURITY_DEPOSIT] DEFAULT ((0)) NULL,
    [TOTAL_RENTAL_PERIOD]     NVARCHAR (9)    CONSTRAINT [DF_ASSET_MACHINE_HISTORY_TOTAL_RENTAL_PERIOD] DEFAULT ('') NULL,
    [RENTAL_PERIOD]           NVARCHAR (15)   CONSTRAINT [DF_ASSET_MACHINE_HISTORY_RENTAL_PERIOD] DEFAULT ('') NULL,
    [RENTAL_PRICE]            DECIMAL (18, 2) CONSTRAINT [DF_ASSET_MACHINE_HISTORY_RENTAL_PRICE] DEFAULT ((0)) NULL,
    [TOTAL_RENTAL_PRICE]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_MACHINE_HISTORY_TOTAL_RENTAL_PRICE] DEFAULT ((0)) NULL,
    [START_RENTAL_DATE]       DATETIME        NULL,
    [END_RENTAL_DATE]         DATETIME        NULL,
    [REMARK]                  NVARCHAR (4000) CONSTRAINT [DF_ASSET_MACHINE_HISTORY_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MODEL_NAME]              NVARCHAR (250)  NULL,
    CONSTRAINT [PK_ASSET_MACHINE_HISTORY] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_MACHINE_HISTORY', @level2type = N'COLUMN', @level2name = N'PURCHASE';

