CREATE TABLE [dbo].[ASSET_DOCUMENT_HISTORY] (
    [ID]             BIGINT          NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   CONSTRAINT [DF_ASSET_DOCUMENT_HISTORY_ASSET_CODE] DEFAULT ('') NULL,
    [DOCUMENT_CODE]  NVARCHAR (50)   CONSTRAINT [DF_ASSET_DOCUMENT_HISTORY_DOCUMENT_CODE] DEFAULT ('') NULL,
    [DOCUMENT_NO]    NVARCHAR (50)   CONSTRAINT [DF_ASSET_DOCUMENT_HISTORY_DOCUMENT_NO] DEFAULT ('') NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_ASSET_DOCUMENT_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [FILE_NAME]      NVARCHAR (250)  CONSTRAINT [DF_ASSET_DOCUMENT_HISTORY_FILE_NAME] DEFAULT ('') NULL,
    [PATH]           NVARCHAR (250)  CONSTRAINT [DF_ASSET_DOCUMENT_HISTORY_PATH] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_DOCUMENT_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

