CREATE TABLE [dbo].[ASSET_EXPENSE_LEDGER] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [REFF_CODE]      NVARCHAR (50)   NOT NULL,
    [REFF_NAME]      NVARCHAR (250)  NOT NULL,
    [REFF_REMARK]    NVARCHAR (4000) NOT NULL,
    [EXPENSE_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NULL,
    [CLIENT_NAME]    NVARCHAR (250)  NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_EXPENSE_LEDGER] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_EXPENSE_LEDGER_AGREEMENT_NO]
    ON [dbo].[ASSET_EXPENSE_LEDGER]([AGREEMENT_NO] ASC)
    INCLUDE([EXPENSE_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_EXPENSE_LEDGER_ASSET_CODE]
    ON [dbo].[ASSET_EXPENSE_LEDGER]([ASSET_CODE] ASC)
    INCLUDE([AGREEMENT_NO], [CLIENT_NAME], [CRE_BY], [CRE_DATE], [CRE_IP_ADDRESS], [DATE], [EXPENSE_AMOUNT], [MOD_BY], [MOD_DATE], [MOD_IP_ADDRESS], [REFF_CODE], [REFF_NAME], [REFF_REMARK]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_EXPENSE_LEDGER_ASSET_CODE_AGREEMENT_NO_20250615]
    ON [dbo].[ASSET_EXPENSE_LEDGER]([ASSET_CODE] ASC, [AGREEMENT_NO] ASC);

