CREATE TABLE [dbo].[ASSET_ENDING_BALANCE] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]           NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_ASSET_ENDING_BALANCE_ASSET_CODE] DEFAULT ('') NOT NULL,
    [PERIOD]               DATETIME        NULL,
    [BALANCE_AMOUNT]       DECIMAL (18, 2) CONSTRAINT [DF_ASSET_ENDING_BALANCE_BALANCE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [BALANCE_AMOUNT_ACCUM] DECIMAL (18, 2) CONSTRAINT [DF_ASSET_ENDING_BALANCE_BALANCE_AMOUNT_ACCUM] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_ENDING_BALANCE_ASSET_CODE]
    ON [dbo].[ASSET_ENDING_BALANCE]([ASSET_CODE] ASC)
    INCLUDE([PERIOD], [BALANCE_AMOUNT], [BALANCE_AMOUNT_ACCUM]);

