CREATE TABLE [dbo].[ASSET_MUTATION_HISTORY] (
    [ID]                       BIGINT         IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]               NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [DATE]                     DATETIME       NOT NULL,
    [DOCUMENT_REFFERENCE_NO]   NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_DOCUMENT_REFFERENCE_NO] DEFAULT ('') NOT NULL,
    [DOCUMENT_REFFERENCE_TYPE] NVARCHAR (10)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_DOCUMENT_REFFERENCE_TYPE] DEFAULT ('') NOT NULL,
    [USAGE_DURATION]           INT            CONSTRAINT [DF_ASSET_MUTATION_HISTORY_USAGE_DURATION] DEFAULT ((0)) NOT NULL,
    [FROM_BRANCH_CODE]         NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [FROM_BRANCH_NAME]         NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [TO_BRANCH_CODE]           NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [TO_BRANCH_NAME]           NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [FROM_LOCATION_CODE]       NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_LOCATION_CODE] DEFAULT ('') NOT NULL,
    [TO_LOCATION_CODE]         NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_LOCATION_CODE] DEFAULT ('') NOT NULL,
    [FROM_PIC_CODE]            NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_PIC_CODE] DEFAULT ('') NOT NULL,
    [TO_PIC_CODE]              NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_PIC_CODE] DEFAULT ('') NOT NULL,
    [FROM_DIVISION_CODE]       NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_DIVISION_CODE] DEFAULT ('') NOT NULL,
    [FROM_DIVISION_NAME]       NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_DIVISION_NAME] DEFAULT ('') NOT NULL,
    [TO_DIVISION_CODE]         NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_DIVISION_CODE] DEFAULT ('') NOT NULL,
    [TO_DIVISION_NAME]         NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_DIVISION_NAME] DEFAULT ('') NOT NULL,
    [FROM_DEPARTMENT_CODE]     NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_DEPARTMENT_CODE] DEFAULT ('') NOT NULL,
    [FROM_DEPARTMENT_NAME]     NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_DEPARTMENT_NAME] DEFAULT ('') NOT NULL,
    [TO_DEPARTMENT_CODE]       NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_DEPARTMENT_CODE] DEFAULT ('') NOT NULL,
    [TO_DEPARTMENT_NAME]       NVARCHAR (250) CONSTRAINT [DF_Table_1_TO_DEPARTMENT_CODE1] DEFAULT ('') NOT NULL,
    [FROM_SUB_DEPARTMENT_CODE] NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_SUB_DEPARTMENT_CODE] DEFAULT ('') NOT NULL,
    [FROM_SUB_DEPARTMENT_NAME] NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_SUB_DEPARTMENT_NAME] DEFAULT ('') NOT NULL,
    [TO_SUB_DEPARTMENT_CODE]   NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_TO_SUB_DEPARTMENT_CODE] DEFAULT ('') NOT NULL,
    [TO_SUB_DEPARTMENT_NAME]   NVARCHAR (250) CONSTRAINT [DF_Table_1_TO_SUB_DEPARTMENT_CODE1] DEFAULT ('') NOT NULL,
    [FROM_UNIT_CODE]           NVARCHAR (50)  CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_UNIT_CODE] DEFAULT ('') NOT NULL,
    [FROM_UNIT_NAME]           NVARCHAR (250) CONSTRAINT [DF_ASSET_MUTATION_HISTORY_FROM_UNIT_NAME] DEFAULT ('') NOT NULL,
    [TO_UNIT_CODE]             NVARCHAR (50)  CONSTRAINT [DF_Table_1_TO_UNITS_CODE] DEFAULT ('') NOT NULL,
    [TO_UNIT_NAME]             NVARCHAR (250) CONSTRAINT [DF_Table_1_TO_UNIT_CODE1] DEFAULT ('') NOT NULL,
    [CRE_DATE]                 DATETIME       NOT NULL,
    [CRE_BY]                   NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                 DATETIME       NOT NULL,
    [MOD_BY]                   NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_ASSET_MUTATION_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_MUTATION_HISTORY_ASSET_CODE_DOCUMENT_REFERENCE_TYPE_DATE]
    ON [dbo].[ASSET_MUTATION_HISTORY]([ASSET_CODE] ASC, [DOCUMENT_REFFERENCE_TYPE] ASC, [DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_MUTATION_HISTORY_DATE]
    ON [dbo].[ASSET_MUTATION_HISTORY]([DATE] ASC)
    INCLUDE([ASSET_CODE]);

