CREATE TABLE [dbo].[ASSET_DEPRECIATION_SCHEDULE_FISCAL] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]          NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_FISCAL_ASSET_CODE] DEFAULT ('') NOT NULL,
    [DEPRECIATION_DATE]   DATETIME        NOT NULL,
    [ORIGINAL_PRICE]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_FISCAL_ORIGINAL_PRICE] DEFAULT ((0)) NOT NULL,
    [DEPRECIATION_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_FISCAL_DEPRECIATION_AMOUNT] DEFAULT ((0)) NOT NULL,
    [ACCUM_DEPRE_AMOUNT]  DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_FISCAL_ACCUM_DEPRE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NET_BOOK_VALUE]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_FISCAL_NET_BOOK_VALUE] DEFAULT ((0)) NOT NULL,
    [TRANSACTION_CODE]    NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_FISCAL_TRANSACTION_CODE] DEFAULT ('') NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NULL,
    CONSTRAINT [PK_ASSET_DEPRECIATION_SCHEDULE_FISCAL] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_SCHEDULE_FISCAL_ASSET_CODE]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_FISCAL]([ASSET_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_SCHEDULE_FISCAL_DEPRECIATION_ASSET_CODE]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_FISCAL]([ASSET_CODE] ASC)
    INCLUDE([DEPRECIATION_DATE], [DEPRECIATION_AMOUNT], [NET_BOOK_VALUE]);

