CREATE TABLE [dbo].[ASSET_HISTORY] (
    [CODE]                       NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]               NVARCHAR (50)   NOT NULL,
    [ITEM_CODE]                  NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_ITEM_CODE] DEFAULT ('') NOT NULL,
    [ITEM_NAME]                  NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_ITEM_NAME] DEFAULT ('') NOT NULL,
    [CONDITION]                  NVARCHAR (50)   NULL,
    [BARCODE]                    NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_BARCODE] DEFAULT ('') NULL,
    [COST_CENTER_CODE]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_COST_CENTER_CODE] DEFAULT ('') NOT NULL,
    [COST_CENTER_NAME]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_COST_CENTER_NAME] DEFAULT ('') NOT NULL,
    [STATUS]                     NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_STATUS] DEFAULT ('') NOT NULL,
    [PO_NO]                      NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_PO_NO] DEFAULT ('') NULL,
    [REQUESTOR_CODE]             NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_REQUESTOR_CODE] DEFAULT ('') NULL,
    [REQUESTOR_NAME]             NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_REQUESTOR_NAME] DEFAULT ('') NULL,
    [VENDOR_CODE]                NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_VENDOR_CODE] DEFAULT ('') NOT NULL,
    [VENDOR_NAME]                NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_VENDOR_NAME] DEFAULT ('') NOT NULL,
    [TYPE_CODE]                  NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_TYPE_CODE] DEFAULT ('') NULL,
    [CATEGORY_CODE]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_CATEGORY_CODE] DEFAULT ('') NULL,
    [CATEGORY_NAME]              NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_CATEGORY_NAME] DEFAULT ('') NULL,
    [PO_DATE]                    DATETIME        NULL,
    [PURCHASE_DATE]              DATETIME        NOT NULL,
    [PURCHASE_PRICE]             DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_PURCHASE_PRICE] DEFAULT ((0)) NOT NULL,
    [INVOICE_NO]                 NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_INVOICE_NO] DEFAULT ('') NULL,
    [INVOICE_DATE]               DATETIME        CONSTRAINT [DF_ASSET_HISTORY_INVOICE_DATE] DEFAULT ('') NULL,
    [ORIGINAL_PRICE]             DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_ORIGINAL_PRICE] DEFAULT ((0)) NOT NULL,
    [SALE_AMOUNT]                DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_SALE_AMOUNT] DEFAULT ((0)) NULL,
    [SALE_DATE]                  DATETIME        NULL,
    [DISPOSAL_DATE]              DATETIME        NULL,
    [BRANCH_CODE]                NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]                NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [LOCATION_CODE]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_LOCATION_CODE] DEFAULT ('') NOT NULL,
    [LOCATION_NAME]              NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_LOCATION_NAME] DEFAULT ('') NULL,
    [DIVISION_CODE]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_DIVISION_CODE] DEFAULT ('') NULL,
    [DIVISION_NAME]              NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_DIVISION_NAME] DEFAULT ('') NULL,
    [DEPARTMENT_CODE]            NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_DEPARTMENT_CODE] DEFAULT ('') NULL,
    [DEPARTMENT_NAME]            NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_DEPARTMENT_NAME] DEFAULT ('') NULL,
    [SUB_DEPARTMENT_CODE]        NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_SUB_DEPARTMENT_CODE] DEFAULT ('') NULL,
    [SUB_DEPARTMENT_NAME]        NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_SUB_DEPARTMENT_NAME] DEFAULT ('') NULL,
    [UNITS_CODE]                 NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_UNITS_CODE] DEFAULT ('') NULL,
    [UNITS_NAME]                 NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_UNITS_NAME] DEFAULT ('') NULL,
    [PIC_CODE]                   NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_PIC_CODE] DEFAULT ('') NULL,
    [PIC_NAME]                   NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_PIC_NAME] DEFAULT ('') NULL,
    [RESIDUAL_VALUE]             DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_RESIDUAL_VALUE] DEFAULT ((0)) NULL,
    [IS_DEPRE]                   NVARCHAR (1)    CONSTRAINT [DF_ASSET_HISTORY_IS_DEPRE] DEFAULT ((0)) NULL,
    [DEPRE_CATEGORY_COMM_CODE]   NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_DEPRE_CATEGORY_COMM_CODE] DEFAULT ('') NOT NULL,
    [TOTAL_DEPRE_COMM]           DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_TOTAL_DEPRE_COMM] DEFAULT ((0)) NOT NULL,
    [DEPRE_PERIOD_COMM]          NVARCHAR (6)    CONSTRAINT [DF_ASSET_HISTORY_DEPRE_PERIOD_COMM] DEFAULT ((0)) NULL,
    [NET_BOOK_VALUE_COMM]        DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_NET_BOOK_VALUE_COMM] DEFAULT ((0)) NOT NULL,
    [DEPRE_CATEGORY_FISCAL_CODE] NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_DEPRE_CATEGORY_FISCAL_CODE] DEFAULT ('') NOT NULL,
    [TOTAL_DEPRE_FISCAL]         DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_TOTAL_DEPRE_FISCAL] DEFAULT ((0)) NOT NULL,
    [DEPRE_PERIOD_FISCAL]        NVARCHAR (6)    CONSTRAINT [DF_ASSET_HISTORY_DEPRE_PERIOD_FISCAL] DEFAULT ('') NULL,
    [NET_BOOK_VALUE_FISCAL]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_HISTORY_NET_BOOK_VALUE_FISCAL] DEFAULT ((0)) NOT NULL,
    [IS_RENTAL]                  NVARCHAR (1)    CONSTRAINT [DF_ASSET_HISTORY_IS_RENTAL] DEFAULT ((0)) NULL,
    [OPL_CODE]                   NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_OPL_CODE] DEFAULT ('') NULL,
    [RENTAL_DATE]                DATETIME        CONSTRAINT [DF_ASSET_HISTORY_RENTAL_DATE] DEFAULT ('') NULL,
    [CONTRACTOR_NAME]            NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_NAME] DEFAULT ('') NULL,
    [CONTRACTOR_ADDRESS]         NVARCHAR (4000) CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_ADDRESS] DEFAULT ('') NULL,
    [CONTRACTOR_EMAIL]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_EMAIL] DEFAULT ('') NULL,
    [CONTRACTOR_PIC]             NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_PIC] DEFAULT ('') NULL,
    [CONTRACTOR_PIC_PHONE]       NVARCHAR (25)   CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_PIC_PHONE] DEFAULT ('') NULL,
    [CONTRACTOR_START_DATE]      DATETIME        CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_START_DATE] DEFAULT ('') NULL,
    [CONTRACTOR_END_DATE]        DATETIME        CONSTRAINT [DF_ASSET_HISTORY_CONTRACTOR_END_DATE] DEFAULT ('') NULL,
    [WARRANTY]                   INT             NULL,
    [WARRANTY_START_DATE]        DATETIME        NULL,
    [WARRANTY_END_DATE]          DATETIME        NULL,
    [REMARKS_WARRANTY]           NVARCHAR (4000) CONSTRAINT [DF_ASSET_HISTORY_REMARKS_WARRANTY] DEFAULT ('') NULL,
    [IS_MAINTENANCE]             NVARCHAR (1)    CONSTRAINT [DF_ASSET_HISTORY_IS_MAINTENANCE] DEFAULT ('') NULL,
    [MAINTENANCE_TIME]           INT             CONSTRAINT [DF_ASSET_HISTORY_MAINTENANCE_TIME] DEFAULT ((0)) NULL,
    [MAINTENANCE_TYPE]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_MAINTENANCE_TYPE] DEFAULT ('') NULL,
    [MAINTENANCE_CYCLE_TIME]     INT             CONSTRAINT [DF_ASSET_HISTORY_MAINTENANCE_CYCLE_TIME] DEFAULT ((0)) NULL,
    [MAINTENANCE_START_DATE]     DATETIME        NULL,
    [USE_LIFE]                   NVARCHAR (15)   NULL,
    [LAST_METER]                 NVARCHAR (15)   NULL,
    [LAST_SERVICE_DATE]          DATETIME        NULL,
    [PPH]                        DECIMAL (9, 6)  CONSTRAINT [DF_ASSET_HISTORY_PPH] DEFAULT ((0)) NULL,
    [PPN]                        DECIMAL (9, 6)  CONSTRAINT [DF_ASSET_HISTORY_PPN] DEFAULT ((0)) NULL,
    [REMARKS]                    NVARCHAR (4000) CONSTRAINT [DF_ASSET_HISTORY_REMARKS] DEFAULT ('') NULL,
    [LAST_SO_DATE]               DATETIME        NULL,
    [LAST_SO_CONDITION]          NVARCHAR (50)   NULL,
    [REGIONAL_CODE]              NVARCHAR (50)   CONSTRAINT [DF_ASSET_HISTORY_REGIONAL_CODE] DEFAULT ('') NULL,
    [REGIONAL_NAME]              NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_REGIONAL_NAME] DEFAULT ('') NULL,
    [LAST_USED_BY_CODE]          NVARCHAR (50)   NULL,
    [LAST_USED_BY_NAME]          NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_LAST_USED_BY_NAME] DEFAULT ('') NULL,
    [LAST_LOCATION_CODE]         NVARCHAR (50)   NULL,
    [LAST_LOCATION_NAME]         NVARCHAR (250)  CONSTRAINT [DF_ASSET_HISTORY_LAST_LOCATION_NAME] DEFAULT ('') NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_HISTORY] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_HISTORY', @level2type = N'COLUMN', @level2name = N'CONDITION';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_HISTORY', @level2type = N'COLUMN', @level2name = N'USE_LIFE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_HISTORY', @level2type = N'COLUMN', @level2name = N'LAST_METER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_HISTORY', @level2type = N'COLUMN', @level2name = N'LAST_USED_BY_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tipe pembayaran pertama pada kontrak pembiayaan tersebut - ADVANCE, menginformasikan bahwa angsuran pertama dibayarkan didepan - ARREAR, menginformasikan bahwa angsuran pertama dibayarkan dibelakang', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_HISTORY', @level2type = N'COLUMN', @level2name = N'LAST_LOCATION_CODE';

