CREATE TABLE [dbo].[ASSET_PREPAID] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [PREPAID_NO]     NVARCHAR (50)   NOT NULL,
    [PREPAID_DATE]   DATETIME        NOT NULL,
    [PREPAID_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [JOURNAL_CODE]   NVARCHAR (50)   NOT NULL,
    [STATUS]         NVARCHAR (25)   CONSTRAINT [DF_ASSET_PREPAID_STATUS] DEFAULT ('') NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_PREPAID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

