CREATE TABLE [dbo].[ASSET_PREPAID_SCHEDULE] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [PREPAID_NO]       NVARCHAR (50)   NOT NULL,
    [PREPAID_DATE]     DATETIME        NOT NULL,
    [PREPAID_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [ACCRUE_REFF_CODE] NVARCHAR (50)   NULL,
    [ACCRUE_DATE]      DATETIME        NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_PREPAID_SCHEDULE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ASSET_PREPAID_SCHEDULE_ASSET_PREPAID_MAIN] FOREIGN KEY ([PREPAID_NO]) REFERENCES [dbo].[ASSET_PREPAID_MAIN] ([PREPAID_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_PREPAID_SCHEDULE_PREPAID_NO]
    ON [dbo].[ASSET_PREPAID_SCHEDULE]([PREPAID_NO] ASC)
    INCLUDE([PREPAID_DATE], [PREPAID_AMOUNT]);

