CREATE TABLE [dbo].[ASSET_VEHICLE] (
    [ASSET_CODE]        NVARCHAR (50)   NOT NULL,
    [MERK_CODE]         NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_MERK_CODE] DEFAULT ('') NULL,
    [MERK_NAME]         NVARCHAR (250)  CONSTRAINT [DF_ASSET_VEHICLE_MERK_NAME] DEFAULT ('') NULL,
    [TYPE_ITEM_CODE]    NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_TYPE_CODE] DEFAULT ('') NULL,
    [TYPE_ITEM_NAME]    NVARCHAR (250)  CONSTRAINT [DF_ASSET_VEHICLE_TYPE_NAME] DEFAULT ('') NULL,
    [MODEL_CODE]        NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_MODEL_CODE] DEFAULT ('') NULL,
    [MODEL_NAME]        NVARCHAR (250)  CONSTRAINT [DF_ASSET_VEHICLE_TYPE_ITEM_NAME1] DEFAULT ('') NULL,
    [PLAT_NO]           NVARCHAR (20)   CONSTRAINT [DF_ASSET_VEHICLE_PLAT_NO] DEFAULT ('') NULL,
    [CHASSIS_NO]        NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_CHASSIS_NO] DEFAULT ('') NULL,
    [ENGINE_NO]         NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_ENGINE_NO] DEFAULT ('') NULL,
    [BPKB_NO]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_BPKB_NO] DEFAULT ('') NULL,
    [COLOUR]            NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_COLOUR] DEFAULT ('') NULL,
    [CYLINDER]          NVARCHAR (20)   CONSTRAINT [DF_ASSET_VEHICLE_CYLINDER] DEFAULT ('') NULL,
    [STNK_NO]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_STNK_NO] DEFAULT ('') NULL,
    [STNK_EXPIRED_DATE] DATETIME        NULL,
    [STNK_TAX_DATE]     DATETIME        NULL,
    [STNK_RENEWAL]      NVARCHAR (15)   CONSTRAINT [DF_ASSET_VEHICLE_STNK_RENEWAL] DEFAULT ('') NULL,
    [KEUR_NO]           NVARCHAR (50)   CONSTRAINT [DF_ASSET_VEHICLE_STNK_NO1] DEFAULT ('') NULL,
    [KEUR_DATE]         DATETIME        NULL,
    [KEUR_EXPIRED_DATE] DATETIME        NULL,
    [BUILT_YEAR]        NVARCHAR (4)    CONSTRAINT [DF_ASSET_VEHICLE_BUILT_YEAR] DEFAULT ('') NULL,
    [REMARK]            NVARCHAR (4000) CONSTRAINT [DF_ASSET_VEHICLE_REMARK] DEFAULT ('') NULL,
    [STNK_NAME]         NVARCHAR (50)   NULL,
    [STNK_DATE]         DATETIME        NULL,
    [STNK_ADDRESS]      NVARCHAR (4000) NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [STCK_NO]           NVARCHAR (50)   NULL,
    [STCK_DATE]         DATETIME        NULL,
    [STCK_EXP_DATE]     DATETIME        NULL,
    CONSTRAINT [PK_ASSET_VEHICLE] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC),
    CONSTRAINT [FK_ASSET_VEHICLE_ASSET] FOREIGN KEY ([ASSET_CODE]) REFERENCES [dbo].[ASSET] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [ASSET_VEHICLE_PLAT_NO]
    ON [dbo].[ASSET_VEHICLE]([PLAT_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [ASSET_VEHICLE_CHASS_CHASSIS_NO]
    ON [dbo].[ASSET_VEHICLE]([CHASSIS_NO] ASC);

