CREATE TABLE [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]          NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_ASSET_CODE] DEFAULT ('') NOT NULL,
    [DEPRECIATION_DATE]   DATETIME        NOT NULL,
    [ORIGINAL_PRICE]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_ORIGINAL_PRICE] DEFAULT ((0)) NOT NULL,
    [DEPRECIATION_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_DEPRECIATION_AMOUNT] DEFAULT ((0)) NOT NULL,
    [ACCUM_DEPRE_AMOUNT]  DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_ACCUM_DEPRE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NET_BOOK_VALUE]      DECIMAL (18, 2) CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_NET_BOOK_VALUE] DEFAULT ((0)) NOT NULL,
    [TRANSACTION_CODE]    NVARCHAR (50)   CONSTRAINT [DF_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_TRANSACTION_CODE] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_ASSET_CODE]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL]([ASSET_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_TRANSACTION_CODE]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL]([TRANSACTION_CODE] ASC)
    INCLUDE([ASSET_CODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_TRANS_CODE]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL]([TRANSACTION_CODE] ASC)
    INCLUDE([ASSET_CODE], [DEPRECIATION_DATE], [ORIGINAL_PRICE], [DEPRECIATION_AMOUNT], [NET_BOOK_VALUE]);


GO
CREATE NONCLUSTERED INDEX [idx_asset_depreciation_schedule_commercial1]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL]([MOD_IP_ADDRESS] ASC)
    INCLUDE([ASSET_CODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_JOB_JOURNAL_REPORT_NOTIFICATION_20230102]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL]([TRANSACTION_CODE] ASC, [DEPRECIATION_DATE] ASC)
    INCLUDE([ASSET_CODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL_ASSET_CODE_20250615]
    ON [dbo].[ASSET_DEPRECIATION_SCHEDULE_COMMERCIAL]([ASSET_CODE] ASC)
    INCLUDE([DEPRECIATION_DATE], [DEPRECIATION_AMOUNT], [ACCUM_DEPRE_AMOUNT]);

