CREATE TABLE [dbo].[ASSET_MAINTENANCE_SCHEDULE_HISTORY] (
    [ID]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]         NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [MAINTENANCE_NO]     NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_MAINTENANCE_NO] DEFAULT ('') NULL,
    [MAINTENANCE_DATE]   DATETIME       CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_MAINTENANCE_DATE] DEFAULT ('') NULL,
    [MAINTENANCE_STATUS] NVARCHAR (20)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_MAINTENANCE_STATUS] DEFAULT ('') NULL,
    [LAST_STATUS_DATE]   DATETIME       CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_LAST_STATUS_DATE] DEFAULT ('') NULL,
    [REFF_TRX_NO]        NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_REFF_TRX_NO] DEFAULT ('') NULL,
    [MILES]              INT            CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_MILES] DEFAULT ('') NULL,
    [MONTH]              INT            CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_MONTH] DEFAULT ((0)) NULL,
    [HOUR]               INT            CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_HOUR] DEFAULT ((0)) NULL,
    [SERVICE_CODE]       NVARCHAR (50)  CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_SERVICE_CODE] DEFAULT ('') NULL,
    [SERVICE_NAME]       NVARCHAR (250) CONSTRAINT [DF_ASSET_MAINTENANCE_SCHEDULE_HISTORY_SERVICE_NAME] DEFAULT ('') NULL,
    [CRE_BY]             NVARCHAR (15)  NULL,
    [CRE_DATE]           DATETIME       NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NULL,
    [MOD_BY]             NVARCHAR (15)  NULL,
    [MOD_DATE]           DATETIME       NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NULL,
    CONSTRAINT [PK_ASSET_MAINTENANCE_SCHEDULE_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

