CREATE TABLE [dbo].[CLAIM_DETAIL_ASSET] (
    [ID]                BIGINT        IDENTITY (1, 1) NOT NULL,
    [CLAIM_CODE]        NVARCHAR (50) NOT NULL,
    [POLICY_ASSET_CODE] NVARCHAR (50) NULL,
    [CRE_DATE]          DATETIME      NOT NULL,
    [CRE_BY]            NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15) NOT NULL,
    [MOD_DATE]          DATETIME      NOT NULL,
    [MOD_BY]            NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_CLAIM_DETAIL_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC)
);

