CREATE TABLE [dbo].[DISPOSAL_HISTORY] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]   NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_HISTORY_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [DISPOSAL_DATE]  DATETIME        NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_HISTORY_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  CONSTRAINT [DF_DISPOSAL_HISTORY_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [LOCATION_CODE]  NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_HISTORY_LOCATION_CODE] DEFAULT ('') NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_DISPOSAL_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [REASON_TYPE]    NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_HISTORY_REASON_TYPE] DEFAULT ('') NOT NULL,
    [REMARKS]        NVARCHAR (4000) CONSTRAINT [DF_DISPOSAL_HISTORY_REMARKS] DEFAULT ('') NULL,
    [STATUS]         NVARCHAR (25)   CONSTRAINT [DF_DISPOSAL_HISTORY_STATUS] DEFAULT ('') NOT NULL,
    [CRE_DATE]       DATETIME        NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DISPOSAL_HISTORY] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

