CREATE TABLE [dbo].[DISPOSAL_DETAIL_HISTORY] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [DISPOSAL_CODE]    NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_DETAIL_HISTORY_DISPOSAL_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]       NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_DETAIL_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [DESCRIPTION]      NVARCHAR (4000) CONSTRAINT [DF_DISPOSAL_DETAIL_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [COST_CENTER_CODE] NVARCHAR (50)   NULL,
    [COST_CENTER_NAME] NVARCHAR (250)  NULL,
    CONSTRAINT [PK_DISPOSAL_DETAIL_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

