CREATE TABLE [dbo].[DISPOSAL_DETAIL] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [DISPOSAL_CODE]    NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_DETAIL_DISPOSAL_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]       NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_DETAIL_ASSET_CODE] DEFAULT ('') NOT NULL,
    [GL_ASSET_CODE]    NVARCHAR (50)   NULL,
    [COST_CENTER_CODE] NVARCHAR (50)   NULL,
    [COST_CENTER_NAME] NVARCHAR (250)  NULL,
    [DESCRIPTION]      NVARCHAR (4000) CONSTRAINT [DF_DISPOSAL_DETAIL_DESCRIPTION] DEFAULT ('') NULL,
    [NET_BOOK_VALUE]   DECIMAL (18, 2) NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DISPOSAL_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DISPOSAL_DETAIL_ASSET] FOREIGN KEY ([ASSET_CODE]) REFERENCES [dbo].[ASSET] ([CODE]),
    CONSTRAINT [FK_DISPOSAL_DETAIL_DISPOSAL] FOREIGN KEY ([DISPOSAL_CODE]) REFERENCES [dbo].[DISPOSAL] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

