CREATE TABLE [dbo].[DISPOSAL_DOCUMENT] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [DISPOSAL_CODE]  NVARCHAR (50)  CONSTRAINT [DF_DISPOSAL_DOCUMENT_DISPOSAL_CODE] DEFAULT ('') NOT NULL,
    [FILE_NAME]      NVARCHAR (250) NULL,
    [PATH]           NVARCHAR (250) NULL,
    [DESCRIPTION]    NVARCHAR (400) NULL,
    [CRE_BY]         NVARCHAR (15)  NULL,
    [CRE_DATE]       DATETIME       NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NULL,
    [MOD_BY]         NVARCHAR (15)  NULL,
    [MOD_DATE]       DATETIME       NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NULL,
    CONSTRAINT [PK_DISPOSAL_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DISPOSAL_DOCUMENT_DISPOSAL] FOREIGN KEY ([DISPOSAL_CODE]) REFERENCES [dbo].[DISPOSAL] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

