CREATE TABLE [dbo].[DISPOSAL] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]   NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [DISPOSAL_DATE]  DATETIME        NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  CONSTRAINT [DF_DISPOSAL_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_DISPOSAL_DESCRIPTION] DEFAULT ('') NULL,
    [REASON_TYPE]    NVARCHAR (50)   CONSTRAINT [DF_DISPOSAL_REASON_CODE] DEFAULT ('') NOT NULL,
    [REMARKS]        NVARCHAR (4000) CONSTRAINT [DF_DISPOSAL_REMARKS] DEFAULT ('') NULL,
    [STATUS]         NVARCHAR (25)   CONSTRAINT [DF_DISPOSAL_STATUS] DEFAULT ('') NOT NULL,
    [CRE_DATE]       DATETIME        NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DISPOSAL] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

