CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_UPDATE_ONGRN] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]           NVARCHAR (50)   NOT NULL,
    [JOB_STATUS]     NVARCHAR (10)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_UPDATE_ONGRN_JOB_STATUS] DEFAULT (N'HOLD') NULL,
    [FAILED_REMARKS] NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_EFAM_INTERFACE_ASSET_UPDATE_ONGRN_1] PRIMARY KEY CLUSTERED ([ID] ASC, [CODE] ASC)
);

