CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_FURNITURE] (
    [ASSET_CODE]     NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MERK_CODE]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_FURNITURE_MERK_CODE] DEFAULT ('') NULL,
    [MERK_NAME]      NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_FURNITURE_MERK_NAME] DEFAULT ('') NULL,
    [TYPE_CODE]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_FURNITURE_TYPE_CODE] DEFAULT ('') NULL,
    [TYPE_NAME]      NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_FURNITURE_TYPE_NAME] DEFAULT ('') NULL,
    [MODEL_CODE]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_FURNITURE_MODEL_CODE] DEFAULT ('') NULL,
    [MODEL_NAME]     NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_FURNITURE_MODEL_NAME] DEFAULT ('') NULL,
    [REMARK]         NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_EFAM_INTERFACE_ASSET_FURNITURE] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);

