CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE] (
    [ID]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]         NVARCHAR (50) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE_ASSET_CODE] DEFAULT ('') NOT NULL,
    [MAINTENANCE_NO]     NVARCHAR (50) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_NO] DEFAULT ('') NULL,
    [MAINTENANCE_DATE]   DATETIME      CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_DATE] DEFAULT ('') NULL,
    [MAINTENANCE_STATUS] NVARCHAR (20) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE_MAINTENANCE_STATUS] DEFAULT ('') NULL,
    [LAST_STATUS_DATE]   DATETIME      CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE_LAST_STATUS_DATE] DEFAULT ('') NULL,
    [REFF_TRX_NO]        NVARCHAR (50) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MAINTENANCE_SCHEDULE_REFF_TRX_NO] DEFAULT ('') NULL,
    [CRE_BY]             NVARCHAR (15) NULL,
    [CRE_DATE]           DATETIME      NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15) NULL,
    [MOD_BY]             NVARCHAR (15) NULL,
    [MOD_DATE]           DATETIME      NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15) NULL
);

