CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_BARCODE_IMAGE] (
    [ASSET_CODE]    NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS CONSTRAINT [DF_EFAM_INTERFACE_ASSET_BARCODE_IMAGE_ASSET_CODE] DEFAULT ('') NOT NULL,
    [BARCODE]       NVARCHAR (50) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_BARCODE_IMAGE_BARCODE] DEFAULT ('') NULL,
    [BARCODE_IMAGE] IMAGE         CONSTRAINT [DF_EFAM_INTERFACE_ASSET_BARCODE_IMAGE_BARCODE_IMAGE] DEFAULT ('') NULL,
    CONSTRAINT [PK_EFAM_INTERFACE_ASSET_BARCODE_IMAGE] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);

