CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_DOCUMENT] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_DOCUMENT_ASSET_CODE] DEFAULT ('') NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_DOCUMENT_DESCRIPTION] DEFAULT ('') NULL,
    [FILE_NAME]      NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_DOCUMENT_FILE_NAME] DEFAULT ('') NULL,
    [PATH]           NVARCHAR (250)  NULL,
    [DOC_FILE]       VARBINARY (MAX) NULL,
    [DOC_NO]         NVARCHAR (50)   NULL,
    [DOC_DATE]       DATETIME        NULL,
    [DOC_EXP_DATE]   DATETIME        NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);

