CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_MACHINE] (
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [MERK_CODE]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_MERK_CODE] DEFAULT ('') NULL,
    [MERK_NAME]      NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_MERK_NAME] DEFAULT ('') NULL,
    [TYPE_ITEM_CODE] NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_TYPE_CODE] DEFAULT ('') NULL,
    [TYPE_ITEM_NAME] NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_TYPE_NAME] DEFAULT ('') NULL,
    [MODEL_CODE]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_MODEL_CODE] DEFAULT ('') NULL,
    [BUILT_YEAR]     NVARCHAR (4)    CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_BUILT_YEAR] DEFAULT ('') NULL,
    [INVOICE_NO]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_CHASSIS_NO1] DEFAULT ('') NULL,
    [CHASSIS_NO]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_CHASSIS_NO] DEFAULT ('') NULL,
    [ENGINE_NO]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_ENGINE_NO] DEFAULT ('') NULL,
    [COLOUR]         NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_COLOUR] DEFAULT ('') NULL,
    [SERIAL_NO]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_SERIAL_NO] DEFAULT ('') NULL,
    [REMARK]         NVARCHAR (4000) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_MACHINE_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MODEL_NAME]     NVARCHAR (250)  NULL,
    CONSTRAINT [PK_EFAM_INTERFACE_ASSET_MACHINE] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);

