CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_OTHER] (
    [ASSET_CODE]     NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [REMARK]         NVARCHAR (4000) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_OTHER_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_EFAM_INTERFACE_ASSET_OTHER] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);

