CREATE TABLE [dbo].[EFAM_INTERFACE_ASSET_HE] (
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [MERK_CODE]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_MERK_CODE] DEFAULT ('') NULL,
    [MERK_NAME]      NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_MERK_NAME] DEFAULT ('') NULL,
    [TYPE_ITEM_CODE] NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_TYPE_ITEM_CODE] DEFAULT ('') NULL,
    [TYPE_ITEM_NAME] NVARCHAR (250)  CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_TYPE_ITEM_NAME] DEFAULT ('') NULL,
    [MODEL_CODE]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_MODEL_CODE] DEFAULT ('') NULL,
    [MODEL_NAME]     NVARCHAR (250)  NULL,
    [BUILT_YEAR]     NVARCHAR (4)    CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_BUILT_YEAR] DEFAULT ('') NULL,
    [INVOICE_NO]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_INVOICE_NO] DEFAULT ('') NULL,
    [CHASSIS_NO]     NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_CHASSIS_NO] DEFAULT ('') NULL,
    [ENGINE_NO]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_ENGINE_NO] DEFAULT ('') NULL,
    [COLOUR]         NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_COLOUR] DEFAULT ('') NULL,
    [SERIAL_NO]      NVARCHAR (50)   CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_SERIAL_NO] DEFAULT ('') NULL,
    [REMARK]         NVARCHAR (4000) CONSTRAINT [DF_EFAM_INTERFACE_ASSET_HE_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_EFAM_INTERFACE_ASSET_HE] PRIMARY KEY CLUSTERED ([ASSET_CODE] ASC)
);

