CREATE TABLE [dbo].[GET_DATA_PROFITABILITY_ASSET] (
    [CODE]        NVARCHAR (50)   NOT NULL,
    [DESCRIPTION] NVARCHAR (50)   NULL,
    [BUDGET]      DECIMAL (18, 2) NULL,
    [ACTUAL]      DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_GET_DATA_PROFITABILITY_ASSET] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

