CREATE TABLE [dbo].[GPS_UNSUBCRIBE_REQUEST] (
    [REQUEST_NO]         NVARCHAR (50)  NOT NULL,
    [FA_CODE]            NVARCHAR (50)  NOT NULL,
    [REQUEST_DATE]       DATETIME       NOT NULL,
    [SOURCE_REFF_NO]     NVARCHAR (50)  NOT NULL,
    [SOURCE_REFF_NAME]   NVARCHAR (100) NOT NULL,
    [REMARK]             NVARCHAR (250) NOT NULL,
    [STATUS]             NVARCHAR (20)  CONSTRAINT [DF_GPS_UNSUBCRIBE_REQUEST_STATUS] DEFAULT ('HOLD') NOT NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [BRANCH_CODE]        NVARCHAR (50)  NULL,
    [BRANCH_NAME]        NVARCHAR (250) NULL,
    [REASON_UNSUBSCRIBE] NVARCHAR (250) NULL,
    [ID_MONITORING_GPS]  BIGINT         NULL,
    [UNSUBSCRIBE_DATE]   DATETIME       NULL,
    CONSTRAINT [PK__GPS_UNSU__71D28297697A07E4] PRIMARY KEY CLUSTERED ([REQUEST_NO] ASC),
    CONSTRAINT [FK_GPS_UNSUBCRIBE_REQUEST_ASSET] FOREIGN KEY ([FA_CODE]) REFERENCES [dbo].[ASSET] ([CODE])
);

