CREATE TABLE [dbo].[HANDOVER_ASSET_DOC] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [HANDOVER_CODE]  NVARCHAR (50)  NOT NULL,
    [DOCUMENT_CODE]  NVARCHAR (50)  NULL,
    [FILE_NAME]      NVARCHAR (250) NULL,
    [FILE_PATH]      NVARCHAR (250) NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_HANDOVER_ASSET_DOC] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_HANDOVER_ASSET_DOC_HANDOVER_ASSET] FOREIGN KEY ([HANDOVER_CODE]) REFERENCES [dbo].[HANDOVER_ASSET] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

