CREATE TABLE [dbo].[IFINAMS_INTERFACE_SPAF_ASSET] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]              NVARCHAR (50)   NOT NULL,
    [DATE]              DATETIME        NOT NULL,
    [FA_CODE]           NVARCHAR (50)   NOT NULL,
    [SPAF_PCT]          DECIMAL (9, 6)  NOT NULL,
    [SPAF_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [VALIDATION_STATUS] NVARCHAR (10)   NULL,
    [VALIDATION_DATE]   DATETIME        NULL,
    [VALIDATION_REMARK] NVARCHAR (4000) NULL,
    [CLAIM_CODE]        NVARCHAR (50)   NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (50)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (50)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (50)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_IFINAMS_INTERFACE_SPAF_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC)
);

