CREATE TABLE [dbo].[INSURANCE_EXPIRED] (
    [POLICY_NO]      NVARCHAR (50)  NULL,
    [TOTAL_ASSET]    INT            NULL,
    [EFF_DATE]       NVARCHAR (50)  NULL,
    [EXP_DATE]       NVARCHAR (50)  NULL,
    [INSURANCE_NAME] NVARCHAR (250) NULL,
    [PAYMENT_STATUS] NVARCHAR (50)  NULL
);

