CREATE TABLE [dbo].[MASTER_MAPPING_VALUE_DETAIL] (
    [ID]                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [MAPPING_VALUE_CODE] NVARCHAR (50)  CONSTRAINT [DF_MASTER_MAPPING_VALUE_DETAIL_MAPPING_VALUE_CODE] DEFAULT ('') NOT NULL,
    [COLUMN_NAME]        NVARCHAR (250) CONSTRAINT [DF_MASTER_MAPPING_VALUE_DETAIL_COLUMN_NAME] DEFAULT ('') NOT NULL,
    [FIELD_NAME]         NVARCHAR (250) CONSTRAINT [DF_MASTER_MAPPING_VALUE_DETAIL_FIELD_NAME] DEFAULT ('') NOT NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_MAPPING_VALUE_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_MAPPING_VALUE_DETAIL_Update_Audit]      
			ON [dbo].[MASTER_MAPPING_VALUE_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([MAPPING_VALUE_CODE]) THEN '[MAPPING_VALUE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COLUMN_NAME]) THEN '[COLUMN_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([FIELD_NAME]) THEN '[FIELD_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_MAPPING_VALUE_DETAIL]
([ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_MAPPING_VALUE_DETAIL]
([ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_MAPPING_VALUE_DETAIL_Delete_Audit]    
			ON [dbo].[MASTER_MAPPING_VALUE_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_MAPPING_VALUE_DETAIL]
([ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_MAPPING_VALUE_DETAIL_Insert_Audit] 
			ON [dbo].[MASTER_MAPPING_VALUE_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_MAPPING_VALUE_DETAIL]
([ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[MAPPING_VALUE_CODE],[COLUMN_NAME],[FIELD_NAME],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 