CREATE TABLE [dbo].[MASTER_CUSTOM_REPORT_CONDITION] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [CUSTOM_REPORT_CODE]  NVARCHAR (50)   CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_CUSTOM_REPORT_CODE] DEFAULT ('') NULL,
    [LOGICAL_OPERATOR]    NVARCHAR (20)   CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_LOGICAL_OPERATOR] DEFAULT ('') NULL,
    [COLUMN_NAME]         NVARCHAR (250)  CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_COLUMN_NAME] DEFAULT ('') NULL,
    [COMPARISON_OPERATOR] NVARCHAR (20)   CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_COMPARISON_OPERATOR] DEFAULT ('') NULL,
    [START_VALUE]         NVARCHAR (4000) CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_START_VALUE] DEFAULT ('') NULL,
    [END_VALUE]           NVARCHAR (4000) CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_END_VALUE] DEFAULT ('') NULL,
    [ORDER_KEY]           INT             CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CONDITION_ORDER_KEY] DEFAULT ('') NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CUSTOM_REPORT_CONDITION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_CUSTOM_REPORT_CONDITION_Insert_Audit] 
			ON [dbo].[MASTER_CUSTOM_REPORT_CONDITION]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT_CONDITION]
([ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_CUSTOM_REPORT_CONDITION_Update_Audit]      
			ON [dbo].[MASTER_CUSTOM_REPORT_CONDITION]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([CUSTOM_REPORT_CODE]) THEN '[CUSTOM_REPORT_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([LOGICAL_OPERATOR]) THEN '[LOGICAL_OPERATOR]-' ELSE '' END + 
CASE WHEN UPDATE([COLUMN_NAME]) THEN '[COLUMN_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([COMPARISON_OPERATOR]) THEN '[COMPARISON_OPERATOR]-' ELSE '' END + 
CASE WHEN UPDATE([START_VALUE]) THEN '[START_VALUE]-' ELSE '' END + 
CASE WHEN UPDATE([END_VALUE]) THEN '[END_VALUE]-' ELSE '' END + 
CASE WHEN UPDATE([ORDER_KEY]) THEN '[ORDER_KEY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT_CONDITION]
([ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT_CONDITION]
([ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_CUSTOM_REPORT_CONDITION_Delete_Audit]    
			ON [dbo].[MASTER_CUSTOM_REPORT_CONDITION]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT_CONDITION]
([ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[CUSTOM_REPORT_CODE],[LOGICAL_OPERATOR],[COLUMN_NAME],[COMPARISON_OPERATOR],[START_VALUE],[END_VALUE],[ORDER_KEY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED