CREATE TABLE [dbo].[MASTER_UPLOAD_TABLE_COLUMN] (
    [CODE]              NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [UPLOAD_TABLE_CODE] NVARCHAR (50) NOT NULL,
    [COLUMN_NAME]       NVARCHAR (50) NOT NULL,
    [DATA_TYPE]         NVARCHAR (10) NOT NULL,
    [MAX_LENGTH]        INT           NOT NULL,
    [CRE_DATE]          DATETIME      NOT NULL,
    [CRE_BY]            NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15) NOT NULL,
    [MOD_DATE]          DATETIME      NOT NULL,
    [MOD_BY]            NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15) NOT NULL,
    PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_COLUMN_Insert_Audit] 
			ON [dbo].[MASTER_UPLOAD_TABLE_COLUMN]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_COLUMN]
([CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_COLUMN_Delete_Audit]    
			ON [dbo].[MASTER_UPLOAD_TABLE_COLUMN]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_COLUMN]
([CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_COLUMN_Update_Audit]      
			ON [dbo].[MASTER_UPLOAD_TABLE_COLUMN]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([UPLOAD_TABLE_CODE]) THEN '[UPLOAD_TABLE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COLUMN_NAME]) THEN '[COLUMN_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DATA_TYPE]) THEN '[DATA_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([MAX_LENGTH]) THEN '[MAX_LENGTH]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_COLUMN]
([CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_COLUMN]
([CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[UPLOAD_TABLE_CODE],[COLUMN_NAME],[DATA_TYPE],[MAX_LENGTH],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END