CREATE TABLE [dbo].[MASTER_UPLOAD_TABLE_VALIDATION] (
    [ID]                       BIGINT        IDENTITY (1, 1) NOT NULL,
    [UPLOAD_TABLE_COLUMN_CODE] NVARCHAR (50) NOT NULL,
    [UPLOAD_VALIDATION_CODE]   NVARCHAR (50) NOT NULL,
    [CRE_DATE]                 DATETIME      NOT NULL,
    [CRE_BY]                   NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15) NOT NULL,
    [MOD_DATE]                 DATETIME      NOT NULL,
    [MOD_BY]                   NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_VALIDATION_Delete_Audit]    
			ON [dbo].[MASTER_UPLOAD_TABLE_VALIDATION]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_VALIDATION]
([ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_VALIDATION_Update_Audit]      
			ON [dbo].[MASTER_UPLOAD_TABLE_VALIDATION]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([UPLOAD_TABLE_COLUMN_CODE]) THEN '[UPLOAD_TABLE_COLUMN_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([UPLOAD_VALIDATION_CODE]) THEN '[UPLOAD_VALIDATION_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_VALIDATION]
([ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_VALIDATION]
([ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_UPLOAD_TABLE_VALIDATION_Insert_Audit] 
			ON [dbo].[MASTER_UPLOAD_TABLE_VALIDATION]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_UPLOAD_TABLE_VALIDATION]
([ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[UPLOAD_TABLE_COLUMN_CODE],[UPLOAD_VALIDATION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 