CREATE TABLE [dbo].[MASTER_CUSTOM_REPORT] (
    [CODE]             NVARCHAR (50)  CONSTRAINT [DF_MASTER_CUSTOM_REPORT_CODE] DEFAULT ('') NOT NULL,
    [COMPANY_CODE]     NVARCHAR (50)  CONSTRAINT [DF_MASTER_CUSTOM_REPORT_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [DESCRIPTION]      NVARCHAR (250) CONSTRAINT [DF_MASTER_CUSTOM_REPORT_DESCRIPTION] DEFAULT ('') NOT NULL,
    [ASSET_TYPE]       NVARCHAR (50)  CONSTRAINT [DF_MASTER_CUSTOM_REPORT_ASSET_TYPE] DEFAULT ('') NOT NULL,
    [TRANSACTION_TYPE] NVARCHAR (50)  CONSTRAINT [DF_MASTER_CUSTOM_REPORT_TRANSACTION_TYPE] DEFAULT ('') NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)   CONSTRAINT [DF_MASTER_CUSTOM_REPORT_IS_ACTIVE] DEFAULT ('') NOT NULL,
    [CRE_DATE]         DATETIME       NOT NULL,
    [CRE_BY]           NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    [MOD_DATE]         DATETIME       NOT NULL,
    [MOD_BY]           NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_CUSTOM_REPORT] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_CUSTOM_REPORT_Insert_Audit] 
			ON [dbo].[MASTER_CUSTOM_REPORT]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_CUSTOM_REPORT_Delete_Audit]    
			ON [dbo].[MASTER_CUSTOM_REPORT]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_CUSTOM_REPORT_Update_Audit]      
			ON [dbo].[MASTER_CUSTOM_REPORT]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([ASSET_TYPE]) THEN '[ASSET_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_TYPE]) THEN '[TRANSACTION_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_CUSTOM_REPORT]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE],[TRANSACTION_TYPE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END