CREATE TABLE [dbo].[MASTER_BARCODE_REGISTER_DETAIL] (
    [ID]                    BIGINT        IDENTITY (1, 1) NOT NULL,
    [BARCODE_REGISTER_CODE] NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [BARCODE_NO]            NVARCHAR (50) NOT NULL,
    [ASSET_CODE]            NVARCHAR (50) NOT NULL,
    [STATUS]                NVARCHAR (20) NOT NULL,
    [CRE_DATE]              DATETIME      NOT NULL,
    [CRE_BY]                NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15) NOT NULL,
    [MOD_DATE]              DATETIME      NOT NULL,
    [MOD_BY]                NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_BARCODE_REGISTER_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MASTER_BARCODE_REGISTER_DETAIL_MASTER_BARCODE_REGISTER] FOREIGN KEY ([BARCODE_REGISTER_CODE]) REFERENCES [dbo].[MASTER_BARCODE_REGISTER] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_BARCODE_REGISTER_DETAIL_Delete_Audit]    
			ON [dbo].[MASTER_BARCODE_REGISTER_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_BARCODE_REGISTER_DETAIL]
([ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_BARCODE_REGISTER_DETAIL_Update_Audit]      
			ON [dbo].[MASTER_BARCODE_REGISTER_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([BARCODE_REGISTER_CODE]) THEN '[BARCODE_REGISTER_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([BARCODE_NO]) THEN '[BARCODE_NO]-' ELSE '' END + 
CASE WHEN UPDATE([ASSET_CODE]) THEN '[ASSET_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([STATUS]) THEN '[STATUS]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BARCODE_REGISTER_DETAIL]
([ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BARCODE_REGISTER_DETAIL]
([ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_BARCODE_REGISTER_DETAIL_Insert_Audit] 
			ON [dbo].[MASTER_BARCODE_REGISTER_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_BARCODE_REGISTER_DETAIL]
([ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BARCODE_REGISTER_CODE],[BARCODE_NO],[ASSET_CODE],[STATUS],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 