CREATE TABLE [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [PUBLIC_SERVICE_BRANCH_CODE] NVARCHAR (50)   NOT NULL,
    [SERVICE_CODE]               NVARCHAR (50)   NOT NULL,
    [SERVICE_FEE_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [ESTIMATE_FINISH_DAY]        INT             CONSTRAINT [DF_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE_ESTIMATE_FINISH] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE_MASTER_PUBLIC_SERVICE_BRANCH] FOREIGN KEY ([PUBLIC_SERVICE_BRANCH_CODE]) REFERENCES [dbo].[MASTER_PUBLIC_SERVICE_BRANCH] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE_Insert_Audit] 
			ON [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]
([ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE_Update_Audit]      
			ON [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([PUBLIC_SERVICE_BRANCH_CODE]) THEN '[PUBLIC_SERVICE_BRANCH_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([SERVICE_CODE]) THEN '[SERVICE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([SERVICE_FEE_AMOUNT]) THEN '[SERVICE_FEE_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([ESTIMATE_FINISH_DAY]) THEN '[ESTIMATE_FINISH_DAY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]
([ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]
([ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE_Delete_Audit]    
			ON [dbo].[MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_PUBLIC_SERVICE_BRANCH_SERVICE]
([ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[PUBLIC_SERVICE_BRANCH_CODE],[SERVICE_CODE],[SERVICE_FEE_AMOUNT],[ESTIMATE_FINISH_DAY],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED