CREATE TABLE [dbo].[MASTER_CATEGORY] (
    [CODE]                         NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]                 NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]                  NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_DESCRIPTION] DEFAULT ('') NOT NULL,
    [ASSET_TYPE_CODE]              NVARCHAR (20)   CONSTRAINT [DF_MASTER_CATEGORY_ASSET_TYPE_CODE] DEFAULT ('') NOT NULL,
    [TRANSACTION_DEPRE_CODE]       NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_DEPRE_CODE] DEFAULT ('') NULL,
    [TRANSACTION_DEPRE_NAME]       NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_DEPRE_NAME] DEFAULT ('') NULL,
    [TRANSACTION_ACCUM_DEPRE_CODE] NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_ACCUM_DEPRE_CODE] DEFAULT ('') NULL,
    [TRANSACTION_ACCUM_DEPRE_NAME] NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_ACCUM_DEPRE_NAME] DEFAULT ('') NULL,
    [TRANSACTION_GAIN_LOSS_CODE]   NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_GAIN_LOSS_CODE] DEFAULT ('') NULL,
    [TRANSACTION_GAIN_LOSS_NAME]   NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_GAIN_LOSS_NAME] DEFAULT ('') NULL,
    [TRANSACTION_PROFIT_SELL_CODE] NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_PROFIT_SELL_CODE] DEFAULT ('') NULL,
    [TRANSACTION_PROFIT_SELL_NAME] NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_PROFIT_SELL_NAME] DEFAULT ('') NULL,
    [TRANSACTION_LOSS_SELL_CODE]   NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_LOSS_SELL_CODE] DEFAULT ('') NULL,
    [TRANSACTION_LOSS_SELL_NAME]   NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_TRANSACTION_LOSS_SELL_NAME] DEFAULT ('') NULL,
    [DEPRE_CAT_FISCAL_CODE]        NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_DEPRE_CAT_FISCAL_CODE] DEFAULT ('') NULL,
    [DEPRE_CAT_FISCAL_NAME]        NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_DEPRE_CAT_FISCAL_NAME] DEFAULT ('') NULL,
    [DEPRE_CAT_COMMERCIAL_CODE]    NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_DEPRE_CAT_COMMERCIAL_CODE] DEFAULT ('') NULL,
    [DEPRE_CAT_COMMERCIAL_NAME]    NVARCHAR (250)  CONSTRAINT [DF_MASTER_CATEGORY_DEPRE_CAT_COMMERCIAL_NAME] DEFAULT ('') NULL,
    [LAST_DEPRE_DATE]              DATETIME        NULL,
    [ASSET_AMOUNT_THRESHOLD]       DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CATEGORY_ASSET_AMOUNT_THRESHOLD] DEFAULT ((0)) NOT NULL,
    [DEPRE_AMOUNT_THRESHOLD]       DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CATEGORY_DEPRE_AMOUNT_THRESHOLD] DEFAULT ((0)) NOT NULL,
    [TOTAL_NET_BOOK_VALUE_AMOUNT]  DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CATEGORY_TOTAL_NET_BOOK_VALUE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [TOTAL_ACCUM_DEPRE_AMOUNT]     DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CATEGORY_TOTAL_ACCUM_DEPRE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [TOTAL_ASSET_VALUE]            DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CATEGORY_TOTAL_ASSET_VALUE] DEFAULT ((0)) NOT NULL,
    [VALUE_TYPE]                   NVARCHAR (50)   CONSTRAINT [DF_MASTER_CATEGORY_VALUE_TYPE] DEFAULT ('') NOT NULL,
    [NDE]                          DECIMAL (18, 6) CONSTRAINT [DF_MASTER_CATEGORY_NDE] DEFAULT ((0)) NULL,
    [IS_ACTIVE]                    NVARCHAR (1)    NOT NULL,
    [CRE_DATE]                     DATETIME        NOT NULL,
    [CRE_BY]                       NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                     DATETIME        NOT NULL,
    [MOD_BY]                       NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CATEGORY] PRIMARY KEY CLUSTERED ([CODE] ASC, [COMPANY_CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_CATEGORY_Delete_Audit]    
			ON [dbo].[MASTER_CATEGORY]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_CATEGORY]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_CATEGORY_Update_Audit]      
			ON [dbo].[MASTER_CATEGORY]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COMPANY_CODE]) THEN '[COMPANY_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([ASSET_TYPE_CODE]) THEN '[ASSET_TYPE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_DEPRE_CODE]) THEN '[TRANSACTION_DEPRE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_DEPRE_NAME]) THEN '[TRANSACTION_DEPRE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_ACCUM_DEPRE_CODE]) THEN '[TRANSACTION_ACCUM_DEPRE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_ACCUM_DEPRE_NAME]) THEN '[TRANSACTION_ACCUM_DEPRE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_GAIN_LOSS_CODE]) THEN '[TRANSACTION_GAIN_LOSS_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_GAIN_LOSS_NAME]) THEN '[TRANSACTION_GAIN_LOSS_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_PROFIT_SELL_CODE]) THEN '[TRANSACTION_PROFIT_SELL_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_PROFIT_SELL_NAME]) THEN '[TRANSACTION_PROFIT_SELL_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_LOSS_SELL_CODE]) THEN '[TRANSACTION_LOSS_SELL_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_LOSS_SELL_NAME]) THEN '[TRANSACTION_LOSS_SELL_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DEPRE_CAT_FISCAL_CODE]) THEN '[DEPRE_CAT_FISCAL_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DEPRE_CAT_FISCAL_NAME]) THEN '[DEPRE_CAT_FISCAL_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DEPRE_CAT_COMMERCIAL_CODE]) THEN '[DEPRE_CAT_COMMERCIAL_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DEPRE_CAT_COMMERCIAL_NAME]) THEN '[DEPRE_CAT_COMMERCIAL_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([LAST_DEPRE_DATE]) THEN '[LAST_DEPRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([ASSET_AMOUNT_THRESHOLD]) THEN '[ASSET_AMOUNT_THRESHOLD]-' ELSE '' END + 
CASE WHEN UPDATE([DEPRE_AMOUNT_THRESHOLD]) THEN '[DEPRE_AMOUNT_THRESHOLD]-' ELSE '' END + 
CASE WHEN UPDATE([TOTAL_NET_BOOK_VALUE_AMOUNT]) THEN '[TOTAL_NET_BOOK_VALUE_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([TOTAL_ACCUM_DEPRE_AMOUNT]) THEN '[TOTAL_ACCUM_DEPRE_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([TOTAL_ASSET_VALUE]) THEN '[TOTAL_ASSET_VALUE]-' ELSE '' END + 
CASE WHEN UPDATE([VALUE_TYPE]) THEN '[VALUE_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([NDE]) THEN '[NDE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_CATEGORY]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_CATEGORY]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_CATEGORY_Insert_Audit] 
			ON [dbo].[MASTER_CATEGORY]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_CATEGORY]
([CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[COMPANY_CODE],[DESCRIPTION],[ASSET_TYPE_CODE],[TRANSACTION_DEPRE_CODE],[TRANSACTION_DEPRE_NAME],[TRANSACTION_ACCUM_DEPRE_CODE],[TRANSACTION_ACCUM_DEPRE_NAME],[TRANSACTION_GAIN_LOSS_CODE],[TRANSACTION_GAIN_LOSS_NAME],[TRANSACTION_PROFIT_SELL_CODE],[TRANSACTION_PROFIT_SELL_NAME],[TRANSACTION_LOSS_SELL_CODE],[TRANSACTION_LOSS_SELL_NAME],[DEPRE_CAT_FISCAL_CODE],[DEPRE_CAT_FISCAL_NAME],[DEPRE_CAT_COMMERCIAL_CODE],[DEPRE_CAT_COMMERCIAL_NAME],[LAST_DEPRE_DATE],[ASSET_AMOUNT_THRESHOLD],[DEPRE_AMOUNT_THRESHOLD],[TOTAL_NET_BOOK_VALUE_AMOUNT],[TOTAL_ACCUM_DEPRE_AMOUNT],[TOTAL_ASSET_VALUE],[VALUE_TYPE],[NDE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE TRANSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE PERUSAHAAN (DSF)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'COMPANY_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'DESKRIPSI TRANSAKSI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'DESCRIPTION';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE TIPE ASSET (''VHCL'', ''MCHN'')', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'ASSET_TYPE_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE COA DEPRESIASI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_DEPRE_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NAMA COA DEPRESIASI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_DEPRE_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE COA AKUMULASI DEPRE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_ACCUM_DEPRE_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NAMA COA AKUMULASI DEPRE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_ACCUM_DEPRE_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_GAIN_LOSS_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_GAIN_LOSS_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE COA KEUNTUNGAN PENJUALAN', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_PROFIT_SELL_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NAMA COA KEUNTUNGAN PENJUALAN', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_PROFIT_SELL_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE COA KERUGIAN PENJUALAN', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_LOSS_SELL_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NAMA COA KERUGIAN PENJUALAN', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TRANSACTION_LOSS_SELL_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE DEPRE FISKAL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'DEPRE_CAT_FISCAL_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NAMA DEPRE FISKAL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'DEPRE_CAT_FISCAL_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'KODE DEPRE COMMERCIAL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'DEPRE_CAT_COMMERCIAL_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NAMA DEPRE COMMERCIAL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'DEPRE_CAT_COMMERCIAL_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'TANGGAL TERAKHIR DI DEPRESIASI', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'LAST_DEPRE_DATE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NILAI ASSET MINIMAL YANG DIAKUI SEBAGAI ASSET', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'ASSET_AMOUNT_THRESHOLD';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NILAI ASSET MINIMAL YANG BAKAL TERDEPRE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'DEPRE_AMOUNT_THRESHOLD';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TOTAL_NET_BOOK_VALUE_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TOTAL_ACCUM_DEPRE_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'TOTAL_ASSET_VALUE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'VALUE_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'NOT USED', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'NDE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'AKTIF (1), TIDAK AKTIF(0)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CATEGORY', @level2type = N'COLUMN', @level2name = N'IS_ACTIVE';

