CREATE TABLE [dbo].[MIG_REGISTER_MAIN] (
    [CODE]                              NVARCHAR (50)   NULL,
    [BRANCH_CODE]                       NVARCHAR (50)   NULL,
    [BRANCH_NAME]                       NVARCHAR (250)  NULL,
    [FA_CODE]                           NVARCHAR (50)   NULL,
    [REGISTER_NO]                       NVARCHAR (50)   NULL,
    [REGISTER_DATE]                     DATETIME        NULL,
    [REGISTER_STATUS]                   NVARCHAR (20)   NULL,
    [REGISTER_PROCESS_BY]               NVARCHAR (50)   NULL,
    [REGISTER_REMARKS]                  NVARCHAR (4000) NULL,
    [ORDER_CODE]                        NVARCHAR (50)   NULL,
    [ORDER_STATUS]                      NVARCHAR (20)   NULL,
    [DP_TO_PUBLIC_SERVICE_DATE]         DATETIME        NULL,
    [DP_TO_PUBLIC_SERVICE_AMOUNT]       DECIMAL (18, 2) NULL,
    [DP_TO_PUBLIC_SERVICE_VOUCHER]      NVARCHAR (50)   NULL,
    [REALIZATION_DATE]                  DATETIME        NULL,
    [REALIZATION_INVOICE_NO]            NVARCHAR (50)   NULL,
    [REALIZATION_INTERNAL_INCOME]       DECIMAL (18, 2) NULL,
    [REALIZATION_ACTUAL_FEE]            DECIMAL (18, 2) NULL,
    [REALIZATION_SERVICE_FEE]           DECIMAL (18, 2) NULL,
    [PUBLIC_SERVICE_SETTLEMENT_DATE]    DATETIME        NULL,
    [PUBLIC_SERVICE_SETTLEMENT_AMOUNT]  DECIMAL (18, 2) NULL,
    [PUBLIC_SERVICE_SETTLEMENT_VOUCHER] NVARCHAR (50)   NULL,
    [DELIVERY_DATE]                     DATETIME        NULL,
    [DELIVERY_RECEIVE_BY]               NVARCHAR (250)  NULL,
    [DELIVERY_REMARKS]                  NVARCHAR (4000) NULL,
    [STNK_NO]                           NVARCHAR (50)   NULL,
    [STNK_TAX_DATE]                     DATETIME        NULL,
    [STNK_EXPIRED_DATE]                 DATETIME        NULL,
    [KEUR_NO]                           NVARCHAR (50)   NULL,
    [KEUR_DATE]                         DATETIME        NULL,
    [KEUR_EXPIRED_DATE]                 DATETIME        NULL,
    [ORDER_DATE]                        DATETIME        NULL,
    [BIROJASA_CODE]                     NVARCHAR (50)   NULL,
    [BIROJASA_NAME]                     NVARCHAR (250)  NULL,
    [CRE_DATE]                          DATETIME        NULL,
    [CRE_BY]                            NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (15)   NULL,
    [MOD_DATE]                          DATETIME        NULL,
    [MOD_BY]                            NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (15)   NULL,
    [PAYMENT_STATUS]                    NVARCHAR (50)   NULL,
    [REALIZATION_PPN_PCT]               DECIMAL (9, 6)  NULL,
    [REALIZATION_PPN_AMOUNT]            DECIMAL (18, 2) NULL,
    [REALIZATION_PPH_PCT]               DECIMAL (9, 6)  NULL,
    [REALIZATION_PPH_AMOUNT]            DECIMAL (18, 2) NULL
);

