CREATE TABLE [dbo].[MIG_REGISTER_MAPPING_BY_EXCEL_PUBLIC_SERVICE_UPDATE] (
    [REGISTER_CODE]     NVARCHAR (50)  NULL,
    [NEW_BIROJASA_CODE] NVARCHAR (50)  NULL,
    [NEW_BIROJASA_NAME] NVARCHAR (250) NULL
);

