CREATE TABLE [dbo].[MIG_REGISTER_MAPPING_BY_EXCEL] (
    [CODE]               NVARCHAR (50)  NULL,
    [CHASSIS_NO]         NVARCHAR (50)  NULL,
    [ENGINE_NO]          NVARCHAR (50)  NULL,
    [PLAT_NO]            NVARCHAR (50)  NULL,
    [BIROJASA_CODE]      NVARCHAR (50)  NULL,
    [BIROJASA_NAME]      NVARCHAR (250) NULL,
    [NEW_BIROJASA_NAME]  NVARCHAR (250) NULL,
    [NEW_BIROJASA_CODE]  NVARCHAR (50)  NULL,
    [PROOF_CHANGE]       NVARCHAR (250) NULL,
    [NEW_PAYMENT_STATUS] NVARCHAR (40)  NULL
);

