CREATE TABLE [dbo].[MUTATION_DOCUMENT_HISTORY] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [MUTATION_CODE]  NVARCHAR (50)  CONSTRAINT [DF_MUTATION_DOCUMENT_HISTORY_MUTATION_CODE] DEFAULT ('') NOT NULL,
    [FILE_NAME]      NVARCHAR (250) CONSTRAINT [DF_MUTATION_DOCUMENT_HISTORY_FILE_NAME] DEFAULT ('') NULL,
    [PATH]           NVARCHAR (250) CONSTRAINT [DF_MUTATION_DOCUMENT_HISTORY_PATH] DEFAULT ('') NULL,
    [DESCRIPTION]    NVARCHAR (400) CONSTRAINT [DF_MUTATION_DOCUMENT_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [CRE_BY]         NVARCHAR (15)  NULL,
    [CRE_DATE]       DATETIME       NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NULL,
    [MOD_BY]         NVARCHAR (15)  NULL,
    [MOD_DATE]       DATETIME       NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NULL,
    CONSTRAINT [PK_MUTATION_DOCUMENT_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

