CREATE TABLE [dbo].[MUTATION_DETAIL_HISTORY] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [MUTATION_CODE]    NVARCHAR (50)   CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_MUTATION_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]       NVARCHAR (50)   CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [COST_CENTER_CODE] NVARCHAR (50)   CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_COST_CENTER_CODE] DEFAULT ('') NOT NULL,
    [COST_CENTER_NAME] NVARCHAR (250)  CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_COST_CENTER_NAME] DEFAULT ('') NOT NULL,
    [DESCRIPTION]      NVARCHAR (4000) CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [RECEIVE_DATE]     DATETIME        NULL,
    [REMARK_UNPOST]    NVARCHAR (4000) CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_REMARK_UNPOST] DEFAULT ('') NULL,
    [REMARK_RETURN]    NVARCHAR (4000) CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_REMARK_RETURN] DEFAULT ('') NULL,
    [FILE_NAME]        NVARCHAR (250)  CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_FILE_NAME] DEFAULT ('') NULL,
    [PATH]             NVARCHAR (250)  CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_PATH] DEFAULT ('') NULL,
    [STATUS_RECEIVED]  NVARCHAR (25)   CONSTRAINT [DF_MUTATION_DETAIL_HISTORY_STATUS_RECEIVED] DEFAULT ('') NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MUTATION_DETAIL_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

