CREATE TABLE [dbo].[OPNAME_HISTORY] (
    [CODE]            NVARCHAR (50)   CONSTRAINT [DF_OPNAME_HISTORY_CODE] DEFAULT ('') NOT NULL,
    [COMPANY_CODE]    NVARCHAR (50)   CONSTRAINT [DF_OPNAME_HISTORY_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [OPNAME_DATE]     DATETIME        NOT NULL,
    [BRANCH_CODE]     NVARCHAR (50)   CONSTRAINT [DF_OPNAME_HISTORY_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]     NVARCHAR (250)  CONSTRAINT [DF_OPNAME_HISTORY_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [LOCATION_CODE]   NVARCHAR (50)   CONSTRAINT [DF_OPNAME_HISTORY_LOCATION_CODE] DEFAULT ('') NOT NULL,
    [DIVISION_CODE]   NVARCHAR (50)   NOT NULL,
    [DIVISION_NAME]   NVARCHAR (100)  NOT NULL,
    [DEPARTMENT_CODE] NVARCHAR (50)   NOT NULL,
    [DEPARTMENT_NAME] NVARCHAR (100)  NOT NULL,
    [STATUS]          NVARCHAR (20)   CONSTRAINT [DF_OPNAME_HISTORY_STATUS] DEFAULT ('') NOT NULL,
    [DESCRIPTION]     NVARCHAR (4000) CONSTRAINT [DF_OPNAME_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [REMARK]          NVARCHAR (4000) CONSTRAINT [DF_OPNAME_HISTORY_REMARK] DEFAULT ('') NULL,
    [CRE_DATE]        DATETIME        NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPNAME_HISTORY] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

