CREATE TABLE [dbo].[OPNAME_DETAIL] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [OPNAME_CODE]    NVARCHAR (50)  CONSTRAINT [DF_RECON_DETAIL_RECON_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)  CONSTRAINT [DF_RECON_DETAIL_ASSET_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)  CONSTRAINT [DF_RECON_DETAIL_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250) CONSTRAINT [DF_RECON_DETAIL_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [LOCATION_CODE]  NVARCHAR (50)  CONSTRAINT [DF_RECON_DETAIL_LOCATION_CODE] DEFAULT ('') NULL,
    [CONDITION_CODE] NVARCHAR (50)  CONSTRAINT [DF_RECON_DETAIL_CONDITION_CODE] DEFAULT ('') NOT NULL,
    [LOCATION_NAME]  NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_LOCATION_CODE1] DEFAULT ('') NULL,
    [FILE_NAME]      NVARCHAR (250) NULL,
    [PATH]           NVARCHAR (250) NULL,
    [KM]             INT            NULL,
    [DATE]           DATETIME       NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_RECON_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

