CREATE TABLE [dbo].[OPNAME_DETAIL_HISTORY] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [OPNAME_CODE]     NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_OPNAME_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]      NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [STOCK]           INT            CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_STOCK] DEFAULT ((0)) NOT NULL,
    [QUANTITY]        INT            CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_QUANTITY] DEFAULT ((0)) NOT NULL,
    [DEPRE_COMERCIAL] NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_DEPRE_COMERCIAL] DEFAULT ('') NULL,
    [DEPRE_FISCAL]    NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_DEPRE_FISCAL] DEFAULT (N'''') NULL,
    [BRANCH_CODE]     NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]     NVARCHAR (250) CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_BRANCH_NAME] DEFAULT ('') NOT NULL,
    [LOCATION_CODE]   NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_LOCATION_CODE] DEFAULT ('') NOT NULL,
    [CONDITION_CODE]  NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_CONDITION_CODE] DEFAULT ('') NOT NULL,
    [LOCATION_IN]     NVARCHAR (50)  CONSTRAINT [DF_OPNAME_DETAIL_HISTORY_LOCATION_IN] DEFAULT ('') NULL,
    [FILE_NAME]       NVARCHAR (250) NULL,
    [PATH]            NVARCHAR (250) NULL,
    [CRE_DATE]        DATETIME       NOT NULL,
    [CRE_BY]          NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)  NOT NULL,
    [MOD_DATE]        DATETIME       NOT NULL,
    [MOD_BY]          NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_OPNAME_DETAIL_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

