CREATE TABLE [dbo].[ORDER_DETAIL] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [ORDER_CODE]           NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [REGISTER_CODE]        NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DP_TO_PUBLIC_SERVICE] DECIMAL (18, 2) NULL,
    [IS_REIMBURSE]         NVARCHAR (1)    NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_ORDER_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ORDER_DETAIL_ORDER_MAIN] FOREIGN KEY ([ORDER_CODE]) REFERENCES [dbo].[ORDER_MAIN] ([CODE]),
    CONSTRAINT [FK_ORDER_DETAIL_REGISTER_MAIN] FOREIGN KEY ([REGISTER_CODE]) REFERENCES [dbo].[REGISTER_MAIN] ([CODE]),
    CONSTRAINT [uq_code] UNIQUE NONCLUSTERED ([ORDER_CODE] ASC, [REGISTER_CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ORDER_DETAIL_20231120]
    ON [dbo].[ORDER_DETAIL]([ORDER_CODE] ASC);

