CREATE TABLE [dbo].[PAYMENT_TRANSACTION_DETAIL] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [PAYMENT_TRANSACTION_CODE] NVARCHAR (50)   NOT NULL,
    [PAYMENT_REQUEST_CODE]     NVARCHAR (50)   NOT NULL,
    [ORIG_CURR_CODE]           NVARCHAR (3)    NOT NULL,
    [ORIG_AMOUNT]              DECIMAL (18, 2) NOT NULL,
    [EXCH_RATE]                DECIMAL (9, 6)  NOT NULL,
    [BASE_AMOUNT]              DECIMAL (18, 2) NOT NULL,
    [TAX_AMOUNT]               DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]                 DATETIME        NULL,
    [CRE_BY]                   NVARCHAR (50)   NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (50)   NULL,
    [MOD_DATE]                 DATETIME        NULL,
    [MOD_BY]                   NVARCHAR (50)   NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (50)   NULL,
    CONSTRAINT [PK_PAYMENT_TRANSACTION_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PAYMENT_TRANSACTION_DETAIL_PAYMENT_TRANSACTION] FOREIGN KEY ([PAYMENT_TRANSACTION_CODE]) REFERENCES [dbo].[PAYMENT_TRANSACTION] ([CODE])
);


GO
CREATE NONCLUSTERED INDEX [IDX_PAYMENT_TRANSACTION_DETAIL_PAYMENT_REQUEST_CODE_20250615]
    ON [dbo].[PAYMENT_TRANSACTION_DETAIL]([PAYMENT_REQUEST_CODE] ASC)
    INCLUDE([PAYMENT_TRANSACTION_CODE]);

