CREATE TABLE [dbo].[PHYSICAL_CHECKING_SUMMARY_COP] (
    [USER_ID]            NVARCHAR (50)   NULL,
    [CODE]               NVARCHAR (50)   NULL,
    [ROW_LABEL_COP]      NVARCHAR (50)   NULL,
    [TOTAL_UNIT_COP]     INT             NULL,
    [SUM_GAINLOSS_COP]   DECIMAL (18, 2) NULL,
    [AVG_PURCHASE_COP]   DECIMAL (18, 2) NULL,
    [AVG_SOLD_PRICE_COP] DECIMAL (18, 2) NULL
);

