CREATE TABLE [dbo].[REGISTER_DETAIL] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [REGISTER_CODE]  NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SERVICE_CODE]   NVARCHAR (50) NOT NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_REGISTER_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTER_DETAIL_REGISTER_MAIN] FOREIGN KEY ([REGISTER_CODE]) REFERENCES [dbo].[REGISTER_MAIN] ([CODE])
);

