CREATE TABLE [dbo].[REGISTER_DELIVERY_DETAIL] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [DELIVERY_CODE]  NVARCHAR (50) NOT NULL,
    [REGISTER_CODE]  NVARCHAR (50) NOT NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK__REGISTER__3214EC27CC57DECF] PRIMARY KEY CLUSTERED ([ID] ASC)
);

