CREATE TABLE [dbo].[REVERSE_SALE_DETAIL_HISTORY] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [REVERSE_SALE_CODE] NVARCHAR (50)   CONSTRAINT [DF_REVERSE_SALE_DETAIL_HISTORY_REVERSE_SALE_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]        NVARCHAR (50)   CONSTRAINT [DF_REVERSE_SALE_DETAIL_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [DESCRIPTION]       NVARCHAR (250)  CONSTRAINT [DF_REVERSE_SALE_DETAIL_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [NET_BOOK_VALUE]    DECIMAL (18, 2) NULL,
    [SALE_VALUE]        DECIMAL (18, 2) CONSTRAINT [DF_REVERSE_SALE_DETAIL_HISTORY_SALE_VALUE] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [COST_CENTER_CODE]  NVARCHAR (50)   NULL,
    CONSTRAINT [PK_REVERSE_SALE_DETAIL_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

