CREATE TABLE [dbo].[REVERSE_DISPOSAL_DETAIL_HISTORY] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [REVERSE_DISPOSAL_CODE] NVARCHAR (50)   CONSTRAINT [DF_REVERSE_DISPOSAL_DETAIL_HISTORY_REVERSE_DISPOSAL_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]            NVARCHAR (50)   CONSTRAINT [DF_REVERSE_DISPOSAL_DETAIL_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [COST_CENTER_CODE]      NVARCHAR (50)   NULL,
    [COST_CENTER_NAME]      NVARCHAR (250)  NULL,
    [DESCRIPTION]           NVARCHAR (4000) CONSTRAINT [DF_REVERSE_DISPOSAL_DETAIL_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_REVERSE_DISPOSAL_DETAIL_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

