CREATE TABLE [dbo].[REVERSE_SALE_DOCUMENT] (
    [ID]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [REVERSE_SALE_CODE] NVARCHAR (50)  CONSTRAINT [DF_Table_1_SALE_CODE] DEFAULT ('') NOT NULL,
    [FILE_NAME]         NVARCHAR (250) CONSTRAINT [DF_REVERSE_SALE_DOCUMENT_FILE_NAME] DEFAULT ('') NULL,
    [PATH]              NVARCHAR (250) CONSTRAINT [DF_REVERSE_SALE_DOCUMENT_PATH] DEFAULT ('') NULL,
    [DESCRIPTION]       NVARCHAR (250) CONSTRAINT [DF_REVERSE_SALE_DOCUMENT_DESCRIPTION] DEFAULT ('') NULL,
    [CRE_BY]            NVARCHAR (15)  NOT NULL,
    [CRE_DATE]          DATETIME       NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    [MOD_BY]            NVARCHAR (15)  NOT NULL,
    [MOD_DATE]          DATETIME       NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_REVERSE_SALE_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

