CREATE TABLE [dbo].[RPT_SURAT_PERINTAH_KERJA] (
    [USER_ID]               NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]        NVARCHAR (250)  NOT NULL,
    [REPORT_ADDRESS]        NVARCHAR (250)  NULL,
    [REPORT_PHONE_NO]       NVARCHAR (50)   NULL,
    [REPORT_FAX_NO]         NVARCHAR (50)   NULL,
    [REPORT_TITLE]          NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]          NVARCHAR (250)  NOT NULL,
    [VENDOR_CODE]           NVARCHAR (50)   NULL,
    [VENDOR_NAME]           NVARCHAR (250)  NULL,
    [ADDRESS]               NVARCHAR (4000) NULL,
    [PHONE_NO]              NVARCHAR (20)   NULL,
    [SPK_NO]                NVARCHAR (50)   NULL,
    [BRANCH_CODE]           NVARCHAR (50)   NULL,
    [BRANCH_NAME]           NVARCHAR (50)   NULL,
    [DATE]                  DATETIME        NULL,
    [SERVICE]               NVARCHAR (250)  NULL,
    [QUANTITY]              INT             NULL,
    [ASSET_CODE]            NVARCHAR (50)   NULL,
    [ASSET_NAME]            NVARCHAR (250)  NULL,
    [ENGINE_NO]             NVARCHAR (50)   NULL,
    [CHASSIS_NO]            NVARCHAR (50)   NULL,
    [ACTUAL_KM]             INT             NULL,
    [PEKERJAAN]             NVARCHAR (4000) NULL,
    [UP]                    NVARCHAR (250)  NULL,
    [POLICE_NO]             NVARCHAR (50)   NULL,
    [YEAR]                  NVARCHAR (4)    NULL,
    [NAMA_SIGNER]           NVARCHAR (50)   NULL,
    [JABATAN]               NVARCHAR (250)  NULL,
    [MERK]                  NVARCHAR (250)  NULL,
    [TYPE]                  NVARCHAR (250)  NULL,
    [WARNA]                 NVARCHAR (50)   NULL,
    [WORK_DATE]             DATETIME        NULL,
    [CLIENT_NAME]           NVARCHAR (250)  NULL,
    [STATUS_MAINTENANCE]    NVARCHAR (250)  NULL,
    [PERMINTAAN_SERVICE]    NVARCHAR (250)  NULL,
    [ESTIMATED_START_DATE]  DATETIME        NULL,
    [ESTIMATED_FINISH_DATE] DATETIME        NULL,
    [LAST_SERVICE_DATE]     DATETIME        NULL,
    [LAST_KM_SERVICE]       INT             NULL
);

