CREATE TABLE [dbo].[RPT_SPPA_WITHOUT_PAYMENT_STATUS_DETAIL] (
    [USER_ID]      NVARCHAR (50)   NOT NULL,
    [NAMA_UNIT]    NVARCHAR (250)  NULL,
    [HARGA_UNIT]   DECIMAL (18, 2) NULL,
    [PERLENGKAPAN] NVARCHAR (4000) NULL,
    [AKSESORIS]    NVARCHAR (50)   NULL,
    [HARGA]        DECIMAL (18, 2) NULL,
    [TOTAL_HARGA]  DECIMAL (18, 2) NULL,
    [ASSET_CODE]   NVARCHAR (50)   NULL
);

