CREATE TABLE [dbo].[RPT_PROFITABILITY_ASSET_EXPENSE] (
    [USER_ID]                        NVARCHAR (50)   NULL,
    [KONTRAK_EXPENSE]                NVARCHAR (50)   NULL,
    [DESCRIPTION_EXPENSE]            NVARCHAR (100)  NULL,
    [INSURANCE_BUDGET_EXPENSE]       DECIMAL (18, 2) NULL,
    [INSURANCE_ACTUAL_EXPENSE]       DECIMAL (18, 2) NULL,
    [PROFIT_LOSS_ACTUAL]             DECIMAL (18, 2) NULL,
    [MAINTENANCE_BUDGET_EXPENSE]     DECIMAL (18, 2) NULL,
    [MAINTENANCE_ACTUAL_EXPENSE]     DECIMAL (18, 2) NULL,
    [MOBILIZATION_BUDGET_EXPENSE]    DECIMAL (18, 2) NULL,
    [MOBILIZATION_ACTUAL_EXPENSE]    DECIMAL (18, 2) NULL,
    [REPLACEMENT_CAR_BUDGET_EXPENSE] DECIMAL (18, 2) NULL,
    [REPLACEMENT_CAR_ACTUAL_EXPENSE] DECIMAL (18, 2) NULL,
    [STNK_KEUR_BUDGET_EXPENSE]       DECIMAL (18, 2) NULL,
    [STNK_KEUR_ACTUAL_EXPENSE]       DECIMAL (18, 2) NULL,
    [BORROW_BURGET_EXPENSE]          DECIMAL (18, 2) NULL,
    [BORROW_ACTUAL_EXPENSE]          DECIMAL (18, 2) NULL,
    [SALE_FEE_BUDGET]                DECIMAL (18, 2) NULL,
    [SALE_FEE_ACTUAL]                DECIMAL (18, 2) NULL,
    [TOTAL_BUDGET]                   DECIMAL (18, 2) NULL
);

