CREATE TABLE [dbo].[RPT_VENDOR_OPL_UI] (
    [USER_ID]          NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]   NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]     NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]     NVARCHAR (50)  NULL,
    [AS_OF_DATE]       DATETIME       NULL,
    [SUPPLIER_CODE]    NVARCHAR (50)  NULL,
    [SUPPLIER_NAME]    NVARCHAR (250) NULL,
    [SALES_DEALER]     NVARCHAR (250) NULL,
    [SALES_CONTACT_NO] NVARCHAR (50)  NULL,
    [SKD_NO]           NVARCHAR (50)  NULL,
    [ORDER_NO]         NVARCHAR (50)  NULL,
    [LESSEE]           NVARCHAR (250) NULL,
    [TYPE_ASSET]       NVARCHAR (250) NULL,
    [CHASSIS_NO]       NVARCHAR (50)  NULL,
    [ENGINE_NO]        NVARCHAR (50)  NULL,
    [STATUS_PLAT_NO]   NVARCHAR (50)  NULL,
    [EXP_DATE]         NVARCHAR (50)  NULL,
    [IS_CONDITION]     NVARCHAR (1)   NULL
);

