CREATE TABLE [dbo].[RPT_PROFITABILITY_ASSET_INCOME] (
    [USER_ID]            NVARCHAR (50)   NULL,
    [KONTRAK_INCOME]     NVARCHAR (50)   NULL,
    [DESCRIPTION_INCOME] NVARCHAR (100)  NULL,
    [BUDGET_INCOME]      DECIMAL (18, 2) NULL,
    [ACTUAL_INCOME]      DECIMAL (18, 2) NULL,
    [BUDGET_SELL]        DECIMAL (18, 2) NULL,
    [ACTUAL_SELL]        DECIMAL (18, 2) NULL
);

