CREATE TABLE [dbo].[RPT_BERITA_ACARA_STOCK_OPNAME] (
    [USER_ID]               NVARCHAR (50)   NULL,
    [FILTER_FROM_DATE]      DATETIME        NULL,
    [FILTER_TO_DATE]        DATETIME        NULL,
    [REPORT_TITLE]          NVARCHAR (250)  NULL,
    [STOCK_OPNAME_DATE]     DATETIME        NULL,
    [CUT_OFF_DATE]          DATETIME        NULL,
    [TRANSCATION_DAY]       NVARCHAR (50)   NULL,
    [TRANSCATION_DATE]      DATETIME        NULL,
    [TRANSCATION_TIME]      DATETIME        NULL,
    [PERIODE_MONTH]         NVARCHAR (25)   NULL,
    [PERIODE_YEAR]          NVARCHAR (4)    NULL,
    [DESCRIPTION]           NVARCHAR (250)  NULL,
    [KLASIFIKASI_ASSET]     NVARCHAR (50)   NULL,
    [HARGA_PEROLEHAN]       DECIMAL (18, 2) NULL,
    [HAKUMULASI_PENYUSUTAN] DECIMAL (18, 2) NULL,
    [NILAI_BUKU]            DECIMAL (18, 2) NULL,
    [JUMLAH_ASSET]          INT             NULL,
    [KETERANGAN]            NVARCHAR (250)  NULL,
    [DIBUAT_OLEH]           NVARCHAR (50)   NULL,
    [DISETUJUI_OLEH]        NVARCHAR (50)   NULL,
    [JABATAN]               NVARCHAR (50)   NULL,
    [APPROVAL_STATUS]       NVARCHAR (50)   NULL,
    [TANGGAL]               DATETIME        NULL,
    [CRE_DATE]              DATETIME        NULL,
    [CRE_BY]                NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NULL,
    [MOD_DATE]              DATETIME        NULL,
    [MOD_BY]                NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NULL
);

