CREATE TABLE [dbo].[RPT_JOURNAL_DEPRECIATION_LIST_SUMMARY] (
    [USER_ID]        NVARCHAR (50)   NULL,
    [ASSET_CODE]     NVARCHAR (50)   NULL,
    [BARCODE]        NVARCHAR (50)   NULL,
    [ASSET_NAME]     NVARCHAR (250)  NULL,
    [CATEGORY]       NVARCHAR (250)  NULL,
    [ITEM_GROUP]     NVARCHAR (250)  NULL,
    [DEPRE_DATE]     DATETIME        NULL,
    [DEPRE_ITEM]     DECIMAL (18, 2) NULL,
    [JOURNAL_ID]     NVARCHAR (50)   NULL,
    [CRE_DATE]       DATETIME        NULL,
    [CRE_BY]         NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NULL,
    [MOD_DATE]       DATETIME        NULL,
    [MOD_BY]         NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NULL
);

