CREATE TABLE [dbo].[RPT_SURAT_JALAN_DETAIL] (
    [USER_ID]   NVARCHAR (50)  NULL,
    [CODE]      NVARCHAR (50)  NULL,
    [OBJECT]    NVARCHAR (250) NULL,
    [YEAR]      NVARCHAR (4)   NULL,
    [CHASIS_NO] NVARCHAR (50)  NULL,
    [ENGINE_NO] NVARCHAR (50)  NULL,
    [PLAT_NO]   NVARCHAR (50)  NULL
);

