CREATE TABLE [dbo].[RPT_CETAKAN_PJB_BERITA_ACARA_SERAH_TERIMA_KENDARAAN] (
    [USER_ID]          NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]   NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]     NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]     NVARCHAR (250)  NOT NULL,
    [REPORT_ADDRESS]   NVARCHAR (4000) NULL,
    [CLIENT_TYPE]      NVARCHAR (50)   NULL,
    [PJB_NO]           NVARCHAR (50)   NULL,
    [HARI_PJB]         NVARCHAR (50)   NULL,
    [TANGGAL_PJB]      DATETIME        NULL,
    [DIREKTUR_NAME]    NVARCHAR (250)  NULL,
    [BUYER_NAME]       NVARCHAR (250)  NULL,
    [BUYER_ADDRESS]    NVARCHAR (4000) NULL,
    [CLIENT_NAME]      NVARCHAR (250)  NULL,
    [CLIENT_ADDRESS]   NVARCHAR (250)  NULL,
    [CLIENT_DIREKTUR]  NVARCHAR (250)  NULL,
    [JABATAN_DIREKTUR] NVARCHAR (250)  NULL
);

