CREATE TABLE [dbo].[RPT_CETAKAN_BAST] (
    [USER_ID]              NVARCHAR (50)   NULL,
    [FILTER_TYPE]          NVARCHAR (50)   NULL,
    [FILTER_AGREEMENT_NO]  NVARCHAR (50)   NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NULL,
    [NAME]                 NVARCHAR (50)   NULL,
    [DIVISI_CABANG]        NVARCHAR (50)   NULL,
    [JABATAN]              NVARCHAR (50)   NULL,
    [WILAYAH_REGION]       NVARCHAR (50)   NULL,
    [NOMOR_TELPON]         NVARCHAR (20)   NULL,
    [NAMA_ATASAN]          NVARCHAR (50)   NULL,
    [EMAIL]                NVARCHAR (50)   NULL,
    [DESCRIPTION]          NVARCHAR (250)  NULL,
    [JENIS_BARANG]         NVARCHAR (100)  NULL,
    [NO_BARCODE]           NVARCHAR (100)  NULL,
    [MERK]                 NVARCHAR (50)   NULL,
    [JENIS]                NVARCHAR (50)   NULL,
    [TYPE]                 NVARCHAR (50)   NULL,
    [JUMLAH_UNIT]          INT             NULL,
    [TAHUN]                NVARCHAR (4)    NULL,
    [JUMLAH_ASSET]         INT             NULL,
    [HARGA_PEROLEHAN]      DECIMAL (18, 2) NULL,
    [NILAL_BUKU]           DECIMAL (18, 2) NULL,
    [JENIS_KENDARAAN]      NVARCHAR (1)    NULL,
    [TAHUN_KENDARAAN]      NVARCHAR (1)    NULL,
    [NOPOL]                NVARCHAR (1)    NULL,
    [NOPOL_DESC]           NVARCHAR (50)   NULL,
    [NO_RANGKA]            NVARCHAR (1)    NULL,
    [NO_RANGKA_DESC]       NVARCHAR (50)   NULL,
    [NO_MESIN_DESC]        NVARCHAR (50)   NULL,
    [TANGGAL_PENGAJUAN]    DATETIME        NULL,
    [TANGGAL_PROSES]       DATETIME        NULL,
    [KETERANGAN]           NVARCHAR (250)  NULL,
    [INFO_LAINNYA]         NVARCHAR (250)  NULL,
    [BESAR_NILAI]          DECIMAL (18, 2) NULL,
    [JENIS_ASSET_MUTATION] NVARCHAR (50)   NULL,
    [JENIS_ASSET_DISPOSAL] NVARCHAR (50)   NULL,
    [JENIS_ASSET_SALE]     NVARCHAR (50)   NULL,
    [CRE_DATE]             DATETIME        NULL,
    [CRE_BY]               NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NULL,
    [MOD_DATE]             DATETIME        NULL,
    [MOD_BY]               NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NULL
);

