CREATE TABLE [dbo].[RPT_SPPA_WITH_PAYMENT_STATUS] (
    [USER_ID]               NVARCHAR (50)   NOT NULL,
    [SPPA_NO]               NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]        NVARCHAR (250)  NULL,
    [REPORT_TITLE]          NVARCHAR (250)  NULL,
    [REPORT_IMAGE]          NVARCHAR (250)  NULL,
    [ASURANSI_NAME]         NVARCHAR (250)  NULL,
    [NAMA_PEMOHON]          NVARCHAR (250)  NULL,
    [ALAMAT_PEMOHON]        NVARCHAR (4000) NULL,
    [NO_KONTRAK]            NVARCHAR (50)   NULL,
    [MERK]                  NVARCHAR (250)  NULL,
    [TYPE]                  NVARCHAR (250)  NULL,
    [TAHUN]                 NVARCHAR (4)    NULL,
    [NO_POLISI]             NVARCHAR (20)   NULL,
    [WARNA]                 NVARCHAR (50)   NULL,
    [NO_RANGKA]             NVARCHAR (50)   NULL,
    [NO_MESIN]              NVARCHAR (50)   NULL,
    [STATUS_PEMBAYARAN]     NVARCHAR (250)  NULL,
    [KONDISI_PERTANGGUNGAN] NVARCHAR (250)  NULL,
    [JANGKA_BULAN]          NVARCHAR (50)   NULL,
    [STAR_PERIODE_JANGKA]   NVARCHAR (50)   NULL,
    [END_PERIODE_JANGKA]    NVARCHAR (50)   NULL,
    [PERTANGGUNGAN_TAHUN1]  DECIMAL (18, 2) NULL,
    [PERTANGGUNGAN_TAHUN2]  DECIMAL (18, 2) NULL,
    [PERTANGGUNGAN_TAHUN3]  DECIMAL (18, 2) NULL,
    [PERTANGGUNGAN_TAHUN4]  DECIMAL (18, 2) NULL,
    [PERTANGGUNGAN_TAHUN5]  DECIMAL (18, 2) NULL,
    [NOTE]                  NVARCHAR (250)  NULL,
    [TPL]                   DECIMAL (18, 2) NULL,
    [PAP]                   DECIMAL (18, 2) NULL,
    [PAD]                   DECIMAL (18, 2) NULL,
    [KENDARAAN_DIGUNAKAN]   NVARCHAR (50)   NULL,
    [STATUS_OBJEK]          NVARCHAR (50)   NULL,
    [PERLENGKAPAN]          NVARCHAR (250)  NULL,
    [PRODUK]                NVARCHAR (50)   NULL,
    [STNK_ATAS_NAMA]        NVARCHAR (50)   NULL,
    [KOTA]                  NVARCHAR (50)   NULL,
    [TANGGAL]               NVARCHAR (50)   NULL,
    [EMPLOYEE_NAME]         NVARCHAR (50)   NULL,
    [ALAMAT_STNK]           NVARCHAR (250)  NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL
);

