CREATE TABLE [dbo].[RPT_SURAT_KUASA] (
    [USER_ID]                 NVARCHAR (50)   NOT NULL,
    [ORDER_NO]                NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]          NVARCHAR (250)  NULL,
    [REPORT_TITLE]            NVARCHAR (250)  NULL,
    [REPORT_IMAGE]            NVARCHAR (250)  NULL,
    [BERTANDA_TANGAN_NAMA]    NVARCHAR (250)  NULL,
    [BERTANDA_TANGAN_JABATAN] NVARCHAR (50)   NULL,
    [BERTANDA_TANGAN_ALAMAT]  NVARCHAR (4000) NULL,
    [MEMBERI_KUASA_NAMA]      NVARCHAR (250)  NULL,
    [MEMBERI_KUASA_ALAMAT]    NVARCHAR (4000) NULL,
    [STNK_NAME]               NVARCHAR (50)   NULL,
    [STNK_ADDRESS]            NVARCHAR (250)  NULL,
    [NOPOL]                   NVARCHAR (50)   NULL,
    [MERK]                    NVARCHAR (50)   NULL,
    [WARNA]                   NVARCHAR (50)   NULL,
    [NO_RANGKA]               NVARCHAR (50)   NULL,
    [NO_MESIN]                NVARCHAR (50)   NULL,
    [TAHUN]                   NVARCHAR (4)    NULL,
    [KOTA]                    NVARCHAR (50)   NULL,
    [TANGGAL]                 DATETIME        NULL,
    [PEMBERI_KUASA_NAME]      NVARCHAR (50)   NULL,
    [PEMBERI_KUASA_JABATAN]   NVARCHAR (50)   NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [REPORT_PHONE_AREA]       NVARCHAR (5)    NULL,
    [REPORT_PHONE_NO]         NVARCHAR (20)   NULL,
    [REPORT_FAX_AREA]         NVARCHAR (5)    NULL,
    [REPORT_FAX_NO]           NVARCHAR (20)   NULL,
    [SERVICE]                 NVARCHAR (250)  NULL
);

