CREATE TABLE [dbo].[RPT_PJB_BASTK] (
    [USER_ID]        NVARCHAR (50)  NOT NULL,
    [HARI]           NVARCHAR (50)  NULL,
    [TANGGAL]        NVARCHAR (50)  NULL,
    [SALE_CODE]      NVARCHAR (50)  NULL,
    [REPORT_COMPANY] NVARCHAR (50)  NULL,
    [LEASED_OBJECT]  NVARCHAR (250) NULL,
    [YEAR]           NVARCHAR (4)   NULL,
    [CHASSIS_NO]     NVARCHAR (50)  NULL,
    [PLAT_NO]        NVARCHAR (50)  NULL,
    [LEESEE_NAME]    NVARCHAR (50)  NULL,
    [LEESOR_NAME]    NVARCHAR (50)  NULL
);

