CREATE TABLE [dbo].[RPT_BERITA_ACARA_STOCK_OPNAME_TOTAL] (
    [USER_ID]               NVARCHAR (50)   NULL,
    [PERIODE_MONTH]         NVARCHAR (20)   NULL,
    [PERIODE_YEAR]          NVARCHAR (4)    NULL,
    [DESCRIPTION]           NVARCHAR (250)  NULL,
    [KLASIFIKASI_ASSET]     NVARCHAR (50)   NULL,
    [HARGA_PEROLEHAN]       DECIMAL (18, 2) NULL,
    [HAKUMULASI_PENYUSUTAN] DECIMAL (18, 2) NULL,
    [NILAI_BUKU]            DECIMAL (18, 2) NULL,
    [JUMLAH_ASSET]          INT             NULL,
    [KETERANGAN]            NVARCHAR (250)  NULL
);

