CREATE TABLE [dbo].[RPT_MONITORING_PAYMENT] (
    [USER_ID]        NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY] NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]   NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]   NVARCHAR (250)  NOT NULL,
    [FROM_DATE]      DATETIME        NULL,
    [TO_DATE]        DATETIME        NULL,
    [VENDOR_NAME]    NVARCHAR (250)  NULL,
    [PAYMENT_DATE]   DATETIME        NULL,
    [NO_KWITANSI]    NVARCHAR (50)   NULL,
    [PLAT_NO]        NVARCHAR (50)   NULL,
    [CUSTOMER]       NVARCHAR (250)  NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NULL,
    [OBJECT_LEASE]   NVARCHAR (250)  NULL,
    [CATEGORY_ASSET] NVARCHAR (4000) NULL,
    [JASA]           DECIMAL (18, 2) NULL,
    [PPH]            DECIMAL (18, 2) NULL,
    [SPARE_PART]     DECIMAL (18, 2) NULL,
    [SUB_MATERIAL]   DECIMAL (18, 2) NULL,
    [PPN]            DECIMAL (18, 2) NULL,
    [MATERIAL]       INT             NULL,
    [OTHER]          INT             NULL,
    [TOTAL]          DECIMAL (18, 2) NULL,
    [IS_CONDITION]   NVARCHAR (1)    NULL,
    [PAYMENT_NO]     NVARCHAR (50)   NULL,
    [BRAND]          NVARCHAR (250)  NULL,
    [TAHUN]          NVARCHAR (4)    NULL,
    [CHASISS_NUMBER] NVARCHAR (50)   NULL,
    [ENGINE_NUMBER]  NVARCHAR (50)   NULL,
    [ACTUAL_KM]      NVARCHAR (15)   NULL,
    [SPK_DATE]       DATETIME        NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_MONITORING_PAYMENT_USER_ID_20250615]
    ON [dbo].[RPT_MONITORING_PAYMENT]([USER_ID] ASC);

