CREATE TABLE [dbo].[RPT_ASSET_MUTATION_LIST_SUMMARY] (
    [USER_ID]                                          NVARCHAR (50)   NULL,
    [ID_OFFICE_NAME1]                                  NVARCHAR (250)  NULL,
    [NAMA_OFFICE_NAME]                                 NVARCHAR (250)  NULL,
    [KODE_ASSET]                                       NVARCHAR (50)   NULL,
    [NAMA_ASET_TETAP]                                  NVARCHAR (250)  NULL,
    [NO_REF_TO_GL]                                     NVARCHAR (50)   NULL,
    [TANGGAL_PEROLEHAN]                                DATETIME        NULL,
    [TANGGAL_AKHIR_PENYUSUTAN]                         DATETIME        NULL,
    [TANGGAL_PEROLEHAN_SETELAH_PENYESUAIAN]            DATETIME        NULL,
    [TANGGAL_AKHIR_PENYUSUTAN_SETELAH_PENYESUAIAN]     DATETIME        NULL,
    [UMUR_MANFAAT_EKONOMIS]                            INT             NULL,
    [UMUR_MANFAAT_EKONOMIS_SETELAH_PENYESUAIAN]        INT             NULL,
    [HARGA_PEROLEHAN]                                  DECIMAL (18, 2) NULL,
    [NILAI_RESIDU]                                     DECIMAL (18, 2) NULL,
    [PENYESUAIAN_HARGA_PEROLEHAN]                      DECIMAL (18, 2) NULL,
    [HARGA_PEROLEHAN_SETELAH_PENYESUAIAN]              DECIMAL (18, 2) NULL,
    [PEYUSUTAN_PER_BULAN]                              DECIMAL (18, 2) NULL,
    [AKUMULASI_PENYUSUTAN_AWAL_TAHUN]                  DECIMAL (18, 2) NULL,
    [PENYUSUTAN_TAHUN_BERJALAN]                        DECIMAL (18, 2) NULL,
    [PENYESUAIAN_PENYUSUTAN]                           DECIMAL (18, 2) NULL,
    [AKUMULASI_PENYUSUTAN_AKHIR_TAHUN]                 DECIMAL (18, 2) NULL,
    [NILAI_BUKU_AKHIR_TAHUN]                           DECIMAL (18, 2) NULL,
    [UMUR_MANFAAT_EKONOMIS_FISKAL]                     INT             NULL,
    [UMUR_MANFAAT_EKONOMIS_FISKAL_SETELAH_PENYESUAIAN] INT             NULL,
    [PENYUSUTAN_PER_BULAN_FISKAL]                      DECIMAL (18, 2) NULL,
    [AKUMULASI_PENYUSUTAN_AWAL_TAHUN_FISKAL]           DECIMAL (18, 2) NULL,
    [PENYUSUTAN_TAHUN_BERJALAN_FISKAL]                 DECIMAL (18, 2) NULL,
    [PENYESUAIAN_FISKAL]                               DECIMAL (18, 2) NULL,
    [AKUMULASI_PENYUSUTAN_AKHIR_TAHUN_FISKAL]          DECIMAL (18, 2) NULL,
    [NILAI_BUKU_AKHIR_TAHUN_FISKAL]                    DECIMAL (18, 2) NULL,
    [SELISIH_NILAI_BUKU_KOMERSIAL_DAN_FISKAL]          DECIMAL (18, 2) NULL,
    [SELISIH_PENYUSUTAN_KOMERSIAL_DAN_FISKAL]          DECIMAL (18, 2) NULL,
    [PENYUSUTAN_TAHUN_BERJALAN_NDE_FISKAL]             DECIMAL (18, 2) NULL,
    [TANGGAL_MUTASI]                                   DATETIME        NULL,
    [OFFICE_NAME_ASAL]                                 NVARCHAR (250)  NULL,
    [OFFICE_NAME_TUJUAN]                               NVARCHAR (250)  NULL,
    [CRE_DATE]                                         DATETIME        NULL,
    [CRE_BY]                                           NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]                                   NVARCHAR (15)   NULL,
    [MOD_DATE]                                         DATETIME        NULL,
    [MOD_BY]                                           NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]                                   NVARCHAR (15)   NULL
);

