CREATE TABLE [dbo].[RPT_DELIVERY_AND_COLLECT_ORDER] (
    [USER_ID]                         NVARCHAR (50)   NOT NULL,
    [REPORT_TITLE]                    NVARCHAR (50)   NULL,
    [REPORT_IMAGE]                    NVARCHAR (50)   NULL,
    [REPORT_COMPANY]                  NVARCHAR (50)   NULL,
    [REQUIREMENT]                     NVARCHAR (250)  NULL,
    [DELIVERY_COLLECT_NO]             NVARCHAR (50)   NULL,
    [DELIVERY_COLLECT_DATE]           DATETIME        NULL,
    [START_TIME]                      DATETIME        NULL,
    [FINISH_TIME]                     DATETIME        NULL,
    [CUSTOMER_SUPPLIER]               NVARCHAR (250)  NULL,
    [AGREEMENT_NO]                    NVARCHAR (50)   NULL,
    [DELIVERY_ADDRESS]                NVARCHAR (250)  NULL,
    [PIC_NAME]                        NVARCHAR (250)  NULL,
    [CONTACT_NUMBER]                  NVARCHAR (20)   NULL,
    [TYPE]                            NVARCHAR (50)   NULL,
    [POLICE_NUMBER]                   NVARCHAR (12)   NULL,
    [TIPE_UNIT]                       NVARCHAR (250)  NULL,
    [STATUS_UNIT]                     NVARCHAR (50)   NULL,
    [YEAR]                            NVARCHAR (4)    NULL,
    [COLOR]                           NVARCHAR (50)   NULL,
    [DELIVERY_PURPOSE_COLLECT_REASON] NVARCHAR (250)  NULL,
    [COLLECT_DELIVERY_BY]             NVARCHAR (50)   NULL,
    [BBM_CHARGE]                      DECIMAL (18, 2) NULL,
    [TOLL_CHARGE]                     DECIMAL (18, 2) NULL,
    [PARKING_CHARGE]                  DECIMAL (18, 2) NULL,
    [TRANSPORT_CHARGE]                DECIMAL (18, 2) NULL,
    [OTHER_COST]                      DECIMAL (18, 2) NULL,
    [CATATAN]                         NVARCHAR (4000) NULL
);

