CREATE TABLE [dbo].[RPT_EXT_DEPRE_MATURE_CONTRACT] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_TYPE]             NVARCHAR (50)   NULL,
    [AS_OF]                  DATETIME        NULL,
    [DEPRECIATION_MONTH]     NVARCHAR (7)    NULL,
    [TOTAL_UNIT]             INT             NULL,
    [DEPR_EXP_STRIGHTLINE]   DECIMAL (18, 2) NULL,
    [DEPR_ACCUM_STRIGHTLINE] DECIMAL (18, 2) NULL,
    [NET_INVESTMENT]         DECIMAL (18, 2) NULL,
    [ASSET_MODEL]            NVARCHAR (50)   NULL,
    [ASSET_BRAND]            NVARCHAR (50)   NULL,
    [SEQUENCE]               NVARCHAR (50)   NULL,
    [AGREEMENT_ID]           NVARCHAR (50)   NULL,
    [ASSET_BRAND_TYPE_NAME]  NVARCHAR (250)  NULL,
    [ASSET_BRAND_TYPE]       NVARCHAR (50)   NULL,
    [ASSET_CONDITION]        NVARCHAR (50)   NULL,
    [END_CONTRACT_MONTH]     NVARCHAR (7)    NULL,
    [CREATE_DATE]            DATETIME        NULL,
    [CREATE_TIME]            DATETIME        NULL,
    [CRE_DATE]               DATETIME        NULL,
    [CRE_BY]                 NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NULL,
    [MOD_DATE]               DATETIME        NULL,
    [MOD_BY]                 NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NULL,
    CONSTRAINT [PK__RPT_EXT___3214EC27654BD79B] PRIMARY KEY CLUSTERED ([ID] ASC)
);

