CREATE TABLE [dbo].[RPT_STATUS_PENGAJUAN_BIRO_JASA] (
    [USER_ID]           NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]    NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]      NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]      NVARCHAR (250) NOT NULL,
    [REPORT_ADDRESS]    NVARCHAR (250) NOT NULL,
    [BRANCH_NAME]       NVARCHAR (50)  NULL,
    [ASSET_NO]          NVARCHAR (50)  NULL,
    [ASSET_DESCRIPTION] NVARCHAR (500) NULL,
    [PLAT_NO]           NVARCHAR (50)  NULL,
    [CHASSIS_NO]        NVARCHAR (50)  NULL,
    [ENGINE_NO]         NVARCHAR (50)  NULL,
    [DOCUMENT_TYPE]     NVARCHAR (50)  NULL,
    [EXP_DATE]          DATETIME       NULL,
    [RENTAL_STATUS]     NVARCHAR (50)  NULL,
    [AGING_DAYS]        INT            NULL
);

