CREATE TABLE [dbo].[RPT_UTILIZATION_REPLACEMENT_CAR] (
    [USER_ID]                  NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]           NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]             NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]             NVARCHAR (50)   NULL,
    [FROM_DATE]                DATETIME        NULL,
    [TO_DATE]                  DATETIME        NULL,
    [DATEOUT]                  DATETIME        NULL,
    [INCOMING_STATUS]          NVARCHAR (50)   NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NULL,
    [STATUS_UNIT]              NVARCHAR (50)   NULL,
    [STATUS_PEMAKAIAN]         NVARCHAR (50)   NULL,
    [EX_CUSTOMER]              NVARCHAR (50)   NULL,
    [LEASED_OBJECT]            NVARCHAR (250)  NULL,
    [YEAR]                     INT             NULL,
    [CHASSIS_NO]               NVARCHAR (50)   NULL,
    [ENGINE_NO]                NVARCHAR (50)   NULL,
    [PLAT_NO]                  NVARCHAR (50)   NULL,
    [CUSTOMER_NAME]            NVARCHAR (50)   NULL,
    [IS_CONDITION]             NVARCHAR (1)    NULL,
    [REPLACEMENT_REASON]       NVARCHAR (250)  NULL,
    [DATE_IN]                  DATETIME        NULL,
    [UNIT_UTAMA_LEASED_OBJECT] NVARCHAR (250)  NULL,
    [UNIT_UTAMA_YEAR]          INT             NULL,
    [UNIT_UTAMA_CHASSIS_NO]    NVARCHAR (50)   NULL,
    [UNIT_UTAMA_ENGINE_NO]     NVARCHAR (50)   NULL,
    [UNIT_UTAMA_PLAT_NO]       NVARCHAR (50)   NULL,
    [AGING]                    INT             NULL,
    [NAMA_BENGKEL]             NVARCHAR (50)   NULL,
    [ALAMAT_BENGKEL]           NVARCHAR (250)  NULL,
    [PIC_BENGKEL]              NVARCHAR (50)   NULL,
    [PHONE_NO_BENGKEL]         NVARCHAR (20)   NULL,
    [REMARKS]                  NVARCHAR (4000) NULL
);

