CREATE TABLE [dbo].[RPT_SURAT_PERINTAH_KERJA_APPROVAL] (
    [USER_ID]           NVARCHAR (50)  NULL,
    [REFF_NO]           NVARCHAR (50)  NULL,
    [APPROVAL_CODE]     NVARCHAR (50)  NOT NULL,
    [APPROVAL_LEVEL]    INT            NOT NULL,
    [EMP_POSITION_CODE] NVARCHAR (50)  NOT NULL,
    [EMP_POSITION_NAME] NVARCHAR (250) NOT NULL,
    [EMP_CODE]          NVARCHAR (50)  NOT NULL,
    [EMP_NAME]          NVARCHAR (250) NOT NULL,
    [RESULT_STATUS]     NVARCHAR (10)  NULL,
    [RESULT_DATE]       DATETIME       NULL
);

