CREATE TABLE [dbo].[RPT_PRINT_PAJAK_INSURANCE_GROUP] (
    [USER_ID]        NVARCHAR (50) NOT NULL,
    [CRE_DATE]       DATETIME      NULL,
    [CRE_BY]         NVARCHAR (50) NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NULL,
    [MOD_DATE]       DATETIME      NULL,
    [MOD_BY]         NVARCHAR (50) NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NULL,
    [POLICY_NO]      NVARCHAR (50) NULL
);

