CREATE TABLE [dbo].[RPT_ASSET_EXCHANGE_LIST_SUMMARY] (
    [USER_ID]                                          NVARCHAR (50)   NULL,
    [ID_OFFICE_NAME1]                                  NVARCHAR (250)  NULL,
    [NAMA_OFFICE_NAME]                                 NVARCHAR (250)  NULL,
    [KODE_ASSET]                                       NVARCHAR (50)   NULL,
    [NAMA_ASET_TETAP]                                  NVARCHAR (250)  NULL,
    [NO_REF_TO_GL]                                     NVARCHAR (50)   NULL,
    [TANGGAL_PEROLEHAN]                                DATETIME        NULL,
    [TANGGAL_AKHIR_PENYUSUTAN]                         NVARCHAR (50)   NULL,
    [TANGGAL_PEROLEHAN_SETELAH_PENYESUAIAN]            DATETIME        NULL,
    [TANGGAL_AKHIR_PENYUSUTAN_SETELAH_PENYESUAIAN]     DATETIME        NULL,
    [UMUR_MANFAAT_EKONOMIS]                            NVARCHAR (50)   NULL,
    [UMUR_MANFAAT_EKONOMIS_SETELAH_PENYESUAIAN]        NVARCHAR (50)   NULL,
    [HARGA_PEROLEHAN]                                  DECIMAL (18, 2) NULL,
    [NILAI_RESIDU]                                     DECIMAL (18, 2) NULL,
    [PENYESUAIAN_HARGA_PEROLEHAN]                      DECIMAL (18, 2) NULL,
    [HARGA_PEROLEHAN_SETELAH_PENYESUAIAN]              DECIMAL (18, 2) NULL,
    [PEYUSUTAN_PER_BULAN]                              NVARCHAR (50)   NULL,
    [AKUMULASI_PENYUSUTAN_AWAL_TAHUN]                  NVARCHAR (50)   NULL,
    [PENYUSUTAN_TAHUN_BERJALAN]                        NVARCHAR (50)   NULL,
    [PENYESUAIAN_PENYUSUTAN]                           NVARCHAR (50)   NULL,
    [AKUMULASI_PENYUSUTAN_AKHIR_TAHUN]                 NVARCHAR (50)   NULL,
    [NILAI_BUKU_AKHIR_TAHUN]                           NVARCHAR (50)   NULL,
    [UMUR_MANFAAT_EKONOMIS_FISKAL]                     NVARCHAR (50)   NULL,
    [UMUR_MANFAAT_EKONOMIS_FISKAL_SETELAH_PENYESUAIAN] NVARCHAR (50)   NULL,
    [PENYUSUTAN_PER_BULAN_FISKAL]                      NVARCHAR (50)   NULL,
    [AKUMULASI_PENYUSUTAN_AWAL_TAHUN_FISKAL]           NVARCHAR (50)   NULL,
    [PENYUSUTAN_TAHUN_BERJALAN_FISKAL]                 NVARCHAR (50)   NULL,
    [PENYESUAIAN_FISKAL]                               NVARCHAR (50)   NULL,
    [AKUMULASI_PENYUSUTAN_AKHIR_TAHUN_FISKAL]          NVARCHAR (50)   NULL,
    [NILAI_BUKU_AKHIR_TAHUN_FISKAL]                    NVARCHAR (50)   NULL,
    [SELISIH_NILAI_BUKU_KOMERSIAL_DAN_FISKAL]          NVARCHAR (50)   NULL,
    [SELISIH_PENYUSUTAN_KOMERSIAL_DAN_FISKAL]          NVARCHAR (50)   NULL,
    [PENYUSUTAN_TAHUN_BERJALAN_NDE_FISKAL]             NVARCHAR (50)   NULL,
    [STATUS]                                           NVARCHAR (50)   NULL,
    [TANGGAL_PERTUKARAN_ASET]                          DATETIME        NULL,
    [KATEGORI_ASAL]                                    NVARCHAR (50)   NULL,
    [KODE_ASET_YANG_DIBERIKAN]                         NVARCHAR (50)   NULL,
    [NILAI_BUKU_ASET_YANG_DIBERIKAN_KOMERSIAL]         NVARCHAR (50)   NULL,
    [NILAI_BUKU_ASET_YANG_DIBERIKAN_FISKAL]            NVARCHAR (50)   NULL,
    [CRE_DATE]                                         DATETIME        NULL,
    [CRE_BY]                                           NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]                                   NVARCHAR (15)   NULL,
    [MOD_DATE]                                         DATETIME        NULL,
    [MOD_BY]                                           NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]                                   NVARCHAR (15)   NULL
);

