CREATE TABLE [dbo].[RPT_PA_WITH_AMORTIZATION] (
    [USER_ID]         NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]  NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]    NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]    NVARCHAR (250)  NOT NULL,
    [AS_OF_DATE]      DATETIME        NULL,
    [TYPE]            NVARCHAR (50)   NULL,
    [BRANCH_CODE]     NVARCHAR (50)   NULL,
    [BRANCH_NAME]     NVARCHAR (50)   NULL,
    [PREPAID_NO]      NVARCHAR (50)   NULL,
    [PREPAID_ACC]     NVARCHAR (50)   NULL,
    [EXPENSE_ACC]     NVARCHAR (50)   NULL,
    [DESCRIPTION]     NVARCHAR (100)  NULL,
    [AMORTIZ_BALANCE] DECIMAL (18, 2) NULL,
    [AMORTIZ_VALUE]   DECIMAL (18, 2) NULL,
    [PREPAID_AMOUNT]  DECIMAL (18, 2) NULL,
    [IS_CONDITION]    NVARCHAR (1)    NULL,
    [PREPAID_TYPE]    NVARCHAR (50)   NULL
);

