CREATE TABLE [dbo].[RPT_PENGEMBALIAN_ASSET] (
    [USER_ID]   NVARCHAR (50)   NULL,
    [CODE]      NVARCHAR (50)   NULL,
    [ITEM_NAME] NVARCHAR (250)  NULL,
    [BARCODE]   NVARCHAR (50)   NULL,
    [IMEI]      NVARCHAR (100)  NULL,
    [CONDITION] NVARCHAR (50)   NULL,
    [REMARKS]   NVARCHAR (4000) NULL,
    [TYPE_NAME] NVARCHAR (250)  NULL,
    [PLAT_NO]   NVARCHAR (20)   NULL,
    [COLOUR]    NVARCHAR (50)   NULL
);

