CREATE TABLE [dbo].[RPT_JOURNAL_DEPRECIATION_LIST_DETAIL] (
    [USER_ID]        NVARCHAR (50)   NULL,
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [BARCODE]        NVARCHAR (50)   NOT NULL,
    [ASSET_NAME]     NVARCHAR (50)   NOT NULL,
    [DEPRE_DATE]     DATETIME        NOT NULL,
    [DEPRE_ITEM]     DECIMAL (18, 2) NOT NULL,
    [CATEGORY]       NVARCHAR (50)   NOT NULL,
    [ITEM_GROUP]     NVARCHAR (50)   NOT NULL,
    [JOURNAL_ID]     NVARCHAR (50)   NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);

