CREATE TABLE [dbo].[RPT_LAPORAN_PJB] (
    [USER_ID]         NVARCHAR (50)   NOT NULL,
    [REPORT_TITLE]    NVARCHAR (50)   NULL,
    [NO_PJB]          NVARCHAR (50)   NULL,
    [TYPE_KENDARAAN]  NVARCHAR (250)  NULL,
    [TAHUN_PEMBUATAN] NVARCHAR (4)    NULL,
    [CHASSIS_NO]      NVARCHAR (50)   NULL,
    [ENGINE_NO]       NVARCHAR (50)   NULL,
    [PLAT_NO]         NVARCHAR (50)   NULL,
    [NAMA_BPKB]       NVARCHAR (50)   NULL,
    [NILAI_JUAL]      DECIMAL (18, 2) NULL
);

