CREATE TABLE [dbo].[RPT_PAYMENT_STNK_KEUR] (
    [USER_ID]        NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY] NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]   NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]   NVARCHAR (50)   NULL,
    [AS_OF_DATE]     DATETIME        NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NULL,
    [CLIENT_NAME]    NVARCHAR (250)  NULL,
    [ITEM_NAME]      NVARCHAR (250)  NULL,
    [PLAT_NO]        NVARCHAR (50)   NULL,
    [JASA]           DECIMAL (18, 2) NULL,
    [KEUR]           NVARCHAR (50)   NULL,
    [OTHER]          DECIMAL (18, 2) NULL,
    [PAJAK_STNK]     DECIMAL (18, 2) NULL,
    [PENALTY]        DECIMAL (18, 2) NULL,
    [PPH]            DECIMAL (18, 2) NULL,
    [TOTAL]          DECIMAL (18, 2) NULL,
    [PAYMENT_STATUS] NVARCHAR (50)   NULL,
    [PAYMENT_DATE]   DATETIME        NULL,
    [IS_CONDITION]   NVARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_PAYMENT_STNK_KEUR_USER_ID_20250615]
    ON [dbo].[RPT_PAYMENT_STNK_KEUR]([USER_ID] ASC);

