CREATE TABLE [dbo].[RPT_SURAT_JALAN] (
    [USER_ID]             NVARCHAR (50)   NULL,
    [REPORT_COMPANY]      NVARCHAR (250)  NULL,
    [COMPANY_ADDRESS]     NVARCHAR (4000) NULL,
    [REPORT_TITLE]        NVARCHAR (250)  NULL,
    [REPORT_IMAGE]        NVARCHAR (250)  NULL,
    [REPORT_COMPANY_CITY] NVARCHAR (50)   NULL,
    [CODE]                NVARCHAR (50)   NULL,
    [TYPE]                NVARCHAR (50)   NULL,
    [HANDOVER_FROM]       NVARCHAR (250)  NULL,
    [HANDOVER_TO]         NVARCHAR (250)  NULL,
    [HANDOVER_ADDRESS]    NVARCHAR (4000) NULL,
    [HANDOVER_PHONE_AREA] NVARCHAR (5)    NULL,
    [HANDOVER_PHONE_NO]   NVARCHAR (15)   NULL,
    [ETA_DATE]            DATETIME        NULL,
    [REMARK]              NVARCHAR (4000) NULL,
    [REFF_CODE]           NVARCHAR (50)   NULL,
    [REFF_NAME]           NVARCHAR (4000) NULL,
    [HANDOVER_CODE]       NVARCHAR (50)   NULL,
    [NEW_PAGES]           NVARCHAR (2)    NULL,
    [CRE_DATE]            DATETIME        NULL,
    [CRE_BY]              NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NULL,
    [MOD_DATE]            DATETIME        NULL,
    [MOD_BY]              NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NULL,
    [NAMA]                NVARCHAR (250)  NULL,
    [JABATAN]             NVARCHAR (250)  NULL,
    [TANGGAL]             NVARCHAR (50)   NULL,
    [REPORT_FAX]          NVARCHAR (50)   NULL,
    [REPORT_FAX_AREA]     NVARCHAR (5)    NULL,
    [REPORT_TELP]         NVARCHAR (50)   NULL,
    [REPORT_TELP_AREA]    NVARCHAR (5)    NULL,
    [PICKUP_NAME]         NVARCHAR (50)   NULL,
    [PICKUP_ADDRESS]      NVARCHAR (250)  NULL,
    [PICKUP_AREA_PHONE]   NVARCHAR (5)    NULL,
    [PICKUP_PHONE]        NVARCHAR (20)   NULL,
    [KOTA]                NVARCHAR (50)   NULL,
    [PIC_NAME]            NVARCHAR (50)   NULL,
    [PIC_AREA_PHONE]      NVARCHAR (5)    NULL,
    [PIC_PHONE_NO]        NVARCHAR (50)   NULL
);

