CREATE TABLE [dbo].[RPT_RECEIVED_ADH_COLLATERAL] (
    [USER_ID]                NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]         NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]           NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]           NVARCHAR (50)   NULL,
    [BRANCH_CODE]            NVARCHAR (50)   NULL,
    [BRANCH_NAME]            NVARCHAR (50)   NULL,
    [FROM_DATE]              DATETIME        NULL,
    [TO_DATE]                DATETIME        NULL,
    [DELIVERY_OR_COLLECT]    NVARCHAR (50)   NULL,
    [UNIT_CONDITION]         NVARCHAR (4000) NULL,
    [STATUS_PENGIRIMAN]      NVARCHAR (50)   NULL,
    [AGREEMENT_NO]           NVARCHAR (50)   NULL,
    [LESSEE]                 NVARCHAR (250)  NULL,
    [LESSEE_ADDRESS]         NVARCHAR (4000) NULL,
    [PIC_LESSEE]             NVARCHAR (250)  NULL,
    [LESSEE_CONTACT_NUMBER]  NVARCHAR (50)   NULL,
    [DESCRIPTION_UNIT_UTAMA] NVARCHAR (4000) NULL,
    [YEAR]                   INT             NULL,
    [PLAT_NO]                NVARCHAR (50)   NULL,
    [CHASSIS_NO]             NVARCHAR (50)   NULL,
    [ENGINE_NO]              NVARCHAR (50)   NULL,
    [COLOR]                  NVARCHAR (50)   NULL,
    [DELIVERY_DATE]          DATETIME        NULL,
    [BAST_DATE]              DATETIME        NULL,
    [UPLOAD_BAST_DATE]       DATETIME        NULL,
    [IS_CONDITION]           NVARCHAR (1)    NULL
);

