CREATE TABLE [dbo].[RPT_MONITORING] (
    [USER_ID]           NVARCHAR (50)  NOT NULL,
    [FILTER_ASSET_NO]   NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]    NVARCHAR (250) NULL,
    [REPORT_TITLE]      NVARCHAR (250) NULL,
    [REPORT_IMAGE]      NVARCHAR (250) NULL,
    [BRANCH_NAME]       NVARCHAR (250) NULL,
    [ASSET_NO]          NVARCHAR (50)  NULL,
    [ASSET_DESC]        NVARCHAR (250) NULL,
    [PLAT_NO]           NVARCHAR (10)  NULL,
    [CHASSIS_NO]        NVARCHAR (50)  NULL,
    [ENGINE_NO]         NVARCHAR (50)  NULL,
    [DOCUMENT_TYPE]     NVARCHAR (50)  NULL,
    [DOCUMENT_EXP_DATE] DATETIME       NULL,
    [RENTAL_STATUS]     NVARCHAR (50)  NULL,
    [AGING_DAYS]        INT            NULL,
    [CRE_DATE]          DATETIME       NOT NULL,
    [CRE_BY]            NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    [MOD_DATE]          DATETIME       NOT NULL,
    [MOD_BY]            NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)  NOT NULL
);

