CREATE TABLE [dbo].[RPT_BARCODE_LIST_QR_SELECTED] (
    [USER_ID]       NVARCHAR (250) CONSTRAINT [DF_RPT_BARCODE_LIST_QR_SELECTED_ASSET_CODE1] DEFAULT ('') NULL,
    [ASSET_CODE]    NVARCHAR (50)  CONSTRAINT [DF_RPT_BARCODE_LIST_QR_SELECTED_ASSET_CODE] DEFAULT ('') NULL,
    [ASSET_NAME]    NVARCHAR (250) CONSTRAINT [DF_RPT_BARCODE_LIST_QR_SELECTED_ASSET_NAME] DEFAULT ('') NULL,
    [BARCODE]       NVARCHAR (50)  CONSTRAINT [DF_RPT_BARCODE_LIST_QR_SELECTED_BARCODE] DEFAULT ('') NULL,
    [BARCODE_IMAGE] IMAGE          CONSTRAINT [DF_RPT_BARCODE_LIST_QR_SELECTED_BARCODE_IMAGE] DEFAULT ('') NULL
);

