CREATE TABLE [dbo].[RPT_ASSET_EXCHANGE_LIST_DETAIL] (
    [USER_ID]                                          NVARCHAR (50)   NULL,
    [ID_OFFICE_NAME1]                                  NVARCHAR (50)   NOT NULL,
    [NAMA_OFFICE_NAME]                                 NVARCHAR (50)   NOT NULL,
    [KODE_ASSET]                                       NVARCHAR (50)   NOT NULL,
    [NAMA_ASET_TETAP]                                  NVARCHAR (50)   NOT NULL,
    [CATEGORY]                                         NVARCHAR (50)   NOT NULL,
    [ITEM_GROUP]                                       NVARCHAR (50)   NOT NULL,
    [NO_REF_TO_GL]                                     NVARCHAR (50)   NOT NULL,
    [TANGGAL_PEROLEHAN]                                DATETIME        NOT NULL,
    [TANGGAL_AKHIR_PENYUSUTAN]                         NVARCHAR (50)   NOT NULL,
    [TANGGAL_PEROLEHAN_SETELAH_PENYESUAIAN]            DATETIME        NOT NULL,
    [TANGGAL_AKHIR_PENYUSUTAN_SETELAH_PENYESUAIAN]     DATETIME        NOT NULL,
    [UMUR_MANFAAT_EKONOMIS]                            INT             NOT NULL,
    [UMUR_MANFAAT_EKONOMIS_SETELAH_PENYESUAIAN]        INT             NOT NULL,
    [HARGA_PEROLEHAN]                                  DECIMAL (18, 2) NOT NULL,
    [NILAI_RESIDU]                                     DECIMAL (18, 2) NOT NULL,
    [PENYESUAIAN_HARGA_PEROLEHAN]                      DECIMAL (18, 2) NOT NULL,
    [HARGA_PEROLEHAN_SETELAH_PENYESUAIAN]              DECIMAL (18, 2) NOT NULL,
    [PEYUSUTAN_PER_BULAN]                              NVARCHAR (50)   NOT NULL,
    [AKUMULASI_PENYUSUTAN_AWAL_TAHUN]                  INT             NOT NULL,
    [PENYUSUTAN_TAHUN_BERJALAN]                        INT             NOT NULL,
    [PENYESUAIAN_PENYUSUTAN]                           NVARCHAR (50)   NOT NULL,
    [AKUMULASI_PENYUSUTAN_AKHIR_TAHUN]                 NVARCHAR (50)   NOT NULL,
    [NILAI_BUKU_AKHIR_TAHUN]                           NVARCHAR (50)   NOT NULL,
    [UMUR_MANFAAT_EKONOMIS_FISKAL]                     INT             NOT NULL,
    [UMUR_MANFAAT_EKONOMIS_FISKAL_SETELAH_PENYESUAIAN] INT             NOT NULL,
    [PENYUSUTAN_PER_BULAN_FISKAL]                      INT             NOT NULL,
    [AKUMULASI_PENYUSUTAN_AWAL_TAHUN_FISKAL]           INT             NOT NULL,
    [PENYUSUTAN_TAHUN_BERJALAN_FISKAL]                 INT             NOT NULL,
    [PENYESUAIAN_FISKAL]                               INT             NOT NULL,
    [AKUMULASI_PENYUSUTAN_AKHIR_TAHUN_FISKAL]          INT             NOT NULL,
    [NILAI_BUKU_AKHIR_TAHUN_FISKAL]                    INT             NOT NULL,
    [SELISIH_NILAI_BUKU_KOMERSIAL_DAN_FISKAL]          INT             NOT NULL,
    [SELISIH_PENYUSUTAN_KOMERSIAL_DAN_FISKAL]          INT             NOT NULL,
    [PENYUSUTAN_TAHUN_BERJALAN_NDE_FISKAL]             INT             NOT NULL,
    [STATUS]                                           NVARCHAR (50)   NOT NULL,
    [TANGGAL_PERTUKARAN_ASET]                          DATETIME        NOT NULL,
    [KATEGORI_ASAL]                                    NVARCHAR (50)   NOT NULL,
    [KODE_ASET_YANG_DIBERIKAN]                         NVARCHAR (50)   NOT NULL,
    [NILAI_BUKU_ASET_YANG_DIBERIKAN_KOMERSIAL]         NVARCHAR (50)   NOT NULL,
    [NILAI_BUKU_ASET_YANG_DIBERIKAN_FISKAL]            NVARCHAR (50)   NOT NULL,
    [CRE_DATE]                                         DATETIME        NOT NULL,
    [CRE_BY]                                           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                                   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                                         DATETIME        NOT NULL,
    [MOD_BY]                                           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                                   NVARCHAR (15)   NOT NULL
);

