CREATE TABLE [dbo].[RPT_HANDOVER] (
    [USER_ID]            NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]       NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]       NVARCHAR (250)  NOT NULL,
    [BRANCH_CODE]        NVARCHAR (50)   NULL,
    [BRANCH_NAME]        NVARCHAR (50)   NULL,
    [FROM_DATE]          DATETIME        NULL,
    [TO_DATE]            DATETIME        NULL,
    [HANDOVER_CODE]      NVARCHAR (50)   NULL,
    [TYPE]               NVARCHAR (50)   NULL,
    [ASSET_NO]           NVARCHAR (50)   NULL,
    [ASSET_DESCRIPTION]  NVARCHAR (100)  NULL,
    [PLAT_NO]            NVARCHAR (50)   NULL,
    [CHASSIS_NO]         NVARCHAR (50)   NULL,
    [ENGINE_NO]          NVARCHAR (50)   NULL,
    [HANDOVER_DATE]      DATETIME        NULL,
    [HANDOVER_FROM]      NVARCHAR (50)   NULL,
    [HANDOVER_TO]        NVARCHAR (50)   NULL,
    [HANDOVER_ADDRESS]   NVARCHAR (500)  NULL,
    [REMARKS]            NVARCHAR (4000) NULL,
    [STATUS]             NVARCHAR (50)   NULL,
    [FILTER_BRANCH_NAME] NVARCHAR (250)  NULL,
    [IS_CONDITION]       NVARCHAR (1)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_HANDOVER_USER_ID_20250615]
    ON [dbo].[RPT_HANDOVER]([USER_ID] ASC);

