CREATE TABLE [dbo].[RPT_BERITA_ACARA_SERAH_TERIMA_DOCUMENT] (
    [USER_ID]  NVARCHAR (50)   NOT NULL,
    [BAST_NO]  NVARCHAR (50)   NOT NULL,
    [DOC_NAME] NVARCHAR (250)  NOT NULL,
    [DOC_B]    NVARCHAR (1)    NOT NULL,
    [DOC_R]    NVARCHAR (1)    NOT NULL,
    [DOC_H]    NVARCHAR (1)    NOT NULL,
    [DOC_T]    NVARCHAR (1)    NOT NULL,
    [REMARK]   NVARCHAR (4000) NULL
);

