CREATE TABLE [dbo].[RPT_DEFFERED_INSURANCE_REGISTRATION] (
    [USER_ID]        NVARCHAR (50)   NOT NULL,
    [REPORT_TITLE]   NVARCHAR (50)   NULL,
    [REPORT_COMPANY] NVARCHAR (50)   NULL,
    [REPORT_IMAGE]   NVARCHAR (250)  NULL,
    [MONTH]          NVARCHAR (50)   NULL,
    [YEAR]           NVARCHAR (4)    NULL,
    [ASSET_CODE]     NVARCHAR (50)   NULL,
    [ASSET_NAME]     NVARCHAR (250)  NULL,
    [PREPAID_DATE]   NVARCHAR (50)   NULL,
    [PREPAID_TYPE]   NVARCHAR (50)   NULL,
    [PREPAID_AMOUNT] DECIMAL (18, 2) NULL,
    [PERIOD]         NVARCHAR (250)  NULL,
    [ACCRUE_AMOUNT]  DECIMAL (18, 2) NULL,
    [ACCRUE_DATE]    DATETIME        NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_DEFFERED_INSURANCE_REGISTRATION_USER_ID_20250615]
    ON [dbo].[RPT_DEFFERED_INSURANCE_REGISTRATION]([USER_ID] ASC);

