CREATE TABLE [dbo].[RPT_STATUS_PENGAJUAN_BIROJASA] (
    [USER_ID]            NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]       NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]       NVARCHAR (250) NOT NULL,
    [FILTER_ASSET_CODE]  NVARCHAR (50)  NULL,
    [FILTER_ASSET_DESC]  NVARCHAR (250) NULL,
    [FILTER_BRANCH_NAME] NVARCHAR (250) NULL,
    [BRANCH_CODE]        NVARCHAR (50)  NULL,
    [BRANCH_NAME]        NVARCHAR (50)  NULL,
    [ASSET_CODE]         NVARCHAR (50)  NULL,
    [ASSET_DESCRIPTION]  NVARCHAR (250) NULL,
    [PLAT_NO]            NVARCHAR (50)  NULL,
    [CHASSIS_NO]         NVARCHAR (50)  NULL,
    [ENGINE_NO]          NVARCHAR (50)  NULL,
    [DOCUMENT_TYPE]      NVARCHAR (50)  NULL,
    [DOC_EXP_DATE]       NVARCHAR (50)  NULL,
    [RENTAL_STATUS]      NVARCHAR (50)  NULL,
    [AGING_DAYS]         INT            NULL,
    [IS_CONDITION]       NVARCHAR (1)   NULL
);

