CREATE TABLE [dbo].[RPT_BERITA_ACARA_SERAH_TERIMA] (
    [USER_ID]              NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]         NVARCHAR (250)  NOT NULL,
    [IN_OR_OUT]            NVARCHAR (10)   NOT NULL,
    [BAST_TYPE]            NVARCHAR (50)   NOT NULL,
    [BAST_NO]              NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]         NVARCHAR (50)   NULL,
    [LEESEE]               NVARCHAR (50)   NULL,
    [ADDRESS]              NVARCHAR (250)  NULL,
    [USED_BY]              NVARCHAR (50)   NULL,
    [USED_BY_CONTACT]      NVARCHAR (50)   NULL,
    [USER_BY_PHONE]        NVARCHAR (50)   NULL,
    [PIHAK_PERTAMA]        NVARCHAR (250)  NOT NULL,
    [IMAGE_ASSET]          NVARCHAR (50)   NULL,
    [KELUAR_MASUK]         NVARCHAR (50)   NULL,
    [ALAMAT_PIHAK_PERTAMA] NVARCHAR (250)  NOT NULL,
    [NO_TLP_PIHAK_PERTAMA] NVARCHAR (15)   NOT NULL,
    [PIHAK_KEDUA]          NVARCHAR (250)  NOT NULL,
    [ALAMAT_PIHAK_KEDUA]   NVARCHAR (250)  NOT NULL,
    [NO_TLP_PIHAK_KEDUA]   NVARCHAR (15)   NOT NULL,
    [PLAT_NO]              NVARCHAR (20)   NOT NULL,
    [MERK_NAME]            NVARCHAR (250)  NOT NULL,
    [TYPE_ITEM_NAME]       NVARCHAR (250)  NOT NULL,
    [COLOUR]               NVARCHAR (50)   NOT NULL,
    [CHASSIS_NO]           NVARCHAR (50)   NOT NULL,
    [ENGINE_NO]            NVARCHAR (50)   NOT NULL,
    [BUILT_YEAR]           NVARCHAR (50)   NOT NULL,
    [UNIT_CONDITION]       NVARCHAR (4000) NOT NULL,
    [COMPANY_ADDRESS]      NVARCHAR (4000) NULL,
    [STNK_DATE]            DATETIME        NULL,
    [AREA_PHONE]           NVARCHAR (20)   NULL,
    [PHONE_NO]             NVARCHAR (20)   NULL,
    [FAX]                  NVARCHAR (20)   NULL,
    [FAX_AREA]             NVARCHAR (20)   NULL
);

