CREATE TABLE [dbo].[RPT_NILAI_WAJAR_TANAH_BANGUNAN_LIST_SUMMARY] (
    [USER_ID]                           NVARCHAR (50)   NULL,
    [LOKASI]                            NVARCHAR (250)  NULL,
    [ALAMAT]                            NVARCHAR (250)  NULL,
    [STATUS_KEPEMILIKAN]                NVARCHAR (50)   NULL,
    [NAMA_PEMEGANG_HAK]                 NVARCHAR (250)  NULL,
    [NOMOR_SERTIFIKAT]                  NVARCHAR (50)   NULL,
    [TANGGAL_SERTIFIKAT]                DATETIME        NULL,
    [JANGKA_WAKTU_AWAL_KEPEMILIKAN]     DATETIME        NULL,
    [JANGKA_WAKTU_BERAKHIR_KEPEMILIKAN] DATETIME        NULL,
    [NOMOR_HAK_TANGGUNGAN]              NVARCHAR (50)   NULL,
    [TANGGAL_TANGGUNGAN]                DATETIME        NULL,
    [NAMA_YANG_BERHAK]                  NVARCHAR (250)  NULL,
    [TANGGAL_ROYA]                      NVARCHAR (50)   NULL,
    [TAHUN_PBB]                         INT             NULL,
    [OBJEK_PAJAK]                       NVARCHAR (50)   NULL,
    [LUAS]                              INT             NULL,
    [KELAS]                             INT             NULL,
    [NJOP]                              DECIMAL (18, 2) NULL,
    [TOTAL_NJOP]                        DECIMAL (18, 2) NULL,
    [NILAI_PBB_TERUTANG]                DECIMAL (18, 2) NULL,
    [NILAI_PBB_YANG_HARUS_DIBAYAR]      DECIMAL (18, 2) NULL,
    [TANGGAL_JATUH_TEMPO_PBB]           DATETIME        NULL,
    [TANGGAL_BAYAR_PBB]                 DATETIME        NULL,
    [NOMOR_APPRAISAL]                   NVARCHAR (50)   NULL,
    [TANGGAL_APPRAISAL]                 DATETIME        NULL,
    [KJPP]                              NVARCHAR (50)   NULL,
    [NILAI_APPRAISAL]                   DECIMAL (18, 2) NULL,
    [CRE_DATE]                          DATETIME        NULL,
    [CRE_BY]                            NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (15)   NULL,
    [MOD_DATE]                          DATETIME        NULL,
    [MOD_BY]                            NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (15)   NULL
);

