CREATE TABLE [dbo].[RPT_ASSET_LIST] (
    [USER_ID]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [REGIONAL]                  NVARCHAR (250)  NULL,
    [CODE_OFFICE_NAME]          NVARCHAR (250)  NULL,
    [INITIAL_OFFICE_NAME]       NVARCHAR (250)  NULL,
    [OFFICE_FULL_NAME]          NVARCHAR (250)  NULL,
    [LOCATION]                  NVARCHAR (50)   NULL,
    [COST_CENTER]               NVARCHAR (50)   NULL,
    [CATEGORY_CODE]             NVARCHAR (50)   NULL,
    [CATEGORY_NAME]             NVARCHAR (250)  NULL,
    [ASSET_TYPE]                NVARCHAR (50)   NULL,
    [PURCHASE_DATE]             DATETIME        NULL,
    [PURCHASE_ORDER_NO]         NVARCHAR (50)   NULL,
    [BARCODE]                   NVARCHAR (50)   NULL,
    [OLD_BARCODE]               NVARCHAR (50)   NULL,
    [ITEM_GROUP]                NVARCHAR (50)   NULL,
    [ITEM_NAME]                 NVARCHAR (250)  NULL,
    [MERK]                      NVARCHAR (250)  NULL,
    [TYPE]                      NVARCHAR (250)  NULL,
    [MODEL]                     NVARCHAR (250)  NULL,
    [SERIAL_NUMBER]             NVARCHAR (50)   NULL,
    [NOMOR_RANGKA]              NVARCHAR (50)   NULL,
    [NOMOR_MESIN]               NVARCHAR (50)   NULL,
    [NOMOR_POLISI]              NVARCHAR (50)   NULL,
    [MANUFACTURING_YEARS]       NVARCHAR (50)   NULL,
    [OBJECT_INFO]               NVARCHAR (4000) NULL,
    [NIK]                       NVARCHAR (50)   NULL,
    [NAME]                      NVARCHAR (250)  NULL,
    [DIVISION]                  NVARCHAR (250)  NULL,
    [DEPARTMENT]                NVARCHAR (250)  NULL,
    [SUB_DEPARTMENT]            NVARCHAR (250)  NULL,
    [UNIT]                      NVARCHAR (250)  NULL,
    [PIC]                       NVARCHAR (50)   NULL,
    [POSITION]                  NVARCHAR (250)  NULL,
    [SUPPLIER]                  NVARCHAR (50)   NULL,
    [ORIGINAL_PRICE]            DECIMAL (18, 2) NULL,
    [FA_ADJUSTMENT_AMOUNT]      NVARCHAR (50)   NULL,
    [PURCHASE_PRICE]            DECIMAL (18, 2) NULL,
    [START_DEPRE_COMMERCIAL]    DATETIME        NULL,
    [TOTAL_DEPRE_COMMERCIAL]    DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_COMMERCIAL] DECIMAL (18, 2) NULL,
    [START_DEPRE_FISCAL]        DATETIME        NULL,
    [TOTAL_DEPRE_FISCAL]        DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_FISCAL]     DECIMAL (18, 2) NULL,
    [LAST_SO_DATE]              DATETIME        NULL,
    [LAST_SO_CONDITION]         NVARCHAR (50)   NULL,
    [STATUS_ASSET]              NVARCHAR (50)   NULL,
    [LOCATION_FROM]             NVARCHAR (50)   NULL,
    [TANGGAL_DEPRE]             DATETIME        NULL,
    [DEPRE_OR_NON_DEPRE]        NVARCHAR (50)   NULL,
    [STATUS_IN_SISTEM]          NVARCHAR (50)   NULL,
    [REMARKS]                   NVARCHAR (4000) NULL,
    [CRE_DATE]                  DATETIME        NULL,
    [CRE_BY]                    NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NULL,
    [MOD_DATE]                  DATETIME        NULL,
    [MOD_BY]                    NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_ASSET_LIST_USER_ID]
    ON [dbo].[RPT_ASSET_LIST]([USER_ID] ASC);

