CREATE TABLE [dbo].[RPT_PENJUALAN_ASSET] (
    [USER_ID]          NVARCHAR (50)   NOT NULL,
    [FILTER_FROM_DATE] DATETIME        NOT NULL,
    [FILTER_TO_DATE]   DATETIME        NOT NULL,
    [FILTER_TYPE]      NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]   NVARCHAR (250)  NULL,
    [REPORT_TITLE]     NVARCHAR (250)  NULL,
    [REPORT_IMAGE]     NVARCHAR (250)  NULL,
    [AGREEMENT_ID]     NVARCHAR (50)   NULL,
    [SEQ]              INT             NULL,
    [CUSTOMER_NAME]    NVARCHAR (250)  NULL,
    [OBJECT]           NVARCHAR (50)   NULL,
    [YEAR]             NVARCHAR (4)    NULL,
    [CHASSIS_NO]       NVARCHAR (50)   NULL,
    [ENGINE_NO]        NVARCHAR (50)   NULL,
    [PLAT_NO]          NVARCHAR (50)   NULL,
    [PURCHASE_PRICE]   DECIMAL (18, 2) NULL,
    [SOLD_PRICE]       DECIMAL (18, 2) NULL,
    [SOLD_DATE]        DATETIME        NULL,
    [BV]               DECIMAL (18, 2) NULL,
    [GAIN_OR_LOSS]     DECIMAL (18, 2) NULL,
    [PROFIT_OR_LOSS]   DECIMAL (18, 2) NULL,
    [PROSENTASE_NILAI] DECIMAL (18, 2) NULL,
    [BUYER_NAME]       NVARCHAR (250)  NULL,
    [TYPE_NAME]        NVARCHAR (50)   NULL,
    [TAHUN]            NVARCHAR (4)    NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [IS_CONDITION]     NVARCHAR (1)    NULL
);

