CREATE TABLE [dbo].[RPT_STNK_AND_KEUR] (
    [USER_ID]                      NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]               NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]                 NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]                 NVARCHAR (50)   NULL,
    [FROM_DATE]                    DATETIME        NULL,
    [TO_DATE]                      DATETIME        NULL,
    [ASSET_NO]                     NVARCHAR (50)   NULL,
    [LESSEE]                       NVARCHAR (250)  NULL,
    [BRAND]                        NVARCHAR (250)  NULL,
    [TYPE]                         NVARCHAR (250)  NULL,
    [SURAT_KUASA]                  NVARCHAR (50)   NULL,
    [OBJECT]                       NVARCHAR (250)  NULL,
    [COLOR]                        NVARCHAR (50)   NULL,
    [YEAR]                         NVARCHAR (50)   NULL,
    [CHASSIS_NO]                   NVARCHAR (50)   NULL,
    [ENGINE_NO]                    NVARCHAR (50)   NULL,
    [PLAT_NO]                      NVARCHAR (50)   NULL,
    [DELIVERY_TO_NAME]             NVARCHAR (50)   NULL,
    [END_DATE_KEUR_OR_STNK]        DATETIME        NULL,
    [AREA]                         NVARCHAR (50)   NULL,
    [ORDER_NAME]                   NVARCHAR (50)   NULL,
    [ORDER_DATE]                   DATETIME        NULL,
    [BIROJASA_NAME]                NVARCHAR (250)  NULL,
    [END_DATE_NEW]                 DATETIME        NULL,
    [DATE_OF_DELIVERY_TO_CUSTOMER] DATETIME        NULL,
    [DELIVERY_TO_ADDRESS]          NVARCHAR (250)  NULL,
    [DELIVERY_TO_PHONE_NO]         NVARCHAR (50)   NULL,
    [RECEIVED_DATE]                DATETIME        NULL,
    [IS_CONDITION]                 NVARCHAR (1)    NULL,
    [AGING]                        INT             NULL,
    [DELIVERY_BY]                  NVARCHAR (50)   NULL,
    [SERVICE_FEE_AMOUNT]           DECIMAL (18, 2) NULL,
    [ACTUAL_FEE]                   DECIMAL (18, 2) NULL,
    [PPN]                          DECIMAL (18, 2) NULL,
    [PPH]                          DECIMAL (18, 2) NULL,
    [TOTAL_AMOUNT]                 DECIMAL (18, 2) NULL,
    [STATUS]                       NVARCHAR (50)   NULL,
    [AS_OF_DATE]                   DATETIME        NULL
);

