CREATE TABLE [dbo].[RPT_MUTATION_ASSET] (
    [USER_ID]                   NVARCHAR (50)   NULL,
    [NO_1]                      INT             NULL,
    [OFFICE_NAME_ID]            NVARCHAR (250)  NULL,
    [OFFICE_NAME_INITIAL]       NVARCHAR (250)  NULL,
    [OFFICE_NAME]               NVARCHAR (250)  NULL,
    [FA_MUTATION_NO]            NVARCHAR (50)   NULL,
    [MUTATION_DATE]             DATETIME        NULL,
    [PURCHASE_DATE]             DATETIME        NULL,
    [RECEIVE_DATE]              DATETIME        NULL,
    [JURNAL_DATE]               DATETIME        NULL,
    [REMARKS]                   NVARCHAR (4000) NULL,
    [CATEGORY_CODE]             NVARCHAR (50)   NULL,
    [CATEGORY_NAME]             NVARCHAR (250)  NULL,
    [ASSET_TYPE]                NVARCHAR (50)   NULL,
    [BARCODE]                   NVARCHAR (250)  NULL,
    [ITEM_GROUP]                NVARCHAR (50)   NULL,
    [ITEM_GROUP_DESC]           NVARCHAR (250)  NULL,
    [ITEM_NAME]                 NVARCHAR (250)  NULL,
    [MERK]                      NVARCHAR (250)  NULL,
    [TYPE]                      NVARCHAR (250)  NULL,
    [MODEL]                     NVARCHAR (250)  NULL,
    [FROM_OFFICE_NAME]          NVARCHAR (250)  NULL,
    [TO_OFFICE_NAME]            NVARCHAR (250)  NULL,
    [FROM_LOCATION]             NVARCHAR (250)  NULL,
    [TO_LOCATION]               NVARCHAR (250)  NULL,
    [FROM_DIVISION]             NVARCHAR (250)  NULL,
    [TO_DIVISION]               NVARCHAR (250)  NULL,
    [FROM_DEPARTMENT]           NVARCHAR (250)  NULL,
    [TO_DEPARTMENT]             NVARCHAR (250)  NULL,
    [FROM_SUB_DEPARTMENT]       NVARCHAR (250)  NULL,
    [TO_SUB_DEPARTMENT]         NVARCHAR (250)  NULL,
    [FROM_UNIT]                 NVARCHAR (50)   NULL,
    [TO_UNIT]                   NVARCHAR (50)   NULL,
    [FROM_PIC]                  NVARCHAR (250)  NULL,
    [TO_PIC]                    NVARCHAR (250)  NULL,
    [REQUEST_OFFICE_NAME]       NVARCHAR (250)  NULL,
    [ORIGINAL_PRICE]            DECIMAL (18, 2) NULL,
    [FA_ADJUSTMENT_AMOUNT]      DECIMAL (18, 2) NULL,
    [PURCHASE_PRICE]            DECIMAL (18, 2) NULL,
    [TOTAL_DEPRE_COMMERCIAL]    DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_COMMERCIAL] DECIMAL (18, 2) NULL,
    [NO_2]                      INT             NULL,
    [OFFICE_NAME_ID_2]          NVARCHAR (250)  NULL,
    [REMARK]                    NVARCHAR (4000) NULL,
    [STATUS]                    NVARCHAR (50)   NULL,
    [RECEIPT_FROM]              NVARCHAR (50)   NULL,
    [RECEIPT_BY]                NVARCHAR (50)   NULL,
    [CRE_DATE]                  DATETIME        NULL,
    [CRE_BY]                    NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NULL,
    [MOD_DATE]                  DATETIME        NULL,
    [MOD_BY]                    NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NULL
);

