CREATE TABLE [dbo].[RPT_ASSET_PREPAID] (
    [USER_ID]              NVARCHAR (50)   NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NULL,
    [REPORT_IMAGE]         NVARCHAR (50)   NULL,
    [ASSET_CODE]           NVARCHAR (50)   NULL,
    [ASSET_NAME]           NVARCHAR (250)  NULL,
    [ASSET_STATUS]         NVARCHAR (50)   NULL,
    [FISICAL_STATUS]       NVARCHAR (50)   NULL,
    [PURCHASE_PRICE]       DECIMAL (18, 2) NULL,
    [PURCHASE_DATE]        DATETIME        NULL,
    [PREPAID_NO]           NVARCHAR (50)   NULL,
    [PREPAID_TYPE]         NVARCHAR (50)   NULL,
    [PREPAID_DATE_SCH]     DATETIME        NULL,
    [PREPAID_DATE]         DATETIME        NULL,
    [PREPAID_REMARK]       NVARCHAR (250)  NULL,
    [TOTAL_PREPAID_AMOUNT] DECIMAL (18, 2) NULL,
    [PREPAID_AMOUNT]       DECIMAL (18, 2) NULL,
    [TOTAL_ACRUE]          DECIMAL (18, 2) NULL,
    [OUTSTANDING]          DECIMAL (18, 2) NULL,
    [OS_PREPAID]           DECIMAL (18, 2) NULL,
    [ACRUE_DATE]           DATETIME        NULL,
    [REFF_NO]              NVARCHAR (50)   NULL,
    [BRANCH_NAME]          NVARCHAR (50)   NULL,
    [BRANCH_CODE]          NVARCHAR (50)   NULL,
    [IS_CONDITION]         NVARCHAR (2)    NULL,
    [PLAT_NO]              NVARCHAR (10)   NULL
);

