CREATE TABLE [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY] (
    [USER_ID]                         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ASSET_CODE]                      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BARCODE]                         NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DESKRIPSI]                       NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SALDO_AWAL]                      DECIMAL (18, 2) NULL,
    [PENAMBAHAN]                      DECIMAL (18, 2) NULL,
    [PENGURANGAN_PENJUALAN]           DECIMAL (18, 2) NULL,
    [PENGURANGAN_PEMUTIHAN]           DECIMAL (18, 2) NULL,
    [PENJABARAN_KURS]                 DECIMAL (18, 2) NULL,
    [REVALUASI]                       DECIMAL (18, 2) NULL,
    [SALDO_AKHIR]                     DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_AWAL]             DECIMAL (18, 2) NULL,
    [SALDO_AWAL_AKUMULASI]            DECIMAL (18, 2) NULL,
    [PENAMBAHAN_AKUMULASI]            DECIMAL (18, 2) NULL,
    [PENGURANGAN_PENJUALAN_AKUMULASI] DECIMAL (18, 2) NULL,
    [PENGURANGAN_PEMUTIHAN_AKUMULASI] DECIMAL (18, 2) NULL,
    [PENJABARAN_KURS_AKUMULASI]       DECIMAL (18, 2) NULL,
    [REVALUASI_AKUMULASI]             DECIMAL (18, 2) NULL,
    [SALDO_AKHIR_AKUMULASI]           DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_AKHIR]            DECIMAL (18, 2) NULL,
    [REGION_CODE]                     NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [REGION_NAME]                     NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OFFICE_CODE]                     NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OFFICE_NAME]                     NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CATEGORY_CODE]                   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CATEGORY_NAME]                   NVARCHAR (250)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ASSET_TYPE]                      NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MUTATION]                        DECIMAL (18, 2) NULL,
    [MUTATION_AKUMULASI]              DECIMAL (18, 2) NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_FIXED_ASSET_LIST_SUMMARY_USER_ID]
    ON [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY]([USER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_FIXED_ASSET_LIST_SUMMARY_USER_ID_ASSET_CODE]
    ON [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY]([USER_ID] ASC)
    INCLUDE([ASSET_CODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_FIXED_ASSET_LIST_SUMMARY_USER_ID_MUTATION]
    ON [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY]([USER_ID] ASC, [MUTATION] ASC)
    INCLUDE([ASSET_CODE], [REGION_CODE], [REGION_NAME], [OFFICE_CODE], [OFFICE_NAME]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_FIXED_ASSET_LIST_SUMMARY_USER_ID_SALDO_AWAL]
    ON [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY]([USER_ID] ASC, [SALDO_AWAL] ASC)
    INCLUDE([ASSET_CODE], [REGION_CODE], [REGION_NAME], [OFFICE_CODE], [OFFICE_NAME]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_FIXED_ASSET_LIST_SUMMARY_USER_ID_ASSET_CODE_SALDO_AWAL]
    ON [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY]([USER_ID] ASC, [ASSET_CODE] ASC, [SALDO_AWAL] ASC)
    INCLUDE([REGION_CODE], [REGION_NAME], [OFFICE_CODE], [OFFICE_NAME]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_FIXED_ASSET_LIST_SUMMARY_USERID]
    ON [dbo].[RPT_FIXED_ASSET_LIST_SUMMARY]([USER_ID] ASC)
    INCLUDE([ASSET_CODE], [BARCODE], [DESKRIPSI], [SALDO_AWAL], [PENAMBAHAN], [PENGURANGAN_PENJUALAN], [PENGURANGAN_PEMUTIHAN], [PENJABARAN_KURS], [REVALUASI], [SALDO_AKHIR], [NET_BOOK_VALUE_AWAL], [SALDO_AWAL_AKUMULASI], [PENAMBAHAN_AKUMULASI], [PENGURANGAN_PENJUALAN_AKUMULASI], [PENGURANGAN_PEMUTIHAN_AKUMULASI], [PENJABARAN_KURS_AKUMULASI], [REVALUASI_AKUMULASI], [SALDO_AKHIR_AKUMULASI], [NET_BOOK_VALUE_AKHIR], [REGION_CODE], [REGION_NAME], [OFFICE_CODE], [OFFICE_NAME], [CATEGORY_CODE], [CATEGORY_NAME], [ASSET_TYPE], [MUTATION], [MUTATION_AKUMULASI]);

