CREATE TABLE [dbo].[SALE] (
    [CODE]                            NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]                    NVARCHAR (50)   CONSTRAINT [DF_SALE_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [SALE_DATE]                       DATETIME        NOT NULL,
    [DESCRIPTION]                     NVARCHAR (4000) CONSTRAINT [DF_SALE_DESCRIPTION] DEFAULT ('') NULL,
    [BRANCH_CODE]                     NVARCHAR (50)   CONSTRAINT [DF_SALE_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]                     NVARCHAR (250)  NULL,
    [SALE_AMOUNT]                     DECIMAL (18, 2) CONSTRAINT [DF_SALE_BIDDING_PRICE] DEFAULT ((0)) NULL,
    [REMARK]                          NVARCHAR (4000) CONSTRAINT [DF_SALE_REMARK] DEFAULT ('') NULL,
    [STATUS]                          NVARCHAR (20)   CONSTRAINT [DF_SALE_STATUS] DEFAULT ('') NOT NULL,
    [SELL_TYPE]                       NVARCHAR (50)   NULL,
    [AUCTION_CODE]                    NVARCHAR (50)   NULL,
    [BUYER_NAME]                      NVARCHAR (250)  NULL,
    [CRE_DATE]                        DATETIME        NOT NULL,
    [CRE_BY]                          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                        DATETIME        NOT NULL,
    [MOD_BY]                          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                  NVARCHAR (15)   NOT NULL,
    [AUCTION_PERIOD]                  NVARCHAR (50)   NULL,
    [TOTAL_AUCTION_RECOMMENDED_PRICE] DECIMAL (18, 2) NULL,
    [TOTAL_ASSET_SELLING_PRICE]       DECIMAL (18, 2) NULL,
    [TOTAL_BOOK_VALUE]                DECIMAL (18, 2) NULL,
    [GAIN_LOSS_SELLING_ASSET]         DECIMAL (18, 2) NULL,
    [TOTAL_PROFITABILITY_ASSET]       DECIMAL (18, 2) NULL,
    [RELATED_CODE_SELL_REQ]           NVARCHAR (50)   NULL,
    [AUCTION_NOTES]                   NVARCHAR (4000) NULL,
    [CLAIM_AMOUNT]                    DECIMAL (18, 2) NULL,
    [TOTAL_ASSET_PURCHASE_PRICE]      DECIMAL (18, 2) NULL,
    [CUSTOMER_NAME]                   NVARCHAR (250)  NULL,
    CONSTRAINT [PK_SALE] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

