CREATE TABLE [dbo].[SALE_DETAIL_FEE] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [SALE_DETAIL_ID]         BIGINT          NOT NULL,
    [FEE_CODE]               NVARCHAR (50)   NOT NULL,
    [FEE_NAME]               NVARCHAR (250)  NOT NULL,
    [FEE_AMOUNT]             DECIMAL (18, 2) CONSTRAINT [DF_SALE_DETAIL_FEE_FEE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [MASTER_TAX_CODE]        NVARCHAR (50)   NULL,
    [MASTER_TAX_DESCRIPTION] NVARCHAR (4000) NULL,
    [PPH_AMOUNT]             DECIMAL (18, 2) CONSTRAINT [DF_SALE_DETAIL_FEE_PPH_AMOUNT] DEFAULT ((0)) NOT NULL,
    [MASTER_TAX_PPH_PCT]     DECIMAL (9, 6)  NULL,
    [PPN_AMOUNT]             DECIMAL (18, 2) CONSTRAINT [DF_SALE_DETAIL_FEE_PPN_AMOUNT] DEFAULT ((0)) NOT NULL,
    [MASTER_TAX_PPN_PCT]     DECIMAL (9, 6)  NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [FK_SALE_DETAIL_FEE_SALE_DETAIL] FOREIGN KEY ([SALE_DETAIL_ID]) REFERENCES [dbo].[SALE_DETAIL] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

