CREATE TABLE [dbo].[SALE_HISTORY] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]   NVARCHAR (50)   CONSTRAINT [DF_SALE_HISTORY_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [SALE_DATE]      DATETIME        NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_SALE_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [BRANCH_CODE]    NVARCHAR (50)   CONSTRAINT [DF_SALE_HISTORY_BRANCH_CODE] DEFAULT ('') NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NULL,
    [LOCATION_CODE]  NVARCHAR (50)   NOT NULL,
    [BUYER]          NVARCHAR (250)  CONSTRAINT [DF_SALE_HISTORY_BUYER] DEFAULT ('') NULL,
    [BUYER_PHONE_NO] NVARCHAR (50)   CONSTRAINT [DF_SALE_HISTORY_BUYER_PHONE_NO] DEFAULT ('') NULL,
    [SALE_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_SALE_HISTORY_SALE_AMOUNT] DEFAULT ((0)) NULL,
    [REMARK]         NVARCHAR (4000) CONSTRAINT [DF_SALE_HISTORY_REMARK] DEFAULT ('') NULL,
    [STATUS]         NVARCHAR (20)   CONSTRAINT [DF_SALE_HISTORY_STATUS] DEFAULT ('') NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_SALE_HISTORY] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

