CREATE TABLE [dbo].[SALE_ATTACHEMENT_GROUP] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [SALE_CODE]      NVARCHAR (50)   NULL,
    [DOCUMENT_CODE]  NVARCHAR (50)   CONSTRAINT [DF_SALE_ATTACHEMENT_GROUP_DOCUMENT_CODE] DEFAULT ('') NULL,
    [VALUE]          NVARCHAR (4000) CONSTRAINT [DF_Table_1_DESCRIPTION] DEFAULT ('') NULL,
    [FILE_NAME]      NVARCHAR (250)  CONSTRAINT [DF_SALE_ATTACHEMENT_GROUP_FILE_NAME] DEFAULT ('') NULL,
    [FILE_PATH]      NVARCHAR (250)  NULL,
    [DOC_FILE]       VARBINARY (MAX) NULL,
    [DOC_NO]         NVARCHAR (50)   NULL,
    [IS_REQUIRED]    NVARCHAR (1)    NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   NULL,
    CONSTRAINT [PK_SALE_ATTACHEMENT_GROUP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

