CREATE TABLE [dbo].[SALE_DETAIL_HISTORY] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [SALE_CODE]        NVARCHAR (50)   CONSTRAINT [DF_SALE_DETAIL_HISTORY_SALE_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]       NVARCHAR (50)   CONSTRAINT [DF_SALE_DETAIL_HISTORY_ASSET_CODE] DEFAULT ('') NOT NULL,
    [DESCRIPTION]      NVARCHAR (4000) CONSTRAINT [DF_SALE_DETAIL_HISTORY_DESCRIPTION] DEFAULT ('') NULL,
    [NET_BOOK_VALUE]   DECIMAL (18, 2) NULL,
    [SALE_VALUE]       DECIMAL (18, 2) CONSTRAINT [DF_SALE_DETAIL_HISTORY_SALE_VALUE] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [COST_CENTER_CODE] NVARCHAR (50)   NULL,
    [COST_CENTER_NAME] NVARCHAR (250)  NULL,
    CONSTRAINT [PK_SALE_DETAIL_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

