CREATE TABLE [dbo].[SPAF_CLAIM_DETAIL] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [SPAF_CLAIM_CODE]   NVARCHAR (50)   NOT NULL,
    [SPAF_PCT]          DECIMAL (9, 6)  NOT NULL,
    [CLAIM_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [SPAF_ASSET_CODE]   NVARCHAR (50)   NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [PPN_AMOUNT_DETAIL] DECIMAL (18, 2) NULL,
    [PPH_AMOUNT_DETAIL] DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_SPAF_CLAIM_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

