CREATE TABLE [dbo].[SURAT_PERMOHONAN_PEMBAYARAN_JASA] (
    [USER_ID]       NVARCHAR (50)   NOT NULL,
    [PART]          NVARCHAR (50)   NOT NULL,
    [SERVICE_FEE]   DECIMAL (18, 2) NOT NULL,
    [QUANTITY]      INT             NOT NULL,
    [TOTAL_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [PPH]           DECIMAL (9, 6)  NOT NULL,
    [PPN]           DECIMAL (18, 6) NOT NULL,
    [TOTAL_PAYMENT] DECIMAL (18, 2) NOT NULL
);

