CREATE TABLE [dbo].[SYS_DOCUMENT_UPLOAD] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [REFF_NO]        NVARCHAR (50)   NOT NULL,
    [REFF_NAME]      NVARCHAR (250)  NOT NULL,
    [REFF_TRX_CODE]  NVARCHAR (50)   NOT NULL,
    [FILE_NAME]      NVARCHAR (250)  NOT NULL,
    [DOC_FILE]       VARBINARY (MAX) NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_SYS_DOCUMENT_UPLOAD] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[SYS_DOCUMENT_UPLOAD_Insert_Audit] 
			ON [dbo].[SYS_DOCUMENT_UPLOAD]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_DOCUMENT_UPLOAD]
([ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_DOCUMENT_UPLOAD_Delete_Audit]    
			ON [dbo].[SYS_DOCUMENT_UPLOAD]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_DOCUMENT_UPLOAD]
([ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[SYS_DOCUMENT_UPLOAD_Update_Audit]      
			ON [dbo].[SYS_DOCUMENT_UPLOAD]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([REFF_NO]) THEN '[REFF_NO]-' ELSE '' END + 
CASE WHEN UPDATE([REFF_NAME]) THEN '[REFF_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([REFF_TRX_CODE]) THEN '[REFF_TRX_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([FILE_NAME]) THEN '[FILE_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DOC_FILE]) THEN '[DOC_FILE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_DOCUMENT_UPLOAD]
([ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_DOCUMENT_UPLOAD]
([ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[REFF_NO],[REFF_NAME],[REFF_TRX_CODE],[FILE_NAME],[DOC_FILE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END