CREATE TABLE [dbo].[TEMP_MIG_ASSET_NOPOL] (
    [ASSET_CODE]   NVARCHAR (50) NULL,
    [AGREEMENT_NO] NVARCHAR (50) NULL,
    [CHASISS_NO]   NVARCHAR (50) NULL,
    [ENGINE_NO]    NVARCHAR (50) NULL,
    [PLAT_NO]      NVARCHAR (50) NULL
);

