CREATE TABLE [dbo].[TEMP_AGRASSET_AND_ASSET] (
    [AGREEMENT_NO]          NVARCHAR (50) NULL,
    [ASSET_NO]              NVARCHAR (50) NULL,
    [ASSET_CODE]            NVARCHAR (50) NULL,
    [ASSET_STATUS_BEFORE]   NVARCHAR (50) NULL,
    [STATUS_BEFORE]         NVARCHAR (50) NULL,
    [RENTAL_STATUS_BEFORE]  NVARCHAR (50) NULL,
    [FISICAL_STATUS_BEFORE] NVARCHAR (50) NULL,
    [CHASISS_NO]            NVARCHAR (50) NULL,
    [ENGINE_NO]             NVARCHAR (50) NULL,
    [PLAT_NO]               NVARCHAR (50) NULL,
    [ASSET_STATUS_AFTER]    NVARCHAR (50) NULL,
    [STATUS_AFTER]          NVARCHAR (50) NULL,
    [RENTAL_STATUS_AFTER]   NVARCHAR (50) NULL,
    [FISICAL_STATUS_AFTER]  NVARCHAR (50) NULL
);

