CREATE TABLE [dbo].[TERMINATION_DETAIL_ASSET] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [TERMINATION_CODE]       NVARCHAR (50)   NOT NULL,
    [POLICY_ASSET_CODE]      NVARCHAR (50)   NULL,
    [ESTIMATE_REFUND_AMOUNT] DECIMAL (18, 2) NULL,
    [REFUND_AMOUNT]          DECIMAL (18, 2) NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_TERMINATION_DETAIL_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC)
);

