CREATE TABLE [dbo].[UPLOAD_ASSET] (
    [UPLOAD_NO]      NVARCHAR (50) NOT NULL,
    [COMPANY_CODE]   NVARCHAR (50) NOT NULL,
    [ASSET_TYPE]     NVARCHAR (50) NULL,
    [DATE]           DATETIME      NULL,
    [STATUS_UPLOAD]  NVARCHAR (20) CONSTRAINT [DF_Table_1_STATUS] DEFAULT ('') NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_UPLOAD_ASSET] PRIMARY KEY CLUSTERED ([UPLOAD_NO] ASC)
);

