CREATE TABLE [dbo].[WORK_ORDER] (
    [CODE]                     NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]             NVARCHAR (50)   CONSTRAINT [DF_WORK_ORDER_COMPANY_CODE] DEFAULT ('') NOT NULL,
    [ASSET_CODE]               NVARCHAR (50)   CONSTRAINT [DF_WORK_ORDER_ASSET_CODE] DEFAULT ('') NOT NULL,
    [MAINTENANCE_CODE]         NVARCHAR (50)   CONSTRAINT [DF_WORK_ORDER_MAINTENANCE_CODE] DEFAULT ('') NOT NULL,
    [MAINTENANCE_BY]           NVARCHAR (50)   CONSTRAINT [DF_WORK_ORDER_MAINTENANCE_BY] DEFAULT ('') NOT NULL,
    [STATUS]                   NVARCHAR (20)   CONSTRAINT [DF_WORK_ORDER_STATUS] DEFAULT ('') NOT NULL,
    [TOTAL_AMOUNT]             DECIMAL (18, 2) NULL,
    [TOTAL_PPN_AMOUNT]         DECIMAL (18, 2) NULL,
    [TOTAL_PPH_AMOUNT]         DECIMAL (18, 2) NULL,
    [PAYMENT_AMOUNT]           DECIMAL (18, 2) NULL,
    [REMARK]                   NVARCHAR (4000) CONSTRAINT [DF_WORK_ORDER_STATUS1] DEFAULT ('') NOT NULL,
    [INVOICE_NO]               NVARCHAR (50)   NULL,
    [FAKTUR_NO]                NVARCHAR (50)   NULL,
    [PAID_DATE]                DATETIME        NULL,
    [PAID_REFF_NO]             NVARCHAR (50)   NULL,
    [FILE_NAME]                NVARCHAR (250)  NULL,
    [FILE_PATH]                NVARCHAR (250)  NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [FAKTUR_DATE]              DATETIME        NULL,
    [WORK_DATE]                DATETIME        NULL,
    [ACTUAL_KM]                INT             NULL,
    [LAST_KM_SERVICE]          INT             NULL,
    [PROCED_BY]                NVARCHAR (50)   NULL,
    [IS_CLAIM_APPROVE]         NVARCHAR (1)    NULL,
    [CLAIM_APPROVE_CLAIM_DATE] DATETIME        NULL,
    [INVOICE_DATE]             DATETIME        NULL,
    [LAST_METER]               INT             NULL,
    [IS_SAVE_PRINT]            NVARCHAR (1)    NULL,
    [RETURN_REASON]            NVARCHAR (4000) NULL,
    CONSTRAINT [PK_WORK_ORDER] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_WORK_ORDER_20230831]
    ON [dbo].[WORK_ORDER]([ASSET_CODE] ASC)
    INCLUDE([COMPANY_CODE], [MAINTENANCE_CODE], [MAINTENANCE_BY], [STATUS], [PAYMENT_AMOUNT], [REMARK]);


GO
CREATE NONCLUSTERED INDEX [IDX_WORK_ORDER_20240104]
    ON [dbo].[WORK_ORDER]([MAINTENANCE_CODE] ASC)
    INCLUDE([PAYMENT_AMOUNT]);

