CREATE TABLE [dbo].[XXX_PAYMENT_REQUEST_DETAIL_20240419] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [PAYMENT_REQUEST_CODE]     NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [GL_LINK_CODE]             NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NOT NULL,
    [FACILITY_CODE]            NVARCHAR (50)   NOT NULL,
    [FACILITY_NAME]            NVARCHAR (250)  NOT NULL,
    [PURPOSE_LOAN_CODE]        NVARCHAR (50)   NOT NULL,
    [PURPOSE_LOAN_NAME]        NVARCHAR (250)  NOT NULL,
    [PURPOSE_LOAN_DETAIL_CODE] NVARCHAR (250)  NOT NULL,
    [PURPOSE_LOAN_DETAIL_NAME] NVARCHAR (50)   NOT NULL,
    [ORIG_CURRENCY_CODE]       NVARCHAR (3)    NOT NULL,
    [EXCH_RATE]                DECIMAL (9, 6)  NOT NULL,
    [ORIG_AMOUNT]              DECIMAL (18, 2) NOT NULL,
    [DIVISION_CODE]            NVARCHAR (50)   NOT NULL,
    [DIVISION_NAME]            NVARCHAR (250)  NOT NULL,
    [DEPARTMENT_CODE]          NVARCHAR (50)   NOT NULL,
    [DEPARTMENT_NAME]          NVARCHAR (250)  NOT NULL,
    [REMARKS]                  NVARCHAR (4000) NOT NULL,
    [IS_TAXABLE]               NVARCHAR (1)    NOT NULL,
    [TAX_AMOUNT]               DECIMAL (18, 2) NOT NULL,
    [TAX_PCT]                  DECIMAL (9, 6)  NOT NULL,
    [CRE_DATE]                 DATETIME        NULL,
    [CRE_BY]                   NVARCHAR (50)   NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (50)   NULL,
    [MOD_DATE]                 DATETIME        NULL,
    [MOD_BY]                   NVARCHAR (50)   NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (50)   NULL,
    [EXT_PPH_TYPE]             NVARCHAR (20)   NULL,
    [EXT_VENDOR_CODE]          NVARCHAR (50)   NULL,
    [EXT_VENDOR_NAME]          NVARCHAR (250)  NULL,
    [EXT_VENDOR_NPWP]          NVARCHAR (20)   NULL,
    [EXT_VENDOR_ADDRESS]       NVARCHAR (4000) NULL,
    [EXT_INCOME_TYPE]          NVARCHAR (250)  NULL,
    [EXT_INCOME_BRUTO_AMOUNT]  DECIMAL (18, 2) NULL,
    [EXT_TAX_RATE_PCT]         DECIMAL (5, 2)  NULL,
    [EXT_PPH_AMOUNT]           DECIMAL (18, 2) NULL,
    [EXT_DESCRIPTION]          NVARCHAR (4000) NULL,
    [EXT_TAX_NUMBER]           NVARCHAR (50)   NULL,
    [EXT_SALE_TYPE]            NVARCHAR (10)   NULL,
    [EXT_TAX_DATE]             DATETIME        NULL
);

