CREATE TABLE [dbo].[XXX_SALE_20241031] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]   NVARCHAR (50)   NOT NULL,
    [SALE_DATE]      DATETIME        NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NULL,
    [SALE_AMOUNT]    DECIMAL (18, 2) NULL,
    [REMARK]         NVARCHAR (4000) NULL,
    [STATUS]         NVARCHAR (20)   NOT NULL,
    [SELL_TYPE]      NVARCHAR (50)   NULL,
    [AUCTION_CODE]   NVARCHAR (50)   NULL,
    [BUYER_NAME]     NVARCHAR (250)  NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);

