CREATE TABLE [dbo].[XXX_REGISTER_MAIN_06112023] (
    [CODE]                              NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [BRANCH_CODE]                       NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                       NVARCHAR (250)  NOT NULL,
    [FA_CODE]                           NVARCHAR (50)   NOT NULL,
    [REGISTER_NO]                       NVARCHAR (50)   NOT NULL,
    [REGISTER_DATE]                     DATETIME        NOT NULL,
    [REGISTER_STATUS]                   NVARCHAR (20)   NOT NULL,
    [REGISTER_PROCESS_BY]               NVARCHAR (50)   NOT NULL,
    [REGISTER_REMARKS]                  NVARCHAR (4000) NOT NULL,
    [IS_REIMBURSE]                      NVARCHAR (1)    NULL,
    [ORDER_CODE]                        NVARCHAR (50)   NULL,
    [ORDER_STATUS]                      NVARCHAR (20)   NULL,
    [DP_TO_PUBLIC_SERVICE_DATE]         DATETIME        NULL,
    [DP_TO_PUBLIC_SERVICE_AMOUNT]       DECIMAL (18, 2) NULL,
    [DP_TO_PUBLIC_SERVICE_VOUCHER]      NVARCHAR (50)   NULL,
    [REALIZATION_DATE]                  DATETIME        NULL,
    [REALIZATION_INVOICE_NO]            NVARCHAR (50)   NOT NULL,
    [REALIZATION_INTERNAL_INCOME]       DECIMAL (18, 2) NOT NULL,
    [REALIZATION_ACTUAL_FEE]            DECIMAL (18, 2) NOT NULL,
    [REALIZATION_SERVICE_FEE]           DECIMAL (18, 2) NOT NULL,
    [REALIZATION_SERVICE_TAX_CODE]      NVARCHAR (50)   NULL,
    [REALIZATION_SERVICE_TAX_NAME]      NVARCHAR (250)  NULL,
    [REALIZATION_SERVICE_TAX_PPN_PCT]   DECIMAL (9, 6)  NULL,
    [REALIZATION_SERVICE_TAX_PPH_PCT]   DECIMAL (9, 6)  NULL,
    [PAYMENT_BANK_NAME]                 NVARCHAR (250)  NULL,
    [PAYMENT_BANK_ACCOUNT_NO]           NVARCHAR (50)   NULL,
    [PAYMENT_BANK_ACCOUNT_NAME]         NVARCHAR (250)  NULL,
    [PUBLIC_SERVICE_SETTLEMENT_DATE]    DATETIME        NULL,
    [PUBLIC_SERVICE_SETTLEMENT_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [PUBLIC_SERVICE_SETTLEMENT_VOUCHER] NVARCHAR (50)   NULL,
    [RECEIVE_DATE]                      DATETIME        NULL,
    [RECEIVE_BY]                        NVARCHAR (250)  NULL,
    [RECEIVE_REMARKS]                   NVARCHAR (4000) NULL,
    [STNK_NO]                           NVARCHAR (50)   NULL,
    [STNK_TAX_DATE]                     DATETIME        NULL,
    [STNK_EXPIRED_DATE]                 DATETIME        NULL,
    [KEUR_NO]                           NVARCHAR (50)   NULL,
    [KEUR_DATE]                         DATETIME        NULL,
    [KEUR_EXPIRED_DATE]                 DATETIME        NULL,
    [DELIVERY_DATE]                     DATETIME        NULL,
    [DELIVERY_RECEIVE_BY]               NVARCHAR (250)  NULL,
    [DELIVERY_REMARKS]                  NVARCHAR (4000) NULL,
    [FAKTUR_NO]                         NVARCHAR (50)   NULL,
    [CRE_DATE]                          DATETIME        NOT NULL,
    [CRE_BY]                            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                          DATETIME        NOT NULL,
    [MOD_BY]                            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (15)   NOT NULL,
    [PAYMENT_STATUS]                    NVARCHAR (50)   NULL,
    [FILE_NAME]                         NVARCHAR (250)  NULL,
    [PATHS]                             NVARCHAR (250)  NULL,
    [DELIVERY_TO_NAME]                  NVARCHAR (250)  NULL,
    [DELIVERY_TO_PHONE_AREA]            NVARCHAR (4)    NULL,
    [DELIVERY_TO_PHONE_NO]              NVARCHAR (15)   NULL,
    [DELIVERY_TO_ADDRESS]               NVARCHAR (4000) NULL
);

