CREATE TABLE [dbo].[XXX_REGISTER_INVOICE_TAX] (
    [PAYMENT_STATUS]       NVARCHAR (50) NOT NULL,
    [PAYMENT_REQUEST_CODE] NVARCHAR (50) NOT NULL,
    [CODE]                 NVARCHAR (50) NOT NULL,
    [PAYMENT_SOURCE_NO]    NVARCHAR (50) NOT NULL,
    [AGREEMENT_NO]         NVARCHAR (50) NULL,
    [INVOICE]              NVARCHAR (50) NULL
);

