CREATE TABLE [dbo].[XXX_ASSET_DEPRECIATION_SCHEDULE_FISCAL_20250831BEFOREEOM] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]          NVARCHAR (50)   NOT NULL,
    [DEPRECIATION_DATE]   DATETIME        NOT NULL,
    [ORIGINAL_PRICE]      DECIMAL (18, 2) NOT NULL,
    [DEPRECIATION_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [ACCUM_DEPRE_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [NET_BOOK_VALUE]      DECIMAL (18, 2) NOT NULL,
    [TRANSACTION_CODE]    NVARCHAR (50)   NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NULL
);

