CREATE TABLE [dbo].[XXX_ASSET_GPS_ISSUE] (
    [CODE]                  NVARCHAR (50)   NULL,
    [PURCHASE_PRICE]        DECIMAL (18, 2) NULL,
    [RESIDUAL_VALUE]        DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_COMM]   DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_FISCAL] DECIMAL (18, 2) NULL,
    [TOTAL_DEPRE_COMM]      DECIMAL (18, 2) NULL,
    [TOTAL_DEPRE_FISCAL]    DECIMAL (18, 2) NULL
);

