CREATE TABLE [dbo].[XXX_INSURANCE_POLICY_MAIN_20240122] (
    [CODE]                   NVARCHAR (50)   NOT NULL,
    [SPPA_CODE]              NVARCHAR (50)   NULL,
    [REGISTER_CODE]          NVARCHAR (50)   NULL,
    [BRANCH_CODE]            NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]            NVARCHAR (250)  NOT NULL,
    [SOURCE_TYPE]            NVARCHAR (20)   NULL,
    [POLICY_STATUS]          NVARCHAR (10)   NOT NULL,
    [POLICY_PAYMENT_STATUS]  NVARCHAR (10)   NOT NULL,
    [INSURED_NAME]           NVARCHAR (250)  NOT NULL,
    [INSURED_QQ_NAME]        NVARCHAR (250)  NOT NULL,
    [POLICY_PAYMENT_TYPE]    NVARCHAR (5)    NOT NULL,
    [OBJECT_NAME]            NVARCHAR (4000) NOT NULL,
    [INSURANCE_CODE]         NVARCHAR (50)   NOT NULL,
    [INSURANCE_TYPE]         NVARCHAR (10)   NOT NULL,
    [CURRENCY_CODE]          NVARCHAR (3)    NOT NULL,
    [COVER_NOTE_NO]          NVARCHAR (50)   NULL,
    [COVER_NOTE_DATE]        DATETIME        NULL,
    [POLICY_NO]              NVARCHAR (50)   NULL,
    [POLICY_EFF_DATE]        DATETIME        NULL,
    [POLICY_EXP_DATE]        DATETIME        NULL,
    [EFF_RATE]               DECIMAL (9, 6)  NULL,
    [FILE_NAME]              NVARCHAR (250)  NULL,
    [PATHS]                  NVARCHAR (250)  NULL,
    [DOC_FILE]               VARBINARY (MAX) NULL,
    [INVOICE_NO]             NVARCHAR (50)   NULL,
    [INVOICE_DATE]           DATETIME        NULL,
    [FAKTUR_NO]              NVARCHAR (50)   NULL,
    [FROM_YEAR]              INT             NOT NULL,
    [TO_YEAR]                INT             NOT NULL,
    [TOTAL_PREMI_BUY_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [TOTAL_DISCOUNT_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [TOTAL_NET_PREMI_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [STAMP_FEE_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [ADMIN_FEE_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [TOTAL_ADJUSMENT_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [IS_POLICY_EXISTING]     NVARCHAR (1)    NOT NULL,
    [ENDORSEMENT_COUNT]      INT             NOT NULL,
    [POLICY_PROCESS_STATUS]  NVARCHAR (20)   NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [FAKTUR_DATE]            DATETIME        NULL
);

