CREATE TABLE [dbo].[XXX_INSURANCE_POLICY_MAIN_PERIOD_21082024] (
    [CODE]              NVARCHAR (50)   NOT NULL,
    [POLICY_CODE]       NVARCHAR (50)   NOT NULL,
    [RATE_DEPRECIATION] DECIMAL (9, 6)  NOT NULL,
    [COVERAGE_CODE]     NVARCHAR (50)   NOT NULL,
    [IS_MAIN_COVERAGE]  NVARCHAR (1)    NULL,
    [YEAR_PERIODE]      INT             NOT NULL,
    [BUY_AMOUNT]        DECIMAL (18, 2) NOT NULL,
    [DISCOUNT_PCT]      DECIMAL (9, 6)  NOT NULL,
    [DISCOUNT_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [ADMIN_FEE_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [STAMP_FEE_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [ADJUSTMENT_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [TOTAL_BUY_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL
);

