CREATE TABLE [dbo].[XXX_SALE_DETAIL_20241129] (
    [ID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [SALE_CODE]                 NVARCHAR (50)   NOT NULL,
    [ASSET_CODE]                NVARCHAR (50)   NOT NULL,
    [GL_ASSET_CODE]             NVARCHAR (50)   NULL,
    [DESCRIPTION]               NVARCHAR (4000) NULL,
    [NET_BOOK_VALUE]            DECIMAL (18, 2) NULL,
    [TOTAL_FEE_AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [TOTAL_PPH_AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [TOTAL_PPN_AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [GAIN_LOSS]                 DECIMAL (18, 2) NOT NULL,
    [IS_SOLD]                   NVARCHAR (1)    NULL,
    [IS_UNIT_OUT]               NVARCHAR (1)    NULL,
    [SALE_DATE]                 DATETIME        NULL,
    [SALE_REMARK]               NVARCHAR (4000) NULL,
    [SALE_DETAIL_STATUS]        NVARCHAR (50)   NULL,
    [SOLD_AMOUNT]               DECIMAL (18, 2) NULL,
    [NET_RECEIVE]               DECIMAL (18, 2) NULL,
    [GAIN_LOSS_PROFIT]          DECIMAL (18, 2) NULL,
    [SELL_REQUEST_AMOUNT]       DECIMAL (18, 2) NULL,
    [TOTAL_INCOME]              DECIMAL (18, 2) NULL,
    [TOTAL_EXPENSE]             DECIMAL (18, 2) NULL,
    [PPN_ASSET]                 DECIMAL (18, 2) NULL,
    [BUYER_TYPE]                NVARCHAR (15)   NULL,
    [BUYER_NAME]                NVARCHAR (250)  NULL,
    [BUYER_AREA_PHONE]          NVARCHAR (4)    NULL,
    [BUYER_AREA_PHONE_NO]       NVARCHAR (15)   NULL,
    [BUYER_ADDRESS]             NVARCHAR (4000) NULL,
    [KTP_NO]                    NVARCHAR (17)   NULL,
    [FILE_NAME]                 NVARCHAR (250)  NULL,
    [FILE_PATH]                 NVARCHAR (250)  NULL,
    [PJB_NO]                    NVARCHAR (50)   NULL,
    [BAST_NO]                   NVARCHAR (50)   NULL,
    [CRE_DATE]                  DATETIME        NOT NULL,
    [CRE_BY]                    NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                  DATETIME        NOT NULL,
    [MOD_BY]                    NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    [BUYER_NPWP]                NVARCHAR (15)   NULL,
    [BUYER_SIGNER_NAME]         NVARCHAR (50)   NULL,
    [FAKTUR_NO]                 NVARCHAR (20)   NULL,
    [BORROWING_INTEREST_AMOUNT] DECIMAL (18, 2) NULL,
    [FAKTUR_DATE]               DATETIME        NULL,
    [PRINT_COUNT]               INT             NULL,
    [ASSET_FAKTUR_NO]           NVARCHAR (50)   NULL,
    [ASSET_INVOICE_NO]          NVARCHAR (50)   NULL
);

