CREATE TABLE [dbo].[XXX_ASSET_DOCUMENT_07112023] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   NULL,
    [DOCUMENT_CODE]  NVARCHAR (50)   NULL,
    [DOCUMENT_NO]    NVARCHAR (50)   NULL,
    [DESCRIPTION]    NVARCHAR (4000) NULL,
    [FILE_NAME]      NVARCHAR (250)  NULL,
    [PATH]           NVARCHAR (250)  NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);

