CREATE TABLE [dbo].[XXX_ASSET_PREPAID_MAIN_20240103] (
    [PREPAID_NO]           NVARCHAR (50)   NOT NULL,
    [FA_CODE]              NVARCHAR (50)   NOT NULL,
    [PREPAID_DATE]         DATETIME        NULL,
    [PREPAID_REMARK]       NVARCHAR (250)  NOT NULL,
    [PREPAID_TYPE]         NVARCHAR (15)   NULL,
    [MONTHLY_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [TOTAL_PREPAID_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [TOTAL_ACCRUE_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [LAST_ACCUE_PERIOD]    NVARCHAR (6)    NOT NULL,
    [REFF_NO]              NVARCHAR (50)   NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL
);

