CREATE TABLE [dbo].[XXX_MASTER_REGION_CITY_22082024] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [REGION_CODE]    NVARCHAR (50)  NOT NULL,
    [CITY_CODE]      NVARCHAR (50)  NOT NULL,
    [CITY_NAME]      NVARCHAR (250) NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL
);

