CREATE TABLE [dbo].[XXX_INSURANCE_POLICY_MAIN_HISTORY_21082024] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [POLICY_CODE]     NVARCHAR (50)   NOT NULL,
    [HISTORY_DATE]    DATETIME        NOT NULL,
    [HISTORY_TYPE]    NVARCHAR (50)   NOT NULL,
    [POLICY_STATUS]   NVARCHAR (20)   NOT NULL,
    [HISTORY_REMARKS] NVARCHAR (4000) NOT NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL
);

