CREATE TABLE [dbo].[XXX_ASSET_VEHICLE_20250617] (
    [ASSET_CODE]        NVARCHAR (50)   NOT NULL,
    [MERK_CODE]         NVARCHAR (50)   NULL,
    [MERK_NAME]         NVARCHAR (250)  NULL,
    [TYPE_ITEM_CODE]    NVARCHAR (50)   NULL,
    [TYPE_ITEM_NAME]    NVARCHAR (250)  NULL,
    [MODEL_CODE]        NVARCHAR (50)   NULL,
    [MODEL_NAME]        NVARCHAR (250)  NULL,
    [PLAT_NO]           NVARCHAR (20)   NULL,
    [CHASSIS_NO]        NVARCHAR (50)   NULL,
    [ENGINE_NO]         NVARCHAR (50)   NULL,
    [BPKB_NO]           NVARCHAR (50)   NULL,
    [COLOUR]            NVARCHAR (50)   NULL,
    [CYLINDER]          NVARCHAR (20)   NULL,
    [STNK_NO]           NVARCHAR (50)   NULL,
    [STNK_EXPIRED_DATE] DATETIME        NULL,
    [STNK_TAX_DATE]     DATETIME        NULL,
    [STNK_RENEWAL]      NVARCHAR (15)   NULL,
    [KEUR_NO]           NVARCHAR (50)   NULL,
    [KEUR_DATE]         DATETIME        NULL,
    [KEUR_EXPIRED_DATE] DATETIME        NULL,
    [BUILT_YEAR]        NVARCHAR (4)    NULL,
    [REMARK]            NVARCHAR (4000) NULL,
    [STNK_NAME]         NVARCHAR (50)   NULL,
    [STNK_DATE]         DATETIME        NULL,
    [STNK_ADDRESS]      NVARCHAR (4000) NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [STCK_NO]           NVARCHAR (50)   NULL,
    [STCK_DATE]         DATETIME        NULL,
    [STCK_EXP_DATE]     DATETIME        NULL
);

