CREATE TABLE [dbo].[XXX_ADJUSTMENT_20241106] (
    [CODE]                     NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]             NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [DATE]                     DATETIME        NOT NULL,
    [ADJUSTMENT_TYPE]          NVARCHAR (50)   NOT NULL,
    [NEW_PURCHASE_DATE]        DATETIME        NOT NULL,
    [PURCHASE_PRICE]           DECIMAL (18, 2) NOT NULL,
    [DESCRIPTION]              NVARCHAR (1000) NOT NULL,
    [ASSET_CODE]               NVARCHAR (50)   NOT NULL,
    [NEW_NETBOOK_VALUE_FISCAL] DECIMAL (18, 2) NOT NULL,
    [NEW_NETBOOK_VALUE_COMM]   DECIMAL (18, 2) NOT NULL,
    [OLD_TOTAL_DEPRE_COMM]     DECIMAL (18, 2) NOT NULL,
    [TOTAL_ADJUSTMENT]         DECIMAL (18, 2) NOT NULL,
    [OLD_NETBOOK_VALUE_FISCAL] DECIMAL (18, 2) NOT NULL,
    [OLD_NETBOOK_VALUE_COMM]   DECIMAL (18, 2) NOT NULL,
    [PAYMENT_BY]               NVARCHAR (10)   NOT NULL,
    [VENDOR_CODE]              NVARCHAR (50)   NOT NULL,
    [VENDOR_NAME]              NVARCHAR (250)  NOT NULL,
    [REMARK]                   NVARCHAR (4000) NOT NULL,
    [STATUS]                   NVARCHAR (25)   NOT NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [ADJUST_TYPE]              NVARCHAR (15)   NULL
);

