CREATE TABLE [dbo].[XXX_ASSET_20250702] (
    [CODE]                          NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]                  NVARCHAR (50)   NOT NULL,
    [ITEM_CODE]                     NVARCHAR (50)   NOT NULL,
    [ITEM_NAME]                     NVARCHAR (250)  NOT NULL,
    [ITEM_GROUP_CODE]               NVARCHAR (50)   NULL,
    [CONDITION]                     NVARCHAR (50)   NULL,
    [BARCODE]                       NVARCHAR (50)   NULL,
    [STATUS]                        NVARCHAR (50)   NOT NULL,
    [FISICAL_STATUS]                NVARCHAR (25)   NULL,
    [INSURANCE_STATUS]              NVARCHAR (10)   NULL,
    [CLAIM_STATUS]                  NVARCHAR (10)   NULL,
    [RENTAL_STATUS]                 NVARCHAR (25)   NULL,
    [RENTAL_REFF_NO]                NVARCHAR (50)   NULL,
    [RESERVED_BY]                   NVARCHAR (50)   NULL,
    [RESERVED_DATE]                 DATETIME        NULL,
    [PO_NO]                         NVARCHAR (50)   NULL,
    [REQUESTOR_CODE]                NVARCHAR (50)   NULL,
    [REQUESTOR_NAME]                NVARCHAR (250)  NULL,
    [VENDOR_CODE]                   NVARCHAR (50)   NOT NULL,
    [VENDOR_NAME]                   NVARCHAR (250)  NOT NULL,
    [TYPE_CODE]                     NVARCHAR (50)   NULL,
    [CATEGORY_CODE]                 NVARCHAR (50)   NULL,
    [CATEGORY_NAME]                 NVARCHAR (250)  NULL,
    [PO_DATE]                       DATETIME        NULL,
    [PURCHASE_DATE]                 DATETIME        NOT NULL,
    [PURCHASE_PRICE]                DECIMAL (18, 2) NOT NULL,
    [INVOICE_NO]                    NVARCHAR (50)   NULL,
    [INVOICE_DATE]                  DATETIME        NULL,
    [ORIGINAL_PRICE]                DECIMAL (18, 2) NOT NULL,
    [SALE_AMOUNT]                   DECIMAL (18, 2) NULL,
    [SALE_DATE]                     DATETIME        NULL,
    [DISPOSAL_DATE]                 DATETIME        NULL,
    [BRANCH_CODE]                   NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                   NVARCHAR (250)  NOT NULL,
    [DIVISION_CODE]                 NVARCHAR (50)   NULL,
    [DIVISION_NAME]                 NVARCHAR (250)  NULL,
    [DEPARTMENT_CODE]               NVARCHAR (50)   NULL,
    [DEPARTMENT_NAME]               NVARCHAR (250)  NULL,
    [PIC_CODE]                      NVARCHAR (50)   NULL,
    [PIC_NAME]                      NVARCHAR (250)  NULL,
    [RESIDUAL_VALUE]                DECIMAL (18, 2) NULL,
    [IS_DEPRE]                      NVARCHAR (1)    NULL,
    [DEPRE_CATEGORY_COMM_CODE]      NVARCHAR (50)   NOT NULL,
    [TOTAL_DEPRE_COMM]              DECIMAL (18, 2) NOT NULL,
    [DEPRE_PERIOD_COMM]             NVARCHAR (6)    NULL,
    [NET_BOOK_VALUE_COMM]           DECIMAL (18, 2) NOT NULL,
    [DEPRE_CATEGORY_FISCAL_CODE]    NVARCHAR (50)   NOT NULL,
    [TOTAL_DEPRE_FISCAL]            DECIMAL (18, 2) NOT NULL,
    [DEPRE_PERIOD_FISCAL]           NVARCHAR (6)    NULL,
    [NET_BOOK_VALUE_FISCAL]         DECIMAL (18, 2) NOT NULL,
    [IS_RENTAL]                     NVARCHAR (1)    NULL,
    [CONTRACTOR_NAME]               NVARCHAR (250)  NULL,
    [CONTRACTOR_ADDRESS]            NVARCHAR (4000) NULL,
    [CONTRACTOR_EMAIL]              NVARCHAR (50)   NULL,
    [CONTRACTOR_PIC]                NVARCHAR (250)  NULL,
    [CONTRACTOR_PIC_PHONE]          NVARCHAR (25)   NULL,
    [CONTRACTOR_START_DATE]         DATETIME        NULL,
    [CONTRACTOR_END_DATE]           DATETIME        NULL,
    [WARRANTY]                      INT             NULL,
    [WARRANTY_START_DATE]           DATETIME        NULL,
    [WARRANTY_END_DATE]             DATETIME        NULL,
    [REMARKS_WARRANTY]              NVARCHAR (4000) NULL,
    [IS_MAINTENANCE]                NVARCHAR (1)    NULL,
    [MAINTENANCE_TIME]              INT             NULL,
    [MAINTENANCE_TYPE]              NVARCHAR (50)   NULL,
    [MAINTENANCE_CYCLE_TIME]        INT             NULL,
    [MAINTENANCE_START_DATE]        DATETIME        NULL,
    [USE_LIFE]                      NVARCHAR (15)   NULL,
    [LAST_METER]                    NVARCHAR (15)   NULL,
    [LAST_SERVICE_DATE]             DATETIME        NULL,
    [PPH]                           DECIMAL (18, 6) NULL,
    [PPN]                           DECIMAL (18, 6) NULL,
    [REMARKS]                       NVARCHAR (4000) NULL,
    [LAST_SO_DATE]                  DATETIME        NULL,
    [LAST_SO_CONDITION]             NVARCHAR (50)   NULL,
    [LAST_USED_BY_CODE]             NVARCHAR (50)   NULL,
    [LAST_USED_BY_NAME]             NVARCHAR (250)  NULL,
    [LAST_LOCATION_CODE]            NVARCHAR (50)   NULL,
    [LAST_LOCATION_NAME]            NVARCHAR (250)  NULL,
    [IS_PO]                         NVARCHAR (1)    NULL,
    [IS_LOCK]                       NVARCHAR (1)    NULL,
    [IS_PERMIT_TO_SELL]             NVARCHAR (1)    NULL,
    [PERMIT_SELL_REMARK]            NVARCHAR (4000) NULL,
    [SELL_REQUEST_AMOUNT]           DECIMAL (18, 2) NULL,
    [ASSET_PURPOSE]                 NVARCHAR (50)   NULL,
    [ASSET_FROM]                    NVARCHAR (50)   NULL,
    [MODEL_CODE]                    NVARCHAR (50)   NULL,
    [MODEL_NAME]                    NVARCHAR (250)  NULL,
    [MERK_CODE]                     NVARCHAR (50)   NULL,
    [MERK_NAME]                     NVARCHAR (250)  NULL,
    [TYPE_CODE_ASSET]               NVARCHAR (50)   NULL,
    [TYPE_NAME_ASSET]               NVARCHAR (250)  NULL,
    [UNIT_PROVINCE_CODE]            NVARCHAR (50)   NULL,
    [UNIT_PROVINCE_NAME]            NVARCHAR (250)  NULL,
    [UNIT_CITY_CODE]                NVARCHAR (50)   NULL,
    [UNIT_CITY_NAME]                NVARCHAR (250)  NULL,
    [PARKING_LOCATION]              NVARCHAR (250)  NULL,
    [PROCESS_STATUS]                NVARCHAR (50)   NULL,
    [AGREEMENT_NO]                  NVARCHAR (50)   NULL,
    [AGREEMENT_EXTERNAL_NO]         NVARCHAR (50)   NULL,
    [ASSET_NO]                      NVARCHAR (50)   NULL,
    [CLIENT_NO]                     NVARCHAR (50)   NULL,
    [CLIENT_NAME]                   NVARCHAR (250)  NULL,
    [SPAF_PCT]                      DECIMAL (9, 6)  NULL,
    [START_PERIOD_DATE]             DATETIME        NULL,
    [END_PERIOD_DATE]               DATETIME        NULL,
    [SPAF_AMOUNT]                   DECIMAL (18, 2) NULL,
    [SUBVENTION_AMOUNT]             DECIMAL (18, 2) NULL,
    [IS_SPAF_USE]                   NVARCHAR (1)    NOT NULL,
    [CLAIM_SPAF]                    NVARCHAR (50)   NULL,
    [CLAIM_SPAF_DATE]               DATETIME        NULL,
    [ACTIVITY_STATUS]               NVARCHAR (250)  NOT NULL,
    [WO_NO]                         NVARCHAR (50)   NULL,
    [CRE_DATE]                      DATETIME        NOT NULL,
    [CRE_BY]                        NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                      DATETIME        NOT NULL,
    [MOD_BY]                        NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [WO_STATUS]                     NVARCHAR (50)   NULL,
    [PERMIT_SELL_DATE]              DATETIME        NULL,
    [DISCOUNT_AMOUNT]               DECIMAL (18, 2) NULL,
    [PPN_AMOUNT]                    DECIMAL (18, 2) NULL,
    [PPH_AMOUNT]                    DECIMAL (18, 2) NULL,
    [RE_RENT_STATUS]                NVARCHAR (10)   NULL,
    [POSTING_DATE]                  DATETIME        NULL,
    [LAST_KM_SERVICE]               INT             NULL,
    [OLD_PURCHASE_PRICE]            DECIMAL (18, 2) NULL,
    [OLD_ORIGINAL_PRICE]            DECIMAL (18, 2) NULL,
    [OLD_NET_BOOK_VALUE_COMMERCIAL] DECIMAL (18, 2) NULL,
    [OLD_NET_BOOK_VALUE_FISCAL]     DECIMAL (18, 2) NULL,
    [INVOICE_POST_DATE]             DATETIME        NULL,
    [INVOICE_RETURN_DATE]           DATETIME        NULL
);

