CREATE TABLE [dbo].[xxx_rpt_asset_202400704] (
    [USER_ID]             NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]      NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]        NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]        NVARCHAR (250)  NOT NULL,
    [FILTER_BRANCH_NAME]  NVARCHAR (250)  NULL,
    [BRANCH_CODE]         NVARCHAR (50)   NULL,
    [BRANCH_NAME]         NVARCHAR (50)   NULL,
    [FROM_DATE]           DATETIME        NULL,
    [TO_DATE]             DATETIME        NULL,
    [PLAT_NO]             NVARCHAR (50)   NULL,
    [BRAND]               NVARCHAR (250)  NULL,
    [PRODUCT_CATEGORY]    NVARCHAR (250)  NULL,
    [VEHICLE_YPE]         NVARCHAR (250)  NULL,
    [CHASSIS_NO]          NVARCHAR (50)   NULL,
    [ENGINE_NO]           NVARCHAR (50)   NULL,
    [YEAR_ITEM]           NVARCHAR (50)   NULL,
    [COLOR]               NVARCHAR (50)   NULL,
    [MILEAGE]             INT             NULL,
    [LESSEE]              NVARCHAR (250)  NULL,
    [AGREEMENT_NO]        NVARCHAR (50)   NULL,
    [BEGINNING_PERIOD]    DATETIME        NULL,
    [ENDING_PERIOD]       DATETIME        NULL,
    [PERIOD]              INT             NULL,
    [STATUS]              NVARCHAR (50)   NULL,
    [AGING]               INT             NULL,
    [PROVINCE]            NVARCHAR (250)  NULL,
    [CITY]                NVARCHAR (250)  NULL,
    [PARKING_LOCATION]    NVARCHAR (250)  NULL,
    [CONTRACT_STATUS]     NVARCHAR (50)   NULL,
    [STNK_DATE]           DATETIME        NULL,
    [KEUR]                DATETIME        NULL,
    [COLOR_PLAT]          NVARCHAR (50)   NULL,
    [INSURANCE_POLIS]     NVARCHAR (250)  NULL,
    [INSURANCE_COMPANY]   NVARCHAR (250)  NULL,
    [START_DATE]          DATETIME        NULL,
    [END_DATE]            DATETIME        NULL,
    [SUPPLIER]            NVARCHAR (250)  NULL,
    [MAINTENANCE_SCHEME]  NVARCHAR (50)   NULL,
    [COP_NON_COP]         NVARCHAR (50)   NULL,
    [NI]                  NVARCHAR (50)   NULL,
    [REGISTRATION_BUDGET] DECIMAL (18, 2) NULL,
    [MAINTENANCE_BUDGET]  DECIMAL (18, 2) NULL,
    [REPLACEMENT_BUDGET]  DECIMAL (18, 2) NULL,
    [INSURANCE_COST]      DECIMAL (18, 2) NULL,
    [MOBILIZATION_COST]   DECIMAL (18, 2) NULL,
    [MARKETING_OFFICER]   NVARCHAR (250)  NULL,
    [REMARK]              NVARCHAR (4000) NULL,
    [IS_CONDITION]        NVARCHAR (1)    NULL,
    [ASSET_CODE]          NVARCHAR (50)   NULL
);

