CREATE TABLE [dbo].[XXX_DATA_ASSET_IFIN] (
    [code]                NVARCHAR (255)  NULL,
    [STATUS]              NVARCHAR (255)  NULL,
    [ITEM_NAME]           NVARCHAR (255)  NULL,
    [BRANCH_NAME]         NVARCHAR (255)  NULL,
    [DEPRE_PERIOD_COMM]   DECIMAL (18, 2) NULL,
    [PURCHASE_PRICE]      DECIMAL (18, 2) NULL,
    [DATA ACCT]           DECIMAL (18, 2) NULL,
    [DIFF DGN ACT]        DECIMAL (18, 2) NULL,
    [TOTAL_DEPRE_COMM]    DECIMAL (18, 2) NULL,
    [NET_BOOK_VALUE_COMM] DECIMAL (18, 2) NULL,
    [RESIDUAL_VALUE]      DECIMAL (18, 2) NULL,
    [DEPRECIATION_AMOUNT] DECIMAL (18, 2) NULL
);

