CREATE TABLE [dbo].[XXX_INSURANCE_POLICY_MAIN_LOADING_21082024] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [POLICY_CODE]         NVARCHAR (50)   NOT NULL,
    [LOADING_CODE]        NVARCHAR (50)   NOT NULL,
    [YEAR_PERIOD]         INT             NOT NULL,
    [INITIAL_BUY_RATE]    DECIMAL (9, 6)  NOT NULL,
    [INITIAL_SELL_RATE]   DECIMAL (9, 6)  NOT NULL,
    [INITIAL_BUY_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [INITIAL_SELL_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [TOTAL_BUY_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [TOTAL_SELL_AMOUNT]   DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL
);

