CREATE TABLE [dbo].[XXX_TEMP_INSURANCE_POLICY_PLUS_ACODE_07112023] (
    [ASSET_CODE]                 VARCHAR (10)   NULL,
    [YEARPERIOD]                 FLOAT (53)     NULL,
    [AGREEMENT NUMBER]           NVARCHAR (255) NULL,
    [SEQ]                        NVARCHAR (255) NULL,
    [CUSTOMER]                   NVARCHAR (255) NULL,
    [OBJECT LEASED]              NVARCHAR (255) NULL,
    [YEAR]                       FLOAT (53)     NULL,
    [CHASIS NUMBER]              NVARCHAR (255) NULL,
    [ENGINENUMBER]               NVARCHAR (255) NULL,
    [POLICE NUMBER]              NVARCHAR (255) NULL,
    [TGL EMAIL SPPA]             NVARCHAR (255) NULL,
    [TANGGAL PENERIMAAN POLIS]   NVARCHAR (255) NULL,
    [NO POLIS]                   NVARCHAR (255) NULL,
    [JANGKA WAKTU]               FLOAT (53)     NULL,
    [END POLIS ASURANSI]         NVARCHAR (255) NULL,
    [TGL JATUH TEMPO PEMBAYARAN] NVARCHAR (255) NULL,
    [NILAI PERTANGGUNGAN]        FLOAT (53)     NULL,
    [NET PREMI]                  FLOAT (53)     NULL,
    [SISA BUDGET]                FLOAT (53)     NULL,
    [TGL KIRIM KE AP]            NVARCHAR (255) NULL,
    [TGL BAYAR KE ASURANSI]      NVARCHAR (255) NULL,
    [KETERANGAN]                 NVARCHAR (255) NULL,
    [LAST YEAR PAID]             FLOAT (53)     NULL,
    [IS NOT PAID]                INT            NOT NULL
);

