CREATE TABLE [dbo].[XXX_MAINTENANCE_07112023] (
    [CODE]                     NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]             NVARCHAR (50)   NOT NULL,
    [ASSET_CODE]               NVARCHAR (50)   NOT NULL,
    [TRANSACTION_DATE]         DATETIME        NOT NULL,
    [TRANSACTION_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [REQUESTOR_CODE]           NVARCHAR (50)   NULL,
    [REQUESTOR_NAME]           NVARCHAR (250)  NULL,
    [DIVISION_CODE]            NVARCHAR (50)   NOT NULL,
    [DIVISION_NAME]            NVARCHAR (250)  NOT NULL,
    [DEPARTMENT_CODE]          NVARCHAR (50)   NOT NULL,
    [DEPARTMENT_NAME]          NVARCHAR (250)  NOT NULL,
    [MAINTENANCE_BY]           NVARCHAR (50)   NOT NULL,
    [VENDOR_CODE]              NVARCHAR (50)   NULL,
    [VENDOR_NAME]              NVARCHAR (250)  NULL,
    [STATUS]                   NVARCHAR (20)   NOT NULL,
    [REMARK]                   NVARCHAR (4000) NULL,
    [ACTUAL_KM]                INT             NULL,
    [WORK_DATE]                DATETIME        NULL,
    [SERVICE_TYPE]             NVARCHAR (20)   NULL,
    [HOUR_METER]               INT             NULL,
    [VENDOR_CITY_NAME]         NVARCHAR (250)  NULL,
    [VENDOR_PROVINCE_NAME]     NVARCHAR (250)  NULL,
    [VENDOR_ADDRESS]           NVARCHAR (4000) NULL,
    [VENDOR_PHONE]             NVARCHAR (20)   NULL,
    [VENDOR_BANK_NAME]         NVARCHAR (250)  NULL,
    [VENDOR_BANK_ACCOUNT_NO]   NVARCHAR (50)   NULL,
    [VENDOR_BANK_ACCOUNT_NAME] NVARCHAR (250)  NULL,
    [IS_REIMBURSE]             NVARCHAR (5)    NULL,
    [BANK_CODE]                NVARCHAR (50)   NULL,
    [BANK_NAME]                NVARCHAR (250)  NULL,
    [BANK_ACCOUNT_NO]          NVARCHAR (50)   NULL,
    [BANK_ACCOUNT_NAME]        NVARCHAR (50)   NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (50)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (50)   NOT NULL,
    [SPK_NO]                   NVARCHAR (50)   NULL,
    [SA_VENDOR_NAME]           NVARCHAR (50)   NULL,
    [SA_VENDOR_AREA_PHONE]     NVARCHAR (5)    NULL,
    [SA_VENDOR_PHONE_NO]       NVARCHAR (20)   NULL,
    [VENDOR_NPWP]              NVARCHAR (20)   NULL,
    [VENDOR_TYPE]              NVARCHAR (25)   NULL
);

