CREATE TABLE [dbo].[XXX_RPT_MONITORING_PAYMENT] (
    [VENDOR_NAME]       NVARCHAR (4000) NULL,
    [WORK_DATE]         DATETIME        NULL,
    [PLAT_NO]           NVARCHAR (50)   NULL,
    [CLIENT_NAME]       NVARCHAR (4000) NULL,
    [AGREEMENT_NO]      NVARCHAR (50)   NULL,
    [ITEM_NAME]         NVARCHAR (4000) NULL,
    [CATEGORY_NAME]     NVARCHAR (50)   NULL,
    [TOTAL_AMOUNT_JASA] DECIMAL (18, 2) NULL,
    [TOTAL_PPH_AMOUNT]  DECIMAL (18, 2) NULL,
    [TOTAL_AMOUNT_ITEM] DECIMAL (18, 2) NULL,
    [TOTAL_PPN_AMOUNT]  DECIMAL (18, 2) NULL,
    [PAYMENT_AMOUNT]    DECIMAL (18, 2) NULL,
    [MERK_NAME]         NVARCHAR (4000) NULL,
    [BUILT_YEAR]        NVARCHAR (50)   NULL,
    [CHASISS_NO]        NVARCHAR (50)   NULL,
    [ENGINE_NO]         NVARCHAR (50)   NULL,
    [ACTUAL_KM]         NVARCHAR (50)   NULL,
    [TRANSACTION_DATE]  DATETIME        NULL
);

