CREATE TABLE [dbo].[xxxMASTER_DEPARTMENT] (
    [CODE]           NVARCHAR (50)  NOT NULL,
    [COMPANY_CODE]   NVARCHAR (50)  NOT NULL,
    [DIVISION_CODE]  NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]    NVARCHAR (250) NOT NULL,
    [IS_ACTIVE]      NVARCHAR (1)   NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_DEPARTMENT_1] PRIMARY KEY CLUSTERED ([CODE] ASC, [COMPANY_CODE] ASC, [DIVISION_CODE] ASC)
);

