CREATE TABLE [dbo].[Z_AUDIT_MASTER_CATEGORY] (
    [CODE]                         NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]                 NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]                  NVARCHAR (250)  NOT NULL,
    [ASSET_TYPE_CODE]              NVARCHAR (20)   NOT NULL,
    [TRANSACTION_DEPRE_CODE]       NVARCHAR (50)   NULL,
    [TRANSACTION_DEPRE_NAME]       NVARCHAR (250)  NULL,
    [TRANSACTION_ACCUM_DEPRE_CODE] NVARCHAR (50)   NULL,
    [TRANSACTION_ACCUM_DEPRE_NAME] NVARCHAR (250)  NULL,
    [TRANSACTION_GAIN_LOSS_CODE]   NVARCHAR (50)   NULL,
    [TRANSACTION_GAIN_LOSS_NAME]   NVARCHAR (250)  NULL,
    [TRANSACTION_PROFIT_SELL_CODE] NVARCHAR (50)   NULL,
    [TRANSACTION_PROFIT_SELL_NAME] NVARCHAR (250)  NULL,
    [TRANSACTION_LOSS_SELL_CODE]   NVARCHAR (50)   NULL,
    [TRANSACTION_LOSS_SELL_NAME]   NVARCHAR (250)  NULL,
    [DEPRE_CAT_FISCAL_CODE]        NVARCHAR (50)   NULL,
    [DEPRE_CAT_FISCAL_NAME]        NVARCHAR (250)  NULL,
    [DEPRE_CAT_COMMERCIAL_CODE]    NVARCHAR (50)   NULL,
    [DEPRE_CAT_COMMERCIAL_NAME]    NVARCHAR (250)  NULL,
    [LAST_DEPRE_DATE]              DATETIME        NULL,
    [ASSET_AMOUNT_THRESHOLD]       DECIMAL (18, 2) NOT NULL,
    [DEPRE_AMOUNT_THRESHOLD]       DECIMAL (18, 2) NOT NULL,
    [TOTAL_NET_BOOK_VALUE_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [TOTAL_ACCUM_DEPRE_AMOUNT]     DECIMAL (18, 2) NOT NULL,
    [TOTAL_ASSET_VALUE]            DECIMAL (18, 2) NOT NULL,
    [VALUE_TYPE]                   NVARCHAR (50)   NOT NULL,
    [NDE]                          DECIMAL (18, 6) NULL,
    [IS_ACTIVE]                    NVARCHAR (1)    NOT NULL,
    [CRE_DATE]                     DATETIME        NOT NULL,
    [CRE_BY]                       NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                     DATETIME        NOT NULL,
    [MOD_BY]                       NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    [AuditDataState]               VARCHAR (10)    NULL,
    [AuditDMLAction]               VARCHAR (10)    NULL,
    [AuditUser]                    [sysname]       NULL,
    [AuditDateTime]                DATETIME        NULL,
    [UpdateColumns]                VARCHAR (MAX)   NULL
);

