CREATE TABLE [dbo].[Z_AUDIT_MASTER_ITEM] (
    [CODE]             NVARCHAR (50)   NOT NULL,
    [COMPANY_CODE]     NVARCHAR (50)   NOT NULL,
    [TRANSACTION_TYPE] NVARCHAR (50)   NOT NULL,
    [ITEM_GROUP_CODE]  NVARCHAR (50)   NOT NULL,
    [MERK_CODE]        NVARCHAR (50)   NULL,
    [MODEL_CODE]       NVARCHAR (50)   NULL,
    [TYPE_CODE]        NVARCHAR (50)   NULL,
    [UOM_CODE]         NVARCHAR (50)   NOT NULL,
    [TYPE_ASSET_CODE]  NVARCHAR (50)   NOT NULL,
    [FA_CATEGORY_CODE] NVARCHAR (50)   NOT NULL,
    [FA_CATEGORY_NAME] NVARCHAR (250)  NOT NULL,
    [PO_LATEST_PRICE]  DECIMAL (18, 2) NOT NULL,
    [PO_AVERAGE_PRICE] DECIMAL (18, 2) NOT NULL,
    [DESCRIPTION]      NVARCHAR (250)  NOT NULL,
    [IS_RENT]          NVARCHAR (1)    NOT NULL,
    [IS_ACTIVE]        NVARCHAR (1)    NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [AuditDataState]   VARCHAR (10)    NULL,
    [AuditDMLAction]   VARCHAR (10)    NULL,
    [AuditUser]        [sysname]       NULL,
    [AuditDateTime]    DATETIME        NULL,
    [UpdateColumns]    VARCHAR (MAX)   NULL
);

