CREATE TABLE [dbo].[Z_AUDIT_MASTER_AUCTION_ADDRESS] (
    [ID]             BIGINT          NULL,
    [AUCTION_CODE]   NVARCHAR (50)   NOT NULL,
    [PROVINCE_CODE]  NVARCHAR (50)   NOT NULL,
    [PROVINCE_NAME]  NVARCHAR (250)  NOT NULL,
    [CITY_CODE]      NVARCHAR (50)   NOT NULL,
    [CITY_NAME]      NVARCHAR (250)  NOT NULL,
    [ZIP_CODE]       NVARCHAR (50)   NOT NULL,
    [SUB_DISTRICT]   NVARCHAR (250)  NOT NULL,
    [VILLAGE]        NVARCHAR (250)  NOT NULL,
    [ADDRESS]        NVARCHAR (4000) NOT NULL,
    [RT]             NVARCHAR (5)    NOT NULL,
    [RW]             NVARCHAR (5)    NOT NULL,
    [IS_LATEST]      NVARCHAR (1)    NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [AuditDataState] VARCHAR (10)    NULL,
    [AuditDMLAction] VARCHAR (10)    NULL,
    [AuditUser]      [sysname]       NULL,
    [AuditDateTime]  DATETIME        NULL,
    [UpdateColumns]  VARCHAR (MAX)   NULL
);

