CREATE TABLE [dbo].[Z_AUDIT_MASTER_COVERAGE_LOADING] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [LOADING_NAME]   NVARCHAR (250)  NOT NULL,
    [LOADING_TYPE]   NVARCHAR (10)   NOT NULL,
    [AGE_FROM]       INT             NOT NULL,
    [AGE_TO]         INT             NOT NULL,
    [RATE_TYPE]      NVARCHAR (10)   NOT NULL,
    [BUY_AMOUNT]     DECIMAL (18, 2) NOT NULL,
    [SELL_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [BUY_RATE_PCT]   DECIMAL (9, 6)  NOT NULL,
    [SALE_RATE_PCT]  DECIMAL (9, 6)  NOT NULL,
    [IS_ACTIVE]      NVARCHAR (1)    NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [AuditDataState] VARCHAR (10)    NULL,
    [AuditDMLAction] VARCHAR (10)    NULL,
    [AuditUser]      [sysname]       NULL,
    [AuditDateTime]  DATETIME        NULL,
    [UpdateColumns]  VARCHAR (MAX)   NULL
);

