CREATE TABLE [dbo].[Z_AUDIT_SYS_IT_PARAM] (
    [SYSTEM_DATE]              DATETIME      NOT NULL,
    [DB_MAIL_PROFILE]          NVARCHAR (50) NOT NULL,
    [USER_AUTO_INACTIVE]       INT           NOT NULL,
    [PASSWORD_MAX_REPEAT_TIME] INT           NOT NULL,
    [PASSWORD_MAX_LOGIN_TRY]   INT           NOT NULL,
    [PASSWORD_NEXT_CHANGE]     INT           NOT NULL,
    [PASSWORD_MIN_CHAR]        INT           NOT NULL,
    [PASSWORD_MAX_CHAR]        INT           NOT NULL,
    [PASSWORD_REGEX]           NVARCHAR (1)  NOT NULL,
    [PASSWORD_USE_UPPERCASE]   NVARCHAR (1)  NOT NULL,
    [PASSWORD_USE_LOWERCASE]   NVARCHAR (1)  NOT NULL,
    [PASSWORD_CONTAIN_NUMBER]  NVARCHAR (1)  NOT NULL,
    [IS_EOD_RUNNING]           NVARCHAR (1)  NOT NULL,
    [EOD_MANUAL_FLAG]          NVARCHAR (1)  NOT NULL,
    [SUBSCRIPTION_TYPE_CODE]   NVARCHAR (50) NOT NULL,
    [MAX_USER]                 INT           NOT NULL,
    [CRE_DATE]                 DATETIME      NOT NULL,
    [CRE_BY]                   NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15) NOT NULL,
    [MOD_DATE]                 DATETIME      NOT NULL,
    [MOD_BY]                   NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15) NOT NULL,
    [AuditDataState]           VARCHAR (10)  NULL,
    [AuditDMLAction]           VARCHAR (10)  NULL,
    [AuditUser]                [sysname]     NULL,
    [AuditDateTime]            DATETIME      NULL,
    [UpdateColumns]            VARCHAR (MAX) NULL
);

