CREATE TABLE [dbo].[AGREEMENT_ASSET_BACKUP2JULI$] (
    [ASSET_NO]       NVARCHAR (255) NULL,
    [AGREEMENT_NO]   NVARCHAR (255) NULL,
    [ASSET_STATUS]   NVARCHAR (255) NULL,
    [FA_CODE]        NVARCHAR (250) NULL,
    [FA_REFF_NO_02]  NVARCHAR (255) NULL,
    [FA_REFF_NO_03]  NVARCHAR (255) NULL,
    [CRE_DATE]       DATETIME       NULL,
    [CRE_BY]         NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS] NVARCHAR (255) NULL,
    [MOD_DATE]       DATETIME       NULL,
    [MOD_BY]         NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS] NVARCHAR (255) NULL
);

