CREATE TABLE [dbo].[AGREEMENT_INVOICE_PAYMENT] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_INVOICE_CODE] NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]             NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]           NVARCHAR (50)   NOT NULL,
    [ASSET_NO]               NVARCHAR (50)   NOT NULL,
    [TRANSACTION_NO]         NVARCHAR (50)   NOT NULL,
    [TRANSACTION_TYPE]       NVARCHAR (20)   NOT NULL,
    [PAYMENT_DATE]           DATETIME        NOT NULL,
    [PAYMENT_AMOUNT]         DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_PAYMENT_PAYMENT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [VOUCHER_NO]             NVARCHAR (50)   NULL,
    [DESCRIPTION]            NVARCHAR (4000) NOT NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MF_PAYMENT_AMOUNT]      DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_AGREEMENT_INVOICE_PAYMENT] PRIMARY KEY CLUSTERED ([ID] ASC, [AGREEMENT_INVOICE_CODE] ASC, [INVOICE_NO] ASC, [AGREEMENT_NO] ASC),
    CONSTRAINT [FK_AGREEMENT_INVOICE_PAYMENT_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_AGREEMENT_INVOICE_PAYMENT_AGREEMENT_INVOICE] FOREIGN KEY ([AGREEMENT_INVOICE_CODE]) REFERENCES [dbo].[AGREEMENT_INVOICE] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_AGREEMENT_INVOICE_PAYMENT_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]),
    CONSTRAINT [FK_AGREEMENT_INVOICE_PAYMENT_INVOICE] FOREIGN KEY ([INVOICE_NO]) REFERENCES [dbo].[INVOICE] ([INVOICE_NO])
);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_PAYMENT_INVOICE_NO_AGREEMENT_NO_ASSET_NO]
    ON [dbo].[AGREEMENT_INVOICE_PAYMENT]([INVOICE_NO] ASC, [AGREEMENT_NO] ASC, [ASSET_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_PAYMENT_20230926]
    ON [dbo].[AGREEMENT_INVOICE_PAYMENT]([AGREEMENT_INVOICE_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_PAYMENT_20240201]
    ON [dbo].[AGREEMENT_INVOICE_PAYMENT]([PAYMENT_AMOUNT] ASC)
    INCLUDE([TRANSACTION_NO], [PAYMENT_DATE]);


GO
CREATE NONCLUSTERED INDEX [idx_xsp_rpt_agreement_amortization_payment_amount]
    ON [dbo].[AGREEMENT_INVOICE_PAYMENT]([PAYMENT_AMOUNT] ASC)
    INCLUDE([ASSET_NO], [VOUCHER_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_aip_invoice]
    ON [dbo].[AGREEMENT_INVOICE_PAYMENT]([INVOICE_NO] ASC)
    INCLUDE([PAYMENT_AMOUNT]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor aplikasi', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_INVOICE_PAYMENT', @level2type = N'COLUMN', @level2name = N'AGREEMENT_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'PAYMENT, CREDIT NOTE ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_INVOICE_PAYMENT', @level2type = N'COLUMN', @level2name = N'TRANSACTION_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'PAYMENT, CREDIT NOTE ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_INVOICE_PAYMENT', @level2type = N'COLUMN', @level2name = N'TRANSACTION_TYPE';

