CREATE TABLE [dbo].[AGREEMENT_MAIN_BACKUP2JULI$] (
    [AGREEMENT_NO]                        NVARCHAR (255) NULL,
    [AGREEMENT_EXTERNAL_NO]               NVARCHAR (255) NULL,
    [APPLICATION_NO]                      NVARCHAR (255) NULL,
    [AGREEMENT_DATE]                      DATETIME       NULL,
    [AGREEMENT_STATUS]                    NVARCHAR (255) NULL,
    [AGREEMENT_SUB_STATUS]                NVARCHAR (255) NULL,
    [TERMINATION_DATE]                    NVARCHAR (255) NULL,
    [TERMINATION_STATUS]                  NVARCHAR (255) NULL,
    [COLLECTION_STATUS]                   NVARCHAR (255) NULL,
    [BRANCH_CODE]                         FLOAT (53)     NULL,
    [BRANCH_NAME]                         NVARCHAR (255) NULL,
    [INITIAL_BRANCH_CODE]                 FLOAT (53)     NULL,
    [INITIAL_BRANCH_NAME]                 NVARCHAR (255) NULL,
    [CURRENCY_CODE]                       NVARCHAR (255) NULL,
    [FACILITY_CODE]                       NVARCHAR (255) NULL,
    [FACILITY_NAME]                       NVARCHAR (255) NULL,
    [CLIENT_TYPE]                         NVARCHAR (255) NULL,
    [CLIENT_NO]                           NVARCHAR (255) NULL,
    [CLIENT_NAME]                         NVARCHAR (255) NULL,
    [TAX_SCHEME_CODE]                     NVARCHAR (255) NULL,
    [PPN_PCT]                             FLOAT (53)     NULL,
    [PPH_PCT]                             FLOAT (53)     NULL,
    [OLD_AGREEMENT_NO]                    NVARCHAR (255) NULL,
    [PAYMENT_PROMISE_DATE]                NVARCHAR (255) NULL,
    [MATURITY_CODE]                       NVARCHAR (255) NULL,
    [IS_STOP_BILLING]                     FLOAT (53)     NULL,
    [IS_PENDING_BILLING]                  FLOAT (53)     NULL,
    [PERIODE]                             FLOAT (53)     NULL,
    [BILLING_TYPE]                        NVARCHAR (255) NULL,
    [CREDIT_TERM]                         FLOAT (53)     NULL,
    [FIRST_PAYMENT_TYPE]                  NVARCHAR (255) NULL,
    [IS_PURCHASE_REQUIREMENT_AFTER_LEASE] FLOAT (53)     NULL,
    [LEASE_OPTION]                        NVARCHAR (255) NULL,
    [ROUND_TYPE]                          NVARCHAR (255) NULL,
    [ROUND_AMOUNT]                        FLOAT (53)     NULL,
    [MARKETING_CODE]                      NVARCHAR (255) NULL,
    [MARKETING_NAME]                      NVARCHAR (255) NULL,
    [OPL_STATUS]                          NVARCHAR (255) NULL,
    [AGREEMENT_SIGN_DATE]                 DATETIME       NULL,
    [CRE_DATE]                            DATETIME       NULL,
    [CRE_BY]                              NVARCHAR (255) NULL,
    [CRE_IP_ADDRESS]                      NVARCHAR (255) NULL,
    [MOD_DATE]                            DATETIME       NULL,
    [MOD_BY]                              NVARCHAR (255) NULL,
    [MOD_IP_ADDRESS]                      NVARCHAR (255) NULL,
    [CLIENT_ID]                           FLOAT (53)     NULL,
    [APPLICATION_NO_EXTERNAL]             NVARCHAR (255) NULL
);

