CREATE TABLE [dbo].[AGREEMENT_CHARGES] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [CHARGES_CODE]   NVARCHAR (50)   NOT NULL,
    [CHARGES_NAME]   NVARCHAR (250)  NOT NULL,
    [CALCULATE_BY]   NVARCHAR (10)   NOT NULL,
    [CHARGES_RATE]   DECIMAL (9, 6)  CONSTRAINT [DF_AGREEMENT_CHARGES_DAFAULT_CHARGES_RATE] DEFAULT ((0)) NOT NULL,
    [CHARGES_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_CHARGES_CHARGES_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_AGREEMENT_CHARGES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AGREEMENT_CHARGES_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

