CREATE TABLE [dbo].[AGREEMENT_1706] (
    [AGREEMENT_NO]   NVARCHAR (255) NULL,
    [ASSET_NO]       NVARCHAR (255) NULL,
    [BILLING_NO]     FLOAT (53)     NULL,
    [DUE_DATE]       DATETIME       NULL,
    [BILLING_DATE]   DATETIME       NULL,
    [BILLING_AMOUNT] FLOAT (53)     NULL
);

