CREATE TABLE [dbo].[AGREEMENT_ASSET_AMORTIZATION] (
    [AGREEMENT_NO]        NVARCHAR (50)   NOT NULL,
    [BILLING_NO]          INT             NOT NULL,
    [ASSET_NO]            NVARCHAR (50)   NOT NULL,
    [DUE_DATE]            DATETIME        NOT NULL,
    [BILLING_DATE]        DATETIME        NOT NULL,
    [BILLING_AMOUNT]      DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_AMORTIZATION_INSTALLMENT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]         NVARCHAR (4000) CONSTRAINT [DF_AGREEMENT_ASSET_AMORTIZATION_DESCRIPTION] DEFAULT ('') NOT NULL,
    [INVOICE_NO]          NVARCHAR (50)   NULL,
    [GENERATE_CODE]       NVARCHAR (50)   NULL,
    [HOLD_BILLING_STATUS] NVARCHAR (10)   NULL,
    [HOLD_DATE]           DATETIME        NULL,
    [REFF_CODE]           NVARCHAR (50)   NULL,
    [REFF_REMARK]         NVARCHAR (4000) NULL,
    [REFF_DATE]           DATETIME        NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_AGREEMENT_AMORTIZATION] PRIMARY KEY CLUSTERED ([AGREEMENT_NO] ASC, [BILLING_NO] ASC, [ASSET_NO] ASC),
    CONSTRAINT [FK_AGREEMENT_AMORTIZATION_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]),
    CONSTRAINT [FK_AGREEMENT_ASSET_AMORTIZATION_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);




GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_ASSET_AMORTIZATION_20230929]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([BILLING_NO] ASC, [ASSET_NO] ASC)
    INCLUDE([DUE_DATE]);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_ASSET_AMORTIZATION_20230929_2]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([AGREEMENT_NO] ASC, [ASSET_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_ASSET_AMORTIZATION_20231003]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([ASSET_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_ASSET_AMORTIZATION_20231003_2]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([ASSET_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_ASSET_AMORTIZATION_20231030]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([AGREEMENT_NO] ASC, [INVOICE_NO] ASC)
    INCLUDE([BILLING_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_ASSET_AMORTIZATION_DUE_DATE_20250516]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([DUE_DATE] ASC)
    INCLUDE([BILLING_AMOUNT], [INVOICE_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_20250827_2]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([AGREEMENT_NO] ASC, [DUE_DATE] ASC)
    INCLUDE([INVOICE_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_20250827_3]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([ASSET_NO] ASC, [BILLING_DATE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor aplikasi', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_ASSET_AMORTIZATION', @level2type = N'COLUMN', @level2name = N'AGREEMENT_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor angsuran', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_ASSET_AMORTIZATION', @level2type = N'COLUMN', @level2name = N'BILLING_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tanggal jatuh tempo pembayaran', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_ASSET_AMORTIZATION', @level2type = N'COLUMN', @level2name = N'DUE_DATE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nilai angsuran yang dibayarkan', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_ASSET_AMORTIZATION', @level2type = N'COLUMN', @level2name = N'BILLING_AMOUNT';


GO
CREATE NONCLUSTERED INDEX [idx_AGREEMENT_ASSET_AMORTIZATION_20251014]
    ON [dbo].[AGREEMENT_ASSET_AMORTIZATION]([ASSET_NO] ASC)
    INCLUDE([DUE_DATE], [BILLING_DATE], [GENERATE_CODE]);

