CREATE TABLE [dbo].[AGREEMENT_INVOICE] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]     NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [ASSET_NO]       NVARCHAR (50)   NOT NULL,
    [BILLING_NO]     INT             NOT NULL,
    [DUE_DATE]       DATETIME        NOT NULL,
    [INVOICE_DATE]   DATETIME        NOT NULL,
    [AR_AMOUNT]      DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_AR_AMOUNT] DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_AGREEMENT_INVOICE_1] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_AGREEMENT_INVOICE_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_AGREEMENT_INVOICE_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_AGREEMENT_INVOICE_INVOICE] FOREIGN KEY ([INVOICE_NO]) REFERENCES [dbo].[INVOICE] ([INVOICE_NO])
);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_AGREEMENT_NO_DUEDATE]
    ON [dbo].[AGREEMENT_INVOICE]([AGREEMENT_NO] ASC, [DUE_DATE] ASC)
    INCLUDE([INVOICE_NO], [ASSET_NO], [AR_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_BILLING_NO]
    ON [dbo].[AGREEMENT_INVOICE]([AGREEMENT_NO] ASC)
    INCLUDE([BILLING_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_20231203]
    ON [dbo].[AGREEMENT_INVOICE]([INVOICE_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_20231206]
    ON [dbo].[AGREEMENT_INVOICE]([AGREEMENT_NO] ASC, [INVOICE_DATE] ASC)
    INCLUDE([INVOICE_NO], [ASSET_NO], [BILLING_NO], [AR_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [idx_xsp_rpt_agreement_amortization_invoice_no]
    ON [dbo].[AGREEMENT_INVOICE]([INVOICE_NO] ASC)
    INCLUDE([AGREEMENT_NO], [ASSET_NO], [BILLING_NO], [AR_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_AGREEMENT_INVOICE_ASSET_NO_20250724]
    ON [dbo].[AGREEMENT_INVOICE]([ASSET_NO] ASC)
    INCLUDE([INVOICE_NO], [AGREEMENT_NO], [BILLING_NO], [AR_AMOUNT]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor aplikasi', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_INVOICE', @level2type = N'COLUMN', @level2name = N'AGREEMENT_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor angsuran', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AGREEMENT_INVOICE', @level2type = N'COLUMN', @level2name = N'BILLING_NO';

