CREATE TABLE [dbo].[APPLICATION_FINANCIAL_ANALYSIS_EXPENSE] (
    [ID]                                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_FINANCIAL_ANALYSIS_CODE] NVARCHAR (50)   NOT NULL,
    [EXPENSE_TYPE]                        NVARCHAR (50)   NOT NULL,
    [EXPENSE_AMOUNT]                      DECIMAL (18, 2) NOT NULL,
    [REMARKS]                             NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                            DATETIME        NOT NULL,
    [CRE_BY]                              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                            DATETIME        NOT NULL,
    [MOD_BY]                              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_FINANCIAL_ANALYSIS_EXPENSE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_FINANCIAL_ANALYSIS_EXPENSE_APPLICATION_FINANCIAL_ANALYSIS] FOREIGN KEY ([APPLICATION_FINANCIAL_ANALYSIS_CODE]) REFERENCES [dbo].[APPLICATION_FINANCIAL_ANALYSIS] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

