CREATE TABLE [dbo].[APPLICATION_ASSET_BUDGET] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_NO]                 NVARCHAR (50)   NOT NULL,
    [COST_CODE]                NVARCHAR (50)   NOT NULL,
    [COST_TYPE]                NVARCHAR (10)   NOT NULL,
    [COST_AMOUNT_MONTHLY]      DECIMAL (18, 2) NOT NULL,
    [COST_AMOUNT_YEARLY]       DECIMAL (18, 2) NOT NULL,
    [BUDGET_ADJUSTMENT_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_ASSET_BUDGET_BUDGET_ADJUSTMENT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [BUDGET_AMOUNT]            DECIMAL (18, 2) NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [IS_SUBJECT_TO_PURCHASE]   NVARCHAR (1)    NULL,
    [PURCHASE_CODE]            NVARCHAR (50)   NULL,
    [PURCHASE_STATUS]          NVARCHAR (250)  NULL,
    CONSTRAINT [PK_APPLICATION_ASSET_BUDGET] PRIMARY KEY CLUSTERED ([ID] ASC, [ASSET_NO] ASC),
    CONSTRAINT [FK_APPLICATION_ASSET_BUDGET_APPLICATION_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[APPLICATION_ASSET] ([ASSET_NO]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_APPLICATION_ASSET_BUDGET_MASTER_BUDGET_COST] FOREIGN KEY ([COST_CODE]) REFERENCES [dbo].[MASTER_BUDGET_COST] ([CODE]) ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_APPLICATION_ASSET_BUDGET_COST_CODE_20250615]
    ON [dbo].[APPLICATION_ASSET_BUDGET]([COST_CODE] ASC)
    INCLUDE([BUDGET_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_APPLICATION_ASSET_BUDGET_ASSET_NO_COST_CODE_20250615]
    ON [dbo].[APPLICATION_ASSET_BUDGET]([ASSET_NO] ASC, [COST_CODE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor asset pada aplikasi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APPLICATION_ASSET_BUDGET', @level2type = N'COLUMN', @level2name = N'ASSET_NO';

