CREATE TABLE [dbo].[APPLICATION_SURVEY_DOCUMENT] (
    [ID]                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_CODE] NVARCHAR (50)  NOT NULL,
    [LOCATION]                NVARCHAR (50)  NULL,
    [REMARK]                  NVARCHAR (50)  NULL,
    [FILE_NAME]               NVARCHAR (250) NULL,
    [PATHS]                   NVARCHAR (250) NULL,
    [CRE_DATE]                DATETIME       NOT NULL,
    [CRE_BY]                  NVARCHAR (50)  NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (50)  NOT NULL,
    [MOD_DATE]                DATETIME       NOT NULL,
    [MOD_BY]                  NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_DOCUMENT_APPLICATION_SURVEY] FOREIGN KEY ([APPLICATION_SURVEY_CODE]) REFERENCES [dbo].[APPLICATION_SURVEY] ([CODE])
);

