CREATE TABLE [dbo].[APPLICATION_SURVEY] (
    [CODE]                            NVARCHAR (50)   NOT NULL,
    [APPLICATION_NO]                  NVARCHAR (50)   NOT NULL,
    [NAMA]                            NVARCHAR (250)  NOT NULL,
    [APPLICATION_TYPE]                NVARCHAR (3)    NOT NULL,
    [GROUP_NAME]                      NVARCHAR (250)  NOT NULL,
    [ALAMAT_KANTOR]                   NVARCHAR (4000) NOT NULL,
    [ALAMAT_KANTOR_KOTA]              NVARCHAR (250)  NOT NULL,
    [ALAMAT_KANTOR_PROVINSI]          NVARCHAR (250)  NOT NULL,
    [ALAMAT_USAHA]                    NVARCHAR (4000) NOT NULL,
    [ALAMAT_USAHA_KOTA]               NVARCHAR (250)  NOT NULL,
    [ALAMAT_USAHA_PROVINSI]           NVARCHAR (250)  NOT NULL,
    [ALAMAT_SEJAK_USAHA]              DATETIME        NULL,
    [KOMODITI]                        NVARCHAR (4000) NOT NULL,
    [TUJUAN_PENGADAAN_UNIT]           NVARCHAR (4000) NOT NULL,
    [AS_OF_DATE]                      DATETIME        NULL,
    [MONTHLY_SALES]                   DECIMAL (18, 2) NOT NULL,
    [TOTAL_MONTHLY_EXPENSE]           DECIMAL (18, 2) NOT NULL,
    [TOTAL_MONTHLY_INSTALLMENT]       DECIMAL (18, 2) NOT NULL,
    [TOTAL_MONTHLY_INSTALLMENT_OTHER] DECIMAL (18, 2) NOT NULL,
    [NET_INCOME]                      DECIMAL (18, 2) NOT NULL,
    [OVERALL_ASSESSMENT]              NVARCHAR (15)   NOT NULL,
    [NOTES]                           NVARCHAR (4000) NOT NULL,
    [ECONOMIC_SECTOR_EVALUATION]      NVARCHAR (30)   NOT NULL,
    [PEMBERI_KERJA]                   NVARCHAR (250)  NOT NULL,
    [KELAS_PEMBERI_KERJA]             NVARCHAR (30)   NOT NULL,
    [MANAGEMENT_STYLE]                NVARCHAR (30)   NOT NULL,
    [LOKASI_AREA_KERJA]               NVARCHAR (4000) NOT NULL,
    [NO_OF_CLIENT]                    NVARCHAR (30)   NOT NULL,
    [NO_OF_EMPLOYEE]                  NVARCHAR (30)   NOT NULL,
    [CREDIT_LINE_OF_BANK]             NVARCHAR (30)   NOT NULL,
    [BUSINESS_EXPANSION]              NVARCHAR (30)   NOT NULL,
    [MO_SUMMARY]                      NVARCHAR (4000) NOT NULL,
    [CAPACITY]                        NVARCHAR (4000) NOT NULL,
    [CHARACTER]                       NVARCHAR (4000) NOT NULL,
    [STRENGTH]                        NVARCHAR (4000) NOT NULL,
    [WEAKNESS]                        NVARCHAR (4000) NOT NULL,
    [DATE_OF_VISIT]                   DATETIME        NULL,
    [TIME]                            NVARCHAR (15)   NOT NULL,
    [SURVEY_METHOD]                   NVARCHAR (30)   NOT NULL,
    [VENUE_1]                         NVARCHAR (4000) NOT NULL,
    [VENUE_2]                         NVARCHAR (4000) NOT NULL,
    [PROJECT]                         NVARCHAR (30)   NOT NULL,
    [CATEGORY]                        NVARCHAR (30)   NOT NULL,
    [TRADE_CHECKING_DATE]             DATETIME        NULL,
    [INTERVIEW_NAME]                  NVARCHAR (250)  NOT NULL,
    [AREA_PHONE_NUMBER]               NVARCHAR (4)    NOT NULL,
    [PHONE_NUMBER]                    NVARCHAR (15)   NOT NULL,
    [TRADE_CHECKING_RESULT]           NVARCHAR (30)   NOT NULL,
    [TRADE_CHECKING_NOTES]            NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                        DATETIME        NOT NULL,
    [CRE_BY]                          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                        DATETIME        NOT NULL,
    [MOD_BY]                          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO])
);

