CREATE TABLE [dbo].[APPLICATION_SURVEY_OTHER_LEASE] (
    [ID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_CODE] NVARCHAR (50)   NOT NULL,
    [RENTAL_COMPANY]          NVARCHAR (250)  NULL,
    [UNIT]                    INT             NULL,
    [JENIS_KENDARAAN]         NVARCHAR (250)  NULL,
    [OS_PERIODE]              INT             NULL,
    [NILAI_PINJAMAN]          DECIMAL (18, 2) NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_OTHER_LIST] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_OTHER_LEASE_APPLICATION_SURVEY] FOREIGN KEY ([APPLICATION_SURVEY_CODE]) REFERENCES [dbo].[APPLICATION_SURVEY] ([CODE])
);

