CREATE TABLE [dbo].[APPLICATION_FEE] (
    [ID]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NO]     NVARCHAR (50)   NOT NULL,
    [FEE_CODE]           NVARCHAR (50)   NOT NULL,
    [CURRENCY_CODE]      NVARCHAR (3)    NOT NULL,
    [DEFAULT_FEE_RATE]   DECIMAL (9, 6)  CONSTRAINT [DF_APPLICATION_FEE_FEE_RATE] DEFAULT ((0)) NOT NULL,
    [DEFAULT_FEE_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_FEE_FEE_AMOUNT1] DEFAULT ((0)) NOT NULL,
    [FEE_AMOUNT]         DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_FEE_FEE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [REMARKS]            NVARCHAR (4000) NOT NULL,
    [IS_CALCULATED]      NVARCHAR (1)    CONSTRAINT [DF_APPLICATION_FEE_IS_CALCULATED] DEFAULT ((0)) NULL,
    [IS_FEE_PAID]        NVARCHAR (1)    CONSTRAINT [DF_APPLICATION_FEE_IS_CALCULATED1] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]           DATETIME        CONSTRAINT [DF_APPLICATION_FEE_CRE_DATE] DEFAULT ((0)) NOT NULL,
    [CRE_BY]             NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_BY]             NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_FEE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_FEE_APPLICATION_MAIN1] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_APPLICATION_FEE_MASTER_FEE] FOREIGN KEY ([FEE_CODE]) REFERENCES [dbo].[MASTER_FEE] ([CODE])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Jenis mata uang yang digunakan pada data master refund tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APPLICATION_FEE', @level2type = N'COLUMN', @level2name = N'CURRENCY_CODE';

