CREATE TABLE [dbo].[APPLICATION_SURVEY_BANK] (
    [ID]                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_CODE] NVARCHAR (50)  NOT NULL,
    [BANK_CODE]               NVARCHAR (50)  NOT NULL,
    [BANK_NAME]               NVARCHAR (50)  NULL,
    [BANK_ACCOUNT_NO]         NVARCHAR (50)  NOT NULL,
    [BANK_ACCOUNT_NAME]       NVARCHAR (250) NOT NULL,
    [CRE_DATE]                DATETIME       NOT NULL,
    [CRE_BY]                  NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                DATETIME       NOT NULL,
    [MOD_BY]                  NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_BANK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_BANK_APPLICATION_SURVEY] FOREIGN KEY ([APPLICATION_SURVEY_CODE]) REFERENCES [dbo].[APPLICATION_SURVEY] ([CODE])
);

