CREATE TABLE [dbo].[APPLICATION_SURVEY_PLAN] (
    [ID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_CODE] NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]             NVARCHAR (4000) NOT NULL,
    [NI_AMOUNT]               DECIMAL (18, 2) NOT NULL,
    [TOTAL_NI_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_PLAN] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_PLAN_APPLICATION_SURVEY] FOREIGN KEY ([APPLICATION_SURVEY_CODE]) REFERENCES [dbo].[APPLICATION_SURVEY] ([CODE])
);

