CREATE TABLE [dbo].[APPLICATION_FINANCIAL_RECAPITULATION] (
    [CODE]                 NVARCHAR (50)  NOT NULL,
    [APPLICATION_NO]       NVARCHAR (50)  NOT NULL,
    [FROM_PERIODE_YEAR]    NVARCHAR (4)   NOT NULL,
    [FROM_PERIODE_MONTH]   NVARCHAR (2)   NOT NULL,
    [TO_PERIODE_YEAR]      NVARCHAR (4)   NOT NULL,
    [TO_PERIODE_MONTH]     NVARCHAR (2)   NOT NULL,
    [CURRENT_RASIO_PCT]    DECIMAL (9, 6) CONSTRAINT [DF_APPLICATION_FINANCIAL_RECAPITULATION_CURRENT_RASIO] DEFAULT ((0)) NOT NULL,
    [DEBET_TO_ASSET_PCT]   DECIMAL (9, 6) CONSTRAINT [DF_APPLICATION_FINANCIAL_RECAPITULATION_CURRENT_RASIO8] DEFAULT ((0)) NOT NULL,
    [RETURN_ON_EQUITY_PCT] DECIMAL (9, 6) CONSTRAINT [DF_APPLICATION_FINANCIAL_RECAPITULATION_CURRENT_RASIO7] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]             DATETIME       NOT NULL,
    [CRE_BY]               NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)  NOT NULL,
    [MOD_DATE]             DATETIME       NOT NULL,
    [MOD_BY]               NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_APPLICATION_FINANCIAL_RECAPITULATION] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_APPLICATION_FINANCIAL_RECAPITULATION_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

