CREATE TABLE [dbo].[APPLICATION_SURVEY_BANK_DETAIL] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_BANK_ID] BIGINT          NOT NULL,
    [COMPANY]                    NVARCHAR (250)  NULL,
    [MONTHLY_AMOUNT]             DECIMAL (18, 2) NULL,
    [AVERAGE]                    DECIMAL (18, 2) NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MUTATION_MONTH]             NVARCHAR (20)   NULL,
    [MUTATION_YEAR]              NVARCHAR (4)    NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_BANK_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_BANK_DETAIL_APPLICATION_SURVEY_BANK] FOREIGN KEY ([APPLICATION_SURVEY_BANK_ID]) REFERENCES [dbo].[APPLICATION_SURVEY_BANK] ([ID])
);

