CREATE TABLE [dbo].[APPLICATION_LOG] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NO]  NVARCHAR (50)   NOT NULL,
    [LOG_DATE]        DATETIME        NOT NULL,
    [LOG_DESCRIPTION] NVARCHAR (4000) NOT NULL,
    [LOG_CYCLE]       INT             CONSTRAINT [DF_APPLICATION_LOG_CYCLE] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_LOG] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_LOG_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

