CREATE TABLE [dbo].[APPLICATION_SCORING_REQUEST] (
    [CODE]                   NVARCHAR (50)   NOT NULL,
    [APPLICATION_NO]         NVARCHAR (50)   NOT NULL,
    [SCORING_STATUS]         NVARCHAR (10)   NOT NULL,
    [SCORING_DATE]           DATETIME        NOT NULL,
    [SCORING_OBJECT]         NVARCHAR (4000) NULL,
    [SCORING_REMARKS]        NVARCHAR (4000) NOT NULL,
    [SCORING_RESULT_DATE]    DATETIME        NULL,
    [SCORING_RESULT_VALUE]   NVARCHAR (250)  NULL,
    [SCORING_RESULT_GRADE]   NVARCHAR (50)   NULL,
    [SCORING_RESULT_REMARKS] NVARCHAR (4000) NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_SCORING_HEADER] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_APPLICATION_SCORING_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

