CREATE TABLE [dbo].[APPLICATION_INFORMATION] (
    [APPLICATION_NO]                    NVARCHAR (50)   NOT NULL,
    [WORKFLOW_STEP]                     INT             NULL,
    [APPLICATION_FLOW_CODE]             NVARCHAR (50)   NULL,
    [SCREEN_FLOW_CODE]                  NVARCHAR (50)   NULL,
    [CLIENT_FLOW_CODE]                  NVARCHAR (50)   NULL,
    [IS_REFUNDED]                       NVARCHAR (1)    CONSTRAINT [DF_APPLICATION_INFORMATION_IS_REFUNDED] DEFAULT ('') NOT NULL,
    [INTEREST_FOR_FIRST_DUEDATE_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_INFORMATION_INTEREST_FOR_FIRST_DUEDATE] DEFAULT ((0)) NOT NULL,
    [GROUP_LIMIT_AMOUNT]                DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_INFORMATION_INTEREST_FOR_FIRST_DUEDATE_AMOUNT1] DEFAULT ((0)) NOT NULL,
    [OS_EXPOSURE_AMOUNT]                DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_INFORMATION_GROUP_LIMIT_AMOUNT1] DEFAULT ((0)) NOT NULL,
    [REFF_LOAN_NO]                      NVARCHAR (50)   NULL,
    [CRE_DATE]                          DATETIME        NOT NULL,
    [CRE_BY]                            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                          DATETIME        NOT NULL,
    [MOD_BY]                            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (15)   NOT NULL,
    [APPROVAL_CODE]                     NVARCHAR (50)   NULL,
    CONSTRAINT [PK_APPLICATION_INFORMATION] PRIMARY KEY CLUSTERED ([APPLICATION_NO] ASC),
    CONSTRAINT [FK_APPLICATION_INFORMATION_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

