CREATE TABLE [dbo].[APPLICATION_SURVEY_CUSTOMER] (
    [ID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_CODE] NVARCHAR (50)   NOT NULL,
    [NAME]                    NVARCHAR (250)  NULL,
    [BUSINESS]                NVARCHAR (250)  NULL,
    [BUSINESS_LOCATION]       NVARCHAR (4000) NULL,
    [UNIT]                    BIGINT          NULL,
    [ADDITIONAL_INFO]         NVARCHAR (4000) NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_CUSTOMER] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_CUSTOMER_APPLICATION_SURVEY] FOREIGN KEY ([APPLICATION_SURVEY_CODE]) REFERENCES [dbo].[APPLICATION_SURVEY] ([CODE])
);

