CREATE TABLE [dbo].[APPLICATION_RECOMENDATION] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NO]       NVARCHAR (50)   NOT NULL,
    [RECOMENDATION_RESULT] NVARCHAR (20)   NULL,
    [RECOMENDATION_DATE]   DATETIME        NOT NULL,
    [EMPLOYEE_CODE]        NVARCHAR (50)   NOT NULL,
    [EMPLOYEE_NAME]        NVARCHAR (250)  NOT NULL,
    [LEVEL_STATUS]         NVARCHAR (20)   NOT NULL,
    [CYCLE]                INT             CONSTRAINT [DF_APPLICATION_RECOMENDATION_CYCLE] DEFAULT ((0)) NOT NULL,
    [REMARKS]              NVARCHAR (4000) NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_RECOMENDATION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_RECOMENDATION_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'RECOMEND, NOT, ESKALASI ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APPLICATION_RECOMENDATION', @level2type = N'COLUMN', @level2name = N'RECOMENDATION_RESULT';

