CREATE TABLE [dbo].[APPLICATION_EXTERNAL_DATA] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [REFF_NAME]           NVARCHAR (250)  NULL,
    [REFF_VALUE_DATATYPE] NVARCHAR (50)   NULL,
    [REFF_VALUE_STRING]   NVARCHAR (50)   NULL,
    [REFF_VALUE_NUMBER]   DECIMAL (18, 2) NULL,
    [REMARK]              NVARCHAR (4000) NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [APPLICATION_NO]      NVARCHAR (50)   NULL,
    CONSTRAINT [PK_APPLICATION_EXTERNAL_DATA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

