CREATE TABLE [dbo].[APPLICATION_FINANCIAL_ANALYSIS_INCOME] (
    [ID]                                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_FINANCIAL_ANALYSIS_CODE] NVARCHAR (50)   NOT NULL,
    [INCOME_TYPE_CODE]                    NVARCHAR (50)   NOT NULL,
    [INCOME_AMOUNT]                       DECIMAL (18, 2) NOT NULL,
    [NET_INCOME_PCT]                      DECIMAL (9, 6)  NOT NULL,
    [NET_INCOME_AMOUNT]                   DECIMAL (18, 2) NOT NULL,
    [REMARKS]                             NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                            DATETIME        NOT NULL,
    [CRE_BY]                              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                            DATETIME        NOT NULL,
    [MOD_BY]                              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_FINANCIAL_ANALYSIS_INCOME] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_FINANCIAL_ANALYSIS_INCOME_APPLICATION_FINANCIAL_ANALYSIS] FOREIGN KEY ([APPLICATION_FINANCIAL_ANALYSIS_CODE]) REFERENCES [dbo].[APPLICATION_FINANCIAL_ANALYSIS] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

