CREATE TABLE [dbo].[APPLICATION_SURVEY_PROJECT] (
    [ID]                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [APPLICATION_SURVEY_CODE] NVARCHAR (50)  NOT NULL,
    [PROJECT_NAME]            NVARCHAR (250) NULL,
    [PROJECT_OWNER]           NVARCHAR (250) NULL,
    [MAIN_KONTRAKTOR]         NVARCHAR (250) NULL,
    [SUB_KONTRAKTOR]          NVARCHAR (250) NULL,
    [SUB_SUB_KONTRAKTOR]      NVARCHAR (250) NULL,
    [MAIN_KOMPETITOR]         NVARCHAR (250) NULL,
    [SUB_KOMPETITOR]          NVARCHAR (250) NULL,
    [SUB_SUB_KOMPETITOR]      NVARCHAR (250) NULL,
    [CRE_DATE]                DATETIME       NOT NULL,
    [CRE_BY]                  NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                DATETIME       NOT NULL,
    [MOD_BY]                  NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_APPLICATION_SURVEY_PROJECT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_SURVEY_PROJECT_APPLICATION_SURVEY] FOREIGN KEY ([APPLICATION_SURVEY_CODE]) REFERENCES [dbo].[APPLICATION_SURVEY] ([CODE])
);

