CREATE TABLE [dbo].[APPLICATION_NOTARY] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NO]      NVARCHAR (50)   NOT NULL,
    [NOTARY_SERVICE_CODE] NVARCHAR (50)   NOT NULL,
    [NOTARY_SERVICE_NAME] NVARCHAR (250)  CONSTRAINT [DF_APPLICATION_NOTARY_NOTARY_SERVICE_NAME] DEFAULT (N'DEFAULT') NOT NULL,
    [CURRENCY_CODE]       NVARCHAR (3)    NOT NULL,
    [FEE_ADMIN_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_NOTARY_FEE_ADMIN_AMOUNT] DEFAULT ((0)) NOT NULL,
    [FEE_BNBP_AMOUNT]     DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_NOTARY_FEE_BNBP_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NOTARY_FEE_AMOUNT]   DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_NOTARY_NOTARY_FEE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [TOTAL_NOTARY_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_APPLICATION_NOTARY_TOTAL_NOTARY_AMOUNT] DEFAULT ((0)) NOT NULL,
    [REMARKS]             NVARCHAR (4000) NOT NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_NOTARY_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_APPLICATION_NOTARY_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

