CREATE TABLE [dbo].[APPLICATION_FINANCIAL_ANALYSIS] (
    [CODE]           NVARCHAR (50)  NOT NULL,
    [APPLICATION_NO] NVARCHAR (50)  NOT NULL,
    [PERIODE_YEAR]   NVARCHAR (4)   NOT NULL,
    [PERIODE_MONTH]  NVARCHAR (2)   NOT NULL,
    [DSR_PCT]        DECIMAL (9, 6) NOT NULL,
    [IDIR_PCT]       DECIMAL (9, 6) NOT NULL,
    [DBR_PCT]        DECIMAL (9, 6) NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_APPLICATION_FINANCIAL_ANALYSIS] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_APPLICATION_FINANCIAL_ANALYSIS_APPLICATION_MAIN] FOREIGN KEY ([APPLICATION_NO]) REFERENCES [dbo].[APPLICATION_MAIN] ([APPLICATION_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

