CREATE TABLE [dbo].[AR_DAILY_BALANCING] (
    [ID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_NO] NVARCHAR (50)   NOT NULL,
    [CLIENT_NAME]  NVARCHAR (250)  NOT NULL,
    [AR_DUE]       DECIMAL (18, 2) NULL,
    [AR_NOT_DUE]   DECIMAL (18, 2) NULL,
    [EOD_DATE]     DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_EOD_DATE_20240603]
    ON [dbo].[AR_DAILY_BALANCING]([EOD_DATE] ASC);

