CREATE TABLE [dbo].[AREA_BLACKLIST_TRANSACTION_DETAIL] (
    [ID]                              BIGINT          IDENTITY (1, 1) NOT NULL,
    [AREA_BLACKLIST_TRANSACTION_CODE] NVARCHAR (50)   NOT NULL,
    [PROVINCE_CODE]                   NVARCHAR (50)   NULL,
    [CITY_CODE]                       NVARCHAR (50)   NULL,
    [PROVINCE_NAME]                   NVARCHAR (4000) NULL,
    [CITY_NAME]                       NVARCHAR (4000) NULL,
    [CRE_DATE]                        DATETIME        NOT NULL,
    [CRE_BY]                          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                        DATETIME        NOT NULL,
    [MOD_BY]                          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_AREA_BLACKLIST_TRANSACTION_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AREA_BLACKLIST_TRANSACTION_DETAIL_AREA_BLACKLIST_TRANSACTION] FOREIGN KEY ([AREA_BLACKLIST_TRANSACTION_CODE]) REFERENCES [dbo].[AREA_BLACKLIST_TRANSACTION] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

