CREATE TABLE [dbo].[AREA_BLACKLIST] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [SOURCE]         NVARCHAR (10)   NOT NULL,
    [PROVINCE_CODE]  NVARCHAR (50)   NOT NULL,
    [CITY_CODE]      NVARCHAR (50)   NULL,
    [PROVINCE_NAME]  NVARCHAR (4000) NOT NULL,
    [CITY_NAME]      NVARCHAR (4000) NULL,
    [ENTRY_DATE]     DATETIME        NOT NULL,
    [ENTRY_REMARKS]  NVARCHAR (4000) NOT NULL,
    [EXIT_DATE]      DATETIME        NULL,
    [EXIT_REMARKS]   NVARCHAR (4000) NULL,
    [IS_ACTIVE]      NVARCHAR (1)    NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_AREA_BLACKLIST] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

