CREATE TABLE [dbo].[ASSET_REPLACEMENT_RETURN] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [REPLACEMENT_CODE] NVARCHAR (50)   NOT NULL,
    [NEW_ASSET_CODE]   NVARCHAR (50)   NOT NULL,
    [REASON_CODE]      NVARCHAR (50)   NOT NULL,
    [ESTIMATE_DATE]    DATETIME        NULL,
    [REMARK]           NVARCHAR (4000) NULL,
    [STATUS]           NVARCHAR (10)   NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

