CREATE TABLE [dbo].[ASSET_REPLACEMENT_DETAIL] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [REPLACEMENT_CODE]      NVARCHAR (50)   NOT NULL,
    [OLD_ASSET_NO]          NVARCHAR (50)   NOT NULL,
    [NEW_FA_CODE]           NVARCHAR (50)   NOT NULL,
    [NEW_FA_NAME]           NVARCHAR (250)  CONSTRAINT [DF_ASSET_REPLACEMENT_DETAIL_NEW_FA_NAME] DEFAULT ('') NOT NULL,
    [NEW_FA_REF_NO_01]      NVARCHAR (50)   NULL,
    [NEW_FA_REF_NO_02]      NVARCHAR (50)   NULL,
    [NEW_FA_REF_NO_03]      NVARCHAR (50)   NULL,
    [REPLACEMENT_TYPE]      NVARCHAR (20)   NOT NULL,
    [REASON_CODE]           NVARCHAR (50)   NOT NULL,
    [ESTIMATE_RETURN_DATE]  DATETIME        NULL,
    [OLD_HANDOVER_IN_DATE]  DATETIME        NULL,
    [OLD_HANDOVER_OUT_DATE] DATETIME        NULL,
    [NEW_HANDOVER_OUT_DATE] DATETIME        NULL,
    [NEW_HANDOVER_IN_DATE]  DATETIME        NULL,
    [REMARK]                NVARCHAR (4000) NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [REFF_NO]               NVARCHAR (50)   NULL,
    [DELIVERY_ADDRESS]      NVARCHAR (4000) NULL,
    [CONTACT_NAME]          NVARCHAR (250)  NULL,
    [CONTACT_PHONE_NO]      NVARCHAR (50)   NULL,
    CONSTRAINT [PK__ASSET_RE__3214EC271E91848B] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ASSET_REPLACEMENT_DETAIL_ASSET_REPLACEMENT] FOREIGN KEY ([REPLACEMENT_CODE]) REFERENCES [dbo].[ASSET_REPLACEMENT] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_ASSET_REPLACEMENT_DETAIL_NEW_FA_CODE_20250615_20250615]
    ON [dbo].[ASSET_REPLACEMENT_DETAIL]([NEW_FA_CODE] ASC);

