CREATE TABLE [dbo].[ASSET_DELIVERY_DETAIL] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [DELIVERY_CODE]  NVARCHAR (50) NOT NULL,
    [ASSET_NO]       NVARCHAR (50) NOT NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_ASSET_DELIVERY_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ASSET_DELIVERY_DETAIL_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_ASSET_DELIVERY_DETAIL_ASSET_DELIVERY] FOREIGN KEY ([DELIVERY_CODE]) REFERENCES [dbo].[ASSET_DELIVERY] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor asset pada aplikasi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASSET_DELIVERY_DETAIL', @level2type = N'COLUMN', @level2name = N'ASSET_NO';

