CREATE TABLE [dbo].[ASSET_REPLACEMENT] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NOT NULL,
    [REMARK]         NVARCHAR (4000) NULL,
    [STATUS]         NVARCHAR (10)   NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK__ASSET_RE__AA1D43785F464D74] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

