CREATE TABLE [dbo].[BILLING_SCHEME] (
    [CODE]              NVARCHAR (50)  NOT NULL,
    [SCHEME_NAME]       NVARCHAR (250) NOT NULL,
    [CLIENT_NO]         NVARCHAR (50)  NOT NULL,
    [CLIENT_NAME]       NVARCHAR (250) NOT NULL,
    [BILLING_MODE]      NVARCHAR (10)  NULL,
    [BILLING_MODE_DATE] INT            NULL,
    [IS_ACTIVE]         NVARCHAR (1)   NOT NULL,
    [CRE_DATE]          DATETIME       NOT NULL,
    [CRE_BY]            NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    [MOD_DATE]          DATETIME       NOT NULL,
    [MOD_BY]            NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_BILLING_SCHEME] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

