CREATE TABLE [dbo].[BILLING_GENERATE_DETAIL] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [GENERATE_CODE]  NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [ASSET_NO]       NVARCHAR (50)   NOT NULL,
    [BILLING_NO]     INT             NOT NULL,
    [DUE_DATE]       DATETIME        NOT NULL,
    [BILLING_DATE]   DATETIME        NULL,
    [RENTAL_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) NOT NULL,
    [INVOICE_NO]     NVARCHAR (50)   NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_BILLING_GENERATE_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BILLING_GENERATE_DETAIL_BILLING_GENERATE] FOREIGN KEY ([GENERATE_CODE]) REFERENCES [dbo].[BILLING_GENERATE] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_BILLING_GENERATE_DETAIL_20230929]
    ON [dbo].[BILLING_GENERATE_DETAIL]([INVOICE_NO] ASC)
    INCLUDE([DUE_DATE]);


GO
CREATE NONCLUSTERED INDEX [IDX_BILLING_GENERATE_DETAIL_20231009]
    ON [dbo].[BILLING_GENERATE_DETAIL]([GENERATE_CODE] ASC)
    INCLUDE([ASSET_NO]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor aplikasi', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'BILLING_GENERATE_DETAIL', @level2type = N'COLUMN', @level2name = N'AGREEMENT_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor angsuran', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'BILLING_GENERATE_DETAIL', @level2type = N'COLUMN', @level2name = N'BILLING_NO';

