CREATE TABLE [dbo].[BUDGET_APPROVAL_DETAIL] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [BUDGET_APPROVAL_CODE] NVARCHAR (50)   NOT NULL,
    [COST_CODE]            NVARCHAR (50)   NOT NULL,
    [COST_TYPE]            NVARCHAR (10)   NOT NULL,
    [COST_AMOUNT_MONTHLY]  DECIMAL (18, 2) NOT NULL,
    [COST_AMOUNT_YEARLY]   DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [FK_BUDGET_APPROVAL_DETAIL_BUDGET_APPROVAL] FOREIGN KEY ([BUDGET_APPROVAL_CODE]) REFERENCES [dbo].[BUDGET_APPROVAL] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

