CREATE TABLE [dbo].[CLEANSING_NPWP$] (
    [AGREEMENT_NO]         NVARCHAR (255) NULL,
    [ASSET_NO]             NVARCHAR (255) NULL,
    [CLIENT_NAME]          NVARCHAR (255) NULL,
    [NPWP NO]              FLOAT (53)     NULL,
    [NPWP_NAME]            NVARCHAR (255) NULL,
    [NPWP_NAME SEHARUSNYA] NVARCHAR (255) NULL,
    [NO NPWP SEHARUSNYA]   NVARCHAR (255) NULL
);

