CREATE TABLE [dbo].[CLIENT_CORPORATE_NOTARIAL] (
    [CODE]                   NVARCHAR (50)   NOT NULL,
    [CLIENT_CODE]            NVARCHAR (50)   NOT NULL,
    [NOTARIAL_DOCUMENT_CODE] NVARCHAR (50)   NOT NULL,
    [DOCUMENT_NO]            NVARCHAR (50)   NOT NULL,
    [DOCUMENT_DATE]          DATETIME        NOT NULL,
    [NOTARY_NAME]            NVARCHAR (250)  NOT NULL,
    [SKMENKUMHAM_DOC_NO]     NVARCHAR (50)   NOT NULL,
    [SUGGEST_BY]             NVARCHAR (250)  NOT NULL,
    [MODAL_DASAR]            DECIMAL (18, 2) CONSTRAINT [DF_CLIENT_CORPORATE_NOTARIAL_MODAL_DASAR] DEFAULT ((0)) NOT NULL,
    [MODAL_SETOR]            DECIMAL (18, 2) CONSTRAINT [DF_CLIENT_CORPORATE_NOTARIAL_MODAL_SETOR] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_CORPORATE_NOTARIAL] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_CLIENT_CORPORATE_NOTARIAL_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_CLIENT_CORPORATE_NOTARIAL_SYS_GENERAL_SUBCODE] FOREIGN KEY ([NOTARIAL_DOCUMENT_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : CRPNTD', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLIENT_CORPORATE_NOTARIAL', @level2type = N'COLUMN', @level2name = N'NOTARIAL_DOCUMENT_CODE';

