CREATE TABLE [dbo].[CLIENT_BLACKLIST_HISTORY] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [CLIENT_BLACKLIST_CODE] NVARCHAR (50)   NOT NULL,
    [HISTORY_DATE]          DATETIME        NOT NULL,
    [HISTORY_REMARKS]       NVARCHAR (4000) NOT NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_BLACKLIST_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CLIENT_BLACKLIST_HISTORY_CLIENT_BLACKLIST] FOREIGN KEY ([CLIENT_BLACKLIST_CODE]) REFERENCES [dbo].[CLIENT_BLACKLIST] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

