CREATE TABLE [dbo].[CLIENT_BANK] (
    [CODE]               NVARCHAR (50)  NOT NULL,
    [CLIENT_CODE]        NVARCHAR (50)  NOT NULL,
    [CURRENCY_CODE]      NVARCHAR (3)   NOT NULL,
    [BANK_CODE]          NVARCHAR (50)  NOT NULL,
    [BANK_NAME]          NVARCHAR (250) NOT NULL,
    [BANK_BRANCH]        NVARCHAR (250) NULL,
    [BANK_ACCOUNT_NO]    NVARCHAR (50)  NOT NULL,
    [BANK_ACCOUNT_NAME]  NVARCHAR (250) NOT NULL,
    [IS_DEFAULT]         NVARCHAR (1)   CONSTRAINT [DF_CLIENT_BANK_IS_DEFAULT] DEFAULT ((0)) NOT NULL,
    [IS_AUTO_DEBET_BANK] NVARCHAR (1)   CONSTRAINT [DF_CLIENT_BANK_IS_AUTO_DEBET_BANK] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]           DATETIME       NOT NULL,
    [CRE_BY]             NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    [MOD_DATE]           DATETIME       NOT NULL,
    [MOD_BY]             NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_CLIENT_BANK] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_CLIENT_BANK_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

