CREATE TABLE [dbo].[CLIENT_CORPORATE_INFO] (
    [CLIENT_CODE]                  NVARCHAR (50)  NOT NULL,
    [FULL_NAME]                    NVARCHAR (50)  NOT NULL,
    [EST_DATE]                     DATETIME       NOT NULL,
    [CORPORATE_STATUS_CODE]        NVARCHAR (50)  NULL,
    [BUSINESS_LINE_CODE]           NVARCHAR (50)  NULL,
    [SUB_BUSINESS_LINE_CODE]       NVARCHAR (50)  NULL,
    [CORPORATE_TYPE_CODE]          NVARCHAR (50)  NULL,
    [BUSINESS_EXPERIENCE_YEAR]     INT            NULL,
    [EMAIL]                        NVARCHAR (50)  NULL,
    [WEBSITE]                      NVARCHAR (50)  NULL,
    [AREA_MOBILE_NO]               NVARCHAR (4)   NULL,
    [MOBILE_NO]                    NVARCHAR (15)  NULL,
    [AREA_FAX_NO]                  NVARCHAR (4)   NULL,
    [FAX_NO]                       NVARCHAR (15)  NULL,
    [CONTACT_PERSON_NAME]          NVARCHAR (250) NULL,
    [CONTACT_PERSON_AREA_PHONE_NO] NVARCHAR (4)   NULL,
    [CONTACT_PERSON_PHONE_NO]      NVARCHAR (15)  NULL,
    [CRE_DATE]                     DATETIME       NOT NULL,
    [CRE_BY]                       NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)  NOT NULL,
    [MOD_DATE]                     DATETIME       NOT NULL,
    [MOD_BY]                       NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_CLIENT_CORPORATE_INFO] PRIMARY KEY CLUSTERED ([CLIENT_CODE] ASC),
    CONSTRAINT [FK_CLIENT_CORPORATE_INFO_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_CLIENT_CORPORATE_INFO_SYS_GENERAL_SUBCODE] FOREIGN KEY ([CORPORATE_STATUS_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE]),
    CONSTRAINT [FK_CLIENT_CORPORATE_INFO_SYS_GENERAL_SUBCODE_DETAIL] FOREIGN KEY ([SUB_BUSINESS_LINE_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE_DETAIL] ([CODE]),
    CONSTRAINT [FK_CLIENT_CORPORATE_INFO_SYS_GENERAL_SUBCODE1] FOREIGN KEY ([CORPORATE_TYPE_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE]),
    CONSTRAINT [FK_CLIENT_CORPORATE_INFO_SYS_GENERAL_SUBCODE2] FOREIGN KEY ([BUSINESS_LINE_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : CRPSTS', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLIENT_CORPORATE_INFO', @level2type = N'COLUMN', @level2name = N'CORPORATE_STATUS_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : CRPTYP', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLIENT_CORPORATE_INFO', @level2type = N'COLUMN', @level2name = N'CORPORATE_TYPE_CODE';

