CREATE TABLE [dbo].[CLIENT_ASSET] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [CLIENT_CODE]     NVARCHAR (50)   NOT NULL,
    [ASSET_TYPE_CODE] NVARCHAR (50)   NOT NULL,
    [ASSET_NAME]      NVARCHAR (250)  CONSTRAINT [DF_SYS_CLIENT_ASSET_ASSET_NAME] DEFAULT (N'') NOT NULL,
    [ASSET_VALUE]     DECIMAL (18, 2) NOT NULL,
    [REFF_NO]         NVARCHAR (50)   NOT NULL,
    [LOCATION]        NVARCHAR (4000) CONSTRAINT [DF_SYS_CLIENT_ASSET_LOCATION] DEFAULT ('') NOT NULL,
    [REMARKS]         NVARCHAR (4000) CONSTRAINT [DF_SYS_CLIENT_ASSET_REMARKS] DEFAULT ('') NOT NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CLIENT_ASSET_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_CLIENT_ASSET_SYS_GENERAL_SUBCODE] FOREIGN KEY ([ASSET_TYPE_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE]),
    CONSTRAINT [FK_SYS_CLIENT_ASSET_SYS_GENERAL_SUBCODE] FOREIGN KEY ([ASSET_TYPE_CODE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : ASTTC', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLIENT_ASSET', @level2type = N'COLUMN', @level2name = N'ASSET_TYPE_CODE';

