CREATE TABLE [dbo].[CLIENT_PERSONAL_WORK] (
    [ID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [CLIENT_CODE]               NVARCHAR (50)   NOT NULL,
    [WORK_TYPE_CODE]            NVARCHAR (50)   CONSTRAINT [DF_CLIENT_PERSONAL_WORK_WORK_TYPE_CODE] DEFAULT (N'JOB0001') NOT NULL,
    [COMPANY_NAME]              NVARCHAR (250)  NOT NULL,
    [COMPANY_BUSINESS_LINE]     NVARCHAR (250)  NOT NULL,
    [COMPANY_SUB_BUSINESS_LINE] NVARCHAR (250)  NOT NULL,
    [AREA_PHONE_NO]             NVARCHAR (4)    NULL,
    [PHONE_NO]                  NVARCHAR (15)   NULL,
    [AREA_FAX_NO]               NVARCHAR (4)    NULL,
    [FAX_NO]                    NVARCHAR (15)   NULL,
    [WORK_DEPARTMENT_NAME]      NVARCHAR (250)  NOT NULL,
    [WORK_START_DATE]           DATETIME        NOT NULL,
    [WORK_END_DATE]             DATETIME        NULL,
    [WORK_POSITION]             NVARCHAR (250)  NOT NULL,
    [PROVINCE_CODE]             NVARCHAR (50)   NULL,
    [PROVINCE_NAME]             NVARCHAR (250)  NULL,
    [CITY_CODE]                 NVARCHAR (50)   NULL,
    [CITY_NAME]                 NVARCHAR (250)  NULL,
    [ZIP_CODE_CODE]             NVARCHAR (50)   NULL,
    [ZIP_CODE]                  NVARCHAR (50)   NULL,
    [ZIP_NAME]                  NVARCHAR (250)  NULL,
    [SUB_DISTRICT]              NVARCHAR (250)  NULL,
    [VILLAGE]                   NVARCHAR (250)  NULL,
    [ADDRESS]                   NVARCHAR (4000) NULL,
    [RT]                        NVARCHAR (5)    NULL,
    [RW]                        NVARCHAR (5)    NULL,
    [IS_LATEST]                 NVARCHAR (1)    NOT NULL,
    [CRE_DATE]                  DATETIME        NOT NULL,
    [CRE_BY]                    NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                  DATETIME        NOT NULL,
    [MOD_BY]                    NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_PERSONAL_WORK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CLIENT_PERSONAL_WORK_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

