CREATE TABLE [dbo].[CLIENT_REFERENCE] (
    [ID]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [CLIENT_CODE]             NVARCHAR (50)   NOT NULL,
    [REFERENCE_TYPE_CODE]     NVARCHAR (50)   NOT NULL,
    [REFERENCE_DATE]          DATETIME        NOT NULL,
    [REFERENCE_FULL_NAME]     NVARCHAR (250)  NOT NULL,
    [REFERENCE_ADDRESS]       NVARCHAR (4000) NOT NULL,
    [REFERENCE_IDENTITY_NO]   NVARCHAR (50)   NOT NULL,
    [REFERENCE_AREA_PHONE_NO] NVARCHAR (4)    NOT NULL,
    [REFERENCE_PHONE_NO]      NVARCHAR (15)   NOT NULL,
    [RELATIONSHIP]            NVARCHAR (250)  NOT NULL,
    [CRE_DATE]                DATETIME        NOT NULL,
    [CRE_BY]                  NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                DATETIME        NOT NULL,
    [MOD_BY]                  NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_REFERENCE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CLIENT_REFERENCE_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'REFFERENCE, EMERGENCY', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CLIENT_REFERENCE', @level2type = N'COLUMN', @level2name = N'REFERENCE_TYPE_CODE';

