CREATE TABLE [dbo].[CLIENT_KYC] (
    [CLIENT_CODE]      NVARCHAR (50)   NOT NULL,
    [AO_REMARK]        NVARCHAR (100)  NULL,
    [AO_SOURCE_FUND]   NVARCHAR (100)  NULL,
    [RESULT_STATUS]    NVARCHAR (20)   NULL,
    [RESULT_REMARK]    NVARCHAR (4000) NULL,
    [KYC_OFFICER_CODE] NVARCHAR (50)   NULL,
    [KYC_OFFICER_NAME] NVARCHAR (250)  NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_KYC] PRIMARY KEY CLUSTERED ([CLIENT_CODE] ASC),
    CONSTRAINT [FK_CLIENT_KYC_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

