CREATE TABLE [dbo].[CREDIT_NOTE_DETAIL] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [CREDIT_NOTE_CODE]  NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]        NVARCHAR (50)   NOT NULL,
    [INVOICE_DETAIL_ID] BIGINT          NOT NULL,
    [ADJUSTMENT_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_Table_1_TOTAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NEW_RENTAL_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_CREDIT_NOTE_DETAIL_NEW_RENTAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NEW_PPN_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_CREDIT_NOTE_DETAIL_PPN_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NEW_PPH_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_CREDIT_NOTE_DETAIL_PPH_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NEW_TOTAL_AMOUNT]  DECIMAL (18, 2) CONSTRAINT [DF_CREDIT_NOTE_DETAIL_TOTAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CREDIT_NOTE_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_CREDIT_NOTE_DETAIL_20241105]
    ON [dbo].[CREDIT_NOTE_DETAIL]([CREDIT_NOTE_CODE] ASC, [INVOICE_DETAIL_ID] ASC)
    INCLUDE([ADJUSTMENT_AMOUNT], [NEW_PPN_AMOUNT]);

