CREATE TABLE [dbo].[DESKCOLL_COSTUMER_INFO] (
    [DESKCOLL_ID]        BIGINT          NOT NULL,
    [CUSTOMER_CLIENT_NO] NVARCHAR (50)   NULL,
    [INVOICE_NO]         NVARCHAR (50)   NULL,
    [INVOICE_DUE_DATE]   DATETIME        NULL,
    [TRANSACTION_AMOUNT] DECIMAL (18, 2) NULL,
    [OS_INVOICE_AMOUNT]  DECIMAL (18, 2) NULL,
    [CRE_DATE]           DATETIME        NOT NULL,
    [CRE_BY]             NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_BY]             NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DESKCOLL_COSTUMER_INFO] PRIMARY KEY CLUSTERED ([DESKCOLL_ID] ASC)
);

