CREATE TABLE [dbo].[DOCUMENT_TBO] (
    [CODE]             NVARCHAR (50) NOT NULL,
    [MAIN_CONTRACT_NO] NVARCHAR (50) NULL,
    [STATUS]           NVARCHAR (50) NULL,
    [CRE_DATE]         DATETIME      NOT NULL,
    [CRE_BY]           NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    [MOD_DATE]         DATETIME      NOT NULL,
    [MOD_BY]           NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_DOCUMENT_TBO] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

