CREATE TABLE [dbo].[DUE_DATE_CHANGE_AMORTIZATION_HISTORY] (
    [DUE_DATE_CHANGE_CODE] NVARCHAR (50)   NOT NULL,
    [INSTALLMENT_NO]       INT             NOT NULL,
    [ASSET_NO]             NVARCHAR (50)   NOT NULL,
    [DUE_DATE]             DATETIME        NOT NULL,
    [BILLING_DATE]         DATETIME        NOT NULL,
    [BILLING_AMOUNT]       DECIMAL (18, 2) CONSTRAINT [DF_DUE_DATE_CHANGE_AMORTIZATION_HISTORY_INSTALLMENT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]          NVARCHAR (4000) CONSTRAINT [DF_DUE_DATE_CHANGE_AMORTIZATION_HISTORY_DESCRIPTION] DEFAULT ('') NOT NULL,
    [OLD_OR_NEW]           NVARCHAR (3)    NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_DUE_DATE_CHANGE_AMORTIZATION_HISTORY] PRIMARY KEY CLUSTERED ([DUE_DATE_CHANGE_CODE] ASC, [INSTALLMENT_NO] ASC, [ASSET_NO] ASC, [OLD_OR_NEW] ASC),
    CONSTRAINT [FK_DUE_DATE_CHANGE_AMORTIZATION_HISTORY_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_DUE_DATE_CHANGE_AMORTIZATION_HISTORY_DUE_DATE_CHANGE_MAIN] FOREIGN KEY ([DUE_DATE_CHANGE_CODE]) REFERENCES [dbo].[DUE_DATE_CHANGE_MAIN] ([CODE])
);

