CREATE TABLE [dbo].[FAKTUR_REGISTRATION_DETAIL] (
    [ID]                BIGINT        IDENTITY (1, 1) NOT NULL,
    [REGISTRATION_CODE] NVARCHAR (50) NOT NULL,
    [YEAR]              NVARCHAR (4)  NOT NULL,
    [FAKTUR_NO]         NVARCHAR (50) NOT NULL,
    [CRE_DATE]          DATETIME      NOT NULL,
    [CRE_BY]            NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15) NOT NULL,
    [MOD_DATE]          DATETIME      NOT NULL,
    [MOD_BY]            NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15) NOT NULL
);

