CREATE TABLE [dbo].[FAKTUR_REGISTRATION] (
    [CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]       NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]       NVARCHAR (250)  NOT NULL,
    [STATUS]            NVARCHAR (10)   NOT NULL,
    [REMARK]            NVARCHAR (4000) NOT NULL,
    [YEAR]              NVARCHAR (4)    NOT NULL,
    [FAKTUR_PREFIX]     NVARCHAR (15)   NOT NULL,
    [FAKTUR_RUNNING_NO] NVARCHAR (35)   NOT NULL,
    [FAKTUR_POSTFIX]    NVARCHAR (10)   NOT NULL,
    [COUNT]             INT             NOT NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FAKTUR_REGISTRATION] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

