CREATE TABLE [dbo].[FAKTUR_NO_REPLACEMENT_DETAIL] (
    [ID]                                BIGINT          IDENTITY (1, 1) NOT NULL,
    [FAKTUR_NO_REPLACEMENT_CODE]        NVARCHAR (50)   NOT NULL,
    [USER_ID]                           NVARCHAR (50)   NOT NULL,
    [UPLOAD_DATE]                       DATETIME        NOT NULL,
    [NPWP_PEMBELI_OR_IDENTITAS_LAINNYA] NVARCHAR (50)   NOT NULL,
    [NAMA_PEMBELI]                      NVARCHAR (50)   NOT NULL,
    [KODE_TRANSAKSI]                    NVARCHAR (50)   NOT NULL,
    [NOMOR_FAKTUR_PAJAK]                NVARCHAR (50)   NOT NULL,
    [TANGGAL_FAKTUR_PAJAK]              DATETIME        NOT NULL,
    [MASA_OR_PAJAK]                     NVARCHAR (50)   NOT NULL,
    [TAHUN]                             NVARCHAR (50)   NOT NULL,
    [STATUS_FAKTUR]                     NVARCHAR (50)   NOT NULL,
    [HARGA_JUAL_OR_PENGGANTIAN_OR_DPP]  DECIMAL (18, 2) NOT NULL,
    [DPP_NILAI_LAIN_OR_DPP]             DECIMAL (18, 2) NOT NULL,
    [PPN]                               DECIMAL (18, 2) NOT NULL,
    [PPNBM]                             DECIMAL (18, 2) NOT NULL,
    [PENANDATANGAN]                     NVARCHAR (50)   NOT NULL,
    [REFERENSI]                         NVARCHAR (50)   NOT NULL,
    [DILAPORKAN_OLEH_PENJUAL]           NVARCHAR (50)   NOT NULL,
    [DILAPORKAN_OLEH_PEMUNGUT_PPN]      NVARCHAR (50)   NOT NULL,
    [FAKTUR_NO_BEFORE]                  NVARCHAR (50)   NOT NULL,
    [CRE_DATE]                          DATETIME        NOT NULL,
    [CRE_BY]                            NVARCHAR (50)   NOT NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (50)   NOT NULL,
    [MOD_DATE]                          DATETIME        NOT NULL,
    [MOD_BY]                            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_FAKTUR_NO_REPLACEMENT_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

