CREATE TABLE [dbo].[FAKTUR_ALLOCATION_DETAIL] (
    [ID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [ALLOCATION_CODE] NVARCHAR (50) NOT NULL,
    [INVOICE_NO]      NVARCHAR (50) NOT NULL,
    [FAKTUR_NO]       NVARCHAR (50) NOT NULL,
    [CRE_DATE]        DATETIME      NOT NULL,
    [CRE_BY]          NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15) NOT NULL,
    [MOD_DATE]        DATETIME      NOT NULL,
    [MOD_BY]          NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_FAKTUR_ALLOCATION_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FAKTUR_ALLOCATION_DETAIL_FAKTUR_ALLOCATION] FOREIGN KEY ([ALLOCATION_CODE]) REFERENCES [dbo].[FAKTUR_ALLOCATION] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

