CREATE TABLE [dbo].[FAKTUR_NO_REPLACEMENT_DETAIL_UPLOAD_1] (
    [ID]                                BIGINT         IDENTITY (1, 1) NOT NULL,
    [FAKTUR_NO_REPLACEMENT_CODE]        NVARCHAR (50)  NOT NULL,
    [USER_ID]                           NVARCHAR (50)  NOT NULL,
    [UPLOAD_DATE]                       DATETIME       NOT NULL,
    [NPWP_PEMBELI_OR_IDENTITAS_LAINNYA] NVARCHAR (250) NULL,
    [NAMA_PEMBELI]                      NVARCHAR (250) NULL,
    [KODE_TRANSAKSI]                    NVARCHAR (50)  NULL,
    [NOMOR_FAKTUR_PAJAK]                NVARCHAR (50)  NULL,
    [TANGGAL_FAKTUR_PAJAK]              NVARCHAR (50)  NULL,
    [MASA_OR_PAJAK]                     NVARCHAR (50)  NULL,
    [TAHUN]                             NVARCHAR (50)  NULL,
    [STATUS_FAKTUR]                     NVARCHAR (50)  NULL,
    [HARGA_JUAL_OR_PENGGANTIAN_OR_DPP]  NVARCHAR (50)  NULL,
    [DPP_NILAI_LAIN_OR_DPP]             NVARCHAR (50)  NULL,
    [PPN]                               NVARCHAR (50)  NULL,
    [PPNBM]                             NVARCHAR (50)  NULL,
    [PENANDATANGAN]                     NVARCHAR (50)  NULL,
    [REFERENSI]                         NVARCHAR (50)  NULL,
    [DILAPORKAN_OLEH_PENJUAL]           NVARCHAR (50)  NULL,
    [DILAPORKAN_OLEH_PEMUNGUT_PPN]      NVARCHAR (50)  NULL,
    [CRE_DATE]                          DATETIME       NULL,
    [CRE_BY]                            NVARCHAR (50)  NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (50)  NULL,
    [MOD_DATE]                          DATETIME       NULL,
    [MOD_BY]                            NVARCHAR (15)  NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_FAKTUR_NO_REPLACEMENT_DETAIL_UPLOAD_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);

