CREATE TABLE [dbo].[FAKTUR_CANCELATION_DETAIL] (
    [ID]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [CANCELATION_CODE] NVARCHAR (50) NOT NULL,
    [FAKTUR_NO]        NVARCHAR (50) NOT NULL,
    [CRE_DATE]         DATETIME      NOT NULL,
    [CRE_BY]           NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    [MOD_DATE]         DATETIME      NOT NULL,
    [MOD_BY]           NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    CONSTRAINT [FK_FAKTUR_CANCELATION_DETAIL_FAKTUR_CANCELATION] FOREIGN KEY ([CANCELATION_CODE]) REFERENCES [dbo].[FAKTUR_CANCELATION] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

