CREATE TABLE [dbo].[FAKTUR_NO_REPLACEMENT] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (50)   NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [REMARKS]        NVARCHAR (4000) NOT NULL,
    [STATUS]         NVARCHAR (20)   NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [validasi]       NVARCHAR (1)    NULL,
    CONSTRAINT [PK_FAKTUR_NO_REPLACEMENT] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

