CREATE TABLE [dbo].[FAKTUR_ALLOCATION] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [STATUS]         NVARCHAR (10)   NOT NULL,
    [REMARK]         NVARCHAR (4000) NOT NULL,
    [AS_OF_DATE]     DATETIME        NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_FAKTUR_ALLOCATION] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

