CREATE TABLE [dbo].[INVOICE_PPH_PAYMENT_DETAIL] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [TAX_PAYMENT_CODE] NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]       NVARCHAR (50)   NOT NULL,
    [PPH_AMOUNT]       DECIMAL (18, 2) CONSTRAINT [DF_Table_1_PPN_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_INVOICE_PPH_PAYMENT_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_INVOICE_PPH_PAYMENT_DETAIL_INVOICE_PPH_PAYMENT] FOREIGN KEY ([TAX_PAYMENT_CODE]) REFERENCES [dbo].[INVOICE_PPH_PAYMENT] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_PPH_PAYMENT_DETAIL', @level2type = N'COLUMN', @level2name = N'PPH_AMOUNT';

