CREATE TABLE [dbo].[INVOICE_DETAIL] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [INVOICE_NO]      NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]    NVARCHAR (50)   NULL,
    [ASSET_NO]        NVARCHAR (50)   NULL,
    [BILLING_NO]      INT             NOT NULL,
    [DESCRIPTION]     NVARCHAR (4000) NOT NULL,
    [QUANTITY]        INT             NOT NULL,
    [TAX_SCHEME_CODE] NVARCHAR (50)   NOT NULL,
    [TAX_SCHEME_NAME] NVARCHAR (250)  NOT NULL,
    [BILLING_AMOUNT]  DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_DETAIL_BILLING_AMOUNT] DEFAULT ((0)) NOT NULL,
    [DISCOUNT_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_DETAIL_DISCOUNT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PPN_PCT]         DECIMAL (9, 6)  CONSTRAINT [DF_INVOICE_DETAIL_PPN_PCT] DEFAULT ((0)) NOT NULL,
    [PPN_AMOUNT]      DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_DETAIL_PPN_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PPH_PCT]         DECIMAL (9, 6)  CONSTRAINT [DF_INVOICE_DETAIL_PPH_PCT] DEFAULT ((0)) NOT NULL,
    [PPH_AMOUNT]      DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_DETAIL_PPH_AMOUNT] DEFAULT ((0)) NOT NULL,
    [TOTAL_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_AGREEMENT_INVOICE_DETAIL_TOTAL_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_INVOICE_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AGREEMENT_INVOICE_DETAIL_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_AGREEMENT_INVOICE_DETAIL_AGREEMENT_INVOICE] FOREIGN KEY ([INVOICE_NO]) REFERENCES [dbo].[INVOICE] ([INVOICE_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL1]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20230929]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC)
    INCLUDE([ASSET_NO], [QUANTITY], [TOTAL_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20231003]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC)
    INCLUDE([QUANTITY], [BILLING_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20231003_2]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC, [ASSET_NO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20231003_3]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC)
    INCLUDE([ASSET_NO], [DESCRIPTION], [QUANTITY], [BILLING_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20231003_4]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC)
    INCLUDE([AGREEMENT_NO], [ASSET_NO], [BILLING_NO], [BILLING_AMOUNT], [DISCOUNT_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20231016]
    ON [dbo].[INVOICE_DETAIL]([AGREEMENT_NO] ASC)
    INCLUDE([ASSET_NO], [BILLING_NO], [INVOICE_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_DETAIL_20231019]
    ON [dbo].[INVOICE_DETAIL]([AGREEMENT_NO] ASC)
    INCLUDE([INVOICE_NO], [BILLING_AMOUNT]);


GO
CREATE NONCLUSTERED INDEX [IDX_invoice_detail_invoice]
    ON [dbo].[INVOICE_DETAIL]([INVOICE_NO] ASC)
    INCLUDE([AGREEMENT_NO]);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor aplikasi', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_DETAIL', @level2type = N'COLUMN', @level2name = N'AGREEMENT_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor angsuran', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_DETAIL', @level2type = N'COLUMN', @level2name = N'BILLING_NO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_DETAIL', @level2type = N'COLUMN', @level2name = N'PPN_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_DETAIL', @level2type = N'COLUMN', @level2name = N'PPH_AMOUNT';

