CREATE TABLE [dbo].[INVOICE_DELIVERY_DETAIL] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [DELIVERY_CODE]   NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]      NVARCHAR (50)   NOT NULL,
    [DELIVERY_STATUS] NVARCHAR (20)   NOT NULL,
    [DELIVERY_DATE]   DATETIME        NULL,
    [DELIVERY_REMARK] NVARCHAR (4000) NOT NULL,
    [RECEIVER_NAME]   NVARCHAR (250)  NULL,
    [FILE_NAME]       NVARCHAR (250)  NULL,
    [FILE_PATH]       NVARCHAR (250)  NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    CONSTRAINT [FK_INVOICE_DELIVERY_DETAIL_INVOICE] FOREIGN KEY ([INVOICE_NO]) REFERENCES [dbo].[INVOICE] ([INVOICE_NO]),
    CONSTRAINT [FK_INVOICE_DELIVERY_DETAIL_INVOICE_DELIVERY] FOREIGN KEY ([DELIVERY_CODE]) REFERENCES [dbo].[INVOICE_DELIVERY] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

