CREATE TABLE [dbo].[INVOICE_PPH] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [INVOICE_NO]        NVARCHAR (50)   NOT NULL,
    [SETTLEMENT_TYPE]   NVARCHAR (10)   NOT NULL,
    [SETTLEMENT_STATUS] NVARCHAR (10)   NOT NULL,
    [FILE_PATH]         NVARCHAR (250)  NULL,
    [FILE_NAME]         NVARCHAR (250)  NULL,
    [PAYMENT_REFF_NO]   NVARCHAR (50)   NULL,
    [PAYMENT_REFF_DATE] DATETIME        NULL,
    [TOTAL_PPH_AMOUNT]  DECIMAL (18, 2) CONSTRAINT [DF_INVOICE_PPH_TOTAL_PPH_AMOUNT] DEFAULT ((0)) NOT NULL,
    [AUDIT_CODE]        NVARCHAR (50)   NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_INVOICE_PPH] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AGREEMENT_INVOICE_PPH_AGREEMENT_INVOICE] FOREIGN KEY ([INVOICE_NO]) REFERENCES [dbo].[INVOICE] ([INVOICE_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_PPH_SETTLEMENT_STATUS]
    ON [dbo].[INVOICE_PPH]([SETTLEMENT_STATUS] ASC, [AUDIT_CODE] ASC)
    INCLUDE([INVOICE_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_INVOICE_PPH_INVOICE_NO]
    ON [dbo].[INVOICE_PPH]([INVOICE_NO] ASC, [AUDIT_CODE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'PAYMENT, UPLOAD', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_PPH', @level2type = N'COLUMN', @level2name = N'SETTLEMENT_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVOICE_PPH', @level2type = N'COLUMN', @level2name = N'TOTAL_PPH_AMOUNT';

