CREATE TABLE [dbo].[MAIN_CONTRACT_TC] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [MAIN_CONTRACT_NO] NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]      NVARCHAR (4000) NULL,
    [CRE_DATE]         DATETIME        NULL,
    [CRE_BY]           NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NULL,
    [MOD_DATE]         DATETIME        NULL,
    [MOD_BY]           NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NULL,
    CONSTRAINT [PK_MAIN_CONTRACT_TC_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MAIN_CONTRACT_TC_MAIN_CONTRACT_MAIN] FOREIGN KEY ([MAIN_CONTRACT_NO]) REFERENCES [dbo].[MAIN_CONTRACT_MAIN] ([MAIN_CONTRACT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

