CREATE TABLE [dbo].[MAIN_CONTRACT_CHARGES] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [MAIN_CONTRACT_NO]       NVARCHAR (50)   NOT NULL,
    [CHARGES_CODE]           NVARCHAR (50)   NOT NULL,
    [DAFAULT_CHARGES_RATE]   DECIMAL (9, 6)  CONSTRAINT [DF_MAIN_CONTRACT_CHARGES_CHARGES_RATE] DEFAULT ((0)) NOT NULL,
    [DAFAULT_CHARGES_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_MAIN_CONTRACT_CHARGES_CHARGES_AMOUNT1] DEFAULT ((0)) NOT NULL,
    [CALCULATE_BY]           NVARCHAR (10)   NOT NULL,
    [CHARGES_RATE]           DECIMAL (9, 6)  CONSTRAINT [DF_MAIN_CONTRACT_CHARGES_DAFAULT_CHARGES_RATE1] DEFAULT ((0)) NOT NULL,
    [CHARGES_AMOUNT]         DECIMAL (18, 2) CONSTRAINT [DF_MAIN_CONTRACT_CHARGES_CHARGES_AMOUNT] DEFAULT ((0)) NOT NULL,
    [NEW_CALCULATE_BY]       NVARCHAR (10)   NOT NULL,
    [NEW_CHARGES_RATE]       DECIMAL (9, 6)  NOT NULL,
    [NEW_CHARGES_AMOUNT]     DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MAIN_CONTRACT_CHARGES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MAIN_CONTRACT_CHARGES_MASTER_CHARGES] FOREIGN KEY ([MAIN_CONTRACT_NO]) REFERENCES [dbo].[MAIN_CONTRACT_MAIN] ([MAIN_CONTRACT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

