CREATE TABLE [dbo].[MASTER_CONTRACT_TERM_CONDITION] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [MAIN_CONTRACT_NO] NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]      NVARCHAR (4000) NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CONTRACT_TERM_CONDITION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

