CREATE TABLE [dbo].[MASTER_SCORING_DIMENSION] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [SCORING_CODE]   NVARCHAR (50)   NOT NULL,
    [REFF_ITEM_CODE] NVARCHAR (50)   NOT NULL,
    [REFF_ITEM_NAME] NVARCHAR (4000) NOT NULL,
    [DIMENSION_CODE] NVARCHAR (50)   NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_SCORING_DIMENSION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_SCORING_DIMENSION_Update_Audit]      
			ON [dbo].[MASTER_SCORING_DIMENSION]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([SCORING_CODE]) THEN '[SCORING_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([REFF_ITEM_CODE]) THEN '[REFF_ITEM_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([REFF_ITEM_NAME]) THEN '[REFF_ITEM_NAME]-' ELSE '' END + 
CASE WHEN UPDATE([DIMENSION_CODE]) THEN '[DIMENSION_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_SCORING_DIMENSION]
([ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_SCORING_DIMENSION]
([ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_SCORING_DIMENSION_Insert_Audit] 
			ON [dbo].[MASTER_SCORING_DIMENSION]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_SCORING_DIMENSION]
([ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_SCORING_DIMENSION_Delete_Audit]    
			ON [dbo].[MASTER_SCORING_DIMENSION]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_SCORING_DIMENSION]
([ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[SCORING_CODE],[REFF_ITEM_CODE],[REFF_ITEM_NAME],[DIMENSION_CODE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED