CREATE TABLE [dbo].[MASTER_CONTRACT_FINANCIAL_RECAPITULATION_DETAIL] (
    [ID]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [FINANCIAL_RECAPITULATION_CODE] NVARCHAR (50)   NOT NULL,
    [REPORT_TYPE]                   NVARCHAR (50)   NOT NULL,
    [STATEMENT_CODE]                NVARCHAR (50)   NOT NULL,
    [STATEMENT_DESCRIPTION]         NVARCHAR (250)  NOT NULL,
    [STATEMENT_PARENT_CODE]         NVARCHAR (50)   NULL,
    [STATEMENT_FROM_VALUE_AMOUNT]   DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CONTRACT_FINANCIAL_RECAPITULATION_DETAIL_STATEMENT_FROM_VALUE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [STATEMENT_TO_VALUE_AMOUNT]     DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CONTRACT_FINANCIAL_RECAPITULATION_DETAIL_STATEMENT_TO_VALUE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [STATEMENT_RATIO_PCT]           DECIMAL (9, 6)  CONSTRAINT [DF_MASTER_CONTRACT_FINANCIAL_RECAPITULATION_DETAIL_STATEMENT_RATIO_PCT] DEFAULT ((0)) NOT NULL,
    [LEVEL_KEY]                     INT             NOT NULL,
    [ORDER_KEY]                     INT             NOT NULL,
    [CRE_DATE]                      DATETIME        NOT NULL,
    [CRE_BY]                        NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                      DATETIME        NOT NULL,
    [MOD_BY]                        NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CONTRACT_FINANCIAL_RECAPITULATION_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : FINRPT', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_CONTRACT_FINANCIAL_RECAPITULATION_DETAIL', @level2type = N'COLUMN', @level2name = N'REPORT_TYPE';

