CREATE TABLE [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [BUDGET_INSURANCE_RATE_CODE] NVARCHAR (50)   NOT NULL,
    [SUM_INSURED_FROM]           DECIMAL (18, 2) NOT NULL,
    [SUM_INSURED_TO]             DECIMAL (18, 2) NOT NULL,
    [REGION_CODE]                NVARCHAR (50)   NOT NULL,
    [REGION_DESCRIPTION]         NVARCHAR (250)  NOT NULL,
    [RATE_1]                     DECIMAL (9, 6)  NOT NULL,
    [RATE_2]                     DECIMAL (9, 6)  NOT NULL,
    [RATE_3]                     DECIMAL (9, 6)  NOT NULL,
    [RATE_4]                     DECIMAL (9, 6)  NOT NULL,
    [CRE_DATE]                   DATETIME        NOT NULL,
    [CRE_BY]                     NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                   DATETIME        NOT NULL,
    [MOD_BY]                     NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_BUDGET_ISURANCE_RATE_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MASTER_BUDGET_INSURANCE_RATE_DETAIL_MASTER_BUDGET_INSURANCE_RATE] FOREIGN KEY ([BUDGET_INSURANCE_RATE_CODE]) REFERENCES [dbo].[MASTER_BUDGET_INSURANCE_RATE] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL_Insert_Audit] 
			ON [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_DETAIL]
([ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL_Update_Audit]      
			ON [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([BUDGET_INSURANCE_RATE_CODE]) THEN '[BUDGET_INSURANCE_RATE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([SUM_INSURED_FROM]) THEN '[SUM_INSURED_FROM]-' ELSE '' END + 
CASE WHEN UPDATE([SUM_INSURED_TO]) THEN '[SUM_INSURED_TO]-' ELSE '' END + 
CASE WHEN UPDATE([REGION_CODE]) THEN '[REGION_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([REGION_DESCRIPTION]) THEN '[REGION_DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([RATE_1]) THEN '[RATE_1]-' ELSE '' END + 
CASE WHEN UPDATE([RATE_2]) THEN '[RATE_2]-' ELSE '' END + 
CASE WHEN UPDATE([RATE_3]) THEN '[RATE_3]-' ELSE '' END + 
CASE WHEN UPDATE([RATE_4]) THEN '[RATE_4]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_DETAIL]
([ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_DETAIL]
([ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL_Delete_Audit]    
			ON [dbo].[MASTER_BUDGET_INSURANCE_RATE_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_DETAIL]
([ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_INSURANCE_RATE_CODE],[SUM_INSURED_FROM],[SUM_INSURED_TO],[REGION_CODE],[REGION_DESCRIPTION],[RATE_1],[RATE_2],[RATE_3],[RATE_4],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED