CREATE TABLE [dbo].[MASTER_CONTRACT_CHARGES] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [MAIN_CONTRACT_NO]       NVARCHAR (50)   NOT NULL,
    [CHARGES_CODE]           NVARCHAR (50)   NOT NULL,
    [DAFAULT_CHARGES_RATE]   DECIMAL (9, 6)  CONSTRAINT [DF_MASTER_CONTRACT_CHARGES_DAFAULT_CHARGES_RATE] DEFAULT ((0)) NULL,
    [DAFAULT_CHARGES_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CONTRACT_CHARGES_DAFAULT_CHARGES_AMOUNT] DEFAULT ((0)) NULL,
    [CALCULATE_BY]           NVARCHAR (10)   NULL,
    [CHARGES_RATE]           DECIMAL (9, 6)  CONSTRAINT [DF_MASTER_CONTRACT_CHARGES_CHARGES_RATE] DEFAULT ((0)) NULL,
    [CHARGES_AMOUNT]         DECIMAL (18, 2) CONSTRAINT [DF_MASTER_CONTRACT_CHARGES_CHARGES_AMOUNT] DEFAULT ((0)) NULL,
    [NEW_CALCULATE_BY]       NVARCHAR (10)   NULL,
    [NEW_CHARGES_RATE]       DECIMAL (9, 6)  NULL,
    [NEW_CHARGES_AMOUNT]     DECIMAL (18, 2) NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CONTRACT_CHARGES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

