CREATE TABLE [dbo].[MASTER_FINANCIAL_STATEMENT] (
    [CODE]           NVARCHAR (50)  NOT NULL,
    [REPORT_TYPE]    NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]    NVARCHAR (250) NOT NULL,
    [PARENT_CODE]    NVARCHAR (50)  NULL,
    [TYPE]           NVARCHAR (10)  NOT NULL,
    [LEVEL_KEY]      INT            NOT NULL,
    [ORDER_KEY]      INT            NOT NULL,
    [IS_ACTIVE]      NVARCHAR (1)   NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_FINANCIAL_STATEMENT] PRIMARY KEY CLUSTERED ([CODE] ASC, [REPORT_TYPE] ASC),
    CONSTRAINT [FK_MASTER_FINANCIAL_STATEMENT_SYS_GENERAL_SUBCODE] FOREIGN KEY ([REPORT_TYPE]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE])
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_FINANCIAL_STATEMENT_Insert_Audit] 
			ON [dbo].[MASTER_FINANCIAL_STATEMENT]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_FINANCIAL_STATEMENT]
([CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_FINANCIAL_STATEMENT_Delete_Audit]    
			ON [dbo].[MASTER_FINANCIAL_STATEMENT]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_FINANCIAL_STATEMENT]
([CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_FINANCIAL_STATEMENT_Update_Audit]      
			ON [dbo].[MASTER_FINANCIAL_STATEMENT]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([REPORT_TYPE]) THEN '[REPORT_TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([DESCRIPTION]) THEN '[DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([PARENT_CODE]) THEN '[PARENT_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TYPE]) THEN '[TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([LEVEL_KEY]) THEN '[LEVEL_KEY]-' ELSE '' END + 
CASE WHEN UPDATE([ORDER_KEY]) THEN '[ORDER_KEY]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_FINANCIAL_STATEMENT]
([CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_FINANCIAL_STATEMENT]
([CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[REPORT_TYPE],[DESCRIPTION],[PARENT_CODE],[TYPE],[LEVEL_KEY],[ORDER_KEY],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GC : FINRPT', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_FINANCIAL_STATEMENT', @level2type = N'COLUMN', @level2name = N'REPORT_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'HEADER, PARENT,DETAIL', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_FINANCIAL_STATEMENT', @level2type = N'COLUMN', @level2name = N'TYPE';

