CREATE TABLE [dbo].[MASTER_BUDGET_DETAIL] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [BUDGET_CODE]    NVARCHAR (50)  NOT NULL,
    [EFF_DATE]       DATETIME       NOT NULL,
    [BUDGET_RATE]    DECIMAL (9, 6) NOT NULL,
    [BASE_CALCULATE] NVARCHAR (10)  NOT NULL,
    [CYCLE]          NVARCHAR (20)  NOT NULL,
    [CRE_DATE]       DATETIME       NOT NULL,
    [CRE_BY]         NVARCHAR (15)  NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    [MOD_DATE]       DATETIME       NOT NULL,
    [MOD_BY]         NVARCHAR (15)  NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_MASTER_BUDGET_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MASTER_BUDGET_DETAIL_MASTER_BUDGET_DETAIL] FOREIGN KEY ([BUDGET_CODE]) REFERENCES [dbo].[MASTER_BUDGET] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_DETAIL_Insert_Audit] 
			ON [dbo].[MASTER_BUDGET_DETAIL]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_DETAIL]
([ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_DETAIL_Delete_Audit]    
			ON [dbo].[MASTER_BUDGET_DETAIL]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_DETAIL]
([ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_DETAIL_Update_Audit]      
			ON [dbo].[MASTER_BUDGET_DETAIL]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([BUDGET_CODE]) THEN '[BUDGET_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([EFF_DATE]) THEN '[EFF_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([BUDGET_RATE]) THEN '[BUDGET_RATE]-' ELSE '' END + 
CASE WHEN UPDATE([BASE_CALCULATE]) THEN '[BASE_CALCULATE]-' ELSE '' END + 
CASE WHEN UPDATE([CYCLE]) THEN '[CYCLE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_DETAIL]
([ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_DETAIL]
([ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[BUDGET_CODE],[EFF_DATE],[BUDGET_RATE],[BASE_CALCULATE],[CYCLE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END