CREATE TABLE [dbo].[MASTER_TRANSACTION_PARAMETER] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [TRANSACTION_CODE]       NVARCHAR (50)   NOT NULL,
    [PROCESS_CODE]           NVARCHAR (50)   NOT NULL,
    [ORDER_KEY]              INT             NOT NULL,
    [PARAMETER_AMOUNT]       DECIMAL (18, 2) CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_PARAMETER_AMOUNT] DEFAULT ((0)) NOT NULL,
    [IS_CALCULATE_BY_SYSTEM] NVARCHAR (1)    NOT NULL,
    [IS_TRANSACTION]         NVARCHAR (1)    NOT NULL,
    [IS_AMOUNT_EDITABLE]     NVARCHAR (1)    NOT NULL,
    [IS_DISCOUNT_EDITABLE]   NVARCHAR (1)    CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_IS_DISCOUNT_EDITABLE] DEFAULT ((0)) NOT NULL,
    [GL_LINK_CODE]           NVARCHAR (50)   NULL,
    [DISCOUNT_GL_LINK_CODE]  NVARCHAR (50)   NULL,
    [MAXIMUM_DISC_PCT]       DECIMAL (9, 6)  CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_MAXIMUM_DISC_PCT] DEFAULT ((0)) NOT NULL,
    [MAXIMUM_DISC_AMOUNT]    DECIMAL (18, 2) CONSTRAINT [DF_MASTER_TRANSACTION_PARAMETER_MAXIMUM_DISC_AMOUNT] DEFAULT ((0)) NOT NULL,
    [IS_JOURNAL]             NVARCHAR (1)    NOT NULL,
    [DEBET_OR_CREDIT]        NVARCHAR (10)   NULL,
    [IS_DISCOUNT_JURNAL]     NVARCHAR (1)    NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_TRANSACTION_PARAMETER] PRIMARY KEY CLUSTERED ([ID] ASC, [PROCESS_CODE] ASC, [TRANSACTION_CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_TRANSACTION_PARAMETER_Insert_Audit] 
			ON [dbo].[MASTER_TRANSACTION_PARAMETER]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_TRANSACTION_PARAMETER_Update_Audit]      
			ON [dbo].[MASTER_TRANSACTION_PARAMETER]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([TRANSACTION_CODE]) THEN '[TRANSACTION_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([PROCESS_CODE]) THEN '[PROCESS_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([ORDER_KEY]) THEN '[ORDER_KEY]-' ELSE '' END + 
CASE WHEN UPDATE([PARAMETER_AMOUNT]) THEN '[PARAMETER_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_CALCULATE_BY_SYSTEM]) THEN '[IS_CALCULATE_BY_SYSTEM]-' ELSE '' END + 
CASE WHEN UPDATE([IS_TRANSACTION]) THEN '[IS_TRANSACTION]-' ELSE '' END + 
CASE WHEN UPDATE([IS_AMOUNT_EDITABLE]) THEN '[IS_AMOUNT_EDITABLE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_DISCOUNT_EDITABLE]) THEN '[IS_DISCOUNT_EDITABLE]-' ELSE '' END + 
CASE WHEN UPDATE([GL_LINK_CODE]) THEN '[GL_LINK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([DISCOUNT_GL_LINK_CODE]) THEN '[DISCOUNT_GL_LINK_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([MAXIMUM_DISC_PCT]) THEN '[MAXIMUM_DISC_PCT]-' ELSE '' END + 
CASE WHEN UPDATE([MAXIMUM_DISC_AMOUNT]) THEN '[MAXIMUM_DISC_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_JOURNAL]) THEN '[IS_JOURNAL]-' ELSE '' END + 
CASE WHEN UPDATE([DEBET_OR_CREDIT]) THEN '[DEBET_OR_CREDIT]-' ELSE '' END + 
CASE WHEN UPDATE([IS_DISCOUNT_JURNAL]) THEN '[IS_DISCOUNT_JURNAL]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[MASTER_TRANSACTION_PARAMETER_Delete_Audit]    
			ON [dbo].[MASTER_TRANSACTION_PARAMETER]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_TRANSACTION_PARAMETER]
([ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[TRANSACTION_CODE],[PROCESS_CODE],[ORDER_KEY],[PARAMETER_AMOUNT],[IS_CALCULATE_BY_SYSTEM],[IS_TRANSACTION],[IS_AMOUNT_EDITABLE],[IS_DISCOUNT_EDITABLE],[GL_LINK_CODE],[DISCOUNT_GL_LINK_CODE],[MAXIMUM_DISC_PCT],[MAXIMUM_DISC_AMOUNT],[IS_JOURNAL],[DEBET_OR_CREDIT],[IS_DISCOUNT_JURNAL],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor urut pada data parameter transaksi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'ORDER_KEY';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nilai parameter pada data parameter transaksi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'PARAMETER_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Apakah parameter transaksi tersebut dihitung oleh sistem?', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_CALCULATE_BY_SYSTEM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Apakah data tersebut merupakan informasi atau transaksi? Jika data di tickmark maka akan digunakan sebagai komponen perhitungan', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_TRANSACTION';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Apakah nilai pada data parameter transaksi tersebut dapat dilakukan proses edit?', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_AMOUNT_EDITABLE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Apakah nilai diskon pada data parameter transaksi tersebut dapat dilakukan proses edit?', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_DISCOUNT_EDITABLE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode general ledger pada data parameter transaksi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'GL_LINK_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Kode general ledger diskon pada data parameter transaksi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'DISCOUNT_GL_LINK_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Persentase maksimal diskon pada data parameter transaksi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'MAXIMUM_DISC_PCT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nilai maksimal diskon pada data parameter transaksi tersebut', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'MAXIMUM_DISC_AMOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Apakah data parameter transaksi tersebut akan membentuk jurnal?', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'MASTER_TRANSACTION_PARAMETER', @level2type = N'COLUMN', @level2name = N'IS_JOURNAL';

