CREATE TABLE [dbo].[MASTER_CONTRACT_DOCUMENT] (
    [ID]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [MAIN_CONTRACT_NO] NVARCHAR (50)   NOT NULL,
    [DOCUMENT_CODE]    NVARCHAR (50)   NOT NULL,
    [REMARKS]          NVARCHAR (4000) NULL,
    [FILENAME]         NVARCHAR (250)  NOT NULL,
    [PATHS]            NVARCHAR (250)  NOT NULL,
    [EXPIRED_DATE]     DATETIME        NULL,
    [PROMISE_DATE]     DATETIME        NULL,
    [IS_REQUIRED]      NVARCHAR (1)    NOT NULL,
    [IS_VALID]         NVARCHAR (1)    CONSTRAINT [DF_MASTER_CONTRACT_DOCUMENT_IS_VALID] DEFAULT ((0)) NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_CONTRACT_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

