CREATE TABLE [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY] (
    [CODE]                 NVARCHAR (50)   NOT NULL,
    [TYPE]                 NVARCHAR (20)   NOT NULL,
    [COVERAGE_CODE]        NVARCHAR (50)   NOT NULL,
    [COVERAGE_DESCRIPTION] NVARCHAR (250)  NOT NULL,
    [COVERAGE_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [RATE_OF_LIMIT]        DECIMAL (9, 6)  NOT NULL,
    [EXP_DATE]             DATETIME        NULL,
    [IS_ACTIVE]            NVARCHAR (1)    NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MASTER_BUDGET_INSURANCE_RATE_LIABILITY] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY_Delete_Audit]    
			ON [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_LIABILITY]
([CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED
GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY_Insert_Audit] 
			ON [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_LIABILITY]
([CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY_Update_Audit]      
			ON [dbo].[MASTER_BUDGET_INSURANCE_RATE_LIABILITY]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([CODE]) THEN '[CODE]-' ELSE '' END + 
CASE WHEN UPDATE([TYPE]) THEN '[TYPE]-' ELSE '' END + 
CASE WHEN UPDATE([COVERAGE_CODE]) THEN '[COVERAGE_CODE]-' ELSE '' END + 
CASE WHEN UPDATE([COVERAGE_DESCRIPTION]) THEN '[COVERAGE_DESCRIPTION]-' ELSE '' END + 
CASE WHEN UPDATE([COVERAGE_AMOUNT]) THEN '[COVERAGE_AMOUNT]-' ELSE '' END + 
CASE WHEN UPDATE([RATE_OF_LIMIT]) THEN '[RATE_OF_LIMIT]-' ELSE '' END + 
CASE WHEN UPDATE([EXP_DATE]) THEN '[EXP_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([IS_ACTIVE]) THEN '[IS_ACTIVE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_LIABILITY]
([CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_MASTER_BUDGET_INSURANCE_RATE_LIABILITY]
([CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT [CODE],[TYPE],[COVERAGE_CODE],[COVERAGE_DESCRIPTION],[COVERAGE_AMOUNT],[RATE_OF_LIMIT],[EXP_DATE],[IS_ACTIVE],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END