CREATE TABLE [dbo].[MATURITY_AMORTIZATION_HISTORY] (
    [MATURITY_CODE]  NVARCHAR (50)   NOT NULL,
    [INSTALLMENT_NO] INT             NOT NULL,
    [ASSET_NO]       NVARCHAR (50)   NOT NULL,
    [DUE_DATE]       DATETIME        NOT NULL,
    [BILLING_DATE]   DATETIME        NOT NULL,
    [BILLING_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_MATURITY_AMORTIZATION_HISTORY_INSTALLMENT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) CONSTRAINT [DF_MATURITY_AMORTIZATION_HISTORY_DESCRIPTION] DEFAULT ('') NOT NULL,
    [OLD_OR_NEW]     NVARCHAR (3)    NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_MATURITY_AMORTIZATION_HISTORY] PRIMARY KEY CLUSTERED ([MATURITY_CODE] ASC, [INSTALLMENT_NO] ASC, [ASSET_NO] ASC),
    CONSTRAINT [FK_MATURITY_AMORTIZATION_HISTORY_AGREEMENT_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[AGREEMENT_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_MATURITY_AMORTIZATION_HISTORY_MATURITY] FOREIGN KEY ([MATURITY_CODE]) REFERENCES [dbo].[MATURITY] ([CODE])
);

