CREATE TABLE [dbo].[MIG_AGREEMENT_ASSET_BORROWING_RATE] (
    [AGREEMENT_NO]     NVARCHAR (50)   NULL,
    [ASSET_NO]         NVARCHAR (50)   NULL,
    [BORROWING_RATE]   DECIMAL (9, 6)  NULL,
    [CRE_DATE]         DATETIME        NULL,
    [CRE_BY]           NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NULL,
    [MOD_DATE]         DATETIME        NULL,
    [MOD_BY]           NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NULL,
    [BORROWING_AMOUNT] DECIMAL (18, 2) NULL
);

