CREATE TABLE [dbo].[OPL_INTERFACE_NOTIFICATION_REQUEST] (
    [ID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                      NVARCHAR (50)   NOT NULL,
    [REQUEST_STATUS]            NVARCHAR (250)  NOT NULL,
    [REQUEST_DATE]              DATETIME        NOT NULL,
    [REQUEST_SENT_DATE]         DATETIME        NOT NULL,
    [HEADER_MESSAGE]            NVARCHAR (250)  NOT NULL,
    [BODY_MESSAGE_1]            NVARCHAR (4000) NOT NULL,
    [BODY_MESSAGE_2]            NVARCHAR (4000) NULL,
    [BODY_MESSAGE_3]            NVARCHAR (4000) NULL,
    [REFERENCE_AMOUNT_1]        DECIMAL (18, 2) NULL,
    [REFERENCE_AMOUNT_2]        DECIMAL (18, 2) NULL,
    [REFERENCE_NO_1]            NVARCHAR (50)   NULL,
    [REFERENCE_NO_2]            NVARCHAR (50)   NULL,
    [REFERENCE_NAME_1]          NVARCHAR (250)  NULL,
    [REFERENCE_NAME_2]          NVARCHAR (250)  NULL,
    [SENDER_COMPANY_NAME]       NVARCHAR (250)  NULL,
    [SENDER_ADDRESS]            NVARCHAR (4000) NULL,
    [SENDER_POSITION]           NVARCHAR (250)  NULL,
    [SENDER_NAME]               NVARCHAR (250)  NULL,
    [SENDER_DEPARTMENT]         NVARCHAR (250)  NULL,
    [RECIPIENT_NAME]            NVARCHAR (250)  NOT NULL,
    [EMAIL]                     NVARCHAR (250)  NULL,
    [EMAIL_CC]                  NVARCHAR (250)  NULL,
    [EMAIL_BCC]                 NVARCHAR (250)  NULL,
    [AREA_PHONE_NO]             NVARCHAR (4)    NULL,
    [PHONE_NO]                  NVARCHAR (15)   NULL,
    [THIRD_PARTY_EMAIL]         NVARCHAR (250)  NULL,
    [THIRD_PARTY_EMAIL_CC]      NVARCHAR (250)  NULL,
    [THIRD_PARTY_EMAIL_BCC]     NVARCHAR (250)  NULL,
    [THIRD_PARTY_AREA_PHONE_NO] NVARCHAR (4)    NULL,
    [THIRD_PARTY_PHONE_NO]      NVARCHAR (15)   NULL,
    [STAFF_EMAIL]               NVARCHAR (250)  NULL,
    [STAFF_EMAIL_CC]            NVARCHAR (250)  NULL,
    [STAFF_EMAIL_BCC]           NVARCHAR (250)  NULL,
    [STAFF_AREA_PHONE_NO]       NVARCHAR (4)    NULL,
    [STAFF_PHONE_NO]            NVARCHAR (15)   NULL,
    [MEDIA_CODE]                NVARCHAR (50)   NULL,
    [TRANSACTION_TYPE_CODE]     NVARCHAR (50)   NULL,
    [MODULE_CODE]               NVARCHAR (50)   NULL,
    [CRE_DATE]                  DATETIME        NOT NULL,
    [CRE_BY]                    NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                  DATETIME        NOT NULL,
    [MOD_BY]                    NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_NOTIFICATION_REQUEST] PRIMARY KEY CLUSTERED ([ID] ASC, [CODE] ASC)
);

