CREATE TABLE [dbo].[OPL_INTERFACE_PAYMENT_REQUEST] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                  NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]           NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]           NVARCHAR (250)  NOT NULL,
    [PAYMENT_BRANCH_CODE]   NVARCHAR (50)   NOT NULL,
    [PAYMENT_BRANCH_NAME]   NVARCHAR (250)  NOT NULL,
    [PAYMENT_SOURCE]        NVARCHAR (50)   NOT NULL,
    [PAYMENT_REQUEST_DATE]  DATETIME        NOT NULL,
    [PAYMENT_SOURCE_NO]     NVARCHAR (50)   NOT NULL,
    [PAYMENT_STATUS]        NVARCHAR (10)   NOT NULL,
    [PAYMENT_CURRENCY_CODE] NVARCHAR (3)    NOT NULL,
    [PAYMENT_AMOUNT]        DECIMAL (18, 2) CONSTRAINT [OPL_INTERFACE_PAYMENT_REQUEST_PAYMENT_AMOUNT] DEFAULT ((0)) NOT NULL,
    [PAYMENT_TO]            NVARCHAR (250)  CONSTRAINT [OPL_INTERFACE_PAYMENT_REQUEST_PAYMENT_TO] DEFAULT (N'HOLD') NOT NULL,
    [PAYMENT_REMARKS]       NVARCHAR (4000) CONSTRAINT [OPL_INTERFACE_PAYMENT_REQUEST_PAYMENT_REMARKS] DEFAULT ('') NOT NULL,
    [TO_BANK_ACCOUNT_NAME]  NVARCHAR (250)  NOT NULL,
    [TO_BANK_NAME]          NVARCHAR (250)  NOT NULL,
    [TO_BANK_ACCOUNT_NO]    NVARCHAR (50)   NOT NULL,
    [PROCESS_DATE]          DATETIME        NULL,
    [PROCESS_REFF_NO]       NVARCHAR (50)   NULL,
    [PROCESS_REFF_NAME]     NVARCHAR (250)  NULL,
    [TAX_PAYER_REFF_CODE]   NVARCHAR (50)   NULL,
    [TAX_TYPE]              NVARCHAR (10)   NULL,
    [TAX_FILE_NO]           NVARCHAR (50)   NULL,
    [TAX_FILE_NAME]         NVARCHAR (250)  NULL,
    [MANUAL_UPLOAD_STATUS]  NVARCHAR (10)   CONSTRAINT [OPL_INTERFACE_PAYMENT_REQUEST_MANUAL_UPLOAD_STATUS] DEFAULT (N'AUTOMATIC') NULL,
    [MANUAL_UPLOAD_REMARKS] NVARCHAR (4000) CONSTRAINT [OPL_INTERFACE_PAYMENT_REQUEST_MANUAL_UPLOAD_REMARKS] DEFAULT (N'Result upload remark') NULL,
    [SETTLE_DATE]           DATETIME        NULL,
    [JOB_STATUS]            NVARCHAR (10)   CONSTRAINT [OPL_INTERFACE_PAYMENT_REQUEST_JOB_STATUS] DEFAULT (N'HOLD') NOT NULL,
    [FAILED_REMARKS]        NVARCHAR (4000) NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_PAYMENT_REQUEST] PRIMARY KEY CLUSTERED ([CODE] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'kode pembayar pajak di master setting.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OPL_INTERFACE_PAYMENT_REQUEST', @level2type = N'COLUMN', @level2name = N'TAX_PAYER_REFF_CODE';

