CREATE TABLE [dbo].[OPL_INTERFACE_CLIENT_BLACKLIST] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [SOURCE]         NVARCHAR (250)  NOT NULL,
    [BLACKLIST_TYPE] NVARCHAR (10)   NULL,
    [CLIENT_NO]      NVARCHAR (50)   NULL,
    [ENTRY_DATE]     DATETIME        NOT NULL,
    [ENTRY_REMARKS]  NVARCHAR (4000) NOT NULL,
    [EXIT_DATE]      DATETIME        NULL,
    [EXIT_REMARKS]   NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);

