CREATE TABLE [dbo].[OPL_INTERFACE_CLIENT_ADDRESS] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [CLIENT_CODE]    NVARCHAR (50)   NOT NULL,
    [ADDRESS]        NVARCHAR (4000) NOT NULL,
    [PROVINCE_CODE]  NVARCHAR (50)   NOT NULL,
    [PROVINCE_NAME]  NVARCHAR (250)  NOT NULL,
    [CITY_CODE]      NVARCHAR (50)   NOT NULL,
    [CITY_NAME]      NVARCHAR (250)  NOT NULL,
    [ZIP_CODE_CODE]  NVARCHAR (50)   NOT NULL,
    [ZIP_CODE]       NVARCHAR (50)   NOT NULL,
    [ZIP_NAME]       NVARCHAR (250)  NOT NULL,
    [SUB_DISTRICT]   NVARCHAR (250)  NOT NULL,
    [VILLAGE]        NVARCHAR (250)  NOT NULL,
    [RT]             NVARCHAR (5)    NOT NULL,
    [RW]             NVARCHAR (5)    NOT NULL,
    [AREA_PHONE_NO]  NVARCHAR (4)    NOT NULL,
    [PHONE_NO]       NVARCHAR (15)   NOT NULL,
    [IS_LEGAL]       NVARCHAR (1)    NOT NULL,
    [IS_COLLECTION]  NVARCHAR (1)    NOT NULL,
    [IS_MAILING]     NVARCHAR (1)    NOT NULL,
    [IS_RESIDENCE]   NVARCHAR (1)    NOT NULL,
    [RANGE_IN_KM]    DECIMAL (18, 2) NOT NULL,
    [OWNERSHIP]      NVARCHAR (50)   NOT NULL,
    [LENGHT_OF_STAY] INT             NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_CLIENT_ADDRESS] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_OPL_INTERFACE_CLIENT_ADDRESS_OPL_INTERFACE_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[OPL_INTERFACE_CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_OPL_INTERFACE_CLIENT_ADDRESS_SYS_GENERAL_SUBCODE] FOREIGN KEY ([OWNERSHIP]) REFERENCES [dbo].[SYS_GENERAL_SUBCODE] ([CODE])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ADDOWN', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OPL_INTERFACE_CLIENT_ADDRESS', @level2type = N'COLUMN', @level2name = N'OWNERSHIP';

