CREATE TABLE [dbo].[OPL_INTERFACE_MASTER_ITEM] (
    [ID]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [TYPE_ASSET_CODE]              NVARCHAR (50)   NULL,
    [ITEM_CODE]                    NVARCHAR (50)   NULL,
    [ITEM_NAME]                    NVARCHAR (250)  NULL,
    [MERK_CODE]                    NVARCHAR (50)   NULL,
    [MERK_NAME]                    NVARCHAR (250)  NULL,
    [MODEL_CODE]                   NVARCHAR (50)   NULL,
    [MODEL_NAME]                   NVARCHAR (250)  NULL,
    [TYPE_CODE]                    NVARCHAR (50)   NULL,
    [TYPE_NAME]                    NVARCHAR (250)  NULL,
    [CATEGORY_TYPE]                NVARCHAR (20)   NULL,
    [CLASS_TYPE_CODE]              NVARCHAR (50)   NULL,
    [CLASS_TYPE_NAME]              NVARCHAR (250)  NULL,
    [INSURANCE_ASSET_TYPE_CODE]    NVARCHAR (50)   NULL,
    [INSURANCE_ASSET_TYPE_NAME]    NVARCHAR (250)  NULL,
    [REGISTRATION_CLASS_TYPE_CODE] NVARCHAR (50)   NULL,
    [REGISTRATION_CLASS_TYPE_NAME] NVARCHAR (250)  NULL,
    [IS_SPAF]                      NVARCHAR (1)    CONSTRAINT [DF_OPL_INTERFACE_MASTER_ITEM_IS_SPAF] DEFAULT ((0)) NULL,
    [SPAF_PCT]                     DECIMAL (9, 6)  CONSTRAINT [DF_OPL_INTERFACE_MASTER_ITEM_SPAF_PCT] DEFAULT ((0)) NULL,
    [SETTLE_DATE]                  DATETIME        NULL,
    [JOB_STATUS]                   NVARCHAR (10)   CONSTRAINT [DF_OPL_INTERFACE_MASTER_ITEM_JOB_STATUS] DEFAULT (N'HOLD') NULL,
    [FAILED_REMARKS]               NVARCHAR (4000) NULL,
    [CRE_DATE]                     DATETIME        NOT NULL,
    [CRE_BY]                       NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_DATE]                     DATETIME        NOT NULL,
    [MOD_BY]                       NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_MASTER_ITEM] PRIMARY KEY CLUSTERED ([ID] ASC)
);

