CREATE TABLE [dbo].[OPL_INTERFACE_SCORING_REQUEST_DETAIL] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [SCORING_REQUEST_CODE] NVARCHAR (50)   NULL,
    [SCORING_ITEM_CODE]    NVARCHAR (50)   NULL,
    [SCORING_ITEM_VALUE]   NVARCHAR (4000) NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK__OPL_INTE__3214EC275C749788] PRIMARY KEY CLUSTERED ([ID] ASC)
);

