CREATE TABLE [dbo].[OPL_INTERFACE_FINAL_GRN_REQUEST] (
    [ID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [FINAL_GRN_REQUEST_NO] NVARCHAR (50)   NOT NULL,
    [APPLICATION_NO]       NVARCHAR (50)   NULL,
    [CLIENT_NAME]          NVARCHAR (250)  NULL,
    [BRANCH_CODE]          NVARCHAR (50)   NULL,
    [BRANCH_NAME]          NVARCHAR (250)  NULL,
    [REQUESTOR_NAME]       NVARCHAR (250)  NULL,
    [APPLICATION_DATE]     DATETIME        NULL,
    [TOTAL_PURCHASE_DATA]  INT             NULL,
    [STATUS]               NVARCHAR (15)   CONSTRAINT [DF_OPL_INTERFACE_FINAL_GRN_REQUEST_STATUS] DEFAULT (N'HOLD') NOT NULL,
    [JOB_STATUS]           NVARCHAR (10)   CONSTRAINT [DF_OPL_INTERFACE_FINAL_GRN_REQUEST_JOB_STATUS] DEFAULT (N'HOLD') NULL,
    [FAILED_REMARKS]       NVARCHAR (4000) NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_FINAL_GRN_REQUEST] PRIMARY KEY CLUSTERED ([FINAL_GRN_REQUEST_NO] ASC)
);

