CREATE TABLE [dbo].[OPL_INTERFACE_INCOME_LEDGER] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [ASSET_CODE]     NVARCHAR (50)   NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [REFF_CODE]      NVARCHAR (50)   NOT NULL,
    [REFF_NAME]      NVARCHAR (250)  NOT NULL,
    [REFF_REMARK]    NVARCHAR (4000) NOT NULL,
    [INCOME_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NULL,
    [CLIENT_NAME]    NVARCHAR (250)  NULL,
    [JOB_STATUS]     NVARCHAR (50)   NULL,
    [FAILED_REMARK]  NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_INCOME_LEDGER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

