CREATE TABLE [dbo].[OPL_INTERFACE_SURVEY_REQUEST] (
    [ID]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                         NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                  NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                  NVARCHAR (250)  NOT NULL,
    [REFF_CODE]                    NVARCHAR (50)   NOT NULL,
    [REFF_NAME]                    NVARCHAR (50)   NOT NULL,
    [REFF_OBJECT]                  NVARCHAR (4000) NULL,
    [REFF_REMARKS]                 NVARCHAR (4000) NOT NULL,
    [STATUS]                       NVARCHAR (10)   NOT NULL,
    [DATE]                         DATETIME        NOT NULL,
    [CURRENCY_CODE]                NVARCHAR (3)    NOT NULL,
    [SURVEYOR_CODE]                NVARCHAR (50)   NULL,
    [SURVEY_FEE_AMOUNT]            DECIMAL (18, 2) CONSTRAINT [DF_OPL_INTERFACE_SURVEY_REQUEST_SURVEY_FEE_AMOUNT] DEFAULT ((0)) NOT NULL,
    [SURVEY_RESULT_DATE]           DATETIME        NULL,
    [SURVEY_RESULT_VALUE]          NVARCHAR (250)  NULL,
    [SURVEY_RESULT_REMARKS]        NVARCHAR (4000) NULL,
    [PROCESS_DATE]                 DATETIME        NULL,
    [PROCESS_REFF_NO]              NVARCHAR (50)   NULL,
    [PROCESS_REFF_NAME]            NVARCHAR (250)  NULL,
    [SETTLE_DATE]                  DATETIME        NULL,
    [JOB_STATUS]                   NVARCHAR (10)   CONSTRAINT [DF_OPL_INTERFACE_SURVEY_REQUEST_JOB_STATUS] DEFAULT (N'HOLD') NULL,
    [FAILED_REMARKS]               NVARCHAR (4000) NULL,
    [APPLICATION_NO]               NVARCHAR (50)   NULL,
    [CONTACT_PERSON_NAME]          NVARCHAR (250)  NULL,
    [CONTACT_PERSON_AREA_PHONE_NO] NVARCHAR (4)    NULL,
    [CONTACT_PERSON_PHONE_NO]      NVARCHAR (15)   NULL,
    [ADDRESS]                      NVARCHAR (4000) NULL,
    [CRE_DATE]                     DATETIME        NOT NULL,
    [CRE_BY]                       NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                     DATETIME        NOT NULL,
    [MOD_BY]                       NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]               NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_SURVEY_REQUEST] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

