CREATE TABLE [dbo].[OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [GL_LINK_TRANSACTION_CODE] NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [GL_LINK_CODE]             NVARCHAR (50)   NOT NULL,
    [CONTRA_GL_LINK_CODE]      NVARCHAR (50)   NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NULL,
    [FACILITY_CODE]            NVARCHAR (50)   NULL,
    [FACILITY_NAME]            NVARCHAR (250)  NULL,
    [PURPOSE_LOAN_CODE]        NVARCHAR (50)   NULL,
    [PURPOSE_LOAN_NAME]        NVARCHAR (250)  NULL,
    [PURPOSE_LOAN_DETAIL_CODE] NVARCHAR (50)   NULL,
    [PURPOSE_LOAN_DETAIL_NAME] NVARCHAR (250)  NULL,
    [ORIG_CURRENCY_CODE]       NVARCHAR (3)    NOT NULL,
    [ORIG_AMOUNT_DB]           DECIMAL (18, 2) CONSTRAINT [DF_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_ORIG_AMOUNT_DB] DEFAULT ((0)) NOT NULL,
    [ORIG_AMOUNT_CR]           DECIMAL (18, 2) CONSTRAINT [DF_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_ORIG_AMOUNT_CR] DEFAULT ((0)) NOT NULL,
    [EXCH_RATE]                DECIMAL (9, 6)  CONSTRAINT [DF_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_EXCH_RATE] DEFAULT ((1)) NOT NULL,
    [BASE_AMOUNT_DB]           DECIMAL (18, 2) CONSTRAINT [DF_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_BASE_AMOUNT_DB] DEFAULT ((0)) NOT NULL,
    [BASE_AMOUNT_CR]           DECIMAL (18, 2) CONSTRAINT [DF_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_BASE_AMOUNT_CR] DEFAULT ((0)) NOT NULL,
    [DIVISION_CODE]            NVARCHAR (50)   NULL,
    [DIVISION_NAME]            NVARCHAR (250)  NULL,
    [DEPARTMENT_CODE]          NVARCHAR (50)   NULL,
    [DEPARTMENT_NAME]          NVARCHAR (250)  NULL,
    [REMARKS]                  NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [ADD_REFF_01]              NVARCHAR (50)   NULL,
    [ADD_REFF_02]              NVARCHAR (50)   NULL,
    [ADD_REFF_03]              NVARCHAR (50)   NULL,
    CONSTRAINT [FK_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION] FOREIGN KEY ([GL_LINK_TRANSACTION_CODE]) REFERENCES [dbo].[OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL_GL_LINK_TRANSACTION_CODE]
    ON [dbo].[OPL_INTERFACE_JOURNAL_GL_LINK_TRANSACTION_DETAIL]([GL_LINK_TRANSACTION_CODE] ASC)
    INCLUDE([ORIG_AMOUNT_DB], [ORIG_AMOUNT_CR]);

