CREATE TABLE [dbo].[OPL_INTERFACE_ASSET_VEHICLE_UPDATE] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [FA_CODE]        NVARCHAR (50)   NULL,
    [FA_REFF_NO_1]   NVARCHAR (50)   NULL,
    [FA_REFF_NO_2]   NVARCHAR (50)   NULL,
    [FA_REFF_NO_3]   NVARCHAR (50)   NULL,
    [SETTLE_DATE]    DATETIME        NULL,
    [JOB_STATUS]     NVARCHAR (10)   NULL,
    [FAILED_REMARKS] NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_ASSET] PRIMARY KEY CLUSTERED ([ID] ASC)
);

