CREATE TABLE [dbo].[OPL_INTERFACE_CLIENT_LOG] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [CLIENT_CODE]    NVARCHAR (50)   NOT NULL,
    [LOG_DATE]       DATETIME        NOT NULL,
    [LOG_REMARKS]    NVARCHAR (4000) NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_CLIENT_LOG] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_OPL_INTERFACE_CLIENT_LOG_OPL_INTERFACE_CLIENT_MAIN] FOREIGN KEY ([CLIENT_CODE]) REFERENCES [dbo].[OPL_INTERFACE_CLIENT_MAIN] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);

