CREATE TABLE [dbo].[OPL_INTERFACE_PURCHASE_ORDER_UPDATE] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [PURCHASE_CODE]  NVARCHAR (50)   NULL,
    [PO_CODE]        NVARCHAR (50)   NULL,
    [ETA_PO_DATE]    DATETIME        NULL,
    [SUPPLIER_CODE]  NVARCHAR (50)   NULL,
    [SUPPLIER_NAME]  NVARCHAR (250)  NULL,
    [UNIT_FROM]      NVARCHAR (25)   NULL,
    [SETTLE_DATE]    DATETIME        NULL,
    [JOB_STATUS]     NVARCHAR (10)   NULL,
    [FAILED_REMARKS] NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_PURCHASE_ORDER_UPDATE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

