CREATE TABLE [dbo].[OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL] (
    [ID]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [CASHIER_RECEIVED_REQUEST_CODE] NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                   NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                   NVARCHAR (250)  NOT NULL,
    [GL_LINK_CODE]                  NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]                  NVARCHAR (50)   NULL,
    [FACILITY_CODE]                 NVARCHAR (50)   NULL,
    [FACILITY_NAME]                 NVARCHAR (250)  NULL,
    [PURPOSE_LOAN_CODE]             NVARCHAR (50)   NULL,
    [PURPOSE_LOAN_NAME]             NVARCHAR (250)  NULL,
    [PURPOSE_LOAN_DETAIL_CODE]      NVARCHAR (50)   NULL,
    [PURPOSE_LOAN_DETAIL_NAME]      NVARCHAR (250)  NULL,
    [ORIG_CURRENCY_CODE]            NVARCHAR (3)    NOT NULL,
    [ORIG_AMOUNT]                   DECIMAL (18, 2) CONSTRAINT [DF_OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL_ORIG_AMOUNT] DEFAULT ((0)) NOT NULL,
    [DIVISION_CODE]                 NVARCHAR (50)   NULL,
    [DIVISION_NAME]                 NVARCHAR (250)  NULL,
    [DEPARTMENT_CODE]               NVARCHAR (50)   NULL,
    [DEPARTMENT_NAME]               NVARCHAR (250)  NULL,
    [REMARKS]                       NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                      DATETIME        NOT NULL,
    [CRE_BY]                        NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                      DATETIME        NOT NULL,
    [MOD_BY]                        NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    CONSTRAINT [FK_OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL_JOURNAL_GL_LINK] FOREIGN KEY ([GL_LINK_CODE]) REFERENCES [dbo].[JOURNAL_GL_LINK] ([CODE]) ON UPDATE CASCADE,
    CONSTRAINT [FK_OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL_OPL_INTERFACE_CASHIER_RECEIVED_REQUEST] FOREIGN KEY ([CASHIER_RECEIVED_REQUEST_CODE]) REFERENCES [dbo].[OPL_INTERFACE_CASHIER_RECEIVED_REQUEST] ([CODE]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IDX_OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL1]
    ON [dbo].[OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL]([CASHIER_RECEIVED_REQUEST_CODE] ASC);

