CREATE TABLE [dbo].[OPL_INTERFACE_SURVEY_REQUEST_DETAIL] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [SURVEY_REQUEST_CODE]   NVARCHAR (50)   NULL,
    [DIMENSION_CODE]        NVARCHAR (50)   NULL,
    [DIMENSION_DESCRIPTION] NVARCHAR (250)  NULL,
    [DIMENSION_VALUE]       NVARCHAR (4000) NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_OPL_INTERFACE_SURVEY_REQUEST_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

