CREATE TABLE [dbo].[REALIZATION_DETAIL] (
    [ID]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [REALIZATION_CODE] NVARCHAR (50) NOT NULL,
    [ASSET_NO]         NVARCHAR (50) NOT NULL,
    [CRE_DATE]         DATETIME      NOT NULL,
    [CRE_BY]           NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    [MOD_DATE]         DATETIME      NOT NULL,
    [MOD_BY]           NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_REALIZATION_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REALIZATION_DETAIL_APPLICATION_ASSET] FOREIGN KEY ([ASSET_NO]) REFERENCES [dbo].[APPLICATION_ASSET] ([ASSET_NO]),
    CONSTRAINT [FK_REALIZATION_DETAIL_REALIZATION_DETAIL] FOREIGN KEY ([REALIZATION_CODE]) REFERENCES [dbo].[REALIZATION] ([CODE])
);

