CREATE TABLE [dbo].[REALIZATION] (
    [CODE]                     NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NOT NULL,
    [STATUS]                   NVARCHAR (15)   NOT NULL,
    [DATE]                     DATETIME        NOT NULL,
    [REMARK]                   NVARCHAR (4000) NOT NULL,
    [APPLICATION_NO]           NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]             NVARCHAR (50)   NOT NULL,
    [AGREEMENT_EXTERNAL_NO]    NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]           DATETIME        NULL,
    [DELIVERY_FROM]            NVARCHAR (250)  NOT NULL,
    [DELIVERY_PIC_CODE]        NVARCHAR (50)   NULL,
    [DELIVERY_PIC_NAME]        NVARCHAR (250)  NULL,
    [DELIVERY_VENDOR_NAME]     NVARCHAR (250)  NULL,
    [DELIVERY_VENDOR_PIC_NAME] NVARCHAR (250)  NULL,
    [SIGNER_CODE]              NVARCHAR (50)   NULL,
    [SIGNER_NAME]              NVARCHAR (250)  NULL,
    [SIGNER_POSITION]          NVARCHAR (250)  NULL,
    [FILE_NAME]                NVARCHAR (250)  NULL,
    [FILE_PATH]                NVARCHAR (250)  NULL,
    [RESULT]                   NVARCHAR (4000) NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [reff_agreement_no]        NVARCHAR (50)   NULL,
    [FILE_MEMO]                NVARCHAR (250)  NULL,
    [FILE_PATH_MEMO]           NVARCHAR (250)  NULL,
    [EXP_DATE]                 DATETIME        NULL,
    CONSTRAINT [PK_REALIZATION_1] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

