CREATE TABLE [dbo].[RPT_DAILY_OVERDUE] (
    [BUCKET]                 INT             NULL,
    [CLIENT_NO]              NVARCHAR (1000) NULL,
    [CLIENT_NAME]            NVARCHAR (1000) NULL,
    [AGREEMENT_NO]           NVARCHAR (1000) NULL,
    [TYPE_UNIT]              NVARCHAR (1000) NULL,
    [JUMLAH_UNIT]            NVARCHAR (1000) NULL,
    [TENOR]                  NVARCHAR (1000) NULL,
    [INVOICE_TYPE]           NVARCHAR (1000) NULL,
    [BILLING_NO]             INT             NULL,
    [INVOICE_DATE]           DATETIME        NULL,
    [NEW_INVOICE_DATE]       DATETIME        NULL,
    [INVOICE_POSTING_DATE]   DATETIME        NULL,
    [INVOICE_NO]             NVARCHAR (1000) NULL,
    [PREVIOUS_INVOICE_NO]    NVARCHAR (1000) NULL,
    [PERIODE_SEWA]           NVARCHAR (1000) NULL,
    [TOP_DAYS]               NVARCHAR (1000) NULL,
    [INVOICE_DUE_DATE]       DATETIME        NULL,
    [LEASE_AMOUNT]           DECIMAL (18, 2) NULL,
    [BILLING_AMOUNT]         DECIMAL (18, 2) NULL,
    [CREDIT_AMOUNT]          DECIMAL (18, 2) NULL,
    [NEW_BILLING_AMOUNT]     DECIMAL (18, 2) NULL,
    [VAT_AMOUNT]             DECIMAL (18, 2) NULL,
    [BILLING_AMOUNT_INC_VAT] DECIMAL (18, 2) NULL,
    [PPH_AMOUNT]             DECIMAL (18, 2) NULL,
    [NETT_AMOUNT]            DECIMAL (18, 2) NULL,
    [OVERDUE_AMOUNT_INC_VAT] DECIMAL (18, 2) NULL,
    [OVERDUE_AMOUNT_EXC_VAT] DECIMAL (18, 2) NULL,
    [OD_DAYS]                NVARCHAR (1000) NULL,
    [PENALTY]                DECIMAL (18, 2) NULL,
    [INVOICE_DELIVERY_DATE]  DATETIME        NULL,
    [INVOICE_RECEIVED_DATE]  DATETIME        NULL,
    [RESULT_DESKCOLL]        NVARCHAR (1000) NULL,
    [REMARK_DESKCOLL]        NVARCHAR (1000) NULL,
    [PROMISE_DATE]           DATETIME        NULL,
    [AGREEMENT_STATUS]       NVARCHAR (1000) NULL,
    [GO_LIVE_AGREEMENT_DATE] DATETIME        NULL,
    [TERMINATION_STATUS]     NVARCHAR (1000) NULL,
    [TERMINATION_DATE]       DATETIME        NULL,
    [DESK_COLLECTOR]         NVARCHAR (1000) NULL,
    [MARKETING_NAME]         NVARCHAR (1000) NULL,
    [MARKETING_LEADER]       NVARCHAR (1000) NULL,
    [CLIENT_ADRESS]          NVARCHAR (1000) NULL,
    [BILLING_ADRESS]         NVARCHAR (1000) NULL,
    [CLIENT_EMAIL]           NVARCHAR (1000) NULL,
    [CLIENT_PHONE_NUMBER]    NVARCHAR (1000) NULL,
    [JUMLAH_INVOICE_PAID]    NVARCHAR (1000) NULL,
    [JUMLAH_INVOICE_NOTDUE]  NVARCHAR (1000) NULL,
    [report_company]         NVARCHAR (250)  NULL,
    [report_image]           NVARCHAR (250)  NULL,
    [report_title]           NVARCHAR (250)  NULL,
    [branch_code]            NVARCHAR (1000) NULL,
    [as_of_date]             DATETIME        NULL,
    [branch_name]            NVARCHAR (1000) NULL,
    [IS_CONDITION]           NVARCHAR (1)    NULL,
    [USER_ID]                NVARCHAR (15)   NULL,
    [PLAT_NO]                NVARCHAR (50)   NULL,
    [ITEM_NAME]              NVARCHAR (4000) NULL,
    [BILLING_DATE]           DATETIME        NULL,
    [REMARK]                 NVARCHAR (4000) NULL,
    [CONTACT_PERSON_NAME]    NVARCHAR (4000) NULL,
    [cre_date]               DATETIME        NULL
);

