CREATE TABLE [dbo].[RPT_SOMASI_PENYELESAIAN_KEWAJIBAN_DAN_PENGEMBALIAN_KENDARAAN_KEKURANGAN_PEMBAYARAN] (
    [USER_ID]               NVARCHAR (50)   NULL,
    [AGREEMENT_NO]          NVARCHAR (50)   NULL,
    [INVOICE_NO]            NVARCHAR (50)   NULL,
    [NOMINAL_INVOICE]       DECIMAL (18, 2) NULL,
    [NOMINAL_PEMBAYARAN]    DECIMAL (18, 2) NULL,
    [TANGGAL_PEMBAYARAN]    DATETIME        NULL,
    [KEKURANGAN_PEMBAYARAN] DECIMAL (18, 2) NULL,
    [PERJANJIAN_INDUK]      NVARCHAR (50)   NULL
);

