CREATE TABLE [dbo].[RPT_SURAT_TAGIH_WRITE_OFF_LAMPIRAN_II] (
    [USER_ID]         NVARCHAR (50)   NOT NULL,
    [SURAT_NO]        NVARCHAR (50)   NULL,
    [NO_PERJANJIAN]   NVARCHAR (50)   NULL,
    [NOMINAL_SEWA]    DECIMAL (18, 2) NULL,
    [PERIODE_SEWA]    NVARCHAR (50)   NULL,
    [NO_INVOICE]      NVARCHAR (50)   NULL,
    [NOMINAL_INVOICE] DECIMAL (18, 2) NULL,
    [TANGGAL_JT]      DATETIME        NULL
);

