CREATE TABLE [dbo].[RPT_EXT_DISBURSEMENT] (
    [ID]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [YEAR]                      NVARCHAR (4)    NULL,
    [MONTH]                     NVARCHAR (2)    NULL,
    [CONTRACT_NO]               NVARCHAR (50)   NULL,
    [SKDNO]                     NVARCHAR (50)   NULL,
    [OFFICEID]                  NVARCHAR (50)   NULL,
    [REGIONAL]                  NVARCHAR (50)   NULL,
    [BRANCH]                    NVARCHAR (250)  NULL,
    [BRAND_CATEGORY]            NVARCHAR (250)  NULL,
    [ASSET_BRAND_ID]            NVARCHAR (50)   NULL,
    [BRAND]                     NVARCHAR (250)  NULL,
    [ASSET_CONDITION]           NVARCHAR (50)   NULL,
    [ASSET_CATEGORY]            NVARCHAR (4000) NULL,
    [ASSET_TYPE_ID]             NVARCHAR (50)   NULL,
    [ASSET_TYPE]                NVARCHAR (250)  NULL,
    [ASSET_MODEL]               NVARCHAR (50)   NULL,
    [ASSET_MODEL_NAME]          NVARCHAR (250)  NULL,
    [MODELTYPEID]               NVARCHAR (50)   NULL,
    [MODELTYPENAME]             NVARCHAR (250)  NULL,
    [ECONOMICSECTORID]          NVARCHAR (50)   NULL,
    [DISBURSE_DATE]             DATETIME        NULL,
    [BUSINEES_TYPE]             NVARCHAR (250)  NULL,
    [FINANCE_TYPE]              NVARCHAR (250)  NULL,
    [PURPOSE_OF_FINANCE]        NVARCHAR (250)  NULL,
    [WAY_OF_FINANCE]            NVARCHAR (250)  NULL,
    [CAMPAIGN]                  NVARCHAR (50)   NULL,
    [CAMPAIGN_TYPE]             NVARCHAR (50)   NULL,
    [TENOR]                     INT             NULL,
    [PAYMENT_METHOD_ID]         NVARCHAR (50)   NULL,
    [PAYMENT_METHOD]            NVARCHAR (250)  NULL,
    [SUPPLIER_GROUP_ID]         NVARCHAR (50)   NULL,
    [GROUP_OF_SUPPLIER_COMPANY] NVARCHAR (250)  NULL,
    [SUPPLIER_ID]               NVARCHAR (50)   NULL,
    [SUPPLIER_COMPANY]          NVARCHAR (250)  NULL,
    [CURRENCY]                  NVARCHAR (3)    NULL,
    [MO_NAME]                   NVARCHAR (250)  NULL,
    [MO_ID]                     NVARCHAR (50)   NULL,
    [BUSINESS_SUB_CATEGORY]     NVARCHAR (50)   NULL,
    [PAYMENT_MODE]              NVARCHAR (15)   NULL,
    [INSURANCE_TYPE_ID]         NVARCHAR (50)   NULL,
    [INSURANCE_TYPE]            NVARCHAR (250)  NULL,
    [INSURANCE_COVERAGE]        NVARCHAR (50)   NULL,
    [SUPPLIER_COMPANY_BRANCH]   NVARCHAR (250)  NULL,
    [SUPPLIER_LOCATION]         NVARCHAR (50)   NULL,
    [PAYMENT_TYPE_ID]           NVARCHAR (50)   NULL,
    [PAYMENT_TYPE]              NVARCHAR (250)  NULL,
    [REPEAT_OR_NEW]             NVARCHAR (50)   NULL,
    [CUSTOMER_ID]               NVARCHAR (50)   NULL,
    [CUSTOMER_NAME]             NVARCHAR (250)  NULL,
    [NI]                        DECIMAL (18, 2) NULL,
    [INTEREST_RATE]             DECIMAL (9, 6)  NULL,
    [COST_PRICE]                DECIMAL (18, 2) NULL,
    [ACCOUNTING_BOOK_DATE]      DATETIME        NULL,
    [CRE_DATE]                  DATETIME        NULL,
    [CRE_BY]                    NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)   NULL,
    [MOD_DATE]                  DATETIME        NULL,
    [MOD_BY]                    NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)   NULL,
    [fa_code]                   NVARCHAR (50)   NULL,
    [registration_class_type]   NVARCHAR (50)   NULL,
    [asset_name]                NVARCHAR (4000) NULL,
    CONSTRAINT [PK__RPT_EXT___3214EC27D1E4A99F] PRIMARY KEY CLUSTERED ([ID] ASC)
);

