CREATE TABLE [dbo].[RPT_INVOICE_DENDA_KETERLAMBATAN_PENGEMBALIAN_ASSET_DETAIL] (
    [USER_ID]      NVARCHAR (50)   NOT NULL,
    [JENIS]        NVARCHAR (250)  NULL,
    [TYPE]         NVARCHAR (250)  NULL,
    [URAIAN]       NVARCHAR (250)  NULL,
    [NO_POLISI]    NVARCHAR (50)   NULL,
    [JUMLAH]       INT             NULL,
    [JUMLAH_DENDA] DECIMAL (18, 2) NULL,
    [JUMLAH_DESC]  NVARCHAR (250)  NULL
);

