CREATE TABLE [dbo].[RPT_QUOTATION] (
    [USER_ID]                       NVARCHAR (50)   NOT NULL,
    [APPLICATION_NO]                NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]                NVARCHAR (250)  NULL,
    [REPORT_TITLE]                  NVARCHAR (250)  NULL,
    [REPORT_IMAGE]                  NVARCHAR (250)  NULL,
    [TANGGAL]                       DATETIME        NULL,
    [SURAT_NO]                      NVARCHAR (50)   NULL,
    [KEPADA]                        NVARCHAR (250)  NULL,
    [MERK]                          NVARCHAR (50)   NULL,
    [MODEL]                         NVARCHAR (50)   NULL,
    [JENIS_BAHAN_BAKAR]             NVARCHAR (50)   NULL,
    [TRANSMISI]                     NVARCHAR (250)  NULL,
    [WARNA_PLAT]                    NVARCHAR (50)   NULL,
    [TAHUN]                         NVARCHAR (4)    NULL,
    [SILINDER]                      INT             NULL,
    [KODE_MESIN]                    NVARCHAR (50)   NULL,
    [KAPASITAS]                     INT             NULL,
    [MUATAN]                        INT             NULL,
    [TIPE_KAROSERI]                 NVARCHAR (50)   NULL,
    [NILAI_SISA]                    DECIMAL (18, 2) NULL,
    [BARU_ATAU_BEKAS]               NVARCHAR (50)   NULL,
    [AKSESORIS]                     NVARCHAR (250)  NULL,
    [PERIODE]                       INT             NULL,
    [TANGGAL_PENGIRIMAN]            DATETIME        NULL,
    [PEMAKAIAN_PERBLN]              INT             NULL,
    [NILAI_SEWA_PERBLN]             DECIMAL (18, 2) NULL,
    [UANG_JAMINAN]                  DECIMAL (18, 2) NULL,
    [TENGGANG_WAKTU]                INT             NULL,
    [LOKASI_PENGIRIMAN]             NVARCHAR (250)  NULL,
    [IS_KONTRAK_SEWA_TERMAKSUK]     NVARCHAR (1)    NULL,
    [IS_KONTRAK_SEWA_TDK_TERMAKSUK] NVARCHAR (1)    NULL,
    [IS_HARGA]                      NVARCHAR (1)    NULL,
    [IS_AKSESORIS]                  NVARCHAR (1)    NULL,
    [IS_STNK]                       NVARCHAR (1)    NULL,
    [IS_ASURANSI]                   NVARCHAR (1)    NULL,
    [IS_PENGANTI]                   NVARCHAR (1)    NULL,
    [IS_PERBAIKAN]                  NVARCHAR (1)    NULL,
    [IS_BANTUAN]                    NVARCHAR (1)    NULL,
    [IS_DARURAT]                    NVARCHAR (1)    NULL,
    [IS_LAIN_LAIN]                  NVARCHAR (1)    NULL,
    [IS_PEMELIHARAAN]               NVARCHAR (1)    NULL,
    [IS_SUKU_CADANG]                NVARCHAR (1)    NULL,
    [IS_OLI]                        NVARCHAR (1)    NULL,
    [IS_AKI]                        NVARCHAR (1)    NULL,
    [IS_BAN]                        NVARCHAR (1)    NULL,
    [IS_KONSUMEN]                   NVARCHAR (1)    NULL,
    [IS_KOMPREHENSIF_TERMAKSUK]     NVARCHAR (1)    NULL,
    [IS_KOMPREHENSIF_TDK_TERMASUK]  NVARCHAR (1)    NULL,
    [IS_THIRD_PARTY]                NVARCHAR (1)    NULL,
    [IS_PASSENGER]                  NVARCHAR (1)    NULL,
    [IS_PERSONAL_PASSENGER]         NVARCHAR (1)    NULL,
    [IS_PERSONAL_DRIVER]            NVARCHAR (1)    NULL,
    [IS_PEMOGOKAN]                  NVARCHAR (1)    NULL,
    [IS_TERORISME]                  NVARCHAR (1)    NULL,
    [IS_BANJIR]                     NVARCHAR (1)    NULL,
    [IS_GEMPA]                      NVARCHAR (1)    NULL,
    [IS_NILAI]                      NVARCHAR (1)    NULL,
    [KETERANGAN]                    NVARCHAR (250)  NULL,
    [CRE_DATE]                      DATETIME        NOT NULL,
    [CRE_BY]                        NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                      DATETIME        NOT NULL,
    [MOD_BY]                        NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [COMPANY_ADDRESS]               NVARCHAR (4000) NULL,
    [COMPANY_TELP]                  NVARCHAR (50)   NULL,
    [COMPANY_FAX]                   NVARCHAR (50)   NULL,
    [IS_COP]                        NVARCHAR (1)    NULL,
    [REPORT_ADDRESS]                NVARCHAR (250)  NULL
);

