CREATE TABLE [dbo].[RPT_SURVEY_TOP_CUSTOMER] (
    [USER_ID]           NVARCHAR (50) NOT NULL,
    [NAMA]              NVARCHAR (50) NULL,
    [BUSINESS]          NVARCHAR (50) NULL,
    [BUSINESS_LOCATION] NVARCHAR (50) NULL,
    [UNIT_OR_OMZET]     INT           NULL,
    [ADDITIONAL_INFO]   NVARCHAR (50) NULL
);

