CREATE TABLE [dbo].[RPT_SOMASI_LAMPIRAN_I] (
    [USER_ID]           NVARCHAR (50)  NULL,
    [LETTER_NO]         NVARCHAR (50)  NULL,
    [NOMOR_PERJANJIAN]  NVARCHAR (50)  NULL,
    [TANGGAL_PERJAJIAN] DATETIME       NULL,
    [TIPE_KENDARAAN]    NVARCHAR (250) NULL,
    [TAHUN_KENDARAAN]   NVARCHAR (4)   NULL,
    [NOMOR_RANGKA]      NVARCHAR (50)  NULL,
    [NOMOR_MESIN]       NVARCHAR (50)  NULL,
    [NOMOR_POLISI]      NVARCHAR (50)  NULL,
    [CRE_DATE]          DATETIME       NULL,
    [CRE_BY]            NVARCHAR (15)  NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)  NULL,
    [MOD_DATE]          DATETIME       NULL,
    [MOD_BY]            NVARCHAR (15)  NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)  NULL
);

