CREATE TABLE [dbo].[RPT_SURVEY_RENCANA_PENGADAAN] (
    [USER_ID]               NVARCHAR (50)   NOT NULL,
    [DESCRIPTION]           NVARCHAR (4000) NULL,
    [NI_AMOUNT]             DECIMAL (18, 2) NULL,
    [KOMODITI]              NVARCHAR (4000) NULL,
    [TUJUAN_PENGADAAN_UNIT] NVARCHAR (4000) NULL
);

