CREATE TABLE [dbo].[RPT_PERJANJIAN_PELAKSANAAN_REPRINT] (
    [USER_ID]                           NVARCHAR (50)   NOT NULL,
    [APPLICATION_NO]                    NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]                    NVARCHAR (250)  NULL,
    [REPORT_COMPANY_ADDRESS]            NVARCHAR (4000) NULL,
    [REPORT_TITLE]                      NVARCHAR (250)  NULL,
    [REPORT_IMAGE]                      NVARCHAR (250)  NULL,
    [AGREEMENT_EXTERNAL_NO]             NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]                    DATETIME        NULL,
    [CLIENT_NAME]                       NVARCHAR (250)  NULL,
    [MAIN_CONTRACT_NO]                  NVARCHAR (50)   NULL,
    [APPLICATION_DATE]                  DATETIME        NULL,
    [LOKASI_PENYERAHAN]                 NVARCHAR (4000) NULL,
    [LOKASI_PENGAMBILAN]                NVARCHAR (4000) NULL,
    [JANGKA_WAKTU]                      INT             NULL,
    [FROM_JANGKA_WAKTU]                 DATETIME        NULL,
    [END_JANGKA_WAKTU]                  DATETIME        NULL,
    [JENIS_KENDARAAN]                   NVARCHAR (250)  NULL,
    [JUMLAH]                            INT             NULL,
    [TAHUN]                             NVARCHAR (50)   NULL,
    [HARGA_SEWA_KESELURUHAN]            DECIMAL (18, 2) NULL,
    [HARGA_SEWA_PERBULAN]               DECIMAL (18, 2) NULL,
    [TANGGAL_BAYAR]                     NVARCHAR (4000) NULL,
    [TANGGAL_SEWA_SATU]                 NVARCHAR (4000) NULL,
    [STAR_SEWA_BERIKUTNYA]              NVARCHAR (50)   NULL,
    [END_SEWA_BERIKUTNYA]               NVARCHAR (50)   NULL,
    [METODE_PEMBAYARAN]                 NVARCHAR (50)   NULL,
    [PERSEN_DENDA]                      DECIMAL (9, 6)  NULL,
    [JARAK_TEMPU]                       INT             NULL,
    [BIAYA_KILOMETER]                   DECIMAL (18, 2) NULL,
    [GOLIVE_DATE]                       DATETIME        NULL,
    [EMPLOYEE_LESSOR]                   NVARCHAR (50)   NULL,
    [JABATAN_LESSOR]                    NVARCHAR (50)   NULL,
    [PIC_LESSEE]                        NVARCHAR (50)   NULL,
    [HARI]                              NVARCHAR (50)   NULL,
    [DAY]                               NVARCHAR (50)   NULL,
    [MONTH]                             NVARCHAR (50)   NULL,
    [YEAR]                              NVARCHAR (4)    NULL,
    [TANGGAL]                           DATETIME        NULL,
    [CLIENT_ADDRESS]                    NVARCHAR (4000) NULL,
    [CREDIT_TERM]                       INT             NULL,
    [BILLING_TYPE]                      INT             NULL,
    [INSURANCE_TPL]                     DECIMAL (18, 2) NULL,
    [INSURANCE_PAD]                     DECIMAL (18, 2) NULL,
    [INSURANCE_PAP]                     DECIMAL (18, 2) NULL,
    [INSURANCE_SRCCTS]                  DECIMAL (18, 2) NULL,
    [ET_PENALTY]                        DECIMAL (9, 6)  NULL,
    [TANGGAL_PEMBAYARAN_AWAL_DAN_AKHIR] NVARCHAR (250)  NULL,
    [PPN_PCT]                           DECIMAL (9, 6)  NULL,
    [NO_RANGKA]                         NVARCHAR (50)   NULL,
    [NO_MESIN]                          NVARCHAR (50)   NULL,
    [KAROSERI]                          NVARCHAR (250)  NULL,
    [AKSESORIS]                         NVARCHAR (250)  NULL
);

