CREATE TABLE [dbo].[RPT_DAILY_OR_MONTHLY_TRANSACTION] (
    [USER_ID]           NVARCHAR (50)   NULL,
    [REPORT_COMPANY]    NVARCHAR (250)  NULL,
    [REPORT_IMAGE]      NVARCHAR (250)  NULL,
    [REPORT_TITLE]      NVARCHAR (250)  NULL,
    [DATE]              NVARCHAR (50)   NULL,
    [NOMOR_SKD]         NVARCHAR (50)   NULL,
    [NOMOR_KONTRAK]     NVARCHAR (50)   NULL,
    [CUSTOMER]          NVARCHAR (250)  NULL,
    [TOTAL_UNIT]        INT             NULL,
    [MERK]              NVARCHAR (250)  NULL,
    [TYPE]              NVARCHAR (250)  NULL,
    [PRODUCT]           NVARCHAR (250)  NULL,
    [ASSET_YEAR]        NVARCHAR (4)    NULL,
    [TENOR]             INT             NULL,
    [VALUE_DATE]        DATETIME        NULL,
    [LR_PCT]            DECIMAL (9, 6)  NULL,
    [ROA_PCT]           DECIMAL (9, 6)  NULL,
    [RV_PCT]            DECIMAL (9, 6)  NULL,
    [OTR_PRICE]         DECIMAL (18, 2) NULL,
    [COST_PRICE]        DECIMAL (18, 2) NULL,
    [NET_INVESTASI]     DECIMAL (18, 2) NULL,
    [RV_AMOUNT]         DECIMAL (18, 2) NULL,
    [RENTAL_FEE]        DECIMAL (18, 2) NULL,
    [TOTAL_PROFIT]      DECIMAL (18, 2) NULL,
    [RENT_TO_OWN]       NVARCHAR (10)   NULL,
    [UNTI_CONDITION]    NVARCHAR (10)   NULL,
    [SKEMA_MAINTENANCE] NVARCHAR (25)   NULL,
    [MAINTENANCE_COST]  DECIMAL (18, 2) NULL,
    [SUPPLIER]          NVARCHAR (250)  NULL,
    [MO]                NVARCHAR (250)  NULL,
    [SECTION]           NVARCHAR (250)  NULL,
    [KETERANGAN]        NVARCHAR (4000) NULL,
    [MITS]              NVARCHAR (50)   NULL,
    [BRANCH_CODE]       NVARCHAR (50)   NULL,
    [BRANCH_NAME]       NVARCHAR (250)  NULL,
    [IS_CONDITION]      NVARCHAR (1)    NULL,
    [CRE_DATE]          DATETIME        NULL,
    [CRE_BY]            NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NULL,
    [MOD_DATE]          DATETIME        NULL,
    [MOD_BY]            NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NULL,
    [MONTH_DESC]        NVARCHAR (50)   NULL,
    [YEAR]              NVARCHAR (50)   NULL
);

