CREATE TABLE [dbo].[RPT_DAILY_OVERDUE_BUTTON_DISABLE] (
    [user_id]    NVARCHAR (50) NOT NULL,
    [is_disable] NVARCHAR (1)  NULL,
    CONSTRAINT [PK_RPT_DAILY_OVERDUE_BUTTON_DISABLE] PRIMARY KEY CLUSTERED ([user_id] ASC)
);

