CREATE TABLE [dbo].[RPT_ASSET_ALLOCATION_PERMOHONAN_PENGIRIMAN_BARANG_ADDRESS] (
    [USER_ID]            NVARCHAR (50)   NOT NULL,
    [FA_CODE]            NVARCHAR (50)   NOT NULL,
    [DELIVER_TO_NAME]    NVARCHAR (50)   NOT NULL,
    [DELIVER_TO_AREA]    NVARCHAR (50)   NOT NULL,
    [DELIVER_TO_ADDRESS] NVARCHAR (4000) NOT NULL,
    [DELIVER_TO_PHONE]   NVARCHAR (50)   NOT NULL,
    [CRE_DATE]           DATETIME        NOT NULL,
    [CRE_BY]             NVARCHAR (50)   NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (50)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_BY]             NVARCHAR (50)   NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (50)   NOT NULL
);

