CREATE TABLE [dbo].[RPT_SOMASI_PEMENUHAN_KEWAJIBAN_LAMPIRAN] (
    [USER_ID]          NVARCHAR (50)  NOT NULL,
    [NO_SURAT_SOMASI]  NVARCHAR (50)  NULL,
    [TANGGAL_SOMASI]   DATETIME       NULL,
    [ASSET_NAME]       NVARCHAR (250) NULL,
    [AGREEMENT_NO]     NVARCHAR (50)  NULL,
    [YEAR]             NVARCHAR (4)   NULL,
    [MAIN_CONTRACT_NO] NVARCHAR (50)  NULL,
    [VEHICLE_TYPE]     NVARCHAR (250) NULL,
    [BRAND]            NVARCHAR (250) NULL,
    [AGREEMENT_DATE]   DATETIME       NULL,
    [CHASSIS_NO]       NVARCHAR (250) NULL,
    [ENGINE_NO]        NVARCHAR (250) NULL,
    [PLAT_NO]          NVARCHAR (250) NULL,
    [CRE_DATE]         DATETIME       NULL,
    [CRE_BY]           NVARCHAR (15)  NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)  NULL,
    [MOD_DATE]         DATETIME       NULL,
    [MOD_BY]           NVARCHAR (15)  NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)  NULL
);

