CREATE TABLE [dbo].[RPT_SURAT_PERINGATAN_II] (
    [USER_ID]               NVARCHAR (50)   NULL,
    [REPORT_IMAGE]          NVARCHAR (250)  NULL,
    [REPORT_TITLE]          NVARCHAR (250)  NULL,
    [REPORT_COMANY_NAME]    NVARCHAR (250)  NULL,
    [REPORT_COMPANY_CITY]   NVARCHAR (4000) NULL,
    [BANK_NAME]             NVARCHAR (250)  NULL,
    [BANK_ACCOUNT_NAME]     NVARCHAR (250)  NULL,
    [BANK_ACCOUNT_NO]       NVARCHAR (50)   NULL,
    [NOMOR_SURAT]           NVARCHAR (50)   NULL,
    [NOMOR_SURAT_SP_1]      NVARCHAR (50)   NULL,
    [TANGGAL_SURAT_PERTAMA] DATETIME        NULL,
    [TANGGAL_SURAT]         DATETIME        NULL,
    [CLIENT_NAME]           NVARCHAR (250)  NULL,
    [CLIENT_ADDRESS]        NVARCHAR (4000) NULL,
    [DIREKRTUR_LESSEE]      NVARCHAR (250)  NULL,
    [AGREEMENT_NO]          NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]        DATETIME        NULL,
    [INVOICE_NO]            NVARCHAR (50)   NULL,
    [PERIODE_PEMAKAIAN]     NVARCHAR (4000) NULL,
    [NILAI_SEWA]            DECIMAL (18, 2) NULL,
    [DENDA_KETERLAMBATAN]   DECIMAL (18, 2) NULL,
    [TANGGAL_JATUH_TEMPO]   DATETIME        NULL,
    [TANGGAL_PELUNASAN]     DATETIME        NULL,
    [DEPT_HEAD_OPL]         NVARCHAR (250)  NULL,
    [PENASIHAT_HUKUM]       NVARCHAR (250)  NULL,
    [CRE_DATE]              DATETIME        NULL,
    [CRE_BY]                NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NULL,
    [MOD_DATE]              DATETIME        NULL,
    [MOD_BY]                NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NULL,
    [NO_PERIODE]            INT             NULL,
    [JABATAN]               NVARCHAR (250)  NULL,
    [JUMLAH_UNIT]           INT             NULL
);

