CREATE TABLE [dbo].[RPT_SURVEY_PROJECT_LESSEE] (
    [USER_ID]            NVARCHAR (50) NOT NULL,
    [PROJECT_NAME]       NVARCHAR (50) NULL,
    [PEMILIK_NAME]       NVARCHAR (50) NULL,
    [MAIN_KONTRAKTOR]    NVARCHAR (50) NULL,
    [KOMPETITOR_MAIN]    NVARCHAR (50) NULL,
    [SUB_KONTRAKTOR]     NVARCHAR (50) NULL,
    [KOMPETITOR_SUB]     NVARCHAR (50) NULL,
    [SUB_SUB_KONTRAKTOR] NVARCHAR (50) NULL,
    [KOMPETITOR_SUB_SUB] NVARCHAR (50) NULL
);

