CREATE TABLE [dbo].[RPT_SKD_APPROVED] (
    [USER_ID]          NVARCHAR (50)   NULL,
    [REPORT_COMPANY]   NVARCHAR (250)  NULL,
    [REPORT_IMAGE]     NVARCHAR (250)  NULL,
    [REPORT_TITLE]     NVARCHAR (250)  NULL,
    [FROM_DATE]        DATETIME        NULL,
    [HEAD]             NVARCHAR (250)  NULL,
    [PIC_MKT]          NVARCHAR (250)  NULL,
    [SKD_NUMBER]       NVARCHAR (50)   NULL,
    [CUSTOMER_NAME]    NVARCHAR (250)  NULL,
    [TOTAL]            INT             NULL,
    [MERK]             NVARCHAR (4000) NULL,
    [UNIT_TYPE]        NVARCHAR (4000) NULL,
    [PRODUCT_CATEGORY] NVARCHAR (4000) NULL,
    [UNIT_CONDITION]   NVARCHAR (4000) NULL,
    [TENOR]            INT             NULL,
    [DATE_OF_APPROVAL] DATETIME        NULL,
    [LR_PCT]           DECIMAL (9, 6)  NULL,
    [RV_PCT]           DECIMAL (9, 6)  NULL,
    [ROA_PCT]          DECIMAL (9, 6)  NULL,
    [REMARKS]          NVARCHAR (4000) NULL,
    [BRANCH_CODE]      NVARCHAR (50)   NULL,
    [BRANCH_NAME]      NVARCHAR (250)  NULL,
    [IS_CONDITION]     NVARCHAR (1)    NULL,
    [CRE_DATE]         DATETIME        NULL,
    [CRE_BY]           NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NULL,
    [MOD_DATE]         DATETIME        NULL,
    [MOD_BY]           NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NULL,
    [TO_DATE]          DATETIME        NULL
);

