CREATE TABLE [dbo].[RPT_BILLING_DUE_LIST] (
    [USER_ID]                  NVARCHAR (15)   NULL,
    [AS_OF_DATE]               DATETIME        NULL,
    [BRANCH_CODE]              NVARCHAR (50)   NULL,
    [REPORT_COMPANY]           NVARCHAR (250)  NULL,
    [REPORT_IMAGE]             NVARCHAR (250)  NULL,
    [REPORT_TITLE]             NVARCHAR (250)  NULL,
    [BRANCH_NAME]              NVARCHAR (250)  NULL,
    [IS_CONDITION]             NVARCHAR (1)    NULL,
    [INVOICE_NO]               NVARCHAR (400)  NULL,
    [CLIENT_NO]                NVARCHAR (400)  NULL,
    [NPWP_NO]                  NVARCHAR (400)  NULL,
    [CLIENT_NAME]              NVARCHAR (400)  NULL,
    [INVOICE_TYPE]             NVARCHAR (400)  NULL,
    [DESCRIPTION]              NVARCHAR (4000) NULL,
    [BILLING_DATE]             DATETIME        NULL,
    [DUE_DATE]                 DATETIME        NULL,
    [STATUS]                   NVARCHAR (400)  NULL,
    [CURRENCY]                 NVARCHAR (400)  NULL,
    [RENTAL_AMOUNT]            DECIMAL (18, 2) NULL,
    [PPN_AMOUNT]               DECIMAL (18, 2) NULL,
    [INVOICE_AMOUNT]           DECIMAL (18, 2) NULL,
    [PPH_AMOUNT]               DECIMAL (18, 2) NULL,
    [NETT_AMOUNT]              DECIMAL (18, 2) NULL,
    [AGREEMEN_NO]              NVARCHAR (50)   NULL,
    [START_SETTLEMENT_PERIODE] DATETIME        NULL,
    [END_SETTLEMENT_PERIODE]   DATETIME        NULL,
    [FA_CODE]                  NVARCHAR (50)   NULL,
    [PLAT_NO]                  NVARCHAR (50)   NULL,
    [UNIT_TYPE]                NVARCHAR (400)  NULL,
    [TOP_DAYS]                 NVARCHAR (400)  NULL,
    [BILLING_TYPE]             NVARCHAR (400)  NULL,
    [FIRST_PAYMENT_TYPE]       NVARCHAR (400)  NULL,
    [BILLING_MODE]             NVARCHAR (400)  NULL,
    [BAST_DATE]                DATETIME        NULL,
    [GOLIVE_DATE]              DATETIME        NULL,
    [ASSET_STATUS]             NVARCHAR (400)  NULL,
    [AGREEMENT_STATUS]         NVARCHAR (400)  NULL,
    [BILLING_NO]               INT             NULL,
    [INVOICE_STATUS]           NVARCHAR (50)   NULL
);

