CREATE TABLE [dbo].[RPT_SOMASI_PEMENUHAN_KEWAJIBAN] (
    [USER_ID]              NVARCHAR (50)   NOT NULL,
    [DELIVERY_NO]          NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NULL,
    [REPORT_IMAGE]         NVARCHAR (250)  NULL,
    [KOTA]                 NVARCHAR (50)   NULL,
    [TANGGAL]              DATETIME        NULL,
    [NO_SURAT]             NVARCHAR (50)   NULL,
    [NAMA_LESSEE]          NVARCHAR (250)  NULL,
    [ALAMAT_LESSEE]        NVARCHAR (4000) NULL,
    [NAMA_DIREKTUR_LESSEE] NVARCHAR (250)  NULL,
    [AGREEMENT_NO]         NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]       DATETIME        NULL,
    [NO_SP1]               NVARCHAR (50)   NULL,
    [TANGGAL_SP1]          DATETIME        NULL,
    [NO_SP2]               NVARCHAR (50)   NULL,
    [TANGGAL_SP2]          DATETIME        NULL,
    [TANGGAL_SOMASI]       DATETIME        NULL,
    [NO_REK]               NVARCHAR (50)   NULL,
    [NAMA_BANK]            NVARCHAR (50)   NULL,
    [ATAS_NAMA]            NVARCHAR (50)   NULL,
    [JUMLAH_UNIT]          INT             NULL,
    [NAMA_OBJECT_LEASE]    NVARCHAR (250)  NULL,
    [TAHUN_OBJECT_LEASE]   NVARCHAR (4)    NULL,
    [NAMA_DEPT_HEAD]       NVARCHAR (250)  NULL,
    [NAMA_PENASIHAT]       NVARCHAR (50)   NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [JABATAN]              NVARCHAR (250)  NULL
);

