CREATE TABLE [dbo].[RPT_INVOICE_DELIVERY] (
    [USER_ID]            NVARCHAR (50)  NULL,
    [REPORT_COMPANY]     NVARCHAR (250) NULL,
    [REPORT_TITLE]       NVARCHAR (250) NULL,
    [REPORT_IMAGE]       NVARCHAR (250) NULL,
    [CUSTOMER_NAME]      NVARCHAR (250) NULL,
    [CLIENT_NO]          NVARCHAR (50)  NULL,
    [NPWP_NO]            NVARCHAR (50)  NULL,
    [BILLING_TO_ADDRESS] NVARCHAR (500) NULL,
    [TANGGAL_KIRIM]      DATETIME       NULL,
    [NO_TANDA_TERIMA]    NVARCHAR (50)  NULL,
    [CRE_DATE]           DATETIME       NULL,
    [CRE_BY]             NVARCHAR (15)  NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)  NULL,
    [MOD_DATE]           DATETIME       NULL,
    [MOD_BY]             NVARCHAR (15)  NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)  NULL,
    [DISIAPKAN_OLEH]     NVARCHAR (250) NULL,
    [MESSANGER]          NVARCHAR (250) NULL,
    [DITERIMA_OLEH]      NVARCHAR (250) NULL
);

