CREATE TABLE [dbo].[RPT_SOMASI_PENYELESAIAN_KEWAJIBAN_DAN_PENGEMBALIAN_KENDARAAN_DENDA_PEMBATALAN] (
    [USER_ID]           NVARCHAR (50)   NULL,
    [AGREEMENT_NO]      NVARCHAR (50)   NULL,
    [NILAI_SEWA]        DECIMAL (18, 2) NULL,
    [SISA_PERIODE_SEWA] INT             NULL,
    [DENDA_PEMBATALAN]  DECIMAL (18, 2) NULL,
    [PERJANJIAN_INDUK]  NVARCHAR (50)   NULL
);

