CREATE TABLE [dbo].[RPT_SCHEDULE_RENTAL] (
    [USER_ID]        NVARCHAR (50)   NULL,
    [REPORT_TITLE]   NVARCHAR (250)  NULL,
    [REPORT_IMAGE]   NVARCHAR (250)  NULL,
    [REPORT_COMPANY] NVARCHAR (250)  NULL,
    [APPLICATION_NO] NVARCHAR (50)   NULL,
    [CLIENT_NAME]    NVARCHAR (50)   NULL,
    [ASSET_NO]       NVARCHAR (50)   NULL,
    [ASSET_NAME]     NVARCHAR (50)   NULL,
    [INSTALLMENT_NO] INT             NULL,
    [DUE_DATE]       DATETIME        NULL,
    [BILLING_DATE]   DATETIME        NULL,
    [BILLING_AMOUNT] DECIMAL (18, 2) NULL,
    [REMARK]         NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NULL,
    [CRE_BY]         NVARCHAR (50)   NULL,
    [CRE_IP_ADDRESS] NVARCHAR (50)   NULL,
    [MOD_DATE]       DATETIME        NULL,
    [MOD_BY]         NVARCHAR (50)   NULL,
    [MOD_IP_ADDRESS] NVARCHAR (50)   NULL
);

