CREATE TABLE [dbo].[RPT_SURVEY_OTHER_LESSEE] (
    [USER_ID]         NVARCHAR (50)   NOT NULL,
    [RENTAL_COMPANY]  NVARCHAR (50)   NULL,
    [JUMLAH_UNIT]     INT             NULL,
    [JENIS_KENDARAAN] NVARCHAR (50)   NULL,
    [OS_PERIODE]      DECIMAL (18, 2) NULL,
    [NILAI_PINJAMAN]  DECIMAL (18, 2) NULL
);

