CREATE TABLE [dbo].[RPT_SOMASI_PENYELESAIAN_KEWAJIBAN_DAN_PENGEMBALIAN_KENDARAAN_TUNGGAKAN] (
    [USER_ID]             NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]        NVARCHAR (50)   NULL,
    [PERIODE_PEMAKAIAN]   NVARCHAR (50)   NULL,
    [NILAI_SEWA]          DECIMAL (18, 2) NULL,
    [TANGGAL_JATUH_TEMPO] DATETIME        NULL,
    [PERJANJIAN_INDUK]    NVARCHAR (50)   NULL
);

