CREATE TABLE [dbo].[RPT_SURVEY_FOTO_AND_DOCUMENT] (
    [USER_ID]   NVARCHAR (50)   NOT NULL,
    [LOCATION]  NVARCHAR (250)  NULL,
    [REMARKS]   NVARCHAR (4000) NULL,
    [FILE_NAME] NVARCHAR (250)  NULL
);

