CREATE TABLE [dbo].[RPT_PROFIT_LOSS_ASSET] (
    [USER_ID]        NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY] NVARCHAR (250)  NOT NULL,
    [REPORT_TITLE]   NVARCHAR (250)  NOT NULL,
    [REPORT_IMAGE]   NVARCHAR (250)  NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NULL,
    [BRANCH_NAME]    NVARCHAR (50)   NULL,
    [AS_OF_DATE]     DATETIME        NULL,
    [ASSET_NO]       NVARCHAR (50)   NULL,
    [MERK]           NVARCHAR (50)   NULL,
    [MODEL]          NVARCHAR (50)   NULL,
    [TYPE]           NVARCHAR (50)   NULL,
    [PLAT_NO]        NVARCHAR (50)   NULL,
    [CHASSIS_NO]     NVARCHAR (50)   NULL,
    [ENGINE_NO]      NVARCHAR (50)   NULL,
    [PURCHASE_PRICE] DECIMAL (18, 2) NULL,
    [EXPENSE]        DECIMAL (18, 2) NULL,
    [REVENUE]        DECIMAL (18, 2) NULL,
    [RV]             DECIMAL (18, 2) NULL,
    [SELL_PRICE]     DECIMAL (18, 2) NULL,
    [GAIN_LOSS]      DECIMAL (18, 2) NULL,
    [IS_CONDITION]   NVARCHAR (1)    NULL
);

