CREATE TABLE [dbo].[RPT_CONTRACT] (
    [USER_ID]             NVARCHAR (50)   NULL,
    [REPORT_IMAGE]        NVARCHAR (50)   NULL,
    [REPORT_COMPANY_NAME] NVARCHAR (250)  NULL,
    [REPORT_TITLE]        NVARCHAR (250)  NULL,
    [AGREEMENT_NO]        NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]      DATETIME        NULL,
    [CONTRACT_NO]         NVARCHAR (50)   NULL,
    [CONTRACT_DATE]       DATETIME        NULL,
    [EMPLOYEE_NAME]       NVARCHAR (250)  NULL,
    [EMPLOYEE_POSITION]   NVARCHAR (250)  NULL,
    [CLIENT_NAME]         NVARCHAR (250)  NULL,
    [CLIENT_EMPLOYEE]     NVARCHAR (250)  NULL,
    [DELIVERY_ADDRESS]    NVARCHAR (4000) NULL,
    [PICKUP_ADDRESS]      NVARCHAR (4000) NULL,
    [PERIODE]             INT             NULL,
    [START_DATE]          DATETIME        NULL,
    [END_DATE]            DATETIME        NULL,
    [UNIT_TYPE]           NVARCHAR (250)  NULL,
    [TOTAL_UNIT]          INT             NULL,
    [ASSET_YEAR]          NVARCHAR (4)    NULL,
    [RENTAL_AMOUNT]       DECIMAL (18, 2) NULL,
    [TOTAL_RENTAL_AMOUNT] DECIMAL (18, 2) NULL,
    [PAYMENT_DATE]        INT             NULL,
    [START_PAYMENT_DATE]  DATETIME        NULL,
    [NEXT_PAYMENT_DATE]   DATETIME        NULL,
    [END_PAYMENT_DATE]    DATETIME        NULL,
    [TOTAL_MILES]         INT             NULL,
    [ADDITIONAL_COST]     DECIMAL (18, 2) NULL,
    [EFFECTIVE_DATE]      DATETIME        NULL,
    [CRE_DATE]            DATETIME        NULL,
    [CRE_BY]              NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NULL,
    [MOD_DATE]            DATETIME        NULL,
    [MOD_BY]              NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NULL
);

