CREATE TABLE [dbo].[RPT_SURAT_TAGIH_WRITE_OFF] (
    [USER_ID]                  NVARCHAR (50)   NOT NULL,
    [WO_CODE]                  NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]           NVARCHAR (250)  NULL,
    [REPORT_TITLE]             NVARCHAR (250)  NULL,
    [REPORT_IMAGE]             NVARCHAR (250)  NULL,
    [KOTA]                     NVARCHAR (50)   NULL,
    [TANGGAL]                  DATETIME        NULL,
    [NO_SURAT]                 NVARCHAR (50)   NULL,
    [NAMA_CLIENT]              NVARCHAR (250)  NULL,
    [ALAMAT_CLIENT]            NVARCHAR (4000) NULL,
    [UP_NAME1]                 NVARCHAR (250)  NULL,
    [UP_NAME2]                 NVARCHAR (250)  NULL,
    [TANGGAL_TUNGGAKAN]        DATETIME        NULL,
    [TOTAL_OBJECT_SEWA]        NVARCHAR (50)   NULL,
    [TUNGGAKAN]                DECIMAL (18, 2) NULL,
    [DENDA]                    DECIMAL (18, 2) NULL,
    [TOTAL_TAGIHAN]            DECIMAL (18, 2) NULL,
    [NAMA_BANK]                NVARCHAR (50)   NULL,
    [NO_REK]                   NVARCHAR (50)   NULL,
    [REK_ATAS_NAMA]            NVARCHAR (50)   NULL,
    [EMPLOYEE_NAME]            NVARCHAR (50)   NULL,
    [EMPLOYEE_POSITION]        NVARCHAR (50)   NULL,
    [CRE_DATE]                 DATETIME        NOT NULL,
    [CRE_BY]                   NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                 DATETIME        NOT NULL,
    [MOD_BY]                   NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]           NVARCHAR (15)   NOT NULL,
    [PERIHAL]                  NVARCHAR (250)  NULL,
    [NO_PERJANJIAN_INDUK]      NVARCHAR (50)   NULL,
    [TANGGAL_PERJANJIAN_INDUK] DATETIME        NULL
);

