CREATE TABLE [dbo].[RPT_QUOTATION_APPLICATION] (
    [USER_ID]                    NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]             NVARCHAR (50)   NULL,
    [REPORT_IMAGE]               NVARCHAR (250)  NULL,
    [REPORT_TITLE]               NVARCHAR (250)  NULL,
    [REPORT_ADDRESS]             NVARCHAR (4000) NULL,
    [APPLICATION_NO]             NVARCHAR (50)   NULL,
    [CLIENT_NAME]                NVARCHAR (250)  NULL,
    [ATTN_NAME]                  NVARCHAR (250)  NULL,
    [PHONE_NO_TO]                NVARCHAR (50)   NULL,
    [EMAIL]                      NVARCHAR (250)  NULL,
    [SUBJECT]                    NVARCHAR (250)  NULL,
    [FROM_NAME]                  NVARCHAR (250)  NULL,
    [DATE]                       DATETIME        NULL,
    [PHONE_NO_FROM]              NVARCHAR (50)   NULL,
    [MOBILE_FROM]                NVARCHAR (50)   NULL,
    [PRODUCT]                    NVARCHAR (250)  NULL,
    [VAT_PCT]                    DECIMAL (18, 2) NULL,
    [WITHHOLDING_TAX]            DECIMAL (18, 2) NULL,
    [IS_STNK]                    NVARCHAR (1)    NULL,
    [IS_ASURANSI]                NVARCHAR (1)    NULL,
    [IS_PENGANTI]                NVARCHAR (1)    NULL,
    [IS_PERBAIKAN]               NVARCHAR (1)    NULL,
    [IS_BANTUAN]                 NVARCHAR (1)    NULL,
    [IS_DARURAT]                 NVARCHAR (1)    NULL,
    [IS_LAIN_LAIN]               NVARCHAR (1)    NULL,
    [IS_PEMELIHARAAN]            NVARCHAR (1)    NULL,
    [IS_SUKU_CADANG]             NVARCHAR (1)    NULL,
    [IS_OLI]                     NVARCHAR (1)    NULL,
    [IS_PASSENGER]               NVARCHAR (1)    NULL,
    [IS_PERSONAL_PASSENGER]      NVARCHAR (1)    NULL,
    [IS_PERSONAL_DRIVER]         NVARCHAR (1)    NULL,
    [IS_PEMOGOKAN]               NVARCHAR (1)    NULL,
    [IS_TERORISME]               NVARCHAR (1)    NULL,
    [IS_BANJIR]                  NVARCHAR (1)    NULL,
    [IS_GEMPA]                   NVARCHAR (1)    NULL,
    [IS_NILAI]                   NVARCHAR (1)    NULL,
    [IS_THIRD_PARTY]             NVARCHAR (1)    NULL,
    [IS_COP]                     NVARCHAR (1)    NULL,
    [TPL]                        DECIMAL (18, 2) NULL,
    [PPL]                        NVARCHAR (250)  NULL,
    [PA_PASSENGER_AMOUNT]        NVARCHAR (250)  NULL,
    [PA_PASSENGER_SEAT]          INT             NULL,
    [PA_DRIVER_AMOUNT]           NVARCHAR (250)  NULL,
    [PAY_OWN_RISK_AMOUNT]        DECIMAL (18, 2) NULL,
    [COUNT_LEASE_RENT]           INT             NULL,
    [PAY_OWN_RISK_LESSOR_AMOUNT] DECIMAL (18, 2) NULL,
    [PARTIAL_TOTAL_LOSS_PCT]     DECIMAL (18, 2) NULL,
    [PARTIAL_TOTAL_LOSS_AMOUNT]  DECIMAL (18, 2) NULL,
    [CLAIM_AMOUNT_PCT]           DECIMAL (18, 2) NULL,
    [CLAIM_AMOUNT_TERBILANG]     NVARCHAR (250)  NULL,
    [CLAIM_AMOUNT]               DECIMAL (18, 2) NULL,
    [NAMA_USER]                  NVARCHAR (250)  NULL,
    [JABATAN_USER]               NVARCHAR (250)  NULL,
    [UNIT_CODE]                  NVARCHAR (250)  NULL,
    [ASSET_NO]                   NVARCHAR (250)  NULL,
    [TYPE_OF_UNIT]               NVARCHAR (500)  NULL,
    [QUANTITY]                   INT             NULL,
    [YEAR]                       NVARCHAR (4)    NULL,
    [LEASE_PERIOD]               INT             NULL,
    [MONTHLY_LEASED_RENT_AMOUNT] DECIMAL (18, 2) NULL,
    [RV_AMOUNT]                  DECIMAL (18, 2) NULL,
    [PREVIOUS_CONTRACT_NUMBER]   NVARCHAR (250)  NULL,
    [COMPREHENSIVE]              NVARCHAR (4000) NULL,
    [BILLING_TYPE]               NVARCHAR (50)   NULL,
    [PAYMENT_TYPE]               NVARCHAR (50)   NULL,
    [CREDIT_TERM]                NVARCHAR (50)   NULL,
    [REMARK]                     NVARCHAR (250)  NULL,
    [CRE_BY]                     NVARCHAR (50)   NULL,
    [CRE_DATE]                   DATETIME        NULL,
    [CRE_IP_ADDRESS]             NVARCHAR (50)   NULL,
    [MOD_BY]                     NVARCHAR (50)   NULL,
    [MOD_DATE]                   DATETIME        NULL,
    [MOD_IP_ADDRESS]             NVARCHAR (50)   NULL
);

