CREATE TABLE [dbo].[RPT_EXPENSE] (
    [USER_ID]           NVARCHAR (50)   NOT NULL,
    [FILTER_AS_OF_DATE] DATETIME        NULL,
    [REPORT_COMPANY]    NVARCHAR (250)  NULL,
    [REPORT_TITLE]      NVARCHAR (250)  NULL,
    [REPORT_IMAGE]      NVARCHAR (250)  NULL,
    [ASSET_NO]          NVARCHAR (50)   NULL,
    [MERK]              NVARCHAR (50)   NULL,
    [MODEL]             NVARCHAR (50)   NULL,
    [TYPE]              NVARCHAR (50)   NULL,
    [PLAT_NO]           NVARCHAR (50)   NULL,
    [CHASSIS_NO]        NVARCHAR (50)   NULL,
    [ENGINE_NO]         NVARCHAR (50)   NULL,
    [PURCHASE_PRICE]    DECIMAL (18, 2) NULL,
    [EXPENSE]           DECIMAL (18, 2) NULL,
    [REVENUE]           DECIMAL (18, 2) NULL,
    [RV_AMOUNT]         DECIMAL (18, 2) NULL,
    [NET_INCOME]        DECIMAL (18, 2) NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL
);

