CREATE TABLE [dbo].[RPT_INVOICE_KWITANSI_DETAIL] (
    [USER_ID]          NVARCHAR (50)   NOT NULL,
    [RECEIPT_NO]       NVARCHAR (50)   NULL,
    [AGREEMENT_NO]     NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]   DATETIME        NULL,
    [JENIS_ALAT]       NVARCHAR (250)  NULL,
    [TYPE]             VARCHAR (4000)  NULL,
    [UNIT]             INT             NULL,
    [STAR_PERIODE]     DATETIME        NULL,
    [END_PERIODE]      DATETIME        NULL,
    [NO_POLISI]        NVARCHAR (50)   NULL,
    [STAR_CONTRACT]    DATETIME        NULL,
    [END_CONTRACT]     DATETIME        NULL,
    [HARGA_PERUNIT]    DECIMAL (18, 2) NULL,
    [JUMLAH_HARGA]     DECIMAL (18, 2) NULL,
    [SUB_TOTAL]        DECIMAL (18, 2) NULL,
    [PPN]              DECIMAL (18, 2) NULL,
    [PPH]              DECIMAL (18, 2) NULL,
    [TOTAL]            DECIMAL (18, 2) NULL,
    [SUM_AGREEMENT]    INT             NULL,
    [SUM_JENI_OR_TYPE] INT             NULL,
    [SUM_UNIT]         INT             NULL,
    [KWITANSI_NO]      NVARCHAR (50)   NULL,
    [DPP_NILAI_LAIN]   DECIMAL (18, 2) NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20231003]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20231003_2]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC)
    INCLUDE([END_PERIODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20231003_3]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC)
    INCLUDE([STAR_PERIODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20032024]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC, [RECEIPT_NO] ASC)
    INCLUDE([END_PERIODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20032024_2]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC)
    INCLUDE([RECEIPT_NO], [AGREEMENT_NO], [AGREEMENT_DATE], [JENIS_ALAT], [TYPE], [UNIT], [STAR_PERIODE], [END_PERIODE], [NO_POLISI], [STAR_CONTRACT], [END_CONTRACT], [HARGA_PERUNIT], [JUMLAH_HARGA], [SUB_TOTAL], [PPN], [PPH], [TOTAL], [SUM_AGREEMENT], [SUM_JENI_OR_TYPE], [SUM_UNIT], [KWITANSI_NO]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20032024_3]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC, [RECEIPT_NO] ASC)
    INCLUDE([STAR_PERIODE]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20032024_4]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC, [RECEIPT_NO] ASC)
    INCLUDE([TYPE]);


GO
CREATE NONCLUSTERED INDEX [IDX_RPT_INVOICE_KWITANSI_DETAIL_20032024_5]
    ON [dbo].[RPT_INVOICE_KWITANSI_DETAIL]([USER_ID] ASC, [RECEIPT_NO] ASC)
    INCLUDE([NO_POLISI]);

