CREATE TABLE [dbo].[RPT_SOMASI_PENYELESAIAN_KEWAJIBAN_DAN_PENGEMBALIAN_KENDARAAN_DENDA_KETERLAMBATAN] (
    [USER_ID]                   NVARCHAR (50)   NULL,
    [AGREEMENT_NO]              NVARCHAR (50)   NULL,
    [NILAI_SEWA]                DECIMAL (18, 2) NULL,
    [TOTAL_HARI_KETERLAMBATAN]  INT             NULL,
    [NILAI_DENDA_KETERLAMBATAN] DECIMAL (18, 2) NULL,
    [PERJANJIAN_INDUK]          NVARCHAR (50)   NULL
);

