CREATE TABLE [dbo].[RPT_SOMASI_PENYELESAIAN_KEWAJIBAN_DAN_PENGEMBALIAN_KENDARAAN] (
    [USER_ID]              NVARCHAR (50)   NOT NULL,
    [DELIVERY_CODE]        NVARCHAR (50)   NOT NULL,
    [REPORT_COMPANY]       NVARCHAR (250)  NULL,
    [REPORT_TITLE]         NVARCHAR (250)  NULL,
    [REPORT_IMAGE]         NVARCHAR (250)  NULL,
    [KOTA]                 NVARCHAR (50)   NULL,
    [TANGGAL]              DATETIME        NULL,
    [NO_SURAT]             NVARCHAR (50)   NULL,
    [NAMA_CLIENT]          NVARCHAR (250)  NULL,
    [ALAMAT_CLIENT]        NVARCHAR (4000) NULL,
    [UP_NAME]              NVARCHAR (250)  NULL,
    [TANGGAL_TUNGGAKAN]    DATETIME        NULL,
    [AGREEMENT_NO]         NVARCHAR (50)   NULL,
    [AGREEMENT_DATE]       DATETIME        NULL,
    [COMPANY_NAME]         NVARCHAR (250)  NULL,
    [NAMA_BANK]            NVARCHAR (50)   NULL,
    [NO_REK]               NVARCHAR (50)   NULL,
    [REK_ATAS_NAMA]        NVARCHAR (50)   NULL,
    [EMPLOYEE_NAME]        NVARCHAR (50)   NULL,
    [MERK]                 NVARCHAR (50)   NULL,
    [CHASSIS_NO]           NVARCHAR (50)   NULL,
    [ENGINE_NO]            NVARCHAR (50)   NULL,
    [WARNA]                NVARCHAR (50)   NULL,
    [TAHUN]                INT             NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [JUMLAH_A]             DECIMAL (18, 2) NULL,
    [JUMLAH_B]             DECIMAL (18, 2) NULL,
    [JUMLAH_C]             DECIMAL (18, 2) NULL,
    [JUMLAH_D]             DECIMAL (18, 2) NULL,
    [ADD_DAYS]             INT             NULL,
    [PERJANJIAN_INDUK]     NVARCHAR (50)   NULL,
    [PERJANJIAN_PELAKSANA] NVARCHAR (50)   NULL,
    [TANGGAL_PERJANJIAN]   DATETIME        NULL,
    [JENIS_KENDARAAN]      NVARCHAR (250)  NULL,
    [NO_SERI]              NVARCHAR (50)   NULL,
    [NO_POLISI]            NVARCHAR (10)   NULL
);

