CREATE TABLE [dbo].[RPT_END_CONTRACT] (
    [USER_ID]                 NVARCHAR (50)   NULL,
    [REPORT_COMPANY]          NVARCHAR (250)  NULL,
    [REPORT_IMAGE]            NVARCHAR (250)  NULL,
    [REPORT_TITLE]            NVARCHAR (250)  NULL,
    [FROM_DATE]               DATETIME        NULL,
    [CUSTOMER]                NVARCHAR (250)  NULL,
    [NOMOR_KONTRAK]           NVARCHAR (50)   NULL,
    [ASSET_NO]                NVARCHAR (50)   NULL,
    [PLAT_NO]                 NVARCHAR (15)   NULL,
    [MERK]                    NVARCHAR (50)   NULL,
    [TYPE]                    NVARCHAR (250)  NULL,
    [PRODUCT]                 NVARCHAR (50)   NULL,
    [ASSET_YEAR]              NVARCHAR (50)   NULL,
    [CONTRACT_END_DATE]       DATETIME        NULL,
    [RV_AMOUNT]               DECIMAL (18, 2) NULL,
    [BRANCH_CODE]             NVARCHAR (50)   NULL,
    [BRANCH_NAME]             NVARCHAR (250)  NULL,
    [IS_CONDITION]            NVARCHAR (1)    NULL,
    [CRE_DATE]                DATETIME        NULL,
    [CRE_BY]                  NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]          NVARCHAR (15)   NULL,
    [MOD_DATE]                DATETIME        NULL,
    [MOD_BY]                  NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]          NVARCHAR (15)   NULL,
    [TO_DATE]                 DATETIME        NULL,
    [LAST_STATUS]             NVARCHAR (50)   NULL,
    [CONTRACT_AGREEMENT_DATE] DATETIME        NULL
);

