CREATE TABLE [dbo].[RPT_SURVEY] (
    [USER_ID]                         NVARCHAR (50)   NOT NULL,
    [SURVEY_REQUEST_NO]               NVARCHAR (50)   NULL,
    [REPORT_COMPANY]                  NVARCHAR (250)  NULL,
    [REPORT_TITLE]                    NVARCHAR (250)  NULL,
    [REPORT_IMAGE]                    NVARCHAR (250)  NULL,
    [NAMA]                            NVARCHAR (250)  NULL,
    [APPLICATION_TYPE]                NVARCHAR (50)   NULL,
    [GROUP_NAME]                      NVARCHAR (250)  NULL,
    [ALAMAT_KANTOR]                   NVARCHAR (4000) NULL,
    [KOTA]                            NVARCHAR (50)   NULL,
    [PROVISI]                         NVARCHAR (50)   NULL,
    [ALAMAT_USAHA]                    NVARCHAR (4000) NULL,
    [KOTA_USAHA]                      NVARCHAR (50)   NULL,
    [PROVISI_USAHA]                   NVARCHAR (50)   NULL,
    [USAHA_SEJAK]                     DATETIME        NULL,
    [AS_OF_DATE]                      DATETIME        NULL,
    [MONTHLY_SALES_OR_REVENUE]        DECIMAL (18, 2) NULL,
    [TOTAL_MONTHLY_EXPENSE]           DECIMAL (18, 2) NULL,
    [TOTAL_MONTHLY_INSTALLMENT_DSF]   DECIMAL (18, 2) NULL,
    [TOTAL_MONTHLY_INSTALLMENT_OTHER] DECIMAL (18, 2) NULL,
    [NET_INCOME_AMOUNT]               DECIMAL (18, 2) NULL,
    [OVERAL_ASSESSMENT]               NVARCHAR (50)   NULL,
    [NOTES]                           NVARCHAR (250)  NULL,
    [ECONOMIC_SEKTOR]                 NVARCHAR (50)   NULL,
    [PEMBELI_KERJA]                   NVARCHAR (250)  NULL,
    [KELAS_PEMBERI_KERJA]             NVARCHAR (50)   NULL,
    [MANAGEMENT_STYLE]                NVARCHAR (50)   NULL,
    [LOKASI_OR_AREA_KERJA]            NVARCHAR (4000) NULL,
    [NO_OF_CLIENT]                    NVARCHAR (50)   NULL,
    [NO_OF_EMPLOYEE]                  NVARCHAR (50)   NULL,
    [CREDIT_LINE_OF_BANK]             NVARCHAR (50)   NULL,
    [BUSINESS_EXPANSION]              NVARCHAR (50)   NULL,
    [MO_SUMMARY]                      NVARCHAR (4000) NULL,
    [CAPACITY]                        NVARCHAR (4000) NULL,
    [CHARACTER]                       NVARCHAR (4000) NULL,
    [WEAKNESS]                        NVARCHAR (4000) NULL,
    [STRENGHT]                        NVARCHAR (4000) NULL,
    [DATE_OF_VISIT]                   DATETIME        NULL,
    [TIME]                            NVARCHAR (50)   NULL,
    [SURVEY_METHOD]                   NVARCHAR (50)   NULL,
    [VENUE_1]                         NVARCHAR (4000) NULL,
    [VENUE_2]                         NVARCHAR (4000) NULL,
    [PROJECT]                         NVARCHAR (50)   NULL,
    [CATEGORY]                        NVARCHAR (50)   NULL,
    [DATE]                            DATETIME        NULL,
    [INTERVIEW_NAME]                  NVARCHAR (50)   NULL,
    [PHONE_NUMBER]                    NVARCHAR (20)   NULL,
    [RESULT]                          NVARCHAR (50)   NULL,
    [NOTES_SURVEY]                    NVARCHAR (4000) NULL
);

