CREATE TABLE [dbo].[RPT_DATA_ASSET] (
    [USER_ID]        NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY] NVARCHAR (250) NOT NULL,
    [REPORT_TITLE]   NVARCHAR (250) NOT NULL,
    [REPORT_IMAGE]   NVARCHAR (250) NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)  NULL,
    [BRANCH_NAME]    NVARCHAR (50)  NULL,
    [AS_OF_DATE]     DATETIME       NULL,
    [STATUS_ASSET]   NVARCHAR (50)  NULL,
    [TOTAL_DATA]     INT            NULL,
    [IS_CONDITION]   NVARCHAR (1)   NULL
);

