CREATE TABLE [dbo].[RPT_MATURITY_DETAIL] (
    [USER_ID]            NVARCHAR (50)   NULL,
    [REPORT_COMPANY]     NVARCHAR (250)  NULL,
    [REPORT_TITLE]       NVARCHAR (250)  NULL,
    [REPORT_IMAGE]       NVARCHAR (250)  NULL,
    [FA_CODE]            NVARCHAR (250)  NULL,
    [DELIVER_TO_NAME]    NVARCHAR (250)  NULL,
    [DELIVER_TO_PHONE]   NVARCHAR (50)   NULL,
    [DELIVER_TO_ADDRESS] NVARCHAR (4000) NULL,
    [CRE_DATE]           DATETIME        NOT NULL,
    [CRE_BY]             NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]     NVARCHAR (15)   NOT NULL,
    [MOD_DATE]           DATETIME        NOT NULL,
    [MOD_BY]             NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]     NVARCHAR (15)   NOT NULL
);

