CREATE TABLE [dbo].[RPT_SURAT_KUASA] (
    [USER_ID]                   NVARCHAR (50)  NOT NULL,
    [REPORT_COMPANY_NAME]       NVARCHAR (50)  NULL,
    [REPORT_TITLE]              NVARCHAR (250) NULL,
    [REPORT_IMAGE]              NVARCHAR (250) NULL,
    [COMPANY_CITY]              NVARCHAR (250) NULL,
    [COMPANY_ADDRESS]           NVARCHAR (400) NULL,
    [LETTER_NO]                 NVARCHAR (50)  NULL,
    [AGREEMENT_NO]              NVARCHAR (50)  NULL,
    [SIGNER_COLLECTOR]          NVARCHAR (250) NULL,
    [SIGNER_COLLECTOR_POSITION] NVARCHAR (50)  NULL,
    [COLLECTOR]                 NVARCHAR (250) NULL,
    [COLLECTOR_POSITION]        NVARCHAR (50)  NULL,
    [AGREEMENT_SIGN_DATE]       DATETIME       NULL,
    [CLIENT_NAME]               NVARCHAR (250) NULL,
    [CLIENT_ADDRESS]            NVARCHAR (400) NULL,
    [CLIENT_PHONE_NO]           NVARCHAR (50)  NULL,
    [ASSET_NO]                  NVARCHAR (50)  NULL,
    [ASSET_NAME]                NVARCHAR (250) NULL,
    [ASSET_YEAR]                NVARCHAR (5)   NULL,
    [FA_REFF_NO_01]             NVARCHAR (50)  NULL,
    [FA_REFF_NO_02]             NVARCHAR (50)  NULL,
    [FA_REF_NO_03]              NVARCHAR (50)  NULL,
    [ASSET_TYPE_CODE]           NVARCHAR (50)  NULL,
    [LETTER_EXP_DATE]           DATETIME       NULL,
    [CRE_DATE]                  DATETIME       NULL,
    [CRE_BY]                    NVARCHAR (15)  NULL,
    [CRE_IP_ADDRESS]            NVARCHAR (15)  NULL,
    [MOD_DATE]                  DATETIME       NULL,
    [MOD_BY]                    NVARCHAR (15)  NULL,
    [MOD_IP_ADDRESS]            NVARCHAR (15)  NULL
);

