CREATE TABLE [dbo].[SETTLEMENT_AGREEMENT_DETAIL] (
    [ID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [SETTLEMENT_ID]       BIGINT          NOT NULL,
    [ASSET_NO]            NVARCHAR (50)   NULL,
    [CONFIRMATION_DATE]   DATETIME        NULL,
    [CONFIRMATION_REMARK] NVARCHAR (4000) NULL,
    [CONFIRMATION_RESULT] NVARCHAR (50)   NULL,
    [ADDITIONAL_PERIODE]  INT             NULL,
    [RETURN_STATUS]       NVARCHAR (10)   CONSTRAINT [DF_SETTLEMENT_AGREEMENT_DETAIL_RETURN_STATUS] DEFAULT (N'HOLD') NULL,
    [RETURN_DATE]         DATETIME        NULL,
    [CRE_DATE]            DATETIME        NOT NULL,
    [CRE_BY]              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]            DATETIME        NOT NULL,
    [MOD_BY]              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]      NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_SETTLEMENT_AGREEMENT_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SETTLEMENT_AGREEMENT_DETAIL_SETTLEMENT_AGREEMENT] FOREIGN KEY ([SETTLEMENT_ID]) REFERENCES [dbo].[SETTLEMENT_AGREEMENT] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

