CREATE TABLE [dbo].[SETTLEMENT_AGREEMENT] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NOT NULL,
    [STATUS]         NVARCHAR (10)   NOT NULL,
    [REMARK]         NVARCHAR (4000) NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_SETTLEMENT_AGREEMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SETTLEMENT_AGREEMENT_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Nomor aplikasi', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SETTLEMENT_AGREEMENT', @level2type = N'COLUMN', @level2name = N'AGREEMENT_NO';

