CREATE TABLE [dbo].[STOP_BILLING] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [STATUS]         NVARCHAR (10)   NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [REMARKS]        NVARCHAR (4000) CONSTRAINT [DF_Table_1_WAIVED_REMARKS] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_STOP_BILLING] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_STOP_BILLING_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

