CREATE TABLE [dbo].[SYS_NOTIFICATION] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [FROM_ADDRESS]   NVARCHAR (250)  NOT NULL,
    [TO_EMAIL]       NVARCHAR (250)  NOT NULL,
    [TO_EMAIL_CC]    NVARCHAR (250)  NULL,
    [TO_EMAIL_BCC]   NVARCHAR (250)  NULL,
    [SUBJECT]        NVARCHAR (250)  NOT NULL,
    [HEADER]         NVARCHAR (4000) NOT NULL,
    [BODY1]          NVARCHAR (4000) NOT NULL,
    [BODY2]          NVARCHAR (4000) NOT NULL,
    [BODY3]          NVARCHAR (4000) NOT NULL,
    [FOOTER]         NVARCHAR (4000) NOT NULL,
    [ATTACHMENT]     NVARCHAR (4000) NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);


GO
    
			CREATE TRIGGER [dbo].[SYS_NOTIFICATION_Insert_Audit] 
			ON [dbo].[SYS_NOTIFICATION]    
			FOR INSERT    
			AS    
			
 INSERT INTO [dbo].[Z_AUDIT_SYS_NOTIFICATION]
([ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Insert',SUSER_SNAME(),getdate(),''  FROM INSERTED 
GO
    
			CREATE TRIGGER [dbo].[SYS_NOTIFICATION_Update_Audit]      
			ON [dbo].[SYS_NOTIFICATION]    
			FOR UPDATE    
			AS 
   
			 
			    DECLARE @UpdatedCols varchar(max) 
			 
			   SELECT @UpdatedCols =  CASE WHEN UPDATE([ID]) THEN '[ID]-' ELSE '' END + 
CASE WHEN UPDATE([FROM_ADDRESS]) THEN '[FROM_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([TO_EMAIL]) THEN '[TO_EMAIL]-' ELSE '' END + 
CASE WHEN UPDATE([TO_EMAIL_CC]) THEN '[TO_EMAIL_CC]-' ELSE '' END + 
CASE WHEN UPDATE([TO_EMAIL_BCC]) THEN '[TO_EMAIL_BCC]-' ELSE '' END + 
CASE WHEN UPDATE([SUBJECT]) THEN '[SUBJECT]-' ELSE '' END + 
CASE WHEN UPDATE([HEADER]) THEN '[HEADER]-' ELSE '' END + 
CASE WHEN UPDATE([BODY1]) THEN '[BODY1]-' ELSE '' END + 
CASE WHEN UPDATE([BODY2]) THEN '[BODY2]-' ELSE '' END + 
CASE WHEN UPDATE([BODY3]) THEN '[BODY3]-' ELSE '' END + 
CASE WHEN UPDATE([FOOTER]) THEN '[FOOTER]-' ELSE '' END + 
CASE WHEN UPDATE([ATTACHMENT]) THEN '[ATTACHMENT]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_DATE]) THEN '[CRE_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_BY]) THEN '[CRE_BY]-' ELSE '' END + 
CASE WHEN UPDATE([CRE_IP_ADDRESS]) THEN '[CRE_IP_ADDRESS]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_DATE]) THEN '[MOD_DATE]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_BY]) THEN '[MOD_BY]-' ELSE '' END + 
CASE WHEN UPDATE([MOD_IP_ADDRESS]) THEN '[MOD_IP_ADDRESS]-' ELSE '' END  
			    
			   IF LTRIM(RTRIM(@UpdatedCols)) <> '' 
			   BEGIN 
			          INSERT INTO [dbo].[Z_AUDIT_SYS_NOTIFICATION]
([ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'New','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM INSERTED     
			    
			          INSERT INTO [dbo].[Z_AUDIT_SYS_NOTIFICATION]
([ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Update',SUSER_SNAME(),getdate(),@UpdatedCols  FROM DELETED  
			   END
GO
    
			CREATE TRIGGER [dbo].[SYS_NOTIFICATION_Delete_Audit]    
			ON [dbo].[SYS_NOTIFICATION]    
			FOR DELETE    
			AS   
  INSERT INTO [dbo].[Z_AUDIT_SYS_NOTIFICATION]
([ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],AuditDataState,AuditDMLAction,AuditUser,AuditDateTime,UpdateColumns)
SELECT CONVERT(bigint,[ID]) as [ID],[FROM_ADDRESS],[TO_EMAIL],[TO_EMAIL_CC],[TO_EMAIL_BCC],[SUBJECT],[HEADER],[BODY1],[BODY2],[BODY3],[FOOTER],[ATTACHMENT],[CRE_DATE],[CRE_BY],[CRE_IP_ADDRESS],[MOD_DATE],[MOD_BY],[MOD_IP_ADDRESS],'Old','Delete',SUSER_SNAME(),getdate(),''  FROM DELETED