CREATE TABLE [dbo].[TBO_DOCUMENT_DETAIL] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [REFF_CODE]       NVARCHAR (50)   NOT NULL,
    [DOCUMENT_CODE]   NVARCHAR (50)   NOT NULL,
    [PROMISE_DATE]    DATETIME        NULL,
    [IS_REQUIRED]     NVARCHAR (1)    NOT NULL,
    [IS_VALID]        NVARCHAR (1)    NULL,
    [IS_RECEIVED]     NVARCHAR (1)    NULL,
    [REMARKS]         NVARCHAR (4000) NULL,
    [CRE_DATE]        DATETIME        NOT NULL,
    [CRE_BY]          NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [MOD_DATE]        DATETIME        NOT NULL,
    [MOD_BY]          NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15)   NOT NULL,
    [APPLICATION_NO]  NVARCHAR (50)   NULL,
    [TBO_DOCUMENT_ID] BIGINT          NULL,
    CONSTRAINT [PK_TBO_DOCUMENT_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TBO_DOCUMENT_DETAIL_SYS_GENERAL_DOCUMENT] FOREIGN KEY ([DOCUMENT_CODE]) REFERENCES [dbo].[SYS_GENERAL_DOCUMENT] ([CODE])
);

