CREATE TABLE [dbo].[TEMP_CLIENT_NAME] (
    [AGREEMENT_NO]     NVARCHAR (255) NULL,
    [CLIENT_NAME]      NVARCHAR (255) NULL,
    [JENIS]            NVARCHAR (255) NULL,
    [CLIENT_NAME_BARU] NVARCHAR (255) NULL
);

