CREATE TABLE [dbo].[TEMP_AGREEMENT_ASSET_AMORTIZATION_RECON_24112023] (
    [AGREEMENT_NO]   NVARCHAR (50)   NULL,
    [ASSET_NO]       NVARCHAR (50)   NULL,
    [BILLING_NO]     INT             NULL,
    [DUE_DATE]       DATETIME        NULL,
    [BILLING_DATE]   DATETIME        NULL,
    [BILLING_AMOUNT] DECIMAL (18, 2) NULL
);

