CREATE TABLE [dbo].[WAIVED_OBLIGATION] (
    [CODE]              NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]       NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]       NVARCHAR (250)  NOT NULL,
    [AGREEMENT_NO]      NVARCHAR (50)   NOT NULL,
    [WAIVED_STATUS]     NVARCHAR (10)   NOT NULL,
    [WAIVED_DATE]       DATETIME        NOT NULL,
    [WAIVED_AMOUNT]     DECIMAL (18, 2) CONSTRAINT [DF_WAIVED_AMOUNT] DEFAULT ((0)) NOT NULL,
    [WAIVED_REMARKS]    NVARCHAR (4000) CONSTRAINT [DF_WAIVED_OBLIGATION_WAIVED_REMARKS] DEFAULT ((0)) NOT NULL,
    [OBLIGATION_AMOUNT] DECIMAL (18, 2) CONSTRAINT [DF_WAIVED_OBLIGATION_AMOUNT] DEFAULT ((0)) NOT NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_WAIVED_OBLIGATION] PRIMARY KEY CLUSTERED ([CODE] ASC),
    CONSTRAINT [FK_WAIVED_OBLIGATION_AGREEMENT_MAIN] FOREIGN KEY ([AGREEMENT_NO]) REFERENCES [dbo].[AGREEMENT_MAIN] ([AGREEMENT_NO]) ON DELETE CASCADE ON UPDATE CASCADE
);

