CREATE TABLE [dbo].[WARNING_LETTER_DELIVERY_BACKUP] (
    [CODE]                        NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                 NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                 NVARCHAR (250)  NOT NULL,
    [DELIVERY_STATUS]             NVARCHAR (10)   NOT NULL,
    [DELIVERY_DATE]               DATETIME        NOT NULL,
    [DELIVERY_COURIER_TYPE]       NVARCHAR (10)   NOT NULL,
    [DELIVERY_COURIER_CODE]       NVARCHAR (50)   NULL,
    [DELIVERY_COLLECTOR_CODE]     NVARCHAR (50)   NULL,
    [DELIVERY_COLLECTOR_NAME]     NVARCHAR (250)  NULL,
    [DELIVERY_REMARKS]            NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                    DATETIME        NOT NULL,
    [CRE_BY]                      NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                    DATETIME        NOT NULL,
    [MOD_BY]                      NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]              NVARCHAR (15)   NOT NULL,
    [CLIENT_NO]                   NVARCHAR (50)   NULL,
    [CLIENT_NAME]                 NVARCHAR (250)  NULL,
    [delivery_address]            NVARCHAR (4000) NULL,
    [delivery_to_name]            NVARCHAR (250)  NULL,
    [client_phone_no]             NVARCHAR (50)   NULL,
    [client_npwp]                 NVARCHAR (50)   NULL,
    [client_email]                NVARCHAR (50)   NULL,
    [letter_date]                 DATETIME        NULL,
    [letter_type]                 NVARCHAR (50)   NULL,
    [generate_type]               NVARCHAR (50)   NULL,
    [overdue_days]                BIGINT          NULL,
    [total_overdue_amount]        DECIMAL (18, 2) NULL,
    [total_agreement]             BIGINT          NULL,
    [total_asset]                 BIGINT          NULL,
    [total_monthly_rental_amount] DECIMAL (18, 2) NULL,
    [last_print_by]               NVARCHAR (50)   NULL,
    [print_count]                 BIGINT          NULL
);

