CREATE TABLE [dbo].[WITHHOLDING_SETTLEMENT_AUDIT] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]    NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]    NVARCHAR (250)  NOT NULL,
    [DATE]           DATETIME        NOT NULL,
    [YEAR]           INT             NOT NULL,
    [REMARK]         NVARCHAR (4000) NOT NULL,
    [STATUS]         NVARCHAR (10)   NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_WITHHOLDING_SETTLEMENT_AUDIT] PRIMARY KEY CLUSTERED ([CODE] ASC)
);

