CREATE TABLE [dbo].[WRITE_OFF_INVOICE] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [WRITE_OFF_CODE] NVARCHAR (50) NOT NULL,
    [INVOICE_NO]     NVARCHAR (50) NOT NULL,
    [CRE_DATE]       DATETIME      NOT NULL,
    [CRE_BY]         NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    [MOD_DATE]       DATETIME      NOT NULL,
    [MOD_BY]         NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_WRITE_OFF_INVOICE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

