CREATE TABLE [dbo].[XXX_AR_DAILY_BALANCING_20250407] (
    [ID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [AGREEMENT_NO] NVARCHAR (50)   NOT NULL,
    [CLIENT_NAME]  NVARCHAR (250)  NOT NULL,
    [AR_DUE]       DECIMAL (18, 2) NULL,
    [AR_NOT_DUE]   DECIMAL (18, 2) NULL,
    [EOD_DATE]     DATETIME        NULL
);

