CREATE TABLE [dbo].[XXX_APPLICATION_MAIN_20240729] (
    [ID]                                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NO]                      NVARCHAR (50)   NOT NULL,
    [APPLICATION_EXTERNAL_NO]             NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                         NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                         NVARCHAR (250)  NOT NULL,
    [APPLICATION_DATE]                    DATETIME        NULL,
    [APPLICATION_STATUS]                  NVARCHAR (10)   NOT NULL,
    [LEVEL_STATUS]                        NVARCHAR (20)   NOT NULL,
    [APPLICATION_REMARKS]                 NVARCHAR (4000) NULL,
    [BRANCH_REGION_CODE]                  NVARCHAR (50)   NOT NULL,
    [BRANCH_REGION_NAME]                  NVARCHAR (250)  NOT NULL,
    [MARKETING_CODE]                      NVARCHAR (50)   NULL,
    [MARKETING_NAME]                      NVARCHAR (250)  NULL,
    [CLIENT_CODE]                         NVARCHAR (50)   NULL,
    [FACILITY_CODE]                       NVARCHAR (50)   NULL,
    [CURRENCY_CODE]                       NVARCHAR (3)    NULL,
    [MAIN_AGREEMENT_NO]                   NVARCHAR (50)   NULL,
    [AGREEMENT_NO]                        NVARCHAR (50)   NULL,
    [AGREEMENT_EXTERNAL_NO]               NVARCHAR (50)   NULL,
    [GOLIVE_DATE]                         DATETIME        NULL,
    [AGREEMENT_SIGN_DATE]                 DATETIME        NULL,
    [FIRST_INSTALLMENT_DATE]              DATETIME        NULL,
    [RENTAL_AMOUNT]                       DECIMAL (18, 2) NOT NULL,
    [IS_BLACKLIST_AREA]                   NVARCHAR (1)    NULL,
    [IS_BLACKLIST_JOB]                    NVARCHAR (1)    NULL,
    [WATCHLIST_STATUS]                    NVARCHAR (10)   NULL,
    [RETURN_COUNT]                        INT             NOT NULL,
    [ASSET_ALLOCATION_STATUS]             NVARCHAR (10)   NULL,
    [TAX_SCHEME_CODE]                     NVARCHAR (50)   NULL,
    [PPN_PCT]                             DECIMAL (9, 6)  NOT NULL,
    [PPH_PCT]                             DECIMAL (9, 6)  NOT NULL,
    [PERIODE]                             INT             NOT NULL,
    [BILLING_TYPE]                        NVARCHAR (50)   NULL,
    [CREDIT_TERM]                         INT             NOT NULL,
    [FIRST_PAYMENT_TYPE]                  NVARCHAR (3)    NOT NULL,
    [IS_PURCHASE_REQUIREMENT_AFTER_LEASE] NVARCHAR (1)    NULL,
    [LEASE_OPTION]                        NVARCHAR (10)   NULL,
    [ROUND_TYPE]                          NVARCHAR (10)   NULL,
    [ROUND_AMOUNT]                        DECIMAL (18, 2) NULL,
    [CLIENT_NAME]                         NVARCHAR (250)  NULL,
    [CLIENT_PHONE_AREA]                   NVARCHAR (4)    NULL,
    [CLIENT_PHONE_NO]                     NVARCHAR (15)   NULL,
    [CLIENT_EMAIL]                        NVARCHAR (250)  NULL,
    [CLIENT_ADDRESS]                      NVARCHAR (4000) NULL,
    [IS_SIMULATION]                       NVARCHAR (1)    NULL,
    [CRE_DATE]                            DATETIME        NOT NULL,
    [CRE_BY]                              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                            DATETIME        NOT NULL,
    [MOD_BY]                              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL
);

