CREATE TABLE [dbo].[XXX_REVISI_CLIENT_NAME] (
    [AGREEMENT_NO] NVARCHAR (255) NULL,
    [CLIENT_NAME]  NVARCHAR (255) NULL,
    [SEHARUSNYA]   NVARCHAR (255) NULL,
    [ADDRESS]      NVARCHAR (255) NULL
);

