CREATE TABLE [dbo].[XXX_FAKTUR_ALLOCATION_DETAIL_20241128] (
    [ID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [ALLOCATION_CODE] NVARCHAR (50) NOT NULL,
    [INVOICE_NO]      NVARCHAR (50) NOT NULL,
    [FAKTUR_NO]       NVARCHAR (50) NOT NULL,
    [CRE_DATE]        DATETIME      NOT NULL,
    [CRE_BY]          NVARCHAR (15) NOT NULL,
    [CRE_IP_ADDRESS]  NVARCHAR (15) NOT NULL,
    [MOD_DATE]        DATETIME      NOT NULL,
    [MOD_BY]          NVARCHAR (15) NOT NULL,
    [MOD_IP_ADDRESS]  NVARCHAR (15) NOT NULL
);

