CREATE TABLE [dbo].[XXX_APPLICATION_SCORING_REQUEST_20241121] (
    [CODE]                   NVARCHAR (50)   NOT NULL,
    [APPLICATION_NO]         NVARCHAR (50)   NOT NULL,
    [SCORING_STATUS]         NVARCHAR (10)   NOT NULL,
    [SCORING_DATE]           DATETIME        NOT NULL,
    [SCORING_OBJECT]         NVARCHAR (4000) NULL,
    [SCORING_REMARKS]        NVARCHAR (4000) NOT NULL,
    [SCORING_RESULT_DATE]    DATETIME        NULL,
    [SCORING_RESULT_VALUE]   NVARCHAR (250)  NULL,
    [SCORING_RESULT_GRADE]   NVARCHAR (50)   NULL,
    [SCORING_RESULT_REMARKS] NVARCHAR (4000) NULL,
    [CRE_DATE]               DATETIME        NOT NULL,
    [CRE_BY]                 NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]         NVARCHAR (15)   NOT NULL,
    [MOD_DATE]               DATETIME        NOT NULL,
    [MOD_BY]                 NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]         NVARCHAR (15)   NOT NULL
);

