CREATE TABLE [dbo].[XXX_AGREEMENT_ASSET_INTEREST_INCOME_22072024] (
    [AGREEMENT_NO]     NVARCHAR (50)   NOT NULL,
    [ASSET_NO]         NVARCHAR (50)   NOT NULL,
    [INSTALLMENT_NO]   INT             NOT NULL,
    [INVOICE_NO]       NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]      NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]      NVARCHAR (250)  NOT NULL,
    [TRANSACTION_DATE] DATETIME        NOT NULL,
    [INCOME_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [REFF_NO]          NVARCHAR (50)   NOT NULL,
    [REFF_NAME]        NVARCHAR (250)  NOT NULL,
    [ACCRUE_TYPE]      NVARCHAR (2)    NULL,
    [CRE_DATE]         DATETIME        NOT NULL,
    [CRE_BY]           NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [MOD_DATE]         DATETIME        NOT NULL,
    [MOD_BY]           NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]   NVARCHAR (15)   NOT NULL,
    [INCOME_AMOUNT_1]  DECIMAL (18, 2) NULL
);

