CREATE TABLE [dbo].[XXX_ADDITIONAL_INVOICE_REQUEST_20240604] (
    [CODE]                 NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]         NVARCHAR (50)   NULL,
    [ASSET_NO]             NVARCHAR (50)   NULL,
    [BRANCH_CODE]          NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]          NVARCHAR (250)  NOT NULL,
    [INVOICE_TYPE]         NVARCHAR (10)   NOT NULL,
    [INVOICE_DATE]         DATETIME        NOT NULL,
    [INVOICE_NAME]         NVARCHAR (250)  NOT NULL,
    [CLIENT_NO]            NVARCHAR (50)   NOT NULL,
    [CLIENT_NAME]          NVARCHAR (250)  NOT NULL,
    [CLIENT_ADDRESS]       NVARCHAR (4000) NOT NULL,
    [CLIENT_AREA_PHONE_NO] NVARCHAR (4)    NOT NULL,
    [CLIENT_PHONE_NO]      NVARCHAR (15)   NOT NULL,
    [CLIENT_NPWP]          NVARCHAR (50)   NULL,
    [CURRENCY_CODE]        NVARCHAR (3)    NOT NULL,
    [TAX_SCHEME_CODE]      NVARCHAR (50)   NOT NULL,
    [TAX_SCHEME_NAME]      NVARCHAR (250)  NOT NULL,
    [BILLING_NO]           INT             NOT NULL,
    [DESCRIPTION]          NVARCHAR (4000) NOT NULL,
    [QUANTITY]             INT             NOT NULL,
    [BILLING_AMOUNT]       DECIMAL (18, 2) NOT NULL,
    [DISCOUNT_AMOUNT]      DECIMAL (18, 2) NOT NULL,
    [PPN_PCT]              DECIMAL (9, 6)  NOT NULL,
    [PPN_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [PPH_PCT]              DECIMAL (9, 6)  NOT NULL,
    [PPH_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [TOTAL_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [REFF_CODE]            NVARCHAR (50)   NOT NULL,
    [REFF_NAME]            NVARCHAR (250)  NOT NULL,
    [STATUS]               NVARCHAR (10)   NOT NULL,
    [CRE_DATE]             DATETIME        NOT NULL,
    [CRE_BY]               NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]       NVARCHAR (15)   NOT NULL,
    [MOD_DATE]             DATETIME        NOT NULL,
    [MOD_BY]               NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]       NVARCHAR (15)   NOT NULL
);

