CREATE TABLE [dbo].[XXX_OPL_INTERFACE_CASHIER_RECEIVED_REQUEST_DETAIL_05012024] (
    [ID]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [CASHIER_RECEIVED_REQUEST_CODE] NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]                   NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                   NVARCHAR (250)  NOT NULL,
    [GL_LINK_CODE]                  NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]                  NVARCHAR (50)   NULL,
    [FACILITY_CODE]                 NVARCHAR (50)   NULL,
    [FACILITY_NAME]                 NVARCHAR (250)  NULL,
    [PURPOSE_LOAN_CODE]             NVARCHAR (50)   NULL,
    [PURPOSE_LOAN_NAME]             NVARCHAR (250)  NULL,
    [PURPOSE_LOAN_DETAIL_CODE]      NVARCHAR (50)   NULL,
    [PURPOSE_LOAN_DETAIL_NAME]      NVARCHAR (250)  NULL,
    [ORIG_CURRENCY_CODE]            NVARCHAR (3)    NOT NULL,
    [ORIG_AMOUNT]                   DECIMAL (18, 2) NOT NULL,
    [DIVISION_CODE]                 NVARCHAR (50)   NULL,
    [DIVISION_NAME]                 NVARCHAR (250)  NULL,
    [DEPARTMENT_CODE]               NVARCHAR (50)   NULL,
    [DEPARTMENT_NAME]               NVARCHAR (250)  NULL,
    [REMARKS]                       NVARCHAR (4000) NOT NULL,
    [CRE_DATE]                      DATETIME        NOT NULL,
    [CRE_BY]                        NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                      DATETIME        NOT NULL,
    [MOD_BY]                        NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                NVARCHAR (15)   NOT NULL
);

