CREATE TABLE [dbo].[XXX_CREDIT_NOTE_DETAIL_20250203] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [CREDIT_NOTE_CODE]  NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]        NVARCHAR (50)   NOT NULL,
    [INVOICE_DETAIL_ID] BIGINT          NOT NULL,
    [ADJUSTMENT_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [NEW_RENTAL_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [NEW_PPN_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [NEW_PPH_AMOUNT]    DECIMAL (18, 2) NOT NULL,
    [NEW_TOTAL_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL
);

