CREATE TABLE [dbo].[XXX_AGREEMENT_MAIN_06112023] (
    [AGREEMENT_NO]                        NVARCHAR (50)   NOT NULL,
    [AGREEMENT_EXTERNAL_NO]               NVARCHAR (50)   NULL,
    [APPLICATION_NO]                      NVARCHAR (50)   NOT NULL,
    [AGREEMENT_DATE]                      DATETIME        NOT NULL,
    [AGREEMENT_STATUS]                    NVARCHAR (10)   NOT NULL,
    [AGREEMENT_SUB_STATUS]                NVARCHAR (20)   NOT NULL,
    [TERMINATION_DATE]                    DATETIME        NULL,
    [TERMINATION_STATUS]                  NVARCHAR (20)   NULL,
    [COLLECTION_STATUS]                   NVARCHAR (20)   NOT NULL,
    [BRANCH_CODE]                         NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]                         NVARCHAR (250)  NOT NULL,
    [INITIAL_BRANCH_CODE]                 NVARCHAR (50)   NOT NULL,
    [INITIAL_BRANCH_NAME]                 NVARCHAR (250)  NOT NULL,
    [CURRENCY_CODE]                       NVARCHAR (3)    NOT NULL,
    [FACILITY_CODE]                       NVARCHAR (50)   NULL,
    [FACILITY_NAME]                       NVARCHAR (250)  NULL,
    [CLIENT_TYPE]                         NVARCHAR (10)   NOT NULL,
    [CLIENT_NO]                           NVARCHAR (50)   NOT NULL,
    [CLIENT_NAME]                         NVARCHAR (250)  NOT NULL,
    [TAX_SCHEME_CODE]                     NVARCHAR (50)   NULL,
    [PPN_PCT]                             DECIMAL (9, 6)  NOT NULL,
    [PPH_PCT]                             DECIMAL (9, 6)  NOT NULL,
    [OLD_AGREEMENT_NO]                    NVARCHAR (50)   NULL,
    [PAYMENT_PROMISE_DATE]                DATETIME        NULL,
    [MATURITY_CODE]                       NVARCHAR (50)   NULL,
    [IS_STOP_BILLING]                     NVARCHAR (1)    NOT NULL,
    [IS_PENDING_BILLING]                  NVARCHAR (1)    NOT NULL,
    [PERIODE]                             INT             NULL,
    [BILLING_TYPE]                        NVARCHAR (50)   NULL,
    [CREDIT_TERM]                         INT             NULL,
    [FIRST_PAYMENT_TYPE]                  NVARCHAR (3)    NULL,
    [IS_PURCHASE_REQUIREMENT_AFTER_LEASE] NVARCHAR (1)    NULL,
    [LEASE_OPTION]                        NVARCHAR (10)   NULL,
    [ROUND_TYPE]                          NVARCHAR (10)   NULL,
    [ROUND_AMOUNT]                        DECIMAL (18, 2) NULL,
    [MARKETING_CODE]                      NVARCHAR (50)   NULL,
    [MARKETING_NAME]                      NVARCHAR (250)  NULL,
    [OPL_STATUS]                          NVARCHAR (15)   NULL,
    [AGREEMENT_SIGN_DATE]                 DATETIME        NULL,
    [CRE_DATE]                            DATETIME        NOT NULL,
    [CRE_BY]                              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                            DATETIME        NOT NULL,
    [MOD_BY]                              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [CLIENT_ID]                           NVARCHAR (50)   NULL,
    [APPLICATION_NO_EXTERNAL]             NVARCHAR (50)   NULL
);

