CREATE TABLE [dbo].[XXX_AGREEMENT_ASSET_20250310] (
    [ASSET_NO]                            NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]                        NVARCHAR (50)   NOT NULL,
    [ASSET_TYPE_CODE]                     NVARCHAR (50)   NOT NULL,
    [ASSET_NAME]                          NVARCHAR (250)  NOT NULL,
    [ASSET_YEAR]                          NVARCHAR (4)    NOT NULL,
    [ASSET_CONDITION]                     NVARCHAR (5)    NOT NULL,
    [ASSET_STATUS]                        NVARCHAR (20)   NOT NULL,
    [BILLING_TO]                          NVARCHAR (10)   NOT NULL,
    [BILLING_TO_NAME]                     NVARCHAR (250)  NOT NULL,
    [BILLING_TO_AREA_NO]                  NVARCHAR (4)    NOT NULL,
    [BILLING_TO_PHONE_NO]                 NVARCHAR (15)   NOT NULL,
    [BILLING_TO_ADDRESS]                  NVARCHAR (4000) NOT NULL,
    [BILLING_TO_FAKTUR_TYPE]              NVARCHAR (3)    NULL,
    [BILLING_TYPE]                        NVARCHAR (50)   NOT NULL,
    [BILLING_MODE]                        NVARCHAR (10)   NOT NULL,
    [BILLING_MODE_DATE]                   INT             NOT NULL,
    [BILLING_TO_NPWP]                     NVARCHAR (20)   NULL,
    [NPWP_NAME]                           NVARCHAR (250)  NULL,
    [NPWP_ADDRESS]                        NVARCHAR (4000) NULL,
    [IS_PURCHASE_REQUIREMENT_AFTER_LEASE] NVARCHAR (1)    NOT NULL,
    [DELIVER_TO]                          NVARCHAR (10)   NOT NULL,
    [DELIVER_TO_NAME]                     NVARCHAR (250)  NOT NULL,
    [DELIVER_TO_AREA_NO]                  NVARCHAR (4)    NOT NULL,
    [DELIVER_TO_PHONE_NO]                 NVARCHAR (15)   NOT NULL,
    [DELIVER_TO_ADDRESS]                  NVARCHAR (4000) NOT NULL,
    [PICKUP_NAME]                         NVARCHAR (250)  NULL,
    [PICKUP_PHONE_AREA_NO]                NVARCHAR (4)    NULL,
    [PICKUP_PHONE_NO]                     NVARCHAR (15)   NULL,
    [PICKUP_ADDRESS]                      NVARCHAR (4000) NULL,
    [MARKET_VALUE]                        DECIMAL (18, 2) NOT NULL,
    [KAROSERI_AMOUNT]                     DECIMAL (18, 2) NOT NULL,
    [ACCESSORIES_AMOUNT]                  DECIMAL (18, 2) NOT NULL,
    [MOBILIZATION_AMOUNT]                 DECIMAL (18, 2) NOT NULL,
    [ASSET_AMOUNT]                        DECIMAL (18, 2) NOT NULL,
    [ASSET_INTEREST_RATE]                 DECIMAL (9, 6)  NULL,
    [ASSET_INTEREST_AMOUNT]               DECIMAL (18, 2) NOT NULL,
    [ASSET_RV_PCT]                        DECIMAL (9, 6)  NULL,
    [ASSET_RV_AMOUNT]                     DECIMAL (18, 2) NOT NULL,
    [PERIODE]                             INT             NOT NULL,
    [FIRST_PAYMENT_TYPE]                  NVARCHAR (3)    NOT NULL,
    [LEASE_OPTION]                        NVARCHAR (10)   NOT NULL,
    [COGS_AMOUNT]                         DECIMAL (18, 2) NOT NULL,
    [BASIC_LEASE_AMOUNT]                  DECIMAL (18, 2) NOT NULL,
    [MARGIN_BY]                           NVARCHAR (50)   NULL,
    [MARGIN_RATE]                         DECIMAL (9, 6)  NULL,
    [MARGIN_AMOUNT]                       DECIMAL (18, 2) NOT NULL,
    [ADDITIONAL_CHARGE_RATE]              DECIMAL (9, 6)  NULL,
    [ADDITIONAL_CHARGE_AMOUNT]            DECIMAL (18, 2) NOT NULL,
    [LEASE_AMOUNT]                        DECIMAL (18, 2) NOT NULL,
    [LEASE_ROUND_TYPE]                    NVARCHAR (10)   NULL,
    [LEASE_ROUND_AMOUNT]                  DECIMAL (18, 2) NOT NULL,
    [LEASE_ROUNDED_AMOUNT]                DECIMAL (18, 2) NOT NULL,
    [NET_MARGIN_AMOUNT]                   DECIMAL (18, 2) NOT NULL,
    [HANDOVER_CODE]                       NVARCHAR (50)   NULL,
    [HANDOVER_BAST_DATE]                  DATETIME        NULL,
    [HANDOVER_STATUS]                     NVARCHAR (10)   NULL,
    [HANDOVER_REMARK]                     NVARCHAR (4000) NULL,
    [FA_CODE]                             NVARCHAR (50)   NULL,
    [FA_NAME]                             NVARCHAR (250)  NULL,
    [FA_REFF_NO_01]                       NVARCHAR (250)  NULL,
    [FA_REFF_NO_02]                       NVARCHAR (250)  NULL,
    [FA_REFF_NO_03]                       NVARCHAR (250)  NULL,
    [REPLACEMENT_FA_CODE]                 NVARCHAR (50)   NULL,
    [REPLACEMENT_FA_NAME]                 NVARCHAR (250)  NULL,
    [REPLACEMENT_FA_REFF_NO_01]           NVARCHAR (50)   NULL,
    [REPLACEMENT_FA_REFF_NO_02]           NVARCHAR (50)   NULL,
    [REPLACEMENT_FA_REFF_NO_03]           NVARCHAR (50)   NULL,
    [REPLACEMENT_END_DATE]                DATETIME        NULL,
    [RETURN_DATE]                         DATETIME        NULL,
    [RETURN_STATUS]                       NVARCHAR (10)   NULL,
    [RETURN_REMARK]                       NVARCHAR (4000) NULL,
    [EMAIL]                               NVARCHAR (250)  NULL,
    [IS_AUTO_EMAIL]                       NVARCHAR (1)    NULL,
    [IS_OTR]                              NVARCHAR (1)    NULL,
    [BBN_LOCATION_CODE]                   NVARCHAR (50)   NULL,
    [BBN_LOCATION_DESCRIPTION]            NVARCHAR (4000) NULL,
    [PLAT_COLOUR]                         NVARCHAR (10)   NULL,
    [USAGE]                               NVARCHAR (10)   NULL,
    [START_MILES]                         INT             NULL,
    [MONTHLY_MILES]                       INT             NULL,
    [IS_USE_REGISTRATION]                 NVARCHAR (1)    NULL,
    [IS_USE_REPLACEMENT]                  NVARCHAR (1)    NULL,
    [IS_USE_MAINTENANCE]                  NVARCHAR (1)    NULL,
    [ESTIMATE_DELIVERY_DATE]              DATETIME        NULL,
    [ESTIMATE_PO_DATE]                    DATETIME        NULL,
    [IS_REQUEST_GTS]                      NVARCHAR (1)    NULL,
    [IS_BBN_CLIENT]                       NVARCHAR (1)    NULL,
    [CLIENT_BBN_NAME]                     NVARCHAR (250)  NULL,
    [CLIENT_BBN_ADDRESS]                  NVARCHAR (4000) NULL,
    [PMT_AMOUNT]                          DECIMAL (18, 2) NULL,
    [INITIAL_PRICE_AMOUNT]                DECIMAL (18, 2) NULL,
    [SUBVENTION_AMOUNT]                   DECIMAL (18, 2) NULL,
    [SPAF_AMOUNT]                         DECIMAL (18, 2) NULL,
    [INSURANCE_COMMISSION_AMOUNT]         DECIMAL (18, 2) NULL,
    [AVERAGE_ASSET_AMOUNT]                DECIMAL (18, 2) NULL,
    [YEARLY_PROFIT_AMOUNT]                DECIMAL (18, 2) NULL,
    [ROA_PCT]                             DECIMAL (9, 6)  NULL,
    [BUDGET_MAINTENANCE_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [BUDGET_INSURANCE_AMOUNT]             DECIMAL (18, 2) NOT NULL,
    [BUDGET_REPLACEMENT_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [BUDGET_REGISTRATION_AMOUNT]          DECIMAL (18, 2) NOT NULL,
    [TOTAL_BUDGET_AMOUNT]                 DECIMAL (18, 2) NULL,
    [MOBILIZATION_CITY_CODE]              NVARCHAR (50)   NULL,
    [MOBILIZATION_CITY_DESCRIPTION]       NVARCHAR (250)  NULL,
    [MOBILIZATION_PROVINCE_CODE]          NVARCHAR (50)   NULL,
    [MOBILIZATION_PROVINCE_DESCRIPTION]   NVARCHAR (250)  NULL,
    [BORROWING_INTEREST_RATE]             DECIMAL (9, 6)  NULL,
    [BORROWING_INTEREST_AMOUNT]           DECIMAL (18, 2) NOT NULL,
    [DISCOUNT_AMOUNT]                     DECIMAL (18, 2) NOT NULL,
    [DISCOUNT_KAROSERI_AMOUNT]            DECIMAL (18, 2) NOT NULL,
    [DISCOUNT_ACCESSORIES_AMOUNT]         DECIMAL (18, 2) NOT NULL,
    [SURAT_NO]                            NVARCHAR (50)   NULL,
    [CRE_DATE]                            DATETIME        NOT NULL,
    [CRE_BY]                              NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                            DATETIME        NOT NULL,
    [MOD_BY]                              NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                      NVARCHAR (15)   NOT NULL,
    [IS_INVOICE_DEDUCT_PPH]               NVARCHAR (1)    NULL,
    [IS_RECEIPT_DEDUCT_PPH]               NVARCHAR (1)    NULL,
    [OTR_AMOUNT]                          DECIMAL (18, 2) NOT NULL,
    [MONTHLY_RENTAL_ROUNDED_AMOUNT]       DECIMAL (18, 2) NULL,
    [IS_USE_GPS]                          NVARCHAR (1)    NULL,
    [GPS_MONTHLY_AMOUNT]                  DECIMAL (18, 2) NULL,
    [GPS_INSTALLATION_AMOUNT]             DECIMAL (18, 2) NULL
);

