CREATE TABLE [dbo].[XXX_AGREEMENT_INVOICE_PPH_14062024] (
    [CODE]           NVARCHAR (50)   NOT NULL,
    [INVOICE_NO]     NVARCHAR (50)   NOT NULL,
    [AGREEMENT_NO]   NVARCHAR (50)   NOT NULL,
    [ASSET_NO]       NVARCHAR (50)   NOT NULL,
    [BILLING_NO]     INT             NOT NULL,
    [DUE_DATE]       DATETIME        NOT NULL,
    [INVOICE_DATE]   DATETIME        NOT NULL,
    [PPH_AMOUNT]     DECIMAL (18, 2) NOT NULL,
    [DESCRIPTION]    NVARCHAR (4000) NOT NULL,
    [CRE_DATE]       DATETIME        NOT NULL,
    [CRE_BY]         NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS] NVARCHAR (15)   NOT NULL,
    [MOD_DATE]       DATETIME        NOT NULL,
    [MOD_BY]         NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS] NVARCHAR (15)   NOT NULL
);

