CREATE TABLE [dbo].[XXX_AGREEMENT_INFORMATION_20240130] (
    [AGREEMENT_NO]                  NVARCHAR (50)   NOT NULL,
    [DESKCOLL_STAFF_CODE]           NVARCHAR (50)   NULL,
    [DESKCOLL_STAFF_NAME]           NVARCHAR (250)  NULL,
    [INSTALLMENT_AMOUNT]            DECIMAL (18, 2) NOT NULL,
    [INSTALLMENT_DUE_DATE]          DATETIME        NULL,
    [NEXT_DUE_DATE]                 DATETIME        NULL,
    [LAST_PAID_PERIOD]              INT             NOT NULL,
    [OVD_PERIOD]                    INT             NOT NULL,
    [OVD_DAYS]                      INT             NOT NULL,
    [OVD_RENTAL_AMOUNT]             DECIMAL (18, 2) NOT NULL,
    [OVD_PENALTY_AMOUNT]            DECIMAL (18, 2) NOT NULL,
    [OS_RENTAL_AMOUNT]              DECIMAL (18, 2) NOT NULL,
    [OS_DEPOSIT_INSTALLMENT_AMOUNT] DECIMAL (18, 2) NOT NULL,
    [OS_PERIOD]                     INT             NOT NULL,
    [LAST_PAYMENT_INSTALLMENT_DATE] DATETIME        NULL,
    [LAST_PAYMENT_OBLIGATION_DATE]  DATETIME        NULL,
    [PAYMENT_PROMISE_DATE]          DATETIME        NULL,
    [SKT_STATUS]                    NVARCHAR (15)   NULL,
    [MATURITY_DATE]                 DATETIME        NULL,
    [MAX_OVD_DAYS]                  INT             NULL,
    [CURRENT_INSTALLMENT_NO]        INT             NULL,
    [CRE_DATE]                      DATETIME        NOT NULL,
    [CRE_BY]                        NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [MOD_DATE]                      DATETIME        NOT NULL,
    [MOD_BY]                        NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]                NVARCHAR (15)   NOT NULL,
    [BLACKLIST_STATUS]              NVARCHAR (10)   NULL,
    [BLACKLIST_DATE]                DATETIME        NULL,
    [BLACKLIST_REMARK]              NVARCHAR (4000) NULL
);

