CREATE TABLE [dbo].[xxx_ASSET_INSURANCE_DETAIL_19122023] (
    [ID]                                BIGINT          NULL,
    [ASSET_NO]                          NVARCHAR (50)   NULL,
    [MAIN_COVERAGE_CODE]                NVARCHAR (50)   NULL,
    [MAIN_COVERAGE_DESCRIPTION]         NVARCHAR (50)   NULL,
    [REGION_CODE]                       NVARCHAR (50)   NULL,
    [REGION_DESCRIPTION]                NVARCHAR (250)  NULL,
    [MAIN_COVERAGE_PREMIUM_AMOUNT]      DECIMAL (18, 2) NULL,
    [IS_USE_TPL]                        NVARCHAR (1)    NULL,
    [TPL_COVERAGE_CODE]                 NVARCHAR (50)   NULL,
    [TPL_COVERAGE_DESCRIPTION]          NVARCHAR (250)  NULL,
    [TPL_PREMIUM_AMOUNT]                DECIMAL (18, 2) NULL,
    [IS_USE_PLL]                        NVARCHAR (1)    NULL,
    [PLL_COVERAGE_CODE]                 NVARCHAR (50)   NULL,
    [PLL_COVERAGE_DESCRIPTION]          NVARCHAR (250)  NULL,
    [PLL_PREMIUM_AMOUNT]                DECIMAL (18, 2) NULL,
    [IS_USE_PA_PASSENGER]               NVARCHAR (1)    NULL,
    [PA_PASSENGER_AMOUNT]               DECIMAL (18, 2) NULL,
    [PA_PASSENGER_SEAT]                 INT             NULL,
    [PA_PASSENGER_PREMIUM_AMOUNT]       DECIMAL (18, 2) NULL,
    [IS_USE_PA_DRIVER]                  NVARCHAR (1)    NULL,
    [PA_DRIVER_AMOUNT]                  DECIMAL (18, 2) NULL,
    [PA_DRIVER_PREMIUM_AMOUNT]          DECIMAL (18, 2) NULL,
    [IS_USE_SRCC]                       NVARCHAR (1)    NULL,
    [SRCC_PREMIUM_AMOUNT]               DECIMAL (18, 2) NULL,
    [IS_USE_TS]                         NVARCHAR (1)    NULL,
    [TS_PREMIUM_AMOUNT]                 DECIMAL (18, 2) NULL,
    [IS_USE_FLOOD]                      NVARCHAR (1)    NULL,
    [FLOOD_PREMIUM_AMOUNT]              DECIMAL (18, 2) NULL,
    [IS_USE_EARTHQUAKE]                 NVARCHAR (1)    NULL,
    [EARTHQUAKE_PREMIUM_AMOUNT]         DECIMAL (18, 2) NULL,
    [IS_COMMERCIAL_USE]                 NVARCHAR (1)    NULL,
    [COMMERCIAL_PREMIUM_AMOUNT]         DECIMAL (18, 2) NULL,
    [IS_AUTHORIZE_WORKSHOP]             NVARCHAR (1)    NULL,
    [AUTHORIZE_WORKSHOP_PREMIUM_AMOUNT] DECIMAL (18, 2) NULL,
    [TOTAL_PREMIUM_AMOUNT]              DECIMAL (18, 2) NULL,
    [CRE_DATE]                          DATETIME        NULL,
    [CRE_BY]                            NVARCHAR (15)   NULL,
    [CRE_IP_ADDRESS]                    NVARCHAR (15)   NULL,
    [MOD_DATE]                          DATETIME        NULL,
    [MOD_BY]                            NVARCHAR (15)   NULL,
    [MOD_IP_ADDRESS]                    NVARCHAR (15)   NULL
);

