CREATE TABLE [dbo].[XXX_INVOICE_PPH_05012024] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [INVOICE_NO]        NVARCHAR (50)   NOT NULL,
    [SETTLEMENT_TYPE]   NVARCHAR (10)   NOT NULL,
    [SETTLEMENT_STATUS] NVARCHAR (10)   NOT NULL,
    [FILE_PATH]         NVARCHAR (250)  NULL,
    [FILE_NAME]         NVARCHAR (250)  NULL,
    [PAYMENT_REFF_NO]   NVARCHAR (50)   NULL,
    [PAYMENT_REFF_DATE] DATETIME        NULL,
    [TOTAL_PPH_AMOUNT]  DECIMAL (18, 2) NOT NULL,
    [AUDIT_CODE]        NVARCHAR (50)   NULL,
    [CRE_DATE]          DATETIME        NOT NULL,
    [CRE_BY]            NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]    NVARCHAR (15)   NOT NULL,
    [MOD_DATE]          DATETIME        NOT NULL,
    [MOD_BY]            NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]    NVARCHAR (15)   NOT NULL
);

