CREATE TABLE [dbo].[XXX_OPL_INTERFACE_HANDOVER_ASSET_20250106] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]                  NVARCHAR (50)   NOT NULL,
    [BRANCH_CODE]           NVARCHAR (50)   NOT NULL,
    [BRANCH_NAME]           NVARCHAR (250)  NOT NULL,
    [STATUS]                NVARCHAR (15)   NOT NULL,
    [TRANSACTION_DATE]      DATETIME        NOT NULL,
    [TYPE]                  NVARCHAR (15)   NOT NULL,
    [REMARK]                NVARCHAR (4000) NOT NULL,
    [FA_CODE]               NVARCHAR (50)   NOT NULL,
    [FA_NAME]               NVARCHAR (250)  NOT NULL,
    [HANDOVER_FROM]         NVARCHAR (250)  NOT NULL,
    [HANDOVER_TO]           NVARCHAR (250)  NOT NULL,
    [UNIT_CONDITION]        NVARCHAR (250)  NOT NULL,
    [REFF_NO]               NVARCHAR (50)   NOT NULL,
    [REFF_NAME]             NVARCHAR (250)  NOT NULL,
    [HANDOVER_ADDRESS]      NVARCHAR (4000) NULL,
    [HANDOVER_PHONE_AREA]   NVARCHAR (5)    NULL,
    [HANDOVER_PHONE_NO]     NVARCHAR (15)   NULL,
    [HANDOVER_ETA_DATE]     DATETIME        NULL,
    [HANDOVER_CODE]         NVARCHAR (50)   NULL,
    [HANDOVER_BAST_DATE]    DATETIME        NULL,
    [HANDOVER_REMARK]       NVARCHAR (4000) NULL,
    [HANDOVER_STATUS]       NVARCHAR (10)   NULL,
    [ASSET_STATUS]          NVARCHAR (15)   NULL,
    [AGREEMENT_EXTERNAL_NO] NVARCHAR (50)   NULL,
    [AGREEMENT_NO]          NVARCHAR (50)   NULL,
    [ASSET_NO]              NVARCHAR (50)   NULL,
    [CLIENT_NO]             NVARCHAR (50)   NULL,
    [CLIENT_NAME]           NVARCHAR (250)  NULL,
    [BBN_LOCATION]          NVARCHAR (250)  NULL,
    [SETTLE_DATE]           DATETIME        NULL,
    [JOB_STATUS]            NVARCHAR (10)   NULL,
    [FAILED_REMARKS]        NVARCHAR (4000) NULL,
    [CRE_DATE]              DATETIME        NOT NULL,
    [CRE_BY]                NVARCHAR (15)   NOT NULL,
    [CRE_IP_ADDRESS]        NVARCHAR (15)   NOT NULL,
    [MOD_DATE]              DATETIME        NOT NULL,
    [MOD_BY]                NVARCHAR (15)   NOT NULL,
    [MOD_IP_ADDRESS]        NVARCHAR (15)   NOT NULL
);

